### ISSUE TITLE
Collecting statistics for SQL queries executed

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#102]
Is it possible to get a notification about every `Db.SQL` execution? 

If not, then how difficult and how expensive in terms of performance would that be?

cc @bigwad

**Comment by k-rus** [comment]
I don't fully understand the question. Do you want to get statistics on how often `Db.SQL` is called? Then you can use a profiling or analysing tool, but I guess it is not what you ask, right? 
Do you want to know statistics on each query, how often it is executed? I guess it is possible to do without significant overhead by maintaining counters inside the query cache.
Or do you want to be notified, i.e., provide a callback, which is called everytime when `Db.SQL` is called?

Can you clarify your need and can you give motivation?

Note that overhead in Level1, i.e., on top of OldSQL, likely to be neglectable, while overhead on top of NewSQL might be visible. Thus it is necessary to be careful in introducing the feature.

**Comment by miyconst** [comment]
>Do you want to know statistics on each query, how often it is executed? I guess it is possible to do without significant overhead by maintaining counters inside the query cache.

I want to collect statistics for all SQL queries executed. What query executed how many times, and how long time it took.

>Or do you want to be notified, i.e., provide a callback, which is called everytime when `Db.SQL` is called?

This is the way I was looking to collect the statistics. Get a callback (event, notification) on every `Db.SQL` start and finish.

**Comment by k-rus** [comment]
> I want to collect statistics for all SQL queries executed. What query executed how many times, and how long time it took.

To my understanding measuring time is unrealistic.



> This is the way I was looking to collect the statistics. Get a callback (event, notification) on every Db.SQL start and finish.

It is possible now, but its meaning unclear in the future. You need to provide more details.

By the way, what do you mean by calls to `Db.SQL`? It returns enumerable for select statements and executes non-select statements.

**Comment by k-rus** [comment]
By the way what is the motivation? Why and when do you want to do it? You can wrap necessary calls inside some intermediate functions, call them in your application, and run the application in the measuring mode.

**Comment by miyconst** [comment]
>To my understanding measuring time is unrealistic.

Agree. Measure execution time of an `IEnumerable` is a tricky task, but at least it's possible to measure time spent inside the `Db.SQL` function. Means how much time it takes to return an `IEnumerable`.

>By the way what is the motivation? Why and when do you want to do it? You can wrap necessary calls inside some intermediate functions, call them in your application, and run the application in the measuring mode.

This is possible when you own the apps. Starcounter is a composition of apps, and every app is controlled by it's developer.

I want to gather statistics of what is happening in the database during it's lifetime.

>You need to provide more details.

I want to have this information:

1. All string queries for all `Db.SQL` calls.
2. How often every SQL string query was executed.
3. How long it took `Db.SQL` to return. Does not matter whether it's an enumerable, single value, or void.
4. How many short running transactions were created.
5. How many readonly short running transactions were created.
6. How long it took to finish a short running transaction.

There are more points, but I skip them for now.

**Comment by k-rus** [comment]
Gathering statistics during database lifetime seems to me to be low priority, taken in account need other more important functionalities. Furthermore, it is not a low hanging fruit and very likely to introduce significant overhead. I also don't see how you can measure time for a call, which takes up to few microseconds.
Requirements for the functionality should take in account multi-threaded environment, where any synchronisation point for statistics will be a bottleneck. Also it should be taken in account future architecture with multi processes and multi hosts.

Some related proposals were discussed earlier, but we don't have resources to put in tooling.
 IMHO discussion of this functionality should be postponed until we released 3.0.

**Comment by miyconst** [comment]
@k-rus this issue is a question and not a requirement. If we don't have - it's fine, I just want to make sure that I am not missing something.

>Gathering statistics during database lifetime seems to me to be low priority...

Does this mean there is some offline statistics?

I am just looking for any possible feature to collect database statistics related to SQL execution. Please let me know if there is anything already available.

**Comment by k-rus** [comment]
> I am just looking for any possible feature to collect database statistics related to SQL execution. Please let me know if there is anything already available.

Nothing is available. Collecting such statistics bring overheads, thus it is not planned until we start working on optimisation and see that such statistics is unavoidable. But we want to avoid collecting statistics in production.

We discussed such things as giving warning if some query executes often, but is not using index. But it can be satisfied with approximate statistics.

**Comment by miyconst** [comment]
Archiving the issue.
