### ISSUE TITLE
Fix ScErrFieldSignatureDeviation (SCERR4128) message so it reflects nullability

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Home#104]
From https://github.com/Starcounter/Home/issues/103

> A database type declared a persistent field that did not match the signature of the attribute in the core schema. The type for property/field 'CreateDate' in class 'Surveys.webpages_Membership' has been changed from 'UInt64' to 'UInt64'.

Should be (example with the new type being nullable):

> A database type declared a persistent field that did not match the signature of the attribute in the core schema. The type for property/field 'CreateDate' in class 'Surveys.webpages_Membership' has been changed from 'UInt64' to 'Nullable\<UInt64>'.

I suggest using `Nullable<T>` as it's easy to miss the question mark in the shorthand `T?`.

@chrhol will you take this?

**Comment by chrhol** [comment]
Sure, I will fix the message.

**Comment by chrhol** [comment]
Fixed yesterday. Pushed to `v2.3` and `develop` branches.

**Comment by chrhol** [comment]
Looks like I didn't do this properly. When the type is a string or object, `Nullable` should of course not be added.

This is how it looks right now: `The type for property/field 'DoubleInB' in class 'SchemaUpgradeTest.B' has been changed from 'Double' to 'Nullable<String>'.`

I will fix this.

**Comment by chrhol** [comment]
Done.
