### ISSUE TITLE
SC Admin Panel User login

### ISSUE THREAD

**Issue by AdeelMalhi** [Starcounter/Home#106]
SC Admin Panel do not have user login option.
Also is it possible to create roles and assign access level to each role.
We are facing problem where internee are running delete queries. we do not want to give DML access to certain kind of role and they can only run Select queries

**Comment by miyconst** [comment]
Hello @AdeelMalhi and thank you for your question.

Currently Starcounter Administrator is designed for database administrators with full database access. Production servers should always block access to the Administrator parts.

If you have some users which require restricted access to the database, it can be solved via an app, which would provide access to the specific items.

Adding access rights and login options for the Administrator is in our plans though.
