### ISSUE TITLE
Starcounter db migration docs

### ISSUE THREAD

**Issue by papusa** [Starcounter/Home#113]
Didn't find any examples or docs about migrations. Currently in cases when for example inheritance of database class was changed we are just resting database. This is ok for development, however it's unacceptable for production. For the production I suppose I have to write migration code. 

I believe it would be nice to have a documentation about how such migrations could be done.

**Comment by mmnosek** [comment]
Please check the documentation here. Migration code is not always required:
* Database refactoring: https://docs.starcounter.io/guides/working-with-starcounter/database-refactoring/
* Star dump tool: https://github.com/Starcounter/StarDump
* Exporting and importing data using StarDump: https://docs.starcounter.io/guides/working-with-starcounter/migrating-from-2.2-to-2.3+/

cc @Mackiovello @miyconst do you have anything to add?

**Comment by Mackiovello** [comment]
This one might be useful as well: https://docs.starcounter.io/guides/working-with-starcounter/unload-reload/

Other than that, I think you got it covered

**Comment by papusa** [comment]
thanks

**Comment by mmnosek** [comment]
@papusa if you'll face any specific problem don't hesitate to ask!
