### ISSUE TITLE
Max HTTP request body size

### ISSUE THREAD

**Issue by papusa** [Starcounter/Home#115]
As I understand from docs (https://docs.starcounter.io/guides/network/network-gateway/) MaximumReceiveContentLength is size of max HTTP request body size. The question is - is it possible to get this value during run time?

**Comment by miyconst** [comment]
cc @alemoi

**Comment by warpech** [comment]
Ugly workaround: you could read the `scnetworkgateway.xml` file from disk.

**Comment by alemoi** [comment]
Here is the way:
```cs
using Starcounter.Internal;
NetworkGateway conf = NetworkGateway.Deserealize();
Console.WriteLine(conf.MaximumReceiveContentLength);
```
Should not be called often though.

**Comment by warpech** [comment]
Can this be added to the Docs? cc @Mackiovello

**Comment by Mackiovello** [comment]
> Can this be added to the Docs? 

Done in 	https://github.com/Starcounter/Docs/commit/20104c86b06cb946b9a36ad4469477ddb25a98c0
