### ISSUE TITLE
SessionOptions.PatchVersioning should be enabled by default

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#117]
Right now, all of the apps that I know, initialise session like this:

```cs
new Session(SessionOptions.PatchVersioning);
```

We don't really have a use case where disabling patch versioning (OT) would be a good idea, which is why I think that it should be enabled by default.

The following code should be equivalent to the above:

```cs
new Session();
```

cc @chrhol, @Mackiovello

**Comment by Mackiovello** [comment]
I'm pretty sure this is how it works in 2.4 already. @chrhol can confirm

**Comment by Mackiovello** [comment]
Duplicate of https://github.com/Starcounter/level1/issues/2966?

**Comment by warpech** [comment]
Oh, indeed! Actually I searched for this but only looked through open issues :)

Okay, then let's forget about it. This makes https://github.com/Starcounter/Docs/issues/77 more important though.
