### ISSUE TITLE
HandlerOptions.ReplaceExistingHandler is missing. what now?

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#119]
I get errors in my applications, because `HandlerOptions.ReplaceExistingHandler` flag is missing. What should I do? How do I replace it? Did I miss that it was obsolete?

**Comment by joozek78** [comment]
@alemoi It seems that [your commit](https://github.com/Starcounter/level1/commit/4c1322274798b814390b1d4c7b96b369b577ae14) is the source. **This breaks existing code**. It seems that existing handlers are now replaced by default (but I can't say for sure). Was this documented?

**Comment by alemoi** [comment]
Thanks for noticing it. It was a mistake by me to remove it, since I didn't expect the non-internal usage. Will avoid such removal in the future. The change however is propagated into the change-log.

**Comment by alemoi** [comment]
The new handler is always replacing the old one now, no need for the parameter. Please reopen the issue if you think it is necessary.

**Comment by joozek78** [comment]
I could just remove this flag from my code, but then my new code would not work in version prior to this (without this flag the handler would not be replaced). What do you think about reintroducing this flag as true-by-default? We can mark it as obsolete and disallow setting it to false (I suppose no one did that anyway). That would leave a strange gap in version history where my code wouldn't build, but apart from that it would be okay everywhere.

BTW it's not only me, at least Sweoffshore is having the same problem, but they haven't upgraded yet. I'm using term "my code" for expression simplicity, but it actually include other people's code too

**Comment by alemoi** [comment]
That's a very valid point. Adding the flag back (blank with "obsolete") and noting for the future. Thanks for the info!

**Comment by alemoi** [comment]
Did the above via 5693a4abbb2320bd5c83e9a2439d108483362b4e
