### ISSUE TITLE
Changing database configuration does not apply after "staradmin start db"

### ISSUE THREAD

**Issue by alemoi** [Starcounter/Home#120]
Scenario:
1. Run some application in default database.
2. Go and modify `Personal\Databases\Default\Default.db.config` and change default port to 8081.
3. `staradmin stop db`
4. `staradmin start db`
5. Start app.

The port still will be 8080 and not 8081.

Should not the port be 8081 after db restart?
Doing the same change via Administrator works.

CC @per-samuelsson @andwah

**Comment by andwah** [comment]
I think you need to restart scservice.exe to reload the configuration files.

**Comment by per-samuelsson** [comment]
@alemoi 

Configuration is managed by the server, and as @andwah says, it's currently only read on startup. Our server-side tooling (e.g. staradmin) have no support to update already existing configuration.

I know we have had this in another issue and said we might want to support updating configuration like you do, but it has never been a prio. I'll see if I can find some relevant issue.
