### ISSUE TITLE
Visual Studio gets stuck while debugging sccode.exe

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#121]
Originally created by @atifwaqar.

SC Version : 2.3.0.5916
Visual Studio : 2015

## Background
When we are debugging sccode (to debug adfenix code) VS gets stuck for a while (so does sccode, no handler works at this stage) 
![2017-03-30](https://cloud.githubusercontent.com/assets/4388707/24518561/b748331a-1582-11e7-9032-06057d50d1a0.png)
If you cancel this tool tip, or you wait for a while it looks like VS has started working again, you can see the yellow debugger control and if you press F11 the yellow control line goes away. But SC is still stuck, no handler works. and you can not detach the debugger, VS gives an error.
![image](https://cloud.githubusercontent.com/assets/4388707/24550371/ffe528ee-161d-11e7-856b-7b2a5766eeec.png)

If you force detach or terminate, VS will be detached but In SC 2.3 all apps crash after this. and in SC 2.2 DB+apps used to crash.

We always thought its VisualStudio bug. So never created the issue here

## How to reproduce this issue
1. DB should be big at least 10GB
2. Query an entire table that has thousands of records
3. Attach and place your debugger after querying the table
4. Hover your mouse on query result variable and expand the results
and as step 5 Sometimes it gets stuck, sometimes it doesn't 

Sometimes it gets stuck even without hovering mouse on any variable, This happens when we are debugging the code line by line (F11)

**Comment by miyconst** [comment]
I confirm the exact same issue in VS2017, and it is very annoying because debugging is very difficult in such conditions.

cc @bigwad, @alemoi

**Comment by miyconst** [comment]
Some more details: I met this issue without having the reproduce criteria, means it is not required to have `10GB` database and a complex query variable to expand. For me it did hang when hovering a simple property which returns an execution result of a simple SQL query.

If you need, I may spend some time providing a simple solution which reproduces the issue.

Worth to note, that adding an extra line to read the value into a string variable works, and watch over the string variable also works with no errors or hangs.

```cs
string value = databaseItem.ValueRetrievedBySql;
```

**Comment by alemoi** [comment]
I suppose its the SC current scheduling model, that does not work well with the VisualStudio threading for watches, etc. I suppose the right way would be to always auto-attach to scheduler in all needed places in SC, like SQL queries. Sounds like an architectural problem. @bigwad can you give an opinion on this please.

**Comment by bigwad** [comment]
I'm also quite confident the problem is related to the SC scheduling. But I didn't investigate further so details are unclear.

**Comment by warpech** [comment]
I can reproduce this problem very often.

**Comment by mtornwall** [comment]
I've a feeling that this happens much more frequently in Visual Studio 2017 than in earlier versions. I'm also rather convinced that the problem occurs independently of database size.

**Comment by Mackiovello** [comment]
> I've a feeling that this happens much more frequently in Visual Studio 2017 than in earlier versions.

That's my experience too, I had to stop writing bugs because of it 😏 On a serious note, this is super annoying to deal with. It makes it almost impossible to debug.

>  I'm also rather convinced that the problem occurs independently of database size.

Yes, database size doesn't matter

**Comment by mtornwall** [comment]
Indeed, this severely impacts developer experience and probably ought to be prioritized for a fix. @dan31 ?

**Comment by atifwaqar** [comment]
The worst part is when debugging a live server is needed (There are many reasons for this). and VS gets stuck. 
It takes too much time to get the server up and running again. And sometimes (Not all times), SC Server(SCData) crashes. and that takes at least 10+ min to get the apps up.

**Comment by alemoi** [comment]
Can someone give a scenario to reproduce the problem so we can check what is the reason behind the hang? Possibly there are even several reasons, but probably its an attempt to execute code outside the SC scheduler, but in VS debugging thread.

**Comment by rogeralsing** [comment]
This gives a 100% reproducable freeze when trying to eval `x` at the last line.

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Starcounter;

namespace StarcounterApplication2
{
    [Database]
    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    [Database]
    public class Order
    {
        public IEnumerable<OrderDetail> Employees => Db.SQL<OrderDetail>("select e from OrderDetail e where e.Order = ?", this);
    }

    [Database]
    public class OrderDetail
    {
        public Order Order { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string ItemId { get; set; }
    }


    class Program
    {
        static void Main()
        {
            Db.Transact(() =>
            {
                var o = new Order()
                {
                    
                };
                var d1 = new OrderDetail()
                {
                    Order = o,
                    ItemId = "abc",
                    Price = 123m,
                };
                var d2 = new OrderDetail()
                {
                    Order = o,
                    ItemId = "abc",
                    Price = 123m,
                };

                var x = o.Employees.ToArray();
            });
        }
    }
}
```

**Comment by alemoi** [comment]
Thanks @rogeralsing
That's exactly the case described above: an attempt to execute SQL code outside scheduler. Not related on VS 2017, generic problem from old times. We need to check what's possible to do regarding threading in VS debugging.

**Comment by Mackiovello** [comment]
Do we have anyone that's responsible for looking into this? It's still a huge pain.

**Comment by bigwad** [comment]
I will

**Comment by bigwad** [comment]
Working on it. Managed to get a reliable reproduction scenario.

What you guys can try as a workaround is to start debugging in the mixed mode. In mixed mode, the debugger might freeze for several seconds and fail to evaluate a property, but after that process and debugger are alive and you can keep debugging your app. At the moment I don't know why is that, but at least it works for me that way.

**Comment by bigwad** [comment]
Remember, you can't detach debugger in the mixed mode, so not particularly suitable for production.

**Comment by bigwad** [comment]
Fixed at long last.
From now on instead of freezing, you might see this message in the Watch window or in a datatip:
![image](https://user-images.githubusercontent.com/2953584/27752194-0b69553c-5de0-11e7-955d-844221dced5a.png)

Just press the icon next to the message to get a value.

**Comment by atifwaqar** [comment]
This is a great news. @bigwad great job.

**Comment by bigwad** [comment]
I got a report that the problem occurs sometimes. Less often than before but still.
If you hit it, please make a dump of sccode.exe process and let me know.
You may use the task manager to create a dump:
![image](https://user-images.githubusercontent.com/2953584/27948866-aa37a1da-62fb-11e7-96e7-5f4d0ce77ee0.png)

**Comment by RickardR** [comment]
What version has this fix? Running Starcounter-RC-2.3.1.6450 right now.

**Comment by bigwad** [comment]
Fixed in 2.3.1.6694

**Comment by RickardR** [comment]
Nice thanx (fyi, the current latest on the download page can't be downloaded.
2.3.1.6769 just gives you an error message). Ill download 6743 meanwhile.

**Comment by alemoi** [comment]
@andwah can you please check what's going on on the download server when you are back?

**Comment by atifwaqar** [comment]
I have SC 2.3.1.6739
and I successfully got my VS stuck :P

**Comment by bigwad** [comment]
@atifwaqar, would you mind to make a dump of sccode.exe next time?

**Comment by atifwaqar** [comment]
Ah, sorry, i totally forgot about it. next time this happens, i'll definitely make a dump

**Comment by RickardR** [comment]
Just got this again in 


 VS 2017, SC version  Starcounter-RC-2.3.1.6924.
Dumped sccode.exe,
https://www.dropbox.com/s/t3i4ssjqz0igi4v/sccode.7z?dl=0

**Comment by bigwad** [comment]
@RickardR 
Thanks for the dump. It really helped. Please try next RC build (version > 2.3.1.7012)

**Comment by RickardR** [comment]
Got 7012 installed now, will install any higher as soon as I see it on starcounter.io

**Comment by atifwaqar** [comment]
Hello guys,
I am on SC version 2.3.1.7294 and VS 2017. I still get the issue. and it feels like its even worst now.

**Comment by bigwad** [comment]
@atifwaqar, please make a dump of sccode.exe once you hit it again

**Comment by bigwad** [comment]
@atifwaqar provided me a dump in which we should have called `Debugger.NotifyOfCrossThreadDependency`, but still VS hanged. I have to reproduce and decide if it VS bug or not and what to do next.

**Comment by miyconst** [comment]
Happening to me with `Starcounter-RC-2.3.1.7742 (Nov 9, 2017 1:02:14 AM)`. Dump file is provided Google Drive.

**Comment by PatrykSzwer** [comment]
What is current status of this issue? It's still happening to me all the time, and TBH I think It's one of the crucial problems with current workflow in VS with Starcounter. It's really annoying and challenging to work with code with so many problems during debugging. And besides that, It's just a little embarrassing for us, to have such issue in such important area.

![image](https://user-images.githubusercontent.com/25042256/37703277-6e2688c2-2cf5-11e8-8964-96717c8103ac.png)

**Comment by tomalec** [comment]
Any updates? It really makes debugging a Starcounter app either 
 - hardcore mouse-over Minesweeper which could stop all your apps (and debugging) when you hover the wrong piece of code,
 - once you disable property evaluation, is just pointless, as you cannot inspect a thing.

**Comment by atifwaqar** [comment]
@tomalec I can feel your pain. :)

**Comment by miyconst** [comment]
@bigwad is going to take this issue next week.

**Comment by bigwad** [comment]
Can someone help with a consistent repro?

**Comment by miyconst** [comment]
The reproduction steps are provided via Slack.

**Comment by miyconst** [comment]
>Is there any estimate for a fix for this?

Unfortunately no, @bigwad is currently working on another important issue, then will switch to this one.

**Comment by bigwad** [comment]
The scenario the @miyconst shared with me though slack is fixed in 2.3, but not yet fully merged to develop. Honestly, I don't expect it covers all cases, so I'm asking all interested to give it a try and publish a repro scenario if it still hangs.

**Comment by miyconst** [comment]
@bigwad thank you for fixing, I will get back with more reproduction steps later today.

**Comment by PatrykSzwer** [comment]
Here are detailed steps to reproduce this annoying issue:
0. Make sure that you have option: `Enable property evaluation and other implicit function calls` in Visual studio enabled (You can find it in Debug -> Options -> General in Debugging section which should be opened already by default)
1. You will need [SignIn](https://github.com/Starcounter/SignIn) app (branch: `master-2.4`) and Blending app (branch: `master`).
2. Run SignIn app and login as admin user:
- Go to http://localhost:8080/signin/createadminuser to create new admin user.
- Use http://localhost:8080/signin/signinuser to login as an admin.
3. Open Blending app in visual studio, build and run in debug mode.
Now basically you can go and place debugger everywhere where `.Data` is called, or view-model property is accessible, but I'll give you a specific example at the specific place:
4. In visual studio navigate to this file: https://github.com/Starcounter/Blending/blob/master/src/BlendingEditor/Website/ViewModels/AllLayoutConditionsPage.json.cs
5. Place a debugger in line https://github.com/Starcounter/Blending/blob/master/src/BlendingEditor/Website/ViewModels/AllLayoutConditionsPage.json.cs#L29
6. Move your cursor at `this.Layouts.Data` in line 24 and try to evaluate It's values.
7. You will get an error that you can see on my screen.
![image](https://user-images.githubusercontent.com/25042256/38802895-e076f68c-416d-11e8-9188-ae557de2d00b.png)

**Comment by miyconst** [comment]
@bigwad did you really mean to close this issue?

**Comment by bigwad** [comment]
No, it got closed by mistake. I'm still working on the latest reproduction scenario.

**Comment by bigwad** [comment]
I've made a good progress in understanding the issue. This gist is that [Debugger.NotifyOfCrossThreadDependency](https://msdn.microsoft.com/en-us/library/system.diagnostics.debugger.notifyofcrossthreaddependency(v=vs.110).aspx) doesn't work if calling thread holds a lock obtained with the [Monitor](https://msdn.microsoft.com/en-us/library/system.threading.monitor(v=vs.110).aspx) class. Worth to mention that C# `lock` statement is implemented in terms of `Monitor` methods. 

All so far unexplicable hangs has happended inside `Db.Scope` which uses `Monitor` internally. The easiest woraround would be to use `AutoResetEvent` or `SemaphoreSlim` instead of `Monitor`.

**Comment by miyconst** [comment]
>All so far unexplicable hangs has happended inside `Db.Scope` which uses `Monitor` internally. The easiest woraround would be to use `AutoResetEvent` or `SemaphoreSlim` instead of `Monitor`.

Are you going this way? How long time it will approximately take?

**Comment by bigwad** [comment]
It's a simple fix, but I have to review performance implications and make sure it actually helps.
I hope I'll finish it today.

**Comment by atifwaqar** [comment]
@bigwad will this fix be in 2.3.1.7294 and 2.4.xxxx both?

**Comment by miyconst** [comment]
>@bigwad will this fix be in 2.3.1.7294 and 2.4.xxxx both?

The fix will be in `2.4.0.xxxx` only.

**Comment by atifwaqar** [comment]
Still good enaough :)

**Comment by bigwad** [comment]
Fixed in builds > `2.4.0.5951`. Please try it out.
Switching from `Monitor` to `SemaphoreSlim` wasn't that straightforward due to recursive locks, permitted by `Monitor`. Also `SemaphoreSlim` was noticeably slower. So I ended up with a custom interlocked-based synchronization primitive, which is almost on par with `Monitor`.

**Comment by PatrykSzwer** [comment]
Checked with the custom build https://teamcity.starcounter.org/viewLog.html?buildId=54033&tab=buildResultsDiv&buildTypeId=Starcounter_DevelopDailyWindows

Unfortunately, It's not working. Not even the issue itself, but I just can't run debug in the Blending app. It starts for a few seconds and then just shutting down (after that I can't even stop the database, I have to use kill all command. `Database "default" in process 13776`). 
Please check if you can debug the Blending app (`master` branch) with this change. In my output I can see error like: `The program '[20088] sccode.exe' has exited with code -531431422 (0xe0530002).`

I managed to start debug with Kitchensink though, and there it seems to be working.

**Comment by PatrykSzwer** [comment]
Errors that I got by running `run.bat` file:
```
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.TypeLoadException: Type 'Simplified.Ring1.Something' from assembly 'Simplified.Data.Model, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' tried to override method 'Starcounter.IObjectViewInternal.get_TypeBinding' but does not implement or inherit that method.
   at BlendingProvider.Website.Api.BlendingHandlers.Register()
epositories\Blending\src\BlendingProvider\Program.cs:line 16
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 549
Version: 2.4.0.5960.
Help page: https://docs.starcounter.io/?q=SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 583
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 277
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 139
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 53
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Processor.cs:line 90
ErrorCode=4259
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR4259
---> System.TypeLoadException: Type 'Simplified.Ring1.Something' from assembly 'Simplified.Data.Model, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' tried to override method 'Starcounter.IObjectViewInternal.get_TypeBinding' but does not implement or inherit that method.
   at BlendingProvider.Website.Api.BlendingHandlers.Register()
epositories\Blending\src\BlendingProvider\Program.cs:line 16
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 549
TypeName=Simplified.Ring1.Something
HResult=-2146233054


[14:10:37, Starcounter (default)]
System.Exception: ScErrDatabaseAlreadyExists (SCERR2047): A database with the specified name already exists. Can't register new codehost "default.
Version: 2.4.0.5960.
Help page: https://docs.starcounter.io/?q=SCERR2047.
   at Starcounter.Internal.AppsBootstrapper.RegisterNewCodehostInGateway() in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 62
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 140
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupFromConfiguration(IHostConfiguration config) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 253
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 133
   at Starcounter.Hosting.RuntimeHosts.Shared.AppSharedRuntimeHost.Run(Func`1 configProvider, Func`1 autoStartProvdier) in C:\TeamCity\BuildAgent\work\sc-17650\Level1\src\Starcounter.Hosting\RuntimeHosts\Shared\AppSharedRuntimeHost.cs:line 19
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR2047
```

**Comment by miyconst** [comment]
I confirm the issue. @bigwad please investigate.

**Comment by bigwad** [comment]
@PatrykSzwer, it's due to other changes. Please try the workaround: https://github.com/Starcounter/level1/issues/4619#issuecomment-383935249

**Comment by miyconst** [comment]
@PatrykSzwer confirms that debugging with Visual Studio works. Big thank you to @bigwad for the fix.

Closing the issue for now. Will reopen if another hanging case found.

**Comment by bigwad** [comment]
as stated earlier: 
>Fixed in builds > `2.4.0.5951`

**Comment by Mihaiii** [comment]
^Sorry, I missed that info.
I tried to reproduce it with >2.4.0.5951 and everything works fine.
Thank you for the fix!

**Comment by RickardR** [comment]
2.4.0.6057
![image](https://user-images.githubusercontent.com/15194364/40177428-e3e57eb8-59de-11e8-8e18-aee5dbeb7be3.png)


I have a dump of sccode.exe i can share through dropbox if needed

**Comment by bigwad** [comment]
@RickardR, 
yes, please do so. Also, would be great if you could share binaries involved.

**Comment by RickardR** [comment]
Posted links in our hotline channel (doctrin) in SC Slack.

**Comment by bigwad** [comment]
Starting from `2.4.0.6159` I made a change that allows debugger more or less safely interrupt hung evaluation. It means that you might still get above error message, but it won't be fatal for a process being debugged. In particular, you'll be able to:
1. continue execution
2. re-evaluate value by pressing 
![image](https://user-images.githubusercontent.com/2953584/40349622-7062908a-5da7-11e8-8d79-59a1d40383c8.png)
3. detach debugger

**Comment by miyconst** [comment]
@RickardR could you please validate?

**Comment by RickardR** [comment]
@miyconst @bigwad  I'll do it as soon as possible, working on a release right now but I'll try to upgrade and play with it asap
