### ISSUE TITLE
How to make url handles without a starcounter session

### ISSUE THREAD

**Issue by malx122** [Starcounter/Home#122]
Earlier (starcounter 1.x) we had a seperate webservice that handled upload, download and thumbnail creating for documents, of course since SC didnt have its own webserver at that time.

With SC nowadays we moved it into SC to decrease the complexity quite a bit. However, this does not go to well since a request to one of those web handlers might take some time blocking one SC thread for each call resulting in a rapid "stop" of the whole db when you get many request.

I noticed in your image app that you just make the files available as "static" files but that is not an option for us. We need to check access rights, create thumbnails for non picture documents and so on.

So what I want is to have a Handle.Get that default does not use a SC thread, is that possible? (I of course want it to be possible to ScheduleTask inside it to do a fast access control etc)

**Comment by miyconst** [comment]
cc @alemoi

**Comment by mtornwall** [comment]
For downloads, did you try using a streaming response (i.e., set `new Response() { StatusCode = 200, ..., BodyStream = myStream }`?

**Comment by alemoi** [comment]
We have discussed the issue and the solution in person with @malx122 last week.
The idea is to used postponed HTTP response and streaming body.

**Comment by alemoi** [comment]
@malx122 please provide an info on how useful or the opposite was the solution.
Thanks!

**Comment by miyconst** [comment]
Archiving the issue.
