### ISSUE TITLE
Static imports in Json code-behind files

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#127]
Including static imports in Json code-behind files, such as:

`using static Starcounter.Templates.Template;`

will give you a build error:

`Error CS0138	A 'using namespace' directive can only be applied to namespaces; 'Template' is a type not a namespace. Consider a 'using static' directive instead`

Presumably since it results in the following code in the json.g.cs:

`using Starcounter.Templates.Template;`

When it should be:

`using static Starcounter.Templates.Template;`

@chrhol

**Comment by chrhol** [comment]
Thank you for reporting this. I was not aware of this syntax before I saw your issue.

I wonder if there is any point in including these usings in the generated code or if they should be omitted. I will take a look.

**Comment by chrhol** [comment]
I've pushed a fix for this to `v2.3` and `develop`. Should be included in the next published builds.

static using directives are omitted when parsing code-behind, and will not end up in the generated code.

**Comment by erikvk** [comment]
Sweet :)
