### ISSUE TITLE
2.3.0 Release is not reflected in CHANGELOG.md

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Home#128]
2.3.0.6350 does not have separate section in 
https://github.com/Starcounter/level1/blob/develop/CHANGELOG.md eveno though it's marked as a Stable Release in downlaods page.

related https://github.com/Starcounter/RebelsLounge/issues/61

**Comment by Mackiovello** [comment]
I made a PR last week: https://github.com/Starcounter/level1/pull/4221

**Comment by Mackiovello** [comment]
Done, closing
