### ISSUE TITLE
ScLLVM exit(1) on dynamic linker error

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Home#129]
When ScLLVM attempts to load an object that references a symbol that LLVM's dynamic linker cannot resolve, it (LLVM, that is) happily reports the error and then [proceeds](https://github.com/llvm-mirror/llvm/blob/93e6e5414ded14bcbb233baaaa5567132fee9a0c/lib/Support/ErrorHandling.cpp#L104) to `exit(1)`. 😡 While ScLLVM certainly is not to blame for this, I'm hoping there might be a workaround we can apply to at least report a sensible error.

**Comment by alemoi** [comment]
Me and @mtornwall will try to push the schema for SCLLVM to produce DLLs and stop using MCJIT completely.
