### ISSUE TITLE
Deprecate property json.Session

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#133]
This issue actually contains of 2 steps:
- Deprecate `json.Session` setter: really confusing behaviour today. Almost (!) the same behaviour as setting `session.Data = json`.
- Investigate what effects deprecating `json.Session` getter has. Where is it used today? In what apps? Can it be replaces with calling `Session.Current` instead.

**Comment by chrhol** [comment]
I think there is still a point in leaving the getter for `json.Session`. In some cases it's useful to be able to get the session from an instance of TypedJSON.

Unfortunately it's not possible to obsolete only the setter or getter,  you have to mark the whole property as obsolete, which means that the warning will be issued when you're getting the session as well. I've tried to add a message though that explains it. 

`"This property will be made readonly in a later version. If an assignment is done use session.Data and assign this instance instead."`

The message will also be changed a bit, when we do the other changes in session (i.e. deprecating `session.Data` and `session.PublicViewModel`).

I've committed the changes for this in a feature branch, and will consider the issue solved for the time being and move to the next issue in the same batch.

**Comment by chrhol** [comment]
I've think I changed my mind when working on the other issues in #139.

We should try to deprecate and remove the `json.Session` property altogether and rely on `Session.Current`. This property makes no sense most of the time, and is confusing.

I will go back to this issue once more when the other ones are in place.

**Comment by warpech** [comment]
The code changes are done in v2.3 but not documented yet.
