### ISSUE TITLE
Deprecate session.Data

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#135]
Dependent on #134.

**Comment by chrhol** [comment]
Also dependent on #137 since `session.Data` was used to determine `session.PublicViewModel`

This is in place. `session.Data` have been deprecated. Instead `session.Store` should be used for keeping state and the root viewmodel to be used for the client is handled automatically.

This is not merged to main branches yet. Can be found in branch `feature/v2.3/home/139` together with the other changes in #139. Everything in that issue will be merged at the same time.

**Comment by warpech** [comment]
The code changes are done in v2.3 but not documented yet.
