### ISSUE TITLE
Deprecate session.PublicViewModel

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#137]
Instead the viewmodel root (that is needed as a starting point for patching) should be infered from the initial typedjson response that is sent to a client.

**Comment by chrhol** [comment]
One thing that was brought up on todays AppArchTF meeting: there need some way to change the root after the first initial request.

**Comment by chrhol** [comment]
The task from the first comment is in place: the viewmodel-instance to be used as root when sending response to client is determined from the instance that is sent when `PartialToStandaloneProvider` middleware is invoked.

I found some problem with the task from the second comment. At least when it comes to handle this automatically that comes from some bad, or non-intuitive flows in how our responses are handled in concern of accept headers in the request.

Basically: I cannot do the changes needed to allow automatic detection of changed root viewmodel without breaking compatibility with existing apps.

I will create a new issue for discussing this (not sure if it's worth fixing or if we just want to live with it until the v3 (Starcounter.Core)).

Current solution is that I've added an extension class to session, `Starcounter.XSON.Advanced.SessionExtension` that contains a method for setting the root for the client manually (much like `session.PublicViewModel`). This is to remove the functionality for everyone that is not interested in it, and to make it more explicit if you need it.

Lets discuss this on the next AppArchTF meeting.

This is not merged to main branches yet. Can be found in branch `feature/v2.3/home/139` together with the other changes in #139. Everything in that issue will be merged at the same time.

**Comment by chrhol** [comment]
After testing the flow in the last referenced issue (https://github.com/StarcounterApps/SignIn/issues/111) I am not sure anymore that my previous comment is valid. 

It might be working exactly as intended 😕 The root should be changed in some cases.

**Comment by warpech** [comment]
The code changes are done but not documented yet.
