### ISSUE TITLE
Handle.GET() - only allow returning TypedJSON without parent set.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#140]
Should be added to `v2.3.x` but be disabled per default. 

Returning a TypedJSON instance that already is attached to a parent has somewhat non-obvious behaviour and is mainly done because of limitations of what you are allowed to store on a session When #134 is in place it should be possible to fix this anti-pattern.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.
