### ISSUE TITLE
Bump LTS release channel

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#144]
The Long-Term Support release channel is on version 2.2.2.4237 and hasn't received any changes since March. My understanding is that the LTS channel should never be behind the release channel. Should LTS be updated to be on the same version as the Release (2.3.0.6350)? 

CC @alemoi

**Comment by alemoi** [comment]
Yes, we had a discussion recently, you wasn't a part of it. Let's discuss it again here. I suppose it should be that current RC channel becomes LTS. What do you think? @dan31

**Comment by Mackiovello** [comment]
That should be the solution if we want to follow our own words: "this channel and the Release channel does not differ in functionality."

I don't think we have to discuss it - just bump it to the current Release version

**Comment by miyconst** [comment]
@ubbeK please guide @threezool into the Urbanstar team.

**Comment by Mackiovello** [comment]
LTS is still on 2.2.

**Comment by ubbeK** [comment]
I see.

What is the reason for having LTS builds when we do not have TeamCity builds for the branch `2.3.1` anymore?

**Comment by Mackiovello** [comment]
> What is the reason for having LTS builds when we do not have TeamCity builds for the branch 2.3.1 anymore?

I don't know. @dan31 established the versioning scheme, maybe he knows something. Anyway, it seems like LTS has been abandoned.

**Comment by ubbeK** [comment]
As I understand it, `2.3.1.8329` is a LTS release where all releases might not be. Hence, it will be added to LTS channel.

**Comment by ubbeK** [comment]
Closing

http://downloads.starcounter.com/download/Starcounter/LTS/2.3.1.8329
