### ISSUE TITLE
Blending debugging on Admin page

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#145]
Blending is an integral (and very specific) part of Starcounter. Although it is hard to explain and it's not obvious how to use it. We are doing changes in API (new `Blender` by @alemoi ), documentation (new blending tutorial by @Mackiovello) and great features on client-side (@tomalec). It is all great and extremely important, but it is still sometimes hard to manage and realize how the current server state looks like and what is blended to what, in what order and from what app.
What do you think about adding some debugging tool to our Admin panel?
1. List of currently registered tokens
2. URIs assigned to each token
3. App name
4. The direction of possible calls to be able to find when specific URI will be called

We already have registered URIs list in the admin panel, why not to have such feature for blending? It would make debugging and development easier. How many of you spend a lot of time trying to find why some handler is not called even if blended? Typo? This kind of list would allow finding a problem many times faster. I'm not sure where in admin it should be placed.

cc @Starcounter/sc-blendingtf @alemoi @andwah

**Comment by warpech** [comment]
This is the greatest proposal since the invention of blending. I am all for it. Perhaps @alemoi or @ubbeK could work on it.

**Comment by alemoi** [comment]
> What do you think about adding some debugging tool to our Admin panel?

I can just add that this information is already added by me in `Blender` class: ListAll, ListTokens, ListTokens.

So if we start adding it to Administrator, then I can extend it with more info.

**Comment by mmnosek** [comment]
@warpech can we assign some volunteer for it? :) It should not be a very big deal because as @alemoi suggested we already have the proper API for it.

**Comment by tomalec** [comment]
That's definitely great idea. I already proposed an app like blending manager, that would list all app views, blending points, etc. Something like the layout editor but to manage the entire views.

But adding it to the admin page is definitely cool thing to have.
But as always the question is who and when?

**Comment by andwah** [comment]
I think i can add this info to admin, just need to know the api. @alemoi  ?

**Comment by alemoi** [comment]
@andwah API is there, but I can help with providing the REST handlers. Basically it will be via CRUD REST API.

**Comment by andwah** [comment]
do you already know the json format and the handler's? then i may start before the final REST API is finished.

**Comment by warpech** [comment]
The same screen in Administrator should allow to enable/disable the mappings. See: https://github.com/Starcounter/RebelsLounge/issues/147

**Comment by warpech** [comment]
The debugging information asked for by the OT is already implemented in the `Attachments` page in BlendingEditor:

![image](https://user-images.githubusercontent.com/566463/49456128-c4bd1700-f7e8-11e8-8699-7f84fd63bf1a.png)

There are issues to extend the functionality to have full CRUD operations on blending rules: https://github.com/Starcounter/Blending/issues/242

Closing as done elsewhere.
