### ISSUE TITLE
Old links on downloads.starcounter.com/download

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#151]
On the top of http://downloads.starcounter.com/download, there is one broken link and one outdated link. 

The "Release Channels" link should go to https://docs.starcounter.io/guides/working-with-starcounter/release-channels-in-starcounter/

The link to the Wiki should either be removed or link to https://docs.starcounter.io/

CC @andwah

**Comment by andwah** [comment]
Fixed.

**Comment by Mackiovello** [comment]
Great! Thank you, closing
