### ISSUE TITLE
How to use sample apps when one app doesn't use Bootstrap

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#153]
I'm trying to run two apps: an app that doesn't import or use Bootstrap and [SignIn](https://github.com/starcounterapps/signin). This causes SignIn's Bootstrap not to be applied. Is there another solution to this than having to include Bootstrap in `PartialToStandaloneHtmlProvider` for both apps? 

![bootstrapstylemissing](https://user-images.githubusercontent.com/19392292/27174359-2acf2652-51bc-11e7-8e02-d87ef6b372bf.PNG)

**Comment by Mackiovello** [comment]
CC @tomalec

**Comment by Mackiovello** [comment]
Including Bootstrap in both apps doesn't seem to be a solution either. The other app uses [material web components](https://material-components-web.appspot.com/) and Bootstrap destroys a fair number of the elements. Is there any other workaround that can be used until we migrate away from Bootstrap?

**Comment by tomalec** [comment]
This will be addressed by https://github.com/Starcounter/RebelsLounge/issues/119

**Comment by Mackiovello** [comment]
I'll close this one as answered and follow what happend in Starcounter/RebelsLounge#119
