### ISSUE TITLE
Change text in elements with blending

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#155]
I have an app where I want to integrate SignIn. The SignIn view looks like this:

![signin](https://user-images.githubusercontent.com/19392292/27258449-db995076-53fa-11e7-9533-acf5824e1e6c.png)

My app is in Swedish. Is there any way to change "Sign in!" to say "Logga in"? 

One solution would be for the SignIn app to store all its user-facing strings in a shared database so that other apps can modify them. That is a clumsy approach.  

Another is to use a CSS workaround like explained in [this StackOverflow question](https://stackoverflow.com/questions/7896402/how-can-i-replace-text-with-css) and include the CSS in the `declarative-shadow-dom`. That's not optimal either.

A third approach is to fork the SignIn app and change it locally.

Is there a simpler, more intuitive way, that I'm overlooking? 

CC @tomalec

**Comment by Mackiovello** [comment]
I've decided to fork since it solves both this and https://github.com/Starcounter/Home/issues/153. If there's a better way, please tell me. I'll close this issue for now.

**Comment by mmnosek** [comment]
@Mackiovello - have you seen this issue? https://github.com/Starcounter/TechComm/issues/214 it would be nice to raise this topic again as it will appear sooner on later. Forking doesn't seem to be a nice solution, but I understand it's the fastest one. Actually, it's not only blending problem. It applies to all:
* user-visible strings in database stored objects
* messages in code (errors, notifications etc.)
* views - UI and blended views as well

I guess that your app will need to be multilingual sooner or later as well.

**Comment by tomalec** [comment]
I would say text's should be general "the content" so should come from the app elements, not from composition. Also, I think i18n should be done outside of blending, as this is orthogonal problem.

**Comment by Mackiovello** [comment]
@tomalec, I think you're completely right, this is not a blending problem. That's my bad.

@mmnosek, it would be nice to demonstrate how to internationalize apps. I don't think it's very urgent, but I'll keep it in mind for the future. It seems like @miyconst knows what's up with that so I'll talk to him when it gets more relevant
