### ISSUE TITLE
Getting started with prefabs

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#156]
The getting started experience is so so when trying the prefabs.

* Is there demo data that can be installed ?
* It is not clear what you should expect or do when starting the prefabs.
* The prefabs do not really give any feedback on why things break. some fail silently if there is a broken schema in the DB.

e.g. trying the sign in app. it says admin/admin is the default... this doesn't work anywhere (as the DB is empty?)

Opening the sign-in app isn't very helpful either *"Error 404: Resource "/signin" not found."*

Opening "website provider" results in a *"Welcome to websiteprovider"* text message.

Opening "SampleWebsiteTheme", there is no description. the page says *"Desktop Theme is enabled"* 

It would be very neat with some linked Github pages describing both what the app is supposed to do, how to interact with it via code, e.g. what entities it contains.
And possibly some feature tour overlay e.g. intro.js for apps that has an actual UI.

Once there are more prefabs and some real 3rd party apps, information on how to get started with those are essential.

**Comment by Mackiovello** [comment]
You are completely right, it's not obvious how to get started with the prefab apps. @Mihaiii just created documentation in the [Content app](https://github.com/starcounterapps/content/tree/develop) that I believe covers what you request. Could you take a look? 

There is an issue in our technical communication tracker that asks for a sample apps tutorial which shows how to use a couple of sample apps together. Is that what you would like to see? 

We really appreciate your feedback! I'll bring this up on the next technical communication meeting next week. After that, I'll write down what we decided so that you can give it a look.

CC @warpech

**Comment by rogeralsing** [comment]
The ReadMe for the content app looks great.
I saw that there is such info for the sign-in app here on Github.

Having that kind of information available on the app warehouse would be awesome.
(I'm thinking something like the movie browser in Netflix, where you can click a movie and get expanded info. )

**Comment by Mackiovello** [comment]
> Having that kind of information available on the app warehouse would be awesome

That's actually a great proposal, I'll see if I can make it happen

**Comment by Mackiovello** [comment]
@warpech is investigating the options of providing more information in the warehouse

**Comment by rogeralsing** [comment]
There is a case of "normal text selection" and grid selection going on at the same time.
Trying to select the text in a cell from start to end is not always as easy as one could wish 

![image](https://user-images.githubusercontent.com/647031/27622618-8063def2-5bd8-11e7-99a7-f88b5dbb9428.png)

**Comment by Mackiovello** [comment]
@rogeralsing was that comment meant for https://github.com/Starcounter/Home/issues/158?

**Comment by rogeralsing** [comment]
Yes, my bad, multiple tabs open :) moving it.

**Comment by warpech** [comment]
Thank you so much @rogeralsing for reporting this. Please continue, especially while you have the fresh perspective.

I have used your input in the below linked initiatives.

> Is there demo data that can be installed ?
> It is not clear what you should expect or do when starting the prefabs.

This is addressed by https://github.com/Starcounter/Guidelines/pull/40. Once agreed, we should implement this in all apps.

> The prefabs do not really give any feedback on why things break. some fail silently if there is a broken schema in the DB.

This is addressed by https://github.com/Starcounter/Guidelines/issues/36

> And possibly some feature tour overlay e.g. intro.js for apps that has an actual UI.

That's a neat idea but I am afraid that would be annoying as well as hard to maintain in the long run. Let's start with static descriptions.

@rogeralsing do you think all your proposals in this thread are addressed by the issues linked above?

**Comment by miyconst** [comment]
Archiving the issue since it's idle for long time. @rogeralsing feel free to reopen.
