### ISSUE TITLE
ScErrThreadNotAttached when trying to test Typed JSON class

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#159]
I have a simple test class that looks like this:

```cs
    [TestClass]
    public class ValidatesPasswordCorrectly
    {
        [TestMethod]
        public void DifferentPasswordsGivesWarning()
        {
            var signUpForm = new SignUpForm();
            var signUpSettings = new SignUpSettings();
            string password = "secretPassword321###";
            signUpForm.PasswordTwo = "##123AnotherPassword";
            var validationResult = signUpForm.ValidatePasswordOne(password);
            Assert.AreEqual(validationResult, signUpSettings.PasswordsNotEqualMessage);
        }
    }
```

When trying to run, I get this message:
```
Message: Test method SignUpTests.ValidatesPasswordCorrectly.DifferentPasswordsGivesWarning threw exception: 
System.Exception: ScErrThreadNotAttached (SCERR1004): The operation failed because the current thread wasn't attached to the scheduler.
Version: 2.3.1.6626.
```

When looking around, I was led to this issue: https://github.com/Starcounter/Home/issues/11, so I tried wrapping the code in `Scheduling.ScheduleTask`. It didn't work.

`SignUpForm` is a Typed JSON class and `SignUpSettings` is a database class. Commenting out `SignUpSettings` doesn't fix the issue. Commenting out `SignUpForm` does. 

There are no tests of Typed JSON classes in the sample apps. Is there a way to make this work? 

A solution would be to move the logic I want to test to a separate class, but that doesn't feel optimal.

**Comment by chrhol** [comment]
There is nothing directly in TypedJSON that requires it to be run on a Starcounter scheduled thread, so the most likely cause is that you are trying to access the database in some place.  

Can you post the stacktrace for the exception above? It might help to point us to the place where it happens.

There are tests in `Starcounter.XSON.Tests` in `Level1` that are run as unittests (meaning that there is no database context available). 

In 2.3 it's not possible to run these kind of tests with access to the database. You need 2.4 for that, @per-samuelsson  have been working on enabling support for self-hosted apps (see for example https://github.com/Starcounter/RebelsLounge/issues/54)

**Comment by Mackiovello** [comment]
> so the most likely cause is that you are trying to access the database in some place.

Taking a closer look, the method I call is trying to access the database. That's my bad. Thank you for clarifying! 

> 2.4 for that, @per-samuelsson have been working on enabling support for self-hosted apps

I'm looking forward to that
