### ISSUE TITLE
Database Backup Verification 

### ISSUE THREAD

**Issue by MujahidRashid** [Starcounter/Home#160]
I have an automated script that takes daily backup of our database using shadow copy as recommended by starcounter. I want to move one step further and want to implement something that would automatically check the database backup to see if it would work correctly if required. 
Current method i use is to copy the backup in to the starcounter folder rename it as personal and run all our apps on a test server.
I would appreciate any advice that would help me in the right direction on the best way to achive this. 

@bigwad

**Comment by bigwad** [comment]
I think your approach is perfectly valid. Do you have any problems with it or lack of some tooling?

**Comment by miyconst** [comment]
@MujahidRashid for now there are only manual validation steps.

The first one you have already described, but I am afraid that apps may do some database changes during the startup, this will lead to non desired changes in the backup.

The other way would be to unload the backed up database using the StarDump tool and query the unloaded SQLite dump.

In the future we might have some automatic validation tool, not for now though.

Closing the issue as answered question.
