### ISSUE TITLE
Multiple /add/ entries to the same array index in one JSON patch

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#161]
```
Starcounter-RC-2.3.1.6633 (Jun 20, 2017 1:01:47 AM)
```

I am receiving the following patch from server side:

```json
[
  {
    "op": "replace",
    "path": "/_ver#s",
    "value": 3
  },
  {
    "op": "test",
    "path": "/_ver#c$",
    "value": 3
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/0",
    "value": {
      "Name$": "Host",
      "Value$": "",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/1",
    "value": {
      "Name$": "Port",
      "Value$": "25",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/0",
    "value": {
      "Name$": "EnableSsl",
      "Value$": "False",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/3",
    "value": {
      "Name$": "UseDefaultCredentials",
      "Value$": "False",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/4",
    "value": {
      "Name$": "UserName",
      "Value$": "",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/2",
    "value": {
      "Name$": "Password",
      "Value$": "",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/1",
    "value": {
      "Name$": "FromAddress",
      "Value$": "",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "add",
    "path": "/CurrentPage/SelectedChannel/Values/2",
    "value": {
      "Name$": "FromDisplayName",
      "Value$": "",
      "DeleteTrigger$": 0
    }
  },
  {
    "op": "replace",
    "path": "/CurrentPage/Channels/1/SenderType",
    "value": "Listonosz.Senders.SmtpSender"
  }
]
```

This patch is not valid, because it adds multiple items to the same array index, which overwrites each other. Although it successfully applies, it does not make any sense.

I will try to get steps to reproduce.

cc @chrhol, @alshakero

**Comment by chrhol** [comment]
According to the jsonpatch spec `add` for arrays will not overwrite or replace, it will insert it so all of these add's should end up in the array so adding items with the same index is not necessarily a bug.

Snippet from https://tools.ietf.org/html/rfc6902#section-4.1:
>  If the target location specifies an array index, a new value is inserted into the array at the specified index.
...
 An element to add to an existing array - whereupon the supplied
      value is added to the array at the indicated location.  Any
      elements at or above the specified index are shifted one position
      to the right.

**Comment by miyconst** [comment]
Okay, then something absolutely weird is happening. Here is what I see on the client side after the patch applied:

![image](https://user-images.githubusercontent.com/6435556/27382135-d74cacce-5685-11e7-90c2-6b1fb7341988.png)

Before the patch, the array was empty. I was not able to reproduce the issue in a simple solution, but I can share source code which can reproduce the issue.

@alshakero, @tomalec  is it something related to Palindrom?

**Comment by chrhol** [comment]
Is it a lot of work for you to share the code? Or maybe I have access to it already. I would like to take a look at the reason the server sends a patch like this instead of just sending the array

**Comment by alshakero** [comment]
+1 I'd really like to see some code.

**Comment by miyconst** [comment]
The code is private, so it will be share outside of this issue.

**Comment by miyconst** [comment]
Here are the steps to reproduce the issue, although the source code is private:

1. Checkout the channel-rework branch.
2. Start the application.
3. Navigate to /Listonosz/channels.
4. Click Add new channel button.
5. In the Sender type select box select "Listonosz SMTP Sender" value.

**Comment by miyconst** [comment]
The `starcounter-debug-aid` shows that the patch was applied correctly, and the view-model has the correct values, still the HTML inside the `dom-repeat` is wrong.

![image](https://user-images.githubusercontent.com/6435556/27420732-8ded8236-5727-11e7-9221-f67fbe0166da.png)

It indicates to a bug inside our component which notifies Polymer about the changes, or the bug is inside Polymer itself.

**Comment by miyconst** [comment]
cc @tomalec, @warpech

**Comment by warpech** [comment]
I think it is very clear, thanks. I would start searching for the problem in https://github.com/Palindrom/palindrom-polymer-client/blob/04716b9620bd0f7786a23e356e3634aa702508f7/palindrom-client.html#L416-L424, because the fact that JSON Patch supports this weirdness:

>  If the target location specifies an array index, a new value is inserted into the array at the specified index.
...
 An element to add to an existing array - whereupon the supplied
      value is added to the array at the indicated location.  Any
      elements at or above the specified index are shifted one position
      to the right.  

doesn't mean that Polymer does. We most probably need to shift the array values before passing them to Polymer.

Now there are few buts:

1. Yes, adding multiple values to the same array index is not against the JSON Patch spec, but it clearly shows that server side Palindrom has some trouble getting the indices right. I think it should be fixed on the server anyway.
2. We want to ditch working on Polymer 1 related problems on the client side: https://github.com/Starcounter/RebelsLounge/issues/66
3. @alshakero does Polymer 2 have `notifySplices`? If yes, then the problem will most probably also affect Polymer 2.

I will bring this up at today's Palindrom TF meeting.

**Comment by miyconst** [comment]
Thanks @warpech for taking a look into it. @chrhol please investigate the server side and fix the patch generation.

**Comment by tomalec** [comment]
Maybe it's similar issue to this one https://github.com/Polymer/polymer/issues/3682 so `notifySplice` called sequential fails.

**Comment by alshakero** [comment]
Or maybe this https://github.com/Palindrom/palindrom-polymer-client/issues/14 (without any serious investigation)

**Comment by warpech** [comment]
We discussed at the today's Palindrom TF that the client-side part of the problem is 50% likely to be gone in Polymer 2, to which we will upgrade in Q3 2017. So at this point it is really advisable to use a workaround in C# or fix it in Starcounter's server side Palindrom. We should not spend more than 1 day investigating the problem in Polymer 1.

**Comment by miyconst** [comment]
@chrhol thank you for the investigation, I will implement one of the workarounds, and I absolutely agree that we should not spend time fixing JSON Patch observers on server side for now.

**Comment by miyconst** [comment]
Archiving the issue.
