### ISSUE TITLE
Child relation helper

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#162]
I'm toying around with some SQL helpers to make my code more refactor friendly:

```csharp
    public struct Relation<T>
    {
        internal T Self;
        public QueryResultRows<TChild> ToMany<TChild>(Expression<Func<TChild,T>> exp)
        {
            //TODO: validate args, prevent injection etc. <<------           
            var m = exp.Body as MemberExpression;
            var name = m.Member.Name;
            var sql = $"select e from {typeof(TChild).Name} e where e.{name} = ?";
            return Db.SQL<TChild>(sql, Self);
        }
    }

    public static class Extensions
    {
        public static Relation<T> From<T>(T self) => new Relation<T>{ Self = self };
    }
```

This can then be used like this:

```csharp
using static Extensions;

    [Database]
    public class SalesOrder
    {
        public IEnumerable<Detail> Details => From(this).ToMany<Detail>(fk => fk.SalesOrder);
    }
```

There is of-course the extra allocations of `Expression of Func`. but maybe the ability to eventually skip the SQL parsing and generate an SQL AST directly could counter weight this.
Or, it could be replaced with just `Func` and use name magic to extract the target property, more lightweight but a lot uglier.
The overhead of the `Relation<T>` should be minimal as it is a struct and gets cleaned up directly (this is used to get rid of explicitly stating an extra generic arg of the source type)

Are there any other drawbacks that would make this a bad idea from a StarcounterDB perspective or would this be safe to use?
(I'm thinking if the weaver does anything magic with the IEnumerable property or so)

**Comment by miyconst** [comment]
This line of code has lots of string operations.

```cs
var sql = $"select e from {typeof(TChild).Name} e where e.{name} = ?";`
```

And may end up being more expensive than query execution very often.

**Comment by rogeralsing** [comment]
Not doing anything serious here, just experimenting with the impact of different SQL formats.

```csharp
public struct Relation<T>
    {
        static class SourceCache<TChild> //type level cache of select statement
        {
            internal static readonly string From = $"select e from {typeof(TChild).Name} e where e.";
        }
        internal T Self;
        public QueryResultRows<TChild> ToMany<TChild>(Expression<Func<TChild,T>> exp)
        {
            //TODO: validate args, prevent injection etc.
            var m = exp.Body as MemberExpression;
            var name = m.Member.Name;
            var sql = string.Concat(SourceCache<TChild>.From, name, " = ?");
            return Db.SQL<TChild>(sql, Self);
        }
    }
```
This brings the string allocs down to a minimum.
But what I find interesting here is that there seems to be a performance penalty to switch the order of the comparands in the where clause:

`where e.Foo = ?` vs. `where ? = e.Foo`, the latter is noticeably slower.

I saw this as I experimented to make the Concat consist of only two strings.

Is there a reason for this? I get it is somewhat unorthodox to have the comparands reversed, but semantically it should be the same, no?

**Comment by Mackiovello** [comment]
CC @k-rus

**Comment by mtornwall** [comment]
Do they produce identical query plans? You can get the plan using this trick:

```
        static string GetPlan(string query, params object[] args) {
            var sqlEnum = (SqlEnumerator<object>)Db.SQL(query, args).GetEnumerator();
            return sqlEnum.ToString();
        }
```

**Comment by rogeralsing** [comment]
I can not replicate this today, and execution plans looks the same.
Must have been a case of random delays showing false positives.
Closing this
