### ISSUE TITLE
Loaded data rendering too late to use in paper-dialog properly

### ISSUE THREAD

**Issue by LordTep** [Starcounter/Home#163]
When using a handler that saturates the view-model data on a button click that also opens a paper-dialog that is supposed to show that data this is what I end up with:

![image](https://user-images.githubusercontent.com/20333891/27426815-265e7cb8-573d-11e7-8ef9-7a5a8c342d9c.png)

@miyconst helped me with a workaround using window.requestAnimationFrame() in which I call .refit() on the dialog. This works fine for my purposes.

cc @tomalec

**Comment by tomalec** [comment]
Could you elaborate a little bit more? What is the problem with screenshot? What is JSON Patch that causes the problem (if any)? Coudl you show some code related to those bindings?

From your brief explanation on Slack, I would expect this to be a Polymer 1.x problem. That's why, if we have working workaround, I'd postpone any deep investigation after Polymer 2.x upgrade (https://github.com/Starcounter/RebelsLounge/issues/66)

**Comment by miyconst** [comment]
@tomalec the problem here is that the dialog's content is loaded with a patch. So the following happens:

- User clicks a button.
- Patch sent to the server.
- The dialog is shown.
- Polymer centers and sizes the dialog.
- Server's response patch arrived.
- The `dom-repeat` template generates items inside the dialog.
- The dialog bleeds out of the screen.

**Comment by tomalec** [comment]
Thanks for clarification :) Could you show me the HTML code with bindings? Now, I'd say it's either poor behavior of `paper-dialog`, or the way we fill the content should fit the limitation of the element we use.

**Comment by LordTep** [comment]
Sorry for late response. Here is the HTML code for the dialog.

`<paper-dialog class="gps-paper-dialog__dialog" entry-animation="scale-up-animation" exit-animation="fade-out-animation" no-cancel-on-outside-click="true" modal="true">
            <div class="gps-select-criteria-tabs">
                <template is="dom-repeat" items="{{model.CriteriaTabs}}">
                    <button class="gps-select-criteria-tabs__button" type="button" value="{{item.TabClick$::click}}" on-click="changeSelectTab" index="{{index}}" disabled="{{item.IsSelected}}">{{item.Name}}</button>
                </template>
            </div>
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-4"><b>Product Property</b></div>
                <div class="col-sm-4"><b>Goal Value</b></div>
                <div class="col-sm-3"><b>Unit</b></div>
            </div>
            <paper-dialog-scrollable>
                <template is="dom-repeat" items="{{model.ProductProperties}}">
                    <div class="row">
                        <template is="dom-if" if="{{local.isQtyCriterium}}">
                            <div class="form-condensed">
                                <div class="checkbox gps-paper-dialog__checkbox col-sm-1">
                                    <label>
                                        <input type="checkbox" checked="{{item.IsQtyDriver$::change}}" disabled="{{model.ReadOnly}}" />
                                    </label>
                                </div>
                            </div>
                        </template>
                        <template is="dom-if" if="{{!local.isQtyCriterium}}">
                            <div class="form-condensed">
                                <div class="checkbox gps-paper-dialog__checkbox col-sm-1">
                                    <label>
                                        <input type="checkbox" checked="{{item.IsChecked$::change}}" disabled="{{model.ReadOnly}}" />
                                    </label>
                                </div>
                            </div>
                        </template>
                        <div class="col-sm-4">{{item.DisplayName}}</div>
                        <div class="col-sm-4">{{item.DisplayGoalValues}}</div>
                        <div class="col-sm-3">{{item.Unit}}</div>
                    </div>
                </template>
            </paper-dialog-scrollable>
            <div class="gps-paper-dialog__dialog-buttons">
                <button class="btn btn-xs btn-default btn-transparent" value="cancel" on-click="closeDialog">
                    <palma-icon name="cancel" state="big"></palma-icon>
                </button>
                <button class="btn btn-xs btn-default btn-transparent" value="confirm" on-click="closeDialog" dialog-confirm>
                    <palma-icon name="ok" state="big"></palma-icon>
                </button>
            </div>
        </paper-dialog>`

**Comment by miyconst** [comment]
The problem was solved in offline mode. Closing the issue.
