### ISSUE TITLE
QUESTION: Get control over <head> tag

### ISSUE THREAD

**Issue by iSuslov** [Starcounter/Home#165]
Hi, sorry if I missed it in the doc, but I want to set the viewport for the app

`<meta name="viewport" content="width=device-width, initial-scale=1.0">` 

how can I do that?

**Comment by Mackiovello** [comment]
Hi again!

The only way to do that right now is to overload `PartialToStandaloneHtmlProvider`. Read more about it here: https://docs.starcounter.io/guides/network/middleware/

```c#
string html = @"<!DOCTYPE html>
<html>
<head>
    <meta charset=""utf-8"">
    <title>{0}</title>
    <script src=""/sys/webcomponentsjs/webcomponents.min.js""></script>
    <script>
      window.Polymer = {{
        dom: ""shadow""
      }};
    </script>
    <link rel=""import"" href=""/sys/polymer/polymer.html"">
    <link rel=""import"" href=""/sys/starcounter.html"">
    <link rel=""import"" href=""/sys/starcounter-include/starcounter-include.html"">
    <link rel=""import"" href=""/sys/starcounter-debug-aid/src/starcounter-debug-aid.html"">
    <link rel=""import"" href=""/sys/bootstrap.html"">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{
            margin: 20px;
        }}
        body > starcounter-include{{
            height: 100%;
        }}
    </style>
</head>
<body>
    <template is=""dom-bind"" id=""puppet-root"">
        <starcounter-include view-model=""{{{{model}}}}"" partial-id$=""{{{{model.Html}}}}""></starcounter-include>
    </template>
    <puppet-client ref=""puppet-root"" remote-url=""{1}""></puppet-client>
    <starcounter-debug-aid></starcounter-debug-aid>
</body>
</html>";

Application.Current.Use(new PartialToStandaloneHtmlProvider(html));
```

I'm closing as answered, please reopen if you don't think it answers the question.

**Comment by atifwaqar** [comment]
@Mackiovello 
Thanks for your response. This worked, but I was stuck in 1 tiny thing for a while, the sequence of `HtmlFromJsonProvider` and `PartialToStandaloneHtmlProvider` matters.
```cs
            Application.Current.Use(new HtmlFromJsonProvider());
            Application.Current.Use(new PartialToStandaloneHtmlProvider(html));
```
If write as following, I dont see my expected results.
```cs
            Application.Current.Use(new PartialToStandaloneHtmlProvider(html));
            Application.Current.Use(new HtmlFromJsonProvider());
```

**Comment by atifwaqar** [comment]
However, it doesn't work if Launcher app is running. I suppose this should be reported as a bug?

**Comment by Mackiovello** [comment]
> If write as following, I dont see my expected results.

Yes, that's because there will be no HTML to wrap without first having `HtmlFromJsonProvider`. It's explained on the page I linked.

> However, it doesn't work if Launcher app is running. I suppose this should be reported as a bug?

That's interesting. Do you get any error or do you only get the template without any wrapping, like so:

```html
<template>
 ...
</template>
```

**Comment by atifwaqar** [comment]
> Do you get any error or do you only get the template without any wrapping, like so:

No errors, I get a template without any wrapping.

**Comment by Mackiovello** [comment]
Since Launcher is moved to the [freezer](https://github.com/starcounterappsfreezer) and is no longer maintained, I don't think we have to worry about this. If it comes up in any other app, we'll look into it.

**Comment by atifwaqar** [comment]
Makes sense. 
Thanks @Mackiovello
