### ISSUE TITLE
QUESTION: Polymer 2.0 support

### ISSUE THREAD

**Issue by iSuslov** [Starcounter/Home#167]
Hello again!
I know that polymer 1.x is injected by default. And support for polymer 2.0 is on the way. Is it possible to get rid of this injection and use polymer 2 installed by the bower?

**Comment by Mackiovello** [comment]
Hi! 

Polymer is served from `C:\Program Files\Starcounter\ClientFiles\StaticFiles\sys\polymer`. You could exchange Polymer 1.9.1, which is in the current version, with 2.0. I don't have any guarantees that it will work.

You could also add Polymer to the `sys` folder of an app and link from it in the overload of `PartialToStandaloneHtmlProvider`. Again, this is my qualified guess.

I don't know what you would do to install it with Bower.

Summoning the expert @tomalec

**Comment by iSuslov** [comment]
Well, what I made is replaced polymer 1.x with 2.x and got an issue where 
`<starcounter-include view-model="{{{{model}}}}" partial-id$="{{{{model.Html}}}}">
    <juicy-composition auto-stamp="">
        <template is="imported-template"></template>
    </juicy-composition>
</starcounter-include>`
not working. So no include happens. I believe it happens because `<template is="dom-bind">` was replaced with `<dom-bind>` in polymer 2.x and probably SC is somehow looks for old `[is="dom-bind"]` and can not find it. Do you know guys why include is broken?

**Comment by miyconst** [comment]
@tomalec please take a look.

**Comment by Mackiovello** [comment]
Yes, that's probably because `<starcounter-include>` and the other web components are not adapted for Polymer 2.0. If I were you, I would wait until we've made our elements [hybrid](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements) which is not too far away.

**Comment by atifwaqar** [comment]
@Mackiovello the thing is, we need to make a demo in Polymer 2.0. and i guess its ok if we dont use `<starcounter-include>`
for this demo we can put all of our code in `PartialToStandaloneHtmlProvider` html

**Comment by Mackiovello** [comment]
@alshakero did you look at something similar or am I mistaken?

**Comment by atifwaqar** [comment]
Nup, I haven't look anything similar. 
But I know Polymer 2.0 can be used in SC somehow.

**Comment by Mackiovello** [comment]
I was referring to https://github.com/StarcounterApps/HelloWorld/issues/45 where @alshakero tried to make a HelloWorld fork with Polymer 2.0. Let's wait for @warpech and @tomalec get back to you

**Comment by iSuslov** [comment]
I can confirm that inside `<dom-bind>` model is not binding to anything.

**Comment by warpech** [comment]
`starcounter-include` right now uses Polymer's notification protocol, hardcoded. That can be made to work with Polymer 2, but we decided to go the clean way and reimplement it in a decoupled way.

We would rather not take any shortcuts, but I guess we can give it a try.

@atifwaqar, @iSuslov - it appears that you work together, is this correct? Is it possible for you to expose a repo for us where we can investigate? Maybe it is few lines to fix it, if we focus on a particular use case.

Out of curiosity, what makes you need to present a demo particularly in Polymer 2? Can you consider a different approach - make the demo in Polymer 1, but use hybrid elements that also work in Polymer 2?

Btw. the owner of Palindrom & Polymer 2 integration is @alshakero.

**Comment by warpech** [comment]
> Is it possible to get rid of this injection and use polymer 2 installed by the bower?

@iSuslov in general you can overwrite any files in Bower by installing them in path `wwwroot/sys/`. So the files in your app's `wwwroot/sys` will overwrite Starcounter's `sys` files. But that only takes you that far.

**Comment by tomalec** [comment]
> I can confirm that inside `<dom-bind>` model is not binding to anything.

That's true, as @warpech mentioned above, we had to workaround many bugs from Polymer 1.x in `starcounter-include` that's why we tangled 1.x notification protocol there, which may not work with `<dom-bind>`. However as we support any vanilla elements, as the DOM is the API, we still attach `model` property to all elements (including `<dom-bind>`). So theoretically you should be able to write Polymer2.x apps on your own. Most probably you will have to adjust `PartialToStandaloneHtmlProvider` to tweak `palindrom-client` a little bit, as it is Polymer 1.x element, or just use `Palindrom` manually.

But I need to see some code, to advice anything specific.

**Comment by warpech** [comment]
For everyone's information, @iSuslov's are now being answered on Slack. We will look into supporting him with Polymer 2 before we can officially ship Polymer 2 with Starcounter (which will be  around Sep 2017).

**Comment by alshakero** [comment]
I created the simplest possible example, simple but still puts one on the right path, in a [branch](https://github.com/StarcounterApps/HelloWorld/tree/polymer-2) of the HelloWorld app. And here is the [most interesting file](https://github.com/StarcounterApps/HelloWorld/blob/polymer-2/src/HelloWorld/Program.cs).

To see it first person, please clone HelloWorld app, checkout `polymer-2` branch, and run the app in Visual Studio.

**Comment by atifwaqar** [comment]
This is good. Just 1 question, `PersonJson.html` is not used at all, am I right?
all the html I see is from `HTML` variable from here `Application.Current.Use(new PartialToStandaloneHtmlProvider(HTML));`, right?

**Comment by warpech** [comment]
`PartialToStandaloneHtmlProvider` inserts root `starcounter-include`. JSON returned from `PersonJson.json` is passed to this include. Include finds `PersonJson.html` in JSON and renders the template found in that file.

**Comment by atifwaqar** [comment]
but to my understanding, in this demo, `PersonJson.html` is not used/rendered at all. I cleaned up the code from this html file, and i still see the same result

**Comment by warpech** [comment]
Ahh... I was not aware of it, I think you are right. The complete view sits here: https://github.com/StarcounterApps/HelloWorld/blob/polymer-2/src/HelloWorld/Program.cs#L46-L69. That must be a temporary solution.

**Comment by atifwaqar** [comment]
okay, so my 2nd question, if our frontend guy develops webcomponents in Polymer 2.0, and make it work in this suggested temporary solution, Will the same webcomponents code work when SC will fully support Polymer 2.0?

**Comment by warpech** [comment]
You will need to do some CTRL+C, CTRL+V. Perhaps with some text replace. But it surely will be just a simple refactoring.

**Comment by atifwaqar** [comment]
Yes CTRL+C/V is fine. I can manage that. So okay, we'll move forward by adding all HTML code in this variable, and hopefully, it will work fine.
Thanks guys for your help :)

**Comment by alshakero** [comment]
@atifwaqar anytime!

**Comment by miyconst** [comment]
Closing the issue as answered question.
