### ISSUE TITLE
ScErrCLRDecToX6DecRangeError when using X6Decimal.MaxValue/X6Decimal.MinValue

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Home#168]
Getting runtime error when assigning a decimal database property to  `Starcounter.Internal.X6Decimal.MaxValue` or `Starcounter.Internal.X6Decimal.MinValue`

`Additional information: ScErrCLRDecToX6DecRangeError (SCERR4246): The CLR Decimal cannot be converted to a Starcounter X6 decimal without data loss. Range error.`

Starcounter Version=2.3.1.6666 (ze # of the beast)

**Comment by mtornwall** [comment]
Actually not a bug, though the naming is quite unfortunate.

Notice that the type of `{Min,Max}Value` is `long`. This, I believe, is because it represents the minimum and maximum raw value (encoded as a `long`), so this works:

```csharp
dbObj.DecimalProperty = X6Decimal.FromRaw(X6Decimal.MaxValue);
```

Use `X6Decimal.{Min,Max}DecimalValue` instead.

**Comment by ubbeK** [comment]
Thanks for that explanation.

Closing, invalid.
