### ISSUE TITLE
Obsolete/drop class Entity and Inherits, Type and TypeName attributes 

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#172]
The `Starcounter` assembly contains some public classes and attributes that comes from discontinued work and in the current shape are not working.

Each of these items should be marked as obsolete in `2.3` and dropped in `2.4` (aka `develop`) 

List of items (class and attributes) to be obsoleted/dropped:
- Entity
- InheritsAttribute
- TypeAttribute
- TypeNameAttribute

**Comment by per-samuelsson** [comment]
I vote we don't even touch them in `2.3` and just drop them in `2.4`. I doubt they are in use anywhere by our external customers.

@k-rus, would you have something to object to us dropping all these?

**Comment by k-rus** [comment]
Where are those attributes in the SQL regression test? I guess they can be dropped.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.
