### ISSUE TITLE
Data fetching error

### ISSUE THREAD

**Issue by nazmuladfenix** [Starcounter/Home#177]
I am running a count query like this 
```C#
Db.SQL<Int64>("SELECT COUNT(ca) FROM AdFenix.Database.Ecommerce.Seller ca WHERE 
PublicationOwner = ? and Name LIKE ?", (adfenixUser as PublicationOwner), "%" + searchText + "%");
```
Result: 63
 But when I am trying to select data by select query like this 
```C#
Db.SQL<Seller>("SELECT ca FROM AdFenix.Database.Ecommerce.Seller ca WHERE 
PublicationOwner = ? and Name LIKE ? ORDER BY Name ASC FETCH ? OFFSET ?",
(adfenixUser as PublicationOwner), "%" + searchText + "%", fetch, offset); 
```
where FETCH value is 10 and OFFSET value is 20 or more its through an exception like " System.IndexOutOfRangeException: Index was outside the bounds of the array. " If the OFFSET value is less than 20 then it's works fine.

Note: When I am running same query in database works fine

**Comment by Mackiovello** [comment]
> Note: When I am running same query in database works fine

So the query works when running in the administrator but not in the application code with `Db.SQL`? 

Just a hint for future reference, please [code blocks and syntax highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for future issues. It makes it much easier to read the code. For example:

```cs
Db.SQL("SELECT COUNT(ca) FROM AdFenix.Database.Ecommerce.Seller ca WHERE PublicationOwner = ? 
    and Name LIKE ?",
    (adfenixUser as PublicationOwner), "%" + searchText + "%");
```

**Comment by k-rus** [comment]
Thank you for reporting the issue. If somebody can prepare a small isolated reproduction test, it would be great. Currently it is difficult to say if it is easy or difficult to reproduce.
I add it to my to-do list and hope to find time after vacation.

**Comment by k-rus** [comment]
What version of Starcounter?

**Comment by nazmuladfenix** [comment]
Thanks for such a quick response. I am using 

> Starcounter-RC-2.3.0.5971

 version. I am currently stuck with this issue. Is it fixed in the latest version ?

**Comment by k-rus** [comment]
> I am currently stuck with this issue.

I suggest you use a work around. If I understood you correctly, you get correct result if you write query without fetch and offset. Is it correct?

**Comment by nazmuladfenix** [comment]
Yes, but with fetch and offset the query works fine if the offset value is less than or equal 20.

**Comment by nazmuladfenix** [comment]
There is an update about the problem. 
If I remove sorting ("ORDER BY Name ASC") from the query then everything works fine.

**Comment by k-rus** [comment]
> If I remove sorting ("ORDER BY Name ASC") from the query then everything works fine.

Thank you for clarifying. So the bug is narrowed down that fetch and offset doesn't work properly in the case of sorting. If you have opportunity, can you provide query plan? It will help me to confirm my guess that it is not using sorted index and runs sort operator.

**Comment by nazmuladfenix** [comment]
Here is the query plan

> Tables(

 0 = AdFenix.Database.Ecommerce.Seller
 1 = AdFenix.Database.PublicationOwner
)
Projection(
 0 = 
  ObjectThis(0)
)
Join(
 Inner
 IndexScan(
  CompanyIndex ON AdFenix.Database.Company
  0
  Name
  StringDynamicRange(
  )
  IsTypePredicate(
   IS
   ObjectThis(0)
   AdFenix.Database.Ecommerce.Seller
  )
  Ascending
 )
 ReferenceLookup(
  1
  ObjectProperty(0, PublicationOwner)
  ComparisonNumerical(
   Equal
   ObjectNoProperty(1, ObjectNo)
   IntegerLiteral(213511)
  )
 )
 Fetch Number(
  IntegerLiteral(10)
 )
 Fetch Offset(
  IntegerLiteral(30)
 )
)

**Comment by k-rus** [comment]
Thank you for the query plan. Is it the execution plan for the query where sorting is present? I.e. the second query in https://github.com/Starcounter/Home/issues/177

If so, then my assumption is not hold.

**Comment by nazmuladfenix** [comment]
Thanks for the reply. Yes this query plan is where sorting present.

**Comment by un-tone** [comment]
I tried without success to reproduce the issue with this test app: <https://gist.github.com/un-tone/ec93906434164757a7c6d36a1c60cd1f>.

I have such model:
```cs
[Database]
public class PublicationOwner
{
    public int Id { get; set; }
}
[Database]
public class Company
{
    public string Name { get; set; }
}
[Database]
public class Seller : Company
{
    public PublicationOwner PublicationOwner { get; set; }
}
```

I populated DB with 100 rows and created the following index:

```cs
Db.SQL($"CREATE INDEX Company_Name_Index ON Home_177.Company (Name)");
```

and use the following query:

```cs
Handle.GET("/test-complex", () =>
{
    // ...............
    var sellers = Db.SQL<Seller>($"SELECT ca FROM Home_177.Seller ca " +
                              "WHERE PublicationOwner = ? AND Name LIKE ? " +
                              "ORDER BY Name ASC FETCH ? OFFSET ?",
                              owner, "%" + searchText + "%", 10, 30);
    return "success " + sellers.Count();
});
```

I guess the case in the data model and I can miss something. @nazmuladfenix could you take a look at this, maybe you have some clues?

I tested in SC 2.3.0.6350

**Comment by nazmuladfenix** [comment]
You don't need to add [Database] attribute on "Seller" because you have already added once on base class "Company".

Just remove database attribute from Seller  class.

**Comment by un-tone** [comment]
@nazmuladfenix it doesn't change the case. I hoped to get some clues regarding data model or something else.

**Comment by miyconst** [comment]
@nazmuladfenix can you still reproduce the issue?
