### ISSUE TITLE
download link doesnt working

### ISSUE THREAD

**Issue by ersintarhan** [Starcounter/Home#180]
Hello, 
Download link on http://downloads.starcounter.com/download/Starcounter/Release/latest does not working. Could you please check ?

**Comment by SenerDemiral** [comment]
Same on Develop!

**Comment by Mackiovello** [comment]
Thank you both for notifying us! We're looking into it at the moment to find what's wrong. Hopefully, we'll have it up and running as soon as possible.

**Comment by Mackiovello** [comment]
While we're working on this, here's the link for the latest RC build: https://drive.google.com/file/d/0B7ErcI3u1ERkTTVZS0dPeERzTGc/view?usp=sharing

Here's the link for the latest develop:
https://drive.google.com/file/d/0B7ErcI3u1ERkR0FBdExaVGI5czg/view?usp=sharing

**Comment by Mackiovello** [comment]
All the latest versions are available for download again! I apologize for the inconvenience

**Comment by SenerDemiral** [comment]
Latest Develop still shows:  2.4.0.2029 (Jun 12, 2017 2:01:48 AM)
