### ISSUE TITLE
Read value from app.config file

### ISSUE THREAD

**Issue by muna-adfenix** [Starcounter/Home#181]
Hello guys,
I have an app.config file in starcounter console app. I have added some configuration data in this file. For example:
```
<configuration> 
<appSettings> 
<add key="Environment1" value="Test-1" /> 
<add key="Environment2" value="Test-2" /> 
<add key="Environment3" value="Test-3" />
 </appSettings> 
</configuration>
```
But when I read this value from code its returns null. For example:
```
var configvalue1 = ConfigurationManager.AppSettings["Environment1"]; 
var configvalue2 = ConfigurationManager.AppSettings["Environment2"]; 
var configvalue3 = ConfigurationManager.AppSettings["Environment3"];
```

Even if when I tried to get value by section, it returns 0(Zero) key of this section. For example
`var appsettings = ConfigurationManager.GetSection("appSettings");`

Is there any way to read the value from app.config file?
Need Help, Thanks in advance.

**Comment by joozek78** [comment]
Starcounter doesn't respect `app.config` files - that's because the process is "merged" into `sccode.exe`.

> Is there any way to read the value from app.config file?

AFAIK you could just find the file and open it like any other on filesystem.

If you feel my answer isn't helpful / complete, please reopen

**Comment by muna-adfenix** [comment]
Great, Then how starcounter manage configuration related data, which vary in the different build environment.

**Comment by joozek78** [comment]
@muna-adfenix What exactly you want to achieve? Our preferred way of storing anything is in the database. You can Check what is your current environment and use it decide which configuration to fetch from DB
