### ISSUE TITLE
Indexed lookup by decimal field may fail

### ISSUE THREAD

**Issue by bigwad** [Starcounter/Home#182]
Indexed lookup doesn't work for certain values. For instance, such code fails:

```csharp
    [Database]
    public class A
    {
        public decimal f;
    }

            Db.SQL("create index a_index on A (f)");
            Db.Transact(() =>
            {
                var a = new A { f = Starcounter.Internal.X6Decimal.MaxDecimalValue };
                Trace.Assert(Db.SQL("select a from A a where a.f=?", a.f).Any());
            });
```

**Comment by un-tone** [comment]
It seems that QP builds `IntegerDynamicRange` by mistake instead of DecimalDynamicRange:

```
{Tables(
	0 = Home_182.A
)
Projection(
	0 = 
		ObjectThis(0)
)
IndexScan(
	a_index ON Home_182.A
	0
	f
	IntegerDynamicRange(
		NumericalRangePoint(
			GreaterThanOrEqual
			NumericalVariable(4398046511103.999999)
		)
		NumericalRangePoint(
			LessThanOrEqual
			NumericalVariable(4398046511103.999999)
		)
	)
	LogicalValue(TRUE)
	Ascending
)
}
```

Checked in SC 2.3.2.141 and 2.4.0.4692

**Comment by un-tone** [comment]
> QP builds IntegerDynamicRange by mistake instead of DecimalDynamicRange

It's not. There is just [an error in the printing](https://github.com/Starcounter/level1/blob/cc97a436146c6b7d45a39555ac249a46637b63a7/src/Starcounter.QueryProcessor/Query/Execution/Ranges/DecimalDynamicRange.cs#L225).

**Comment by miyconst** [comment]
@un-tone please remember to update the change log.

**Comment by un-tone** [comment]
Updated the changelog. Closing as done.
