### ISSUE TITLE
Administrator UI for database settings does not cover all properties

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Home#188]
My database config (`C:\Users\tomalec\Documents\Starcounter\Personal\Databases\Default\Default.db.config`) contains much more properties than UI covers (http://localhost:8181/#/databases/default/settings)

```xml
<LoadEditionLibraries>true</LoadEditionLibraries>
<WrapJsonInNamespaces>true</WrapJsonInNamespaces>
<UseAlternativeNamespacesForJson>true</UseAlternativeNamespacesForJson>
<EnforceURINamespaces>false</EnforceURINamespaces>
<MergeJsonSiblings>true</MergeJsonSiblings>
<XFilePathHeader>false</XFilePathHeader>
<UriMappingEnabled>true</UriMappingEnabled>
<OntologyMappingEnabled>true</OntologyMappingEnabled>
<RequestFiltersEnabled>true</RequestFiltersEnabled>
<TempDirectory>C:\Users\tomalec\Documents\Starcounter\Personal\Temp\Default\Default-20170606T025146313</TempDirectory>
<ImageDirectory>C:\Users\tomalec\Documents\Starcounter\Personal\Data\Default\Default-20170606T025146313</ImageDirectory>
<TransactionLogDirectory>C:\Users\tomalec\Documents\Starcounter\Personal\Data\Default\Default-20170606T025146313</TransactionLogDirectory>
<SQLProcessPort>8066</SQLProcessPort>
<DefaultUserHttpPort>8080</DefaultUserHttpPort>
<DefaultSessionTimeoutMinutes>20</DefaultSessionTimeoutMinutes>
<ChunksNumber>65536</ChunksNumber>
<SchedulerCount xsi:nil="true" />
```

vs.
![Admin UI screenshoot with just three properties to set](https://user-images.githubusercontent.com/17435/28581206-f7a5b352-7161-11e7-9ddd-85262e8b7994.png)

Therefore Web UI is not so 100% compatible alternative to chaning file manually as the docs suggests https://docs.starcounter.io/guides/database/database-configuration/
https://docs.starcounter.io/guides/working-with-starcounter/administrator-web-ui/

Are we hiding some of those on purpose?

//cc @Mackiovello @andwah

**Comment by Mackiovello** [comment]
I've adjusted the pages linked above to reflect that you can just configure a subset of the options from the Administrator.

I'm not sure why it's the way it is, but I guess it's because most of the options are not relevant such as 
```xml
<UriMappingEnabled>true</UriMappingEnabled>
<OntologyMappingEnabled>true</OntologyMappingEnabled>
```

**Comment by andwah** [comment]
> Are we hiding some of those on purpose?

i think we just added the fields we thought where necessary at the time to to UI and after that new fields where added to the configuration file and not added to the UI.

**Comment by Mihaiii** [comment]
Can this be closed in favor of https://github.com/Starcounter/level1/issues/3891 ?

**Comment by Mihaiii** [comment]
Closing as done.
