### ISSUE TITLE
Update Administrator to use Palindrom.filterLocalChange

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Home#189]
The administrator now depends on filterChangedCallback which will be removed after https://github.com/Palindrom/Palindrom/issues/142 is implemented. 

Use `Palindrom.filter` instead.

**Comment by warpech** [comment]
It is now called `Palindrom.filterLocalChange` and is explained in https://palindrom.github.io/#/docs/v3.0.5/03-Filtering%20Patches

**Comment by alshakero** [comment]
Sorry, this is implemented long ago but I forgot to refer to the issue in my PR. 

https://github.com/Starcounter/level1/commit/b737da745cd4656fa5fe874565c0dda7c54d065b (August 28th).
