### ISSUE TITLE
Download "Develop" disappeared!

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#192]

**Comment by Mackiovello** [comment]
That's not good. @andwah @alemoi do you guys know anything?

**Comment by alemoi** [comment]
I think its related to usage of VS 2017 during build of installer for `develop`.  How urgent is this? I can provide the link to latest build from TeamCity.

**Comment by SenerDemiral** [comment]
Link is enough for me.

**Comment by alemoi** [comment]
> Link is enough for me.

Sorry for the late response, here it is: https://www.dropbox.com/s/rfohmjpzdzunsxt/Starcounter-Develop-2.4.0.2418-Setup.exe?dl=0

**Comment by SenerDemiral** [comment]
Never mind, thank you.

**Comment by SenerDemiral** [comment]
@alemoi Is there any improvement?

**Comment by alemoi** [comment]
> @alemoi Is there any improvement?

Yes, almost fixed! We have a side problem with Nuget at the moment, but once its solved, I will report here!

**Comment by alemoi** [comment]
Should be fixed now.
