### ISSUE TITLE
No versions after 2.3.1.6826 works for us

### ISSUE THREAD

**Issue by RickardR** [Starcounter/Home#193]
Something has happened since 6839. For us , no versions after 6826 works, at all.

For our server we're developing right now, the masterpage is not loaded, at all, if we install anything after that version. There is no indication on what goes wrong , except after the Palindrome version (6846), in that case we do get an error in the browser:
Nothing is logged in the starcounter log. Except for the below message.

palindrom-dom.min.js:2 Uncaught Error: remoteUrl is required
    at e (palindrom-dom.min.js:2)
    at HTMLElement.attached (palindrom-client.html:201)
    at HTMLElement.puppetClient.attached (palindrom-client.html:608)
    at Array.<anonymous> (polymer-micro.html:279)
    at Object._makeReady (polymer-micro.html:118)
    at polymer-micro.html:124

What changes have you made since version 6826? I'm unable to find any information at all. Something has made the latest versions 100% incompatible with our existing code.

**Comment by warpech** [comment]
@alshakero could you pls take a look?

**Comment by alshakero** [comment]
Sure.

Could you please share `Program.cs` code here?

**Comment by RickardR** [comment]
Suppose you want the handler? It's not gonna help you much :)

public class DoctrinProgram
    {
        internal const string RootUrl = "/doctrin";

        static void OnDatabaseShutdown(object sender, EventArgs e)
        {
        }

        static void Main()
        {
            Db.DatabaseStopping += OnDatabaseShutdown;

            ScheduleJobsAdmin.Init();

            EvisitLogModule.Initialize();
            EvisitLogModule.AddSystemLogger(new StarcounterLogLogger());

            // Assure Indexes!
            EvisitLogModule.Log("Assuring indexes", LogSeverity.Low, LogReason.SystemInformation, LogTarget.System);
            IndexUtil.AssureIndexes();

            // Init system config singleteon.
            SystemConfigurationSingleton.Init();

            IDoctrinHandlers handlers = new DoctrinHandlers();
            handlers = new DoctrinAPIAuthenticationHandlers(handlers);
            handlers = new DoctrinAdministrationHandlers(handlers);
            handlers = new DoctrinDashboardHandlers(handlers);
            handlers = new DoctrinCaseHandlers(handlers);
            handlers = new DoctrinApiAdminHandlers(handlers);
            handlers.CreateHandlers();            
            
        }

**Comment by RickardR** [comment]
Handlers for the landing page
Handle.GET("/doctrin", () =>
            {
                MasterPage master;

                if (Session.Current != null && Session.Current.Data != null)
                {
                    master = (MasterPage)Session.Current.Data;
                }
                else
                {
                    master = new MasterPage();
                    UserSession us = new UserSession(master);
                    if (Session.Current != null)
                    {
                        master.Html = "/doctrin/LauncherWrapperPage.html";
                        master.Session = Session.Current;
                    }
                    else
                    {
                        master.Html = "/doctrin/MasterPage.html";
                        master.Session = new Session(SessionOptions.PatchVersioning | SessionOptions.StrictPatchRejection);
                        master.Data = us;
                    }

                    master.IndexPage = new UserSessionPage()
                    {
                        Html = "/doctrin/login.html",
                        Data = us,
                    };
                }
                return master;
            });

            AuthorizedHandler.GET("/doctrin/homepage", () =>
            {
                MasterPage master = Self.GET<MasterPage>("/doctrin");
                if (!(master.IndexPage is HomePage))
                {
                    master.IndexPage = GetLauncherPage("/doctrin/partials/homepage");
                }
                return master;
            });

            AuthorizedHandler.GET("/doctrin/partials/homepage", () =>
            {
                HomePage indexPage = new HomePage()
                {
                    Html = "/doctrin/homepage.html",
                };

                return indexPage;
            });

**Comment by alshakero** [comment]
I see. Could you please go to the app homepage (that is not working) and show me the source. From the browser?

**Comment by RickardR** [comment]
Will do, got some problems atm but ill do it asap

**Comment by warpech** [comment]
Please compare the dates from the nightly builds (http://downloads.starcounter.com/) and the changelog (https://github.com/Starcounter/level1/commits/v2.3/CHANGELOG.md) and our blog (https://starcounter.io/blog/).

Is there some migration path that we forgot to announce, or warnings that we should throw but don't?

**Comment by RickardR** [comment]
Cannot see antyhing that should break it in the logs. I think it's something badly written on my side. I'll do some refactoring (I see some stuff that really needs to change anyway), and get back here fairly soon if I cannot solve it.

**Comment by alshakero** [comment]
I really recommend sharing the HTML source before that.

**Comment by warpech** [comment]
I think that `/doctrin/MasterPage.html` is the problem. Our current advice is not to have a `/doctrin/MasterPage.html` but use the standard one provided by `PartialToStandaloneHtmlProvider`. Then, your app only needs to provide `/doctrin/LauncherWrapperPage.html` at all times.

**Comment by RickardR** [comment]
Sorry been quite busy with non-coding stuff last couple of days (bleh!)

Got it to work. Refactored the code to be more like masterpage in the Persons project, and used PartialToStandaloneHtmlProvider as per @warpech  recommendation.

Though, didn't work first, but that was because  my masterpage.json inherited from Page, not Json. Then it didn't work at all. 

Don't know what was wrong before, but now at least  I can continue. I've also started using Session.Store instead, since you've marked Session.Current.Data deprecated sometime after *6826 , and the code is more as per recommendation :) Running on 6924 now, so all is good.
