### ISSUE TITLE
Optimization Suggestion: Replace ThreadStatic for round-robin index with interlocked increments

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#195]
https://github.com/Starcounter/level1/blob/e429db17fbf7e37be55a41d40978e5afb4378862/src/Starcounter/DbSession.cs#L148

ThreadStatics are very heavyweight as their data needs to be looked up via thread storage.
Having a shared round robin index using interlocked increments would be more efficient.

**Comment by bigwad** [comment]
I disagree here. Managed ThreadStatics are super optimized, but what is more important - it scales on multicore while interlocked functions don't scale and lead to heavy contention on multicore. 

Here are results of my [benchmark](https://gist.github.com/bigwad/58d8fa7c248c223b78325fa46502ca51) performing 10M of increments in a specified number of threads. ```Interlocked``` and ```threadstatic``` rows are self-explained and ```direct``` is just unguarded ++ operator.

Method | N of cores | Mean | Error | StdDev 
------------ | ------------- | --------------- | -------------- | ----------------
interlocked |            1 |    53.76 ms | 0.2019 ms | 0.1888 ms
threadstatic |            1 |    20.81 ms | 0.1194 ms | 0.0997 ms
direct | 1 |    19.65 ms | 0.3924 ms | 0.6109 ms
interlocked |            4 |   761.59 ms | 3.0653 ms | 2.8673 ms
threadstatic |            4 |    20.00 ms | 0.1575 ms | 0.1473 ms
direct |            4 |    27.27 ms | 0.9758 ms | 2.8771 ms
interlocked |            8 | 1,521.86 ms | 1.4767 ms | 1.3813 ms
threadstatic |            8 |    20.29 ms | 0.4093 ms | 0.7787 ms
direct |            8 |    56.48 ms | 0.2818 ms | 0.2498 ms

I think even some retarded ThreadStatic implementation, say with a dictionary under the hood, would outperform interlocked starting from a certain number of cores. So if one can make a progress with share nothing - it's the way to go. An alternative to TLS here might be passing some context explicitly, but in this case I think it's unpractical.

**Comment by bigwad** [comment]
Suddenly I realized that inlining and hyperthreading might have influenced the results, so I factored them out (updated benchmark code by the same link). 
Basically, the same trend  - steady threadstatic and non-scalable interlocked.

Method | N of cores | Mean | Error | StdDev 
------------ | ------------- | --------------- | -------------- | ----------------
run_interlocked |            1 |  53.33 ms | 0.1430 ms | 0.1268 ms
run_threadstatic |            1 |  67.91 ms | 0.3705 ms | 0.3466 ms
run_direct |            1 |  16.97 ms | 0.1498 ms | 0.1328 ms
run_interlocked |            2 | 388.60 ms | 3.5507 ms | 3.3213 ms
run_threadstatic |            2 |  68.12 ms | 0.4103 ms | 0.3637 ms
run_direct |            2 |  61.27 ms | 1.2423 ms | 3.6628 ms
run_interlocked |            4 | 762.88 ms | 1.2725 ms | 1.1280 ms
run_threadstatic |            4 |  70.60 ms | 0.8786 ms | 0.8219 ms
run_direct |            4 | 170.59 ms | 0.2250 ms | 0.2105 ms

**Comment by rogeralsing** [comment]
Interesting, we saw some really bad numbers when touching thread-statics back when building the mailbox for Akka.NET. 
Do you know if there is there a difference of storing primitives and object references in them?

**Comment by bigwad** [comment]
>Do you know if there is there a difference of storing primitives and object references in them?

Almost no difference. But again - the main pro for ThreadStatic is the scaling.

**Comment by miyconst** [comment]
@rogeralsing thank you for the suggestion.

Archiving the issue as won't be fixed, at least not now.
