### ISSUE TITLE
Optimization Suggestion: Replace ConcurrentQueue with MpscQueues

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#196]
In the current implementation of the .NET Schedulers we use ConcurrentQueue.
ConcurrentQueue is fairly well designed, but it does generate a lot of GC pressure under load due to the need to allocate new chunks.

We could improve the performance of the schedulers in .NET by replacing the ConcurrentQueues with fixed size MpscQueues (https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Mailbox/MPMCQueue.cs#L36)

These are a lot faster to interact with as they are allocation free and ConcurrentQueue is not.
As we have a fixed number of schedulers, having bounded queues of a semi large size, e.g. 1000-10000 slots would not be a problem.

**Comment by miyconst** [comment]
@alemoi how relevant is this suggestion? As far as I know, we are planning to move to the native .net scheduling.

**Comment by alemoi** [comment]
@rogeralsing thanks for finding this out. Though I think we should instead concentrate on native .NET scheduling asap, so I agree with @miyconst point.

**Comment by alemoi** [comment]
I don't this is actual at the moment, since we are moving towards Nova. Will close the issue.
