### ISSUE TITLE
ReSharper cannot resolve the symbol when QueryResultRows is used

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#201]
I have a simple program that works fine (I will use screenshots with a code on purpose):
![resharper1](https://user-images.githubusercontent.com/4943949/29121718-076ac872-7d10-11e7-8324-c6cbb99d4a11.png)

When I change `IEnumerable` to `QueryResultRows` (line 20) ReSharper says "Cannot resolve symbol `Something`" and marks it red (line 24). I use VS2017.

![resharper2](https://user-images.githubusercontent.com/4943949/29121771-41db4018-7d10-11e7-8918-1f3b8c6ee359.png)

It's important that program compiles and works fine. Also, the problem disappears when I suspend ReSharper. Anybody experienced the same? Can we do something about it?

If you want to copy code:
```csharp
namespace Test
{
    [Database]
    public class Entity
    {
        public string Something;
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() => {
                QueryResultRows<Entity> resultSet = Db.SQL<Entity>("SELECT c FROM Test.Entity c");

                foreach (var item in resultSet)
                {
                    item.Something = "aasa";
                }
            });
         }
    }
}
```

cc @Starcounter/sc-apps

**Comment by PatrykSzwer** [comment]
I've tested this on ReSharper version `2017.1.2`, same result. Most of the times I saw and used myself second type projection (which is obviously not needed and shouldn't be done like that, but I just though that It won't build without it). I would love to see this issue fixed.

**Comment by mmnosek** [comment]
>  I would love to see this issue fixed
I expect that we need to ask ReSharper guys for this ;)

**Comment by bigwad** [comment]
Why do you use this type? I would say don't use to be compatible with upcoming Starcounter.Core

**Comment by mmnosek** [comment]
> Why do you use this type? I would say don't use to be compatible with upcoming Starcounter.Core

You mean why I use `QueryResultRows`?

**Comment by bigwad** [comment]
>You mean why I use QueryResultRows?

exactly

**Comment by rogeralsing** [comment]
that is what you get even if writing `var` which still gives the same false error warning

**Comment by mmnosek** [comment]
Because of:
1. https://docs.starcounter.io/guides/database/querying-using-sql/
2. https://github.com/search?q=org%3AStarcounterApps+QueryResultRows&type=Code
3. You get it when use `varz
4. It's default, not deprecated.

I expect whole AppsTeam uses it, our partners as well. Or I missed something.

**Comment by warpech** [comment]
The movement did not progress because it got no response from the core team. Your input is welcome there. I think we would be very happy to just stop using `QueryResultRows` and use `IEnumerable` + Linq's `First()`, if that's the recommendation.

**Comment by miyconst** [comment]
Closing the issue since because of - [Remove QueryResultRow object, return IEnumerable instead](https://github.com/Starcounter/level1/issues/4244).
