### ISSUE TITLE
Administration Deletion is malfunctioning

### ISSUE THREAD

**Issue by Joltrix** [Starcounter/Home#203]
Deletion seems to not work as intended when someone is running multiple apps and trying to consecutively delete apps.

Instead of deleting the app whose button is pressed, other apps are instead deleted.

![mistakeshavebeenmade](https://user-images.githubusercontent.com/10708580/29276618-742063ca-810f-11e7-9c51-ee6b761463bd.gif)

**Comment by per-samuelsson** [comment]
Ouch. What version is this?

cc @andwah

**Comment by Joltrix** [comment]
Ah, sorry! forgot to include it!...
Starcounter version 2.3.1.6981

**Comment by andwah** [comment]
Just tried and i could also reproduce it, in my browser console window i got a lot of warnings like this:

`You're accessing an object that is detached from the observedObject tree, see https://github.com/Palindrom/JSONPatcherProxy#detached-objects`

After i deleted an app and then tried to delete another app.

 i checked the source history then i can see that we switch to use Palindrom 3.0.0 in Administrator 22 days ago, maybe some issue there? @warpech?
I never seen this problem before.

**Comment by warpech** [comment]
I know what that is. I have updated PuppetJs used in Administrator to Palindrom 3.0.0, which has this bug.

Few days ago, [Palindrom 3.0.2 was released with a bugfix](https://github.com/Palindrom/Palindrom/releases).

@andwah could you pls update Palindrom in Administrator? It was already updated in the `sys` folder.

Or consider this: https://github.com/Starcounter/level1/issues/3194

**Comment by andwah** [comment]
i tried with latest Palindrom 3.0.2 then i get this error in browser console:

`TypeError: Cannot read property 'bind' of undefined
    at new <anonymous> (HostModelService.js:45)
    at e (angular.js:4203)
    at Object.instantiate (angular.js:4211)
    at Object.<anonymous> (angular.js:4072)
    at Object.e [as invoke] (angular.js:4203)
    at Object.$get (angular.js:4056)
    at Object.e [as invoke] (angular.js:4203)
    at angular.js:4021
    at d (angular.js:4162)
    at Object.e [as invoke] (angular.js:4194)`

**Comment by andwah** [comment]
*Bump*  

Anyone knows someting the error (See previous post) i get when i try using Palindrom 3.0.2 and how to fix it?

**Comment by andwah** [comment]
Not sure how to solve this? revert the palindrom introduction?

**Comment by Mackiovello** [comment]
@alshakero do you know anything?

**Comment by alshakero** [comment]
@Mackiovello sorry, I was at a conference.

Is this reproducible with the latest RC?

**Comment by Joltrix** [comment]
@alshakero Yes, it's still reproduceable.

I just tried it with the latest RC (v. 2.3.1.7063)

**Comment by alshakero** [comment]
Apparently, Admin uses its own Palindrom. Which isn't updated. Updating it now.

**Comment by andwah** [comment]
I tried with Palindrom 3.0.2  (see comment above) with no success.

**Comment by alshakero** [comment]
Yes, I've seen it, this was fixed in 3.0.3.

**Comment by alshakero** [comment]
Fixed in 2.3.1.7071! Thank you so much @andwah and @Joltrix. I'll leave closing to @Joltrix.

**Comment by Joltrix** [comment]
I've also tried to recreate this, but haven't managed to.

I'll go ahead and close this issue in that case :)

Thanks @alshakero for fixing this :D
