### ISSUE TITLE
Starpack unable to execute with release mode

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#205]
I've build my project in release mode and I want to build package.zip from the exe generated under release folder using the following command

`starpack -p -c=release`
`starpack -p -c='release'`

but I get the following errors
`Visual Studio project file not found (-c=release)`

Can someone please help me in writing the right command?

**Comment by andwah** [comment]
I can just confirm that this is true, there is some issues around the -c argument, i have still not figured out why it sometimes/all the time picks the wrong configuration when using the -c argument.

Sometimes i need to rebuild both debug and release to make it work and even then it sometimes picks the 'debug' version when i used -c=release.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.
