### ISSUE TITLE
 [v2.4] Trying to get the enumerator from a result from a DROP TABLE stmt fails.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#207]
The statement succeeds though (i.e. the table is dropped), however an error is returned when the enumerator is retrieved from the result of the query. 

This is only reproducible in `v2.4 (develop)`. In `v2.3` it works without any problems.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.QueryResultRows`1.GetEnumerator() in c:\users\christian\code\Starcounter\Versions\Develop\Level1\src\Starcounter\Query\SQL\SqlResultGeneric.cs:line 37
   at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in c:\users\christian\code\Starcounter\Versions\Develop\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 103
HResult=-2147467261
```

**How to reproduce**
Take the following steps from issue in private tracker (https://github.com/Starcounter/level1/issues/3387):
1. Create a new application with `staradmin +`.
2. Edit the generated `app.cs` like shown below.
3. Run it in a new database, e.g. `star -d=newdb app.cs`
4. Stop the application: `staradmin -d=newdb stop app app`
5. Go to web admin SQL, database `newdb`, execute `DROP TABLE Foo`.

**app.cs**

``` cs
using Starcounter;
using System;

[Database] public class Foo {
}

class Program {
    static void Main() {
        Console.WriteLine("{0} starting...", Application.Current);
    }
}
```

**Comment by bigwad** [comment]
I'll check if the redesign of Query Processor has something to do with it.

**Comment by bigwad** [comment]
Checking a fix

**Comment by bigwad** [comment]
Fixed
