### ISSUE TITLE
Update documentation of DELETE clause

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#208]
Is there any way to delete select objects from the Starcounter Admin page?

E.g. like:

```SQL
DELETE FROM Person p WHERE p.Name = 'John Doe'
```

The docs are a bit unclear on what is supported saying only that in Starcounter SQL the support for `DELETE` is limited, but not in what way. The examples all show `DELETE` without a `WHERE` clause, so I assume this is one of the limitations.

Anyway, it would be nice to be able to do this without having to write C# code and deploy an app. Is it possible?

**Comment by miyconst** [comment]
Yes, the `WHERE` clause is supported in the `DELETE` statement, please report is some specific query is failing.

@Mackiovello please update the documentation page.

**Comment by Mackiovello** [comment]
Documentation is updated. Closing

**Comment by eriksunsol** [comment]
Just to conclude this, my example in the original post didn't work because there is a syntax error in it. The correct way is like this:

```SQL
DELETE FROM Person WHERE Name = 'John Doe'
```
