### ISSUE TITLE
Automatically enable Crash Dumps upon Starcounter installation

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#210]
Starcounter installer should automatically enable application crash dumps, but it should be possible to disable it via advanced settings during installation.

https://msdn.microsoft.com/en-us/library/bb787181(VS.85).aspx

**Comment by ubbeK** [comment]
Which starcounter applications did you have in mind?

**Comment by miyconst** [comment]
I meant windows application crash dumps, not the system crash dumps. Just what is described in the link.

**Comment by ubbeK** [comment]
A crash dump from sccode will be triggered for non-catchable exception like StackOverflow. An infinite recursion method will do the trick.

**Comment by ubbeK** [comment]
This issue has been implemented to `Release Candidate` and `Develop`.

![installer1](https://user-images.githubusercontent.com/8124023/29923144-b622e3d2-8e58-11e7-8276-feca681ca500.PNG)
![installer2](https://user-images.githubusercontent.com/8124023/29923146-b87b333c-8e58-11e7-85c3-eee4326d03f9.PNG)

**Comment by miyconst** [comment]
The checkbox is checked by default, correct?

**Comment by ubbeK** [comment]
> The checkbox is checked by default, correct? 

Yes, it is opt-out.
