### ISSUE TITLE
Starcounter database repositories folder best practices

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#211]
I need some advice/best practices for handling Starcounter repositories folders in production. The general issue is that the Personal/Data folder gets rather big for some of our clients. It would be good to know what can be safely removed.

The database subfolder inside the Data folder (e.g. Personal\Data\mopedo2\mopedo2-20170304T200630409) contains an Archive folder, some .log files and an .optlog file.

What is the purpose of the Archive folder? Under what circumstances can I start clearing the contents of the Archive folder?

In issue #58, @bigwad describes the Archive folder as essentially safe to clear if we're not interested in log replication. How will this replication be affected if I clear parts of the Archive folder?

**Comment by per-samuelsson** [comment]
> How will this replication be affected if I clear parts of the Archive folder?

I guess replication would not function properly if you would delete some log whose content was not yet replicated to all nodes.

Since I got a similar question the other day, and @bigwad helped me with an answer about retention policy, I can paste it here until he get the chance to bring some more insight:

> There is a default retention period of 30 days during which we keep log files in the archive folder. If this default period doesn't suite you, you can change it or set up manual cleanup task (probably using windows task scheduler). Currently one can change retention period only machine-wide, not on per-database basis. To do that you should edit %StarcounterBin%\on_new_log.cmd file. Find the line set retention_period=30 and change 30 to desired amount of days. Given that this setting is machine-wide and likely to be reverted back to the default value during starcounter upgrade, I'd recommend to go with a manual task.

**Comment by miyconst** [comment]
Closing the issue as answered question. @bigwad if you have something more to add - feel free to do so.
