### ISSUE TITLE
Update PartialToStandaloneHtmlProvider to use palindrom-client

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Home#213]
`<puppet-client>` is deprecated in favor of `<palindrom-client>` for a couple of months already. It's the time to update it in Starcounter and apps.

https://github.com/Starcounter/level1/blob/4eb50fb275308132de8520445314ff533728a149/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs

**Comment by chrhol** [comment]
A note: `starcounter-debug-aid` needs to be updated as well it looks like. When switching to `<palindrom-client>`, no viewmodel is shown and a warning in the console is logged that no `puppet-client` is found.

(https://github.com/Starcounter/starcounter-debug-aid/issues/47?)

**Comment by Mihaiii** [comment]
I couldn't find it in any app from `StarcounterApps` (they all seem to use it from Starcounter), but I might be wrong.

Does anyone know an example of an app that has it?

**Comment by alshakero** [comment]
@Mihaiii it's in the platform (level1) not in apps.

**Comment by tomalec** [comment]
Please note, that since you merged Polymer 2.0 version to master branch of `palindrom-client` we will have to use `palindrom-client: "#4.0.0"`

**Comment by warpech** [comment]
@alshakero could you please take this in `v2.4`?

**Comment by alshakero** [comment]
@warpech sure. "in `v2.3` meaning only PR to `develop` right?

**Comment by warpech** [comment]
In **v2.4**

**Comment by alshakero** [comment]
It’s a typo I swear 😅

**Comment by warpech** [comment]
This is done in https://github.com/Starcounter/StarcounterClientFiles/commit/ac7946dabef846363f4a85bb97ed491c5cdd4a67, will be part of the next release of StarcounterClientFiles 2.x

**Comment by warpech** [comment]
Closing as done

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.0
- published in the App Warehouse
