### ISSUE TITLE
Migrating indexes from old version (1.x) of Starcounter

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#215]
A question coming from migrating code from Starcounter 1.x to Starcounter 2.x

In 1.x an index can be created with a filter, that tells if undefined or only defined values should be included in the filter (`Filter="D"` for defined and `Filter="U"` for undefined)

```xml
<ClassConfig Name="Concepts.Ring2.TradesideConfiguration">
  <Index Filter="D">Vendible</Index>
</ClassConfig>
```

Is there something similar in 2.x?

I have no real idea what the purpose of the filter was (or at least I don't remember), but I think it had to (?) be set to defined for index on references, so maybe it was some way around some other limitation in 1.x

cc @k-rus, (and perhaps @per-samuelsson or @eriohl if you remember the reason for it in 1.x).

**Comment by per-samuelsson** [comment]
Nothing similar in 2.x AFAIK. Regarding 1.x I have some vague memory but I'm sure @eriohl has an even better one, so let's see if what he can provide. 😃

**Comment by chrhol** [comment]
Snippet from some old documentation (for 1.x):

```
4 Reference indices have to be filtered
Reference indices have to be filtered because it’s 
impossible to index undefined reference values. 
A set reference needs to be materialized in order 
to determine if the reference is invalid, and 
therefore undefined. You will for this reason get 
an error during binding if a reference index isn’t 
filtered to include defined values only.
```

So the guess would be that this is no longer needed and can safely be ignored.

**Comment by eriohl** [comment]
You can still not use the index to determine which references are NULL. But there is no longer any filter.

**Comment by chrhol** [comment]
Thanks, I will consider this issue answered!
