### ISSUE TITLE
Error when class inheritance has changed

### ISSUE THREAD

**Issue by HRidge** [Starcounter/Home#217]
I change the inheritance for a database class.

When trying to start the apps I get:
`An entity type declared a base class that did not match the base class previously bound to the core database schema. The inheritance for class 'XX.MyClass' has been changed from 'XX.Something' to 'XXX.Other'`

I have tried with this recommended test:
- Restore the original database schema.
- Execute `DELETE FROM XX.MyClass`
- Stop the apps.
- Execute `DROP TABLE XX.MyClass`
- Update the schema.
- Try to start the apps.

The error above will be reported at the last step.

I can not use stardump because we happen to use binary datatype in some class.

This class:
````
namespace XX
{
    /// <summary>
    /// My class
    /// </summary>
    [Database]
    public class MyClass : Something
    {
        ...
    }
}
````

Was changed to this:
````
namespace XX
{
    /// <summary>
    /// My class
    /// </summary>
    [Database]
    public class MyClass : Other
    {
        ...
    }
}
````

cc @miyconst 

Using verwsion "Starcounter-RC-2.3.1.6826 (19 jul 2017 01:02:04)"

**Comment by per-samuelsson** [comment]
Changed title of this, since it's not related to weaving, but instead when binding classes during app bootstrapping.

Also, I'm curious about:

>  I can not use stardump because we happen to use binary datatype in some class.

Is that some limitation we have?

cc @miyconst @ubbeK

**Comment by miyconst** [comment]
>Is that some limitation we have?

Yes, it is. Currently StarDump does not support Binary format.

**Comment by miyconst** [comment]
StarDump now supports binary data. Changing inheritance of a class is not supported by automatic migration, it will be addressed later. Closing this issue.
