### ISSUE TITLE
Incorrect url on error popup

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#220]
When running starcounter on a VM/Container/Non local Address, whenever the error popup appears, the link to the error log tries to move you to "localhost" which is not correct as the SC instance is running elsewhere.
See marked sections of screenshot

![image](https://user-images.githubusercontent.com/647031/29926348-796c3fe6-8e63-11e7-91d4-7f20c7c47aeb.png)

**Comment by Mihaiii** [comment]
Closing as done.
