### ISSUE TITLE
Installer fails to find VS extension and rolls back entire installation

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#222]
This is something new.

![image](https://user-images.githubusercontent.com/6435556/30018740-5b271f3a-915e-11e7-9d68-4dbe80a39235.png)

```
Starcounter-Develop-2.4.0.2791-Setup.exe
```

@ubbeK please close the issue if you can't reproduce it.

**Comment by miyconst** [comment]
Further investigation shows that:

- `Starcounter-Develop-2.4.0.2721-Setup.exe` also fails with the same exception.
- `Starcounter-Develop-2.4.0.2608-Setup.exe` works fine.

Was the extension file removed from the installer?

**Comment by ubbeK** [comment]
Let me check the source.

**Comment by Mihaiii** [comment]
+1 Same issue.

**Comment by miyconst** [comment]
Note, upgrading from the previous installation works fine, since the extension file left in the folder. Only clean install fails.

**Comment by ubbeK** [comment]
@alemoi https://github.com/Starcounter/level1/commit/5b7cd687a3507a15f506753c761dfa63b149c378 Reference to Starcounvter.VisualStudio nuget package has been removed. What intention did this remove have?

**Comment by alemoi** [comment]
I was failing the build by some reason I don't remember. Also was sounding like `Starcounvter.VisualStudio` referenced itself as a Nuget package? I think this is wrong.

And again, let's remove VSIX installation from installer. Again we are facing such problems.

**Comment by ubbeK** [comment]
It is not refrencing itself, `Starcounvter.VisualStudio` nuget is referencing https://github.com/Starcounter/Starcounter.VisualStudio/tree/develop/build since it was moved from Level1 repo to its own. Why there still exists a Starcounter.VisualStudio.csproj i Level1 beats me. @per-samuelsson Any idea?

**Comment by alemoi** [comment]
Same question from me then @ubbeK 
The reason I made this quick fix is because I had to migrate to VS 2017 quickly.

**Comment by per-samuelsson** [comment]
> Why there still exists a Starcounter.VisualStudio.csproj i Level1 beats me. @per-samuelsson Any idea?

That's the actual extension code in there, building `Starcounter.VisualStudio.dll`. To support debugging using F5, the TypedJSON development aid (supporting for example renaming of file pairs), etc.

What's in the `Starcounter.VisualStudio` repository is the actual setup + project templates.

If there is a problem with that design, just let me know.

**Comment by ubbeK** [comment]
> If there is a problem with that design, just let me know.

No problem really, its just unfortunate that they both have the same name since now the dependency from `Level1/Starcounter.VisualStudio` to `Starcounter.VisualStudio` got removed by mistake.

**Comment by ubbeK** [comment]
`Starcounter.VisualStudio 2.0.0-RC1` nuget package has been added to `Staracounter.InstallEngine` where it is called upon. This adds Staracounter.VS.vsix installer to the installation.

Closing
