### ISSUE TITLE
Add Db.TransactAsync that returns result

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#224]
Currently there is no `Db.TransactAsync` overload that returns a `Task<T>`. This can be worked around with code such as one below, but it's error-prone and really shouldn't be required from anyone.
```c#
public static Task<T> DbTransactAsync<T>(Func<T> operation)
{
    var taskCompletionSource = new TaskCompletionSource<T>();
    T result = default(T);
    Db.TransactAsync(() => result = operation())
        .ContinueWith(task => {
            if (task.IsCompleted)
            {
                taskCompletionSource.SetResult(result);
            }
            else if(task.IsCanceled)
            {
                taskCompletionSource.SetCanceled();
            }
            else // task is faulted
            {
                taskCompletionSource.SetException(task.Exception);
            }
        });
    return taskCompletionSource.Task;
}
```

**Comment by bigwad** [comment]
Two notes. 
1. Can't it be rewritten simpler as?
```csharp
public static async Task<T> DbTransactAsync<T>(Func<T> operation)
{
    T result = default(T);
    await Db.TransactAsync(() => result = operation());
    return result;
}
```
2. `Task<T>` changes the semantic of TransactAsync. What I mean here is that a `Task` being returned represents the action of flushing transaction log to a durable storage. Delegate passed to TransactAsync is executed synchronously to make sure transaction effects are visible without awaiting. While with `Task<T>` user is unable to get delegate's return value until the log is flushed. So consistent DbTransactAsync<T> rather would look like:
```csharp
public static Task DbTransactAsync<T>(Func<T> operation, out T result)
{
    T r = default(T);
    var t =  Db.TransactAsync(() => r = operation());
    result = r;
    return t;
}
```

Seems simple enough. WDYT?

**Comment by joozek78** [comment]
Re 1st example: You're right. Please note that my proposition in PR actually uses `await` instead of `ContinueWith`
Re 2nd example: Problem with this proposition is that `r = operation()` can be retried (leading to a different outcome) by `TransactAsync` if a transaction conflict happens. IMO it's extremely unlikely that someone will need a predicted result of the operation before he's sure that the transaction has been committed. The popular case is that I want the final result when it's really final and confirmed.

**Comment by joozek78** [comment]
> Delegate passed to TransactAsync is executed synchronously to make sure transaction effects are visible without awaiting.

I find it confusing - if only the commitment of transaction is asynchronous then how can we handle conflicts synchronously? Does that mean that if the synchronous part returns, the transaction can only be committed successfully or fail (without room for conflicts and retries)?

**Comment by bigwad** [comment]
>Problem with this proposition is that r = operation() can be retried (leading to a different outcome) by TransactAsync if a transaction conflict happens. IMO it's extremely unlikely that someone will need a predicted result of the operation before he's sure that the transaction has been committed

It's not a case. As I said, a delegate passed to Db.TransactAsync runs synchronously. It includes possible retries.

**Comment by joozek78** [comment]
Then I think it will be best to include both overloads:
* `Task<T> TransactAsync` will be obvious and safe (guarantees that the user won't use the return value before the transaction is confirmed to be committed) - to be used in general cases
* `Task TransactAsync(out T)` will be more powerful, but has to be used wisely - to be used where it's necessary

---

Do you use VS2017? If so, instead of having out variable you can return a tuple: `(Task task, T result) TransactAsync`. It will be backwards compatible (as `ValueTuple<Task, T>`), but in C# 7 should be usable as such:
```c#
(var task, var result) = TransactAsync(operation());
Console.WriteLine($"result is: {result}");
await task;
```
```c#
// equivalent
var tuple = TransactAsync(operation());
Console.WriteLine($"result is: {tuple.result}");
await tuple.task;
```

**Comment by bigwad** [comment]
I don't know. For me, it seems excessive and hard to explain.

For instance, `Task<T> TransactAsync()` overload seems to be the most natural and familiar to a user but in fact `Task TransactAsync(out T) ` should be favored, as being the direct counterpart of existing `Task TransactAsync`.
And emulating latter it in user code comes quite smoothly:
```csharp

int r = 0;
Db.TransactAsync(()=>
{
 //some code
 r = Db.SQL(...);
// some other code
});

```

Let's wait for other opinions.

**Comment by joozek78** [comment]
> in fact `Task TransactAsync(out T)` should be favored as being the direct counterpart of existing `Task TransactAsync`

I don't think it's a valid argument to use it more often than the other. It's true that it represents more accurately how things happen underneath, but I think people rarely need such control.



> Let's wait for other opinions.

Agree. @Starcounter/sc-apps?

**Comment by miyconst** [comment]
@joozek78, I think it's important that you understand how `Db.TransactAsync` works.

Since entire database is in memory, there is no I/O operations per transaction. There is no reason for making a transaction asynchronous. The only I/O operation, is flushing transaction log to storage device (HDD/SSD).

So, the in memory database transaction is executed synchronously regardless of which method is used `Db.Transact` or `Db.TransactAsync`.

This makes it very easy to read transaction result and construct application code. Here is a similar code snippet to what @bigwad provides.

```cs
Order o = null;

Task t = Db.TransactAsync(() => {
    o = new Order();
});

// The new order is already created in the database and available, since the transaction has already finished.

// While I/O operation in progress writing transaction log to storage, we can do something else.
// For example, send an email.
// It may happen that hardware failure happens, and transaction log will never be flushed.
// In this case email might get sent with incorrect information.
// It may be critical or not critical depending on the situation.
// But it gives nice options to balance speed and consistency.
EmailHelper.NewOrderNotification(o);

// Waiting for I/O operation to complete before we inform user, that his order is completed.
Task.Wait(t);

// At this point we are fully consistent.
return;
```

Those being said, I don't really see a need for `Task<T> Db.TransactAsync` overload.

**Comment by joozek78** [comment]
Thank you for your explanations. I've created an issue to properly document this method to avoid confusion in the future

**Comment by joozek78** [comment]
Aha, I closed too hastily. I agreed not to implement the `Task<T>` overload, but the one bigwad proposed (`(T, Task)`) is a useful thing. Reopening

**Comment by miyconst** [comment]
@joozek78 I tend to disagree here. It's just syntax sugaring, which I personally don't like.

Since you are currently working on `Level1`, please feel free to add this overload, and push, just make sure that it all goes through the tests, otherwise just close the issue.

Assigning the issue on you.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2 and the feature is available in the upcoming Starcounter 3.
