### ISSUE TITLE
Add Scheduling.ScheduleTask that returns a result

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#225]
See also: similar issue https://github.com/Starcounter/Home/issues/224

There is no `Scheduling.ScheduleTask` that returns `Task<T>`. This can be worked around, but really we should provide it. Possible workaround:

```c#
public static async Task<T> ScheduleTask<T>(Func<T> operation)
{
    T result = default(T);
    // RunTask is not documented, but it seems it properly handles exceptions
    await Scheduling.RunTask(() => {
        result = operation();
    });

    return result;
}
```

**Comment by miyconst** [comment]
Starcounter has it's own thread scheduling mechanism right now. It will be abandoned in the favor of the .net standard scheduling with the `Task` object in the upcoming .Net Core code host.

Closing the issue as `won't fix`.
