### ISSUE TITLE
Make public methods in Db class internal 

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#226]
To be able to have a decent reference documentation in the future, we have to make sure that only the methods and properties that are intended to be used by end users are public.

In `Db` there are a couple of methods that shouldn't be public:
* [RenameTable](https://github.com/Starcounter/level1/blob/e659e57b3e0733c25b95f03be917e43a94540345/src/Starcounter/Db.cs#L189)
* [DropTable](https://github.com/Starcounter/level1/blob/e659e57b3e0733c25b95f03be917e43a94540345/src/Starcounter/Db.cs#L204)
* [SetEnvironment](https://github.com/Starcounter/level1/blob/e659e57b3e0733c25b95f03be917e43a94540345/src/Starcounter/Db.cs#L535)
* [CreateTable](https://github.com/Starcounter/level1/blob/e659e57b3e0733c25b95f03be917e43a94540345/src/Starcounter/Db.cs#L110) - one of the overloads are already internal, why aren't the others?

There's no documentation of these methods and they are not used in any of our apps.

**Comment by Mackiovello** [comment]
@eriohl these have had been added by you, could you remove or make them internal?

**Comment by miyconst** [comment]
@chrhol volunteered to take this issue, and we agreed to:

- Obsolete the methods in `v2.3`.
- Change visibility level from `public` to `internal` in `develop`.

**Comment by chrhol** [comment]
I'm about to mark them as obsolete in `v2.3`. 

It looks like the only thing  `Db.DropTable` and `Db.RenameTable` does at this time is to throw a `NotSupportedException` so I think that I will drop these completely instead of making them internal in `develop` branch.

**Comment by chrhol** [comment]
Done, obsoleted in `v2.3`. Made internal and removed in `develop`
