### ISSUE TITLE
Improve documentation for Db.TransactAsync

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#228]
See discussion in #224 
`Db.TransactAsync` name can suggest that the db operation is performed asynchronously. This is not true, only the IO flush is scheduled for later. To avoid confusion in the future I propose following docstring:
```c#
/// <summary>
/// Executes the given <paramref name="action"/> within a new transaction and schedules IO flush for a later time
/// </summary>
/// <param name="action">DB action to be executed.
/// Can be retried multiple times according to <paramref name="opts"/>.<see cref="Advanced.TransactOptions.maxRetries"/>
/// This action is always executed synchronously</param>
/// <param name="flags">**describe where can you find the flags to use**. Defaults to 0</param>
/// <param name="opts"></param>
/// <returns>When this task is completed it means that the transaction has been flushed to permanent storage</returns>
public static System.Threading.Tasks.Task TransactAsync(Action action, uint flags, Advanced.TransactOptions opts)
```

The [docs.starcounter.io article](https://docs.starcounter.io/guides/transactions/using-transactions/) should also be updated to avoid confusion

**Comment by Mackiovello** [comment]
It says in the docs that "It returns a `Task` object that is marked as completed when flushing the transaction log for this transaction." Doesn't that describe it? Would you like it to be clearer?

**Comment by joozek78** [comment]
I think it should be underlined that despite the name (Async) most of work is done synchronously. It took two people for me to understand that the actual db operation is synchronous. I think someone else could make the same mistake. My proposal:

> `Db.TransactAsync` executes the database operations synchronously (just like `Db.Transact`), but it schedules IO flush for a later time. (example by @miyconst)

```cs
Order o = null;

Task t = Db.TransactAsync(() => {
    o = new Order();
});

// The new order is already created in the database and available, since the transaction has already finished.

// While I/O operation in progress writing transaction log to storage, we can do something else.
// For example, send an email.
// It may happen that hardware failure happens, and transaction log will never be flushed.
// In this case email might get sent with incorrect information.
// It may be critical or not critical depending on the situation.
// But it gives nice options to balance speed and consistency.
EmailHelper.NewOrderNotification(o);

// Waiting for I/O operation to complete before we inform user, that his order is completed.
Task.Wait(t);

// At this point we are fully consistent.
return;
```

**Comment by mmnosek** [comment]
Duplicate: https://github.com/Starcounter/Docs/issues/90

**Comment by joozek78** [comment]
> Duplicate: Starcounter/Docs#90

True, but the part pertaining to docstrings in code is still relevant

**Comment by bigwad** [comment]
If it's about documentation comments - it's done already
