### ISSUE TITLE
Document or remove classes SELECT, SELECT.FROM, and Table

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#230]
In Db.cs there are a bunch of classes that seem to be based on legacy concepts:

* `SELECT<T>`
* `SELECT.WHERE`
* `Table<T>`
* `SELECT`

These can all be found [here](https://github.com/Starcounter/level1/blame/ee5717dc53167402f79b4caa790438da621f311e/src/Starcounter/Mock/Db.cs#L169).

These are polluting our public namespace and might be confusing for new users. At the same time that these are dealt with, [public class F](https://github.com/Starcounter/level1/blame/ee5717dc53167402f79b4caa790438da621f311e/src/Starcounter/Mock/Db.cs#L192) can probably be removed too.

@k-rus could you deal with this?

**Comment by k-rus** [comment]
Somebody was looking to this question and was going to remove theses classes, I think. But I don't remember who.

**Comment by Mackiovello** [comment]
You're right, I found it. Closing in favor of https://github.com/Starcounter/level1/issues/1339
