### ISSUE TITLE
Incorrect docstrings for SQL and SlowSQL

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#231]
The docstrings for `SQL` and `SlowSQL` says "Returns the result of an SQL query as an SqlResult which implements IEnumerable.". This is incorrect, they return `QueryResultRows`.

`SlowSQL` says: "Especially queries with expected slow execution are supported, as for example aggregations.". This is also incorrect. The only thing that `SlowSQL` supports that `SQL` doesn't support is literals.

**Comment by Mackiovello** [comment]
Dang, making changes in level1 requires more setup than I thought. Resigning to someone that already has level1 set up.

Suggested docstrings:
`SQL`:
> Returns the result of an SQL query as QueryResultRows which implements IEnumerable.

`SlowSQL`:
> Returns the result of an SQL query as QueryResultRows which implements IEnumerable.
  Supports literals in queries. Queries with literals will execute slower than queries that use parameters.

**Comment by miyconst** [comment]
Since the `QueryResultRows` is deprecated now, the docstring should state:

>Returns the result of an SQL query as IEnumerable.

**Comment by miyconst** [comment]
@Mackiovello I think you can do it yourself, just follow the contribution rules.

**Comment by Mackiovello** [comment]
Done
