### ISSUE TITLE
Security warning about Open file is showed twice for Starcounter Installer

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#233]
When I'm trying to update my Starcounter with an installer, Windows always shows the "Open File - Security Warning" for files that can be potentially harmful for our PC. It's totally okey and expected behavior. Except that, always when I'm trying to run installer for updating Starcounter, the window, for some reason, is showed twice. it's bug/behavior that exists since I remember.

Is It known and expected behavior? Does any one of You had the same observation or It's just my local problem?

My account control settings are set to "Never notify"

Here's what I mean in video:
![rep](https://user-images.githubusercontent.com/25042256/30313965-7c0c224e-979f-11e7-8576-f50ac740e6d5.gif)

**Comment by andwah** [comment]
@alemoi, Can that be because we "relaunch" the installer in elevated mode?  just guessing here...

**Comment by alemoi** [comment]
@PatrykSzwer can you please write the Starcounter version here? Thanks.

**Comment by PatrykSzwer** [comment]
As I said, It happens to me since I remember, It was like that in versions 2.3.1.4xxx, 2.3.1.5xxx etc. I just tried current stable version, 2.3.0.6350 and It's same behavior.

**Comment by alemoi** [comment]
Thanks. If its `2.3.0.6350` then there are no recent changes that could affect the behaviour. Have you tried on a different machine?

**Comment by PatrykSzwer** [comment]
I couldn't actually make this window show in a first place in some1s other PC.

**Comment by alemoi** [comment]
I checked and its true. This is of a quite low priority though. CC @ubbeK

**Comment by ubbeK** [comment]
> Can that be because we "relaunch" the installer in elevated mode? just guessing here...

Kind of sounds like it.

**Comment by miyconst** [comment]
Never happened to me, but if it's still the case, then it's a valid issue with low priority.

**Comment by miyconst** [comment]
cc @iqbalskd

**Comment by iqbalskd** [comment]
I tried following but could not reproduce:

* Created a fresh vpc Windows 10, and Windows Server 2016 . Seems working fine on both.
* Created a user on Windows Server 2016, with basic user rights, seems working fine too. It asks for administrator password though.

Feel free to re-open and assign it to me if someone still facing it.
