### ISSUE TITLE
Empty response causes whole server crash

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#235]
I got simple program:
```csharp
using Starcounter;

class Program
{
    static void Main()
    {
        Handle.GET("/test", () =>
        {
            return new Response();
        });
    }
}
```

When I send request to `/test` it hangs for couple seconds and then suddenly app and server crashes. All I can see in logs:
```
ScErrDataManagerDisconnected (SCERR4296): Communication with data manager failed because client was disconnected by data manager.
Process exitcode: -1073740791
ScErrNetworkGatewayTerminated (SCERR10021): The server detected that the network gateway executable (scnetworkgateway.exe) unexpectedly terminated.
```

What might happen?

Starcounter version: 2.3.1.7166

**Comment by bigwad** [comment]
Easily reproduced.
 scnetworkgateway crashes and then scservices kills the rest.

cc @alemoi

**Comment by bigwad** [comment]
cc @miyconst

**Comment by miyconst** [comment]
@mmnosek is it `2.3` or `2.4`?

**Comment by mmnosek** [comment]
It's 2.3, sorry for not including the version in the desc.

**Comment by mmnosek** [comment]
Oh, actually the version was included! 😄

**Comment by alemoi** [comment]
Fixed via throwing an exception to the user regarding an empty response. @mmnosek you should also have seen an assertion in server log from gateway regarding this one.
