### ISSUE TITLE
Cannot use "data" as a key in TypedJson

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#236]
I need a REST service that returns a response like this:
```JSON
{
  "data": [
    {
      "someProperty": "a"      
    },
    {
      "someProperty": "b"      
    },
    {
      "someProperty": "c"      
    }
  ]
}
```

So I created TypeJSON looking like this:
```JSON
{
  "data":  [
    {
      "someProperty": ""
    }
  ]
}
```

But it doesn't compile. Error is: 
`JsonByExample parsing failed: Example.json already contains a definition for 'data'.```

I understand that `Data` is already used, but for the user it's confusing. Can it be solved somehow? Also, I think error description is not informative enough. It's very confusing.

We looked at it with @joozek78 - do you have any opinion?
@chrhol - any idea what can be done?

**Comment by chrhol** [comment]
This a general problem in TypedJSON. All existing properties in baseclasses will clash. There was a discussion in another issue, but we never reached a conclusion or a good solution for it. 

I will improve the errormessage though, to get a small step in the right direction.

**Comment by miyconst** [comment]
Archiving.
