### ISSUE TITLE
Cannot create binding between TypedJSON and the Dataobject - nullable types

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#237]
According to the https://docs.starcounter.io/guides/database/datatypes#nullable-types Starcounter supports nullable types. It also supports effortless, direct binding between TypedJSON and the Database. It doesn't work with nullable types. Let's take an example:

*Program.cs:*
```csharp
[Database]
public class Entity
{
    public DateTime? SomeDateTime;
    public int? SomeInt;
}
class Program
{
    static void Main()
    {
        Db.Transact(() =>
        {
            var entity = new Entity();
        });

        Handle.GET("/test", () =>
        {
            var page = new Example();
            page.Data = Db.SQL<Entity>("SELECT c FROM Entity c").First;

            return page;
        });
    }
}
```

*Example.json:*
```json
{
  "SomeDateTime": "",
  "SomeInt": ""
}
```

If you hit `/test` handler error occurs:
```
System.Exception: ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Incompatible types for binding. Json property 'Example.SomeInt' (System.String), data property 'Entity.SomeInt' (System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]])
```
```
System.Exception: ScErrCreateDataBindingForJson (SCERR14006): Cannot create binding between typed json and dataobject. Incompatible types for binding. Json property 'Example.SomeDateTime' (System.String), data property 'Entity.SomeDateTime' (System.Nullable`1[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]).
```

Shouldn't nullable types be also "bindable" as Starcounter supports them on the database level?

**Comment by chrhol** [comment]
This is a long-time known limitation and needed enhancement that have not been prioritized (or rather that more urgent issues have taken priority). The original issue was created when Level1 tracker still was public, and have not been moved (https://github.com/Starcounter/level1/issues/3864)

So short answer: nullable or null values are currently not supported in TypedJSON. This is something we want though, but I cannot give any estimate on when it will be done or in which version at this moment.

**Comment by chrhol** [comment]
I will close this issue as answered @mmnosek. If you are not satisfied please reopen it. We will have to try to get this enhancement in the roadmap, but that is out of the scope for this issue I think.

**Comment by mmnosek** [comment]
Thanks for the answer @chrhol ! I'm fine with the answer and I understand (even though I would prefer to prioritize it ;)) How can I be sure it will be somehow included to the roadmap? Is original Level1 issue enough?

**Comment by chrhol** [comment]
We need to get some roadmap and some prioritization of the existing issues and needed improvements in place.
