### ISSUE TITLE
Update the Release channel description

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#238]
The Release channel description is wrong, it says:

>  It is updated approximately once in a few weeks. Documentation matches the latest release version in this channel unless stated otherwise.

The second sentence about documentation can be removed since the documentation uses versioning. The first sentence should be changed to:

> It is updated approximately every sixth month.

**Comment by andwah** [comment]
When the text is updated i can also updated the text on http://downloads.starcounter.com/download

**Comment by Mackiovello** [comment]
It's updated in the docs: https://docs.starcounter.io/guides/working-with-starcounter/release-channels-in-starcounter

**Comment by andwah** [comment]
downloads.starcounter.com page is now updated. 
(at the moment there is some connection problems with that site)

**Comment by Mackiovello** [comment]
Thank you! Closing
