### ISSUE TITLE
Usage of `script.previousElementSibling` in apps

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Home#242]
I was looking at something on `inside.starcounter.com` and in console I noticed 

> [dom-bind::_annotatedComputationEffect]: compute method `isLastParent` not defined

 for `inside.starcounter.com/people/persons`.

So I had a look at the file and it's like this:
```
    <template>
    [...]
    </template>
    <script>!function(e,t,r,n,c,h,o){function a(e,t,r,n){for(r='',n='0x'+e.substr(t,2)|0,t+=2;t<e.length;t+=2)r+=String.fromCharCode('0x'+e.substr(t,2)^n);return r}try{for(c=e.getElementsByTagName('a'),o='/cdn-cgi/l/email-protection#',n=0;n<c.length;n++)try{(t=(h=c[n]).href.indexOf(o))>-1&&(h.href='mailto:'+a(h.href,t+o.length))}catch(e){}for(c=e.querySelectorAll('.__cf_email__'),n=0;n<c.length;n++)try{(h=c[n]).parentNode.replaceChild(e.createTextNode(a(h.getAttribute('data-cfemail'),0)),h)}catch(e){}}catch(e){}}(document);</script>
    <script>

        (function () {
            var script = document._currentScript || document.currentScript;
            var template = script.previousElementSibling;
            [...]
         })
    </script>

```

There is an email protection script that is injected and therefore `script.previousElementSibling` doesn't return what is expected. 

There might be other and more serious problems in the future for different cases.

**Comment by warpech** [comment]
In this case it should obviously be changed to `var template = script.previousElementSibling;`

Alternatively you can give an ID to the template and do `var template = document.getElementById(...)`, but do we want to maintain so many ids?

**Comment by warpech** [comment]
Seriously though, what is 

```
<script>!function(e,t,r,n,c,h,o){function a(e,t,r,n){for(r='',n='0x'+e.substr(t,2)|0,t+=2;t<e.length;t+=2)r+=String.fromCharCode('0x'+e.substr(t,2)^n);return r}try{for(c=e.getElementsByTagName('a'),o='/cdn-cgi/l/email-protection#',n=0;n<c.length;n++)try{(t=(h=c[n]).href.indexOf(o))>-1&&(h.href='mailto:'+a(h.href,t+o.length))}catch(e){}for(c=e.querySelectorAll('.__cf_email__'),n=0;n<c.length;n++)try{(h=c[n]).parentNode.replaceChild(e.createTextNode(a(h.getAttribute('data-cfemail'),0)),h)}catch(e){}}catch(e){}}(document);</script>
```

That should be loaded from an external file, preferably a custom element. Or at least put a comment above it.

**Comment by warpech** [comment]
Sorry, I haven't expected that.

@tomalec WDYT? I think this is a serious flaw of CloudFlare. 

I don't see how we can generally avoid using `previousElementSibling` other than maintaining `id`s for all temlpates. In this case, maybe just add an `id` for this template?

**Comment by warpech** [comment]
Another solution is to add the methods on Polymer `dom-bind`'s prototype instead of instance. Then you will not have to get the reference to the template.

Can you investigate that?

**Comment by miyconst** [comment]
Archiving.
