### ISSUE TITLE
Admin login with the sign in app

### ISSUE THREAD

**Issue by mrunhem** [Starcounter/Home#244]
In the description to the Sign in app it states:
 
Sign In

Authenticate **users** with a username and password (default admin/admin).
6.0.0 (Aug 17, 2017 10:07:20 AM)

This is not correct. There is no default admin user. You need to first create the admin user by using the link http://localhost:8080/signin/generateadminuser

This might be stated inside some development doc but since it shall be possible to install the app from  the warehouse, SC must either include a better description or provide a readme-link.

Another question: How secure is the generateadmin-link? If someone forgets to delete it this might cause a security issue...

/Mike

**Comment by andwah** [comment]
Releated https://github.com/StarcounterApps/SignIn/issues/51

**Comment by warpech** [comment]
cc @LarsTjernstrom

**Comment by warpech** [comment]
> This is not correct. There is no default admin user. You need to first create the admin user by using the link http://localhost:8080/signin/generateadminuser

This should be corrected in README.

> Another question: How secure is the generateadmin-link? If someone forgets to delete it this might cause a security issue...

That link only works when accessed from `localhost` and only when there are no users in the database.

**Comment by LarsTjernstrom** [comment]
Hi
In the new version of the SignInApp, calling the link 
> http://localhost:8080/signin/generateadminuser
> 

Only results in a message stating that you have to create the admin user by pressing the create admin button and fill in the password to actually create the admin user account. The documentation has not been updated.

Skickat från min iPhone

**Comment by Mihaiii** [comment]
Closing as done.
