### ISSUE TITLE
The help link in Admin does not work

### ISSUE THREAD

**Issue by mrunhem** [Starcounter/Home#245]
In the SC admin (version unknown/have not found the version info) there is a Help link at the upper right corner.
The link does not work:
https://github.com/starcounter/starcounter/wiki does not exist.

/Mike

**Comment by Mihaiii** [comment]
Thank you!
Right now `https://github.com/starcounter/starcounter/wiki` redirects to `https://github.com/Starcounter/level1/wiki` and `level1` is a private repositoy.

@Mackiovello Please let me know what page should be opened and I'll make the change. Thanks in advance!

**Comment by Mackiovello** [comment]
The old link would be the equivalent of pointing to docs.starcounter.io. I think the right place to point to is https://docs.starcounter.io/guides/working-with-starcounter/administrator-web-ui

**Comment by Mihaiii** [comment]
Closing as done.
