### ISSUE TITLE
Auto-start feature does not work from CLI

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#247]
In Administrator, you can mark an app as "Auto-start" (explained here: https://docs.starcounter.io/guides/working-with-starcounter/administrator-web-ui#control-apps).

Sadly, the apps start automatically only when the db is stared using the "Start" button in the Administrator. If the db is started via `staradmin start db`, the auto-start option in the apps is ignored.

It should work consistentli accross CLI and the Administrator Web UI.

**Comment by andwah** [comment]
related https://github.com/Starcounter/level1/issues/3951

**Comment by Mihaiii** [comment]
Thank you @andwah for the info.
https://github.com/Starcounter/level1/issues/2705 should be solved first.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
