### ISSUE TITLE
Request.PortNumber returns 0

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#249]
I tested on WebsiteProvider app.

#### Steps to reproduce

1. Run **WebsiteEditor** and **WebsiteProvider** apps from `develop` branch in debug mode.
1. Set breakpoint on [ContentHandlers.cs:74](https://github.com/StarcounterApps/Website/blob/07049a818c8d0729259fa5295c2d29791de4e768/src/WebsiteProvider/Api/ContentHandlers.cs#L74)
1. Check value of the `request.PortNumber`

##### Starcounter version 2.3.1.7280

**Comment by warpech** [comment]
@alemoi can you pls take a look?

@un-tone is this a regression?

**Comment by warpech** [comment]
@alemoi can you pls take a look?

@un-tone is this a regression? How does it affect Website app or other apps?

**Comment by warpech** [comment]
Reply to self - it causes tests in Website app to fail: https://github.com/StarcounterApps/Website/pull/197#issuecomment-331379038, so this must be a regression.

**Comment by warpech** [comment]
Reply to self - it causes tests in Website app to fail: https://github.com/StarcounterApps/Website/pull/197#issuecomment-331379038, so this must be a regression.

@miyconst I advise this goes in 2.3.1

**Comment by un-tone** [comment]
I use it when calling `Handler.GetHandlerForUri(string method, string uri, ushort portNumber)` method [here](https://github.com/StarcounterApps/Website/blob/15de635821e35082bccda172ae91267b31ea8622/src/WebsiteProvider/Api/ContentHandlers.cs#L232).

**Comment by alemoi** [comment]
Thanks for reporting @un-tone 
Fixed, now returns user handlers port, e.g. 8080.
