### ISSUE TITLE
Filtering by calculated property is case-insensitive

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#252]
I got this issue when testing WebsiteProvider app.

`Simplified.Ring1.Something` class has the following property:

```csharp
public string Key
{
  get
  {
    return this.GetObjectID();
  }
}
```

#### Using Key property

When I run the following query:

```sql
SELECT * FROM Simplified.Ring6.WebUrl u WHERE u.Key = 'T'
```
I'm getting this:
![image](https://user-images.githubusercontent.com/1625378/30851798-59bb634e-a2b2-11e7-8ac9-8eab195fd6ad.png)
We can see here that that the filtering is case-insensitive.

#### Using ObjectID property
If I use `ObjectID` property instead of `Key`

```sql
SELECT * FROM Simplified.Ring6.WebUrl u WHERE u.ObjectID = 'T'
```
I'm getting correct results:

![image](https://user-images.githubusercontent.com/1625378/30851966-f01b380a-a2b2-11e7-867b-640b6abca2b2.png)

-----

@k-rus could you please take a look at this? Maybe it is a correct behavior, please explain why in this case.

**Comment by k-rus** [comment]
Filtering in SQL is case-insensitive, which is according the standard. 

`ObjectID` is treated case-sensitively, since it is an id. But it doesn't work so always, see https://github.com/Starcounter/level1/issues/4210

Is your question answered?

**Comment by un-tone** [comment]
Yes, now it's clear. Thank you!
