### ISSUE TITLE
Feature review: automatically create a TypedJSON object based on a dataobject.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#253]
This functionality needs a serious review. The current implementation was added a long time ago, and has not gotten any attention until now. 

The main problem is performance. It's very, very slow today. It's uses a combination of reflection and dictionary-lookups to map a public property to a template for TypedJSON, and there is no caching of the result meaning that if this is used for an array, the result will be horrific (as seen and verified in https://github.com/StarcounterApps/People/issues/129).

Possible ways forward:
1. Remove the functionality altogether.
2. Make it more explicit so you have to be aware that you are actually creating new objects all the time. 
3. Keep it as-is today, but go through the code and enhance it to be more performance friendly (caching/reusing existing TypedJSON object, avoid reflection by using metadata for databaseobjects, etc...)

As usual it's a matter of priority and in what direction we want to go. My vote would go to number 2, and maybe the enhancement part of 3. but that also the most work. On the other hand, making it more explicit might at least getting rid of using this feature by mistake.

And of course, anyway we go, document it properly.

How you use it today: Set the `Data` property on an object or array that is declared as empty in JSON-by-example (or instantiate an empty json that has no template).

**Example.json**
```javascript
{
  "Obj": { },
  "Items": [ { } ]
}
```

**Program.cs**
```csharp
[Database]
public class Person {
    public string Firstname { get; set; }
    public string Surname { get; set; }
}

class Program {
    static void Main() {
        Db.Transact(() => {
             new Person() { Firstname = "John", Surname = "Doe" };
             new Person() { Firstname = "Jane", Surname = "Doe" };
        });

        var example = new Example();
        example.Obj.Data = Db.SQL("SELECT p FROM Person p").First;
        example.Items.Data = Db.SQL("SELECT p FROM Person p");

        // example.Obj will contain two properties, Firstname and Surname
        // example.Items will contain two items with two properties each, Firstname and Surname
        Console.Writeline(example.ToJson());
    }
}
```

**Output**
```
{"Obj":{"Firstname":"John","Surname":"Doe"},"Items":[{"Firstname":"John","Surname":"Doe"},{"Firstname":Jane","Surname":"Doe"}]}
```

cc @warpech, @miyconst, @rogeralsing, @LarsTjernstrom

**Comment by miyconst** [comment]
I vote for removing this feature all together. Also, those kind of issues are once again reminding me, that we should reconsider our JSON view-model strategy, possible in favor of proposed by me, so called compiled JSON.

**Comment by warpech** [comment]
Do we have a way to check what apps are using it?

**Comment by warpech** [comment]
Is there a way to add an obsolete message for this in 2.3.1?

I agree this is a highly magical feature that should be removed.

**Comment by chrhol** [comment]
Awesome, then the verdict seems to be in favour of removing it altogether.

> Is there a way to add an obsolete message for this in 2.3.1?

This I'm not sure about, I have to test. Maybe. The problem is that it's not directly public. Worst case we can add a warning to the log.

**Comment by chrhol** [comment]
Added a new issue for the actual task, closing this one. Thanks for the feedback!
