### ISSUE TITLE
Remove feature for automatic creation of TypedJSON based on dataobject.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#254]
Explained here: https://github.com/Starcounter/Home/issues/253

* Drop in Odessa, and instead generate an exception if `json.Data` is set on an object or array without a template. 
* Obsolete in `v2.3.1`. If obsoleting this feature doesn't work (due to the fact that it's not directly a public API) generate a warning in the Starcounter log instead.

**Comment by chrhol** [comment]
@miyconst: I added this issue as scheduled for both 2.3.1 and Odessa projects. Please let me know or move them if you think otherwise

**Comment by chrhol** [comment]
Unfortunately I cannot find any way to mark this as obsolete in 2.3.1. I will add a warning in the Starcounter log instead. Not optimal, since it requires a user to actively look in the log to spot it, but I see no other option.

**Comment by chrhol** [comment]
I've been working on this issue for some hours now. It's not going as well as I hoped. There's quite a lot of unittests in XSON that depends on this functionality.

The status is that the issue itself is done for both versions but the tests needs to be updated. I will postpone this issue for a little while, since I have some more urgent things to finish.

**Comment by chrhol** [comment]
Got back to this again. I had to tweak the initial issue a bit. 

Instead of dropping it altogether, which when doing a more thorough review is not really feasible and would have been incorrect, this functionality is only permitted by a more explicit use. 

What this means is that for cases as explained in #253, this will not be permitted. An exception will be thrown in these cases, which will stop accidental usage. 

However, if the template (or parent) is marked as dynamic, this way will still be allowed.

**Warning in 2.3**
```
Automatic adding of properties for a TypedJSON object or array that doesn't define any, based on dataobject, have been obsoleted and will be removed in later versions (2.4+). Json: PersonPage.CountryList, datatype: System.Collections.ObjectModel.Collection`1[[People.ISO3166Country, People, Version=7.1.2.0, Culture=neutral, PublicKeyToken=null]]
```

**Exception in 2.4**
```
System.InvalidOperationException: ScErrInvalidOperationDataOnEmptyJson (SCERR14013): A dataobject was set on a TypedJSON object or array that does not define any properties. Json: PersonPage.CountryList, datatype: System.Collections.ObjectModel.Collection`1[[People.ISO3166Country, People, Version=7.1.2.0, Culture=neutral, PublicKeyToken=null]]
```

**Comment by miyconst** [comment]
Looks very valid for me. @warpech what do you think?

**Comment by chrhol** [comment]
This change have been merged to both `v2.3` and `develop` branches. 

How should it be documented? I don't think this behaviour is mentioned anywhere today, so maybe we can add a page for the specific errorcode in 2.4 (i.e. `ScErrInvalidOperationDataOnEmptyJson`). cc @Mackiovello

**Comment by Mackiovello** [comment]
> How should it be documented? I don't think this behaviour is mentioned anywhere today, so maybe we can add a page for the specific errorcode in 2.4 (i.e. ScErrInvalidOperationDataOnEmptyJson). cc @Mackiovello

I'll add an explanation of `ScErrInvalidOperationDataOnEmptyJson` on the Data Bindings page for 2.4.

**Comment by warpech** [comment]
> Looks very valid for me. @warpech what do you think?

Looks very good to me

**Comment by Mackiovello** [comment]
I'm a little confused. The example in https://github.com/Starcounter/Home/issues/253 looks like this:

```cs
using System;
using Starcounter;

namespace StarcounterApplication2
{
    [Database]
    public class Person
    {
        public string Firstname { get; set; }
        public string Surname { get; set; }
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() =>
            {
                Db.SQL("DELETE FROM Person");
                new Person() { Firstname = "John", Surname = "Doe" };
                new Person() { Firstname = "Jane", Surname = "Doe" };
            });

            var example = new Example();
            example.Obj.Data = Db.SQL("SELECT p FROM Person p").First;
            example.Items.Data = Db.SQL("SELECT p FROM Person p"); // => SCERR14013

            // example.Obj will contain two properties, Firstname and Surname
            // example.Items will contain two items with two properties each, Firstname and Surname
            var json = example.ToJson();
        }
    }
}
```

Why isn't `SCERR14013` thrown on `example.Obj.Data = Db.SQL("SELECT p FROM Person p").First;`? 

If I comment out `example.Items.Data = Db.SQL("SELECT p FROM Person p"); // => SCERR14013`, `json` contains this: `"{\"Obj\":{},\"Items\":[]}"`. 

Is there any difference between how arrays and objects work here? 

Starcounter version: 2.4.0.3397

```json
{
  "Obj": {},
  "Items": [ { } ]
}
```

**Comment by chrhol** [comment]
> Why isn't SCERR14013 thrown on example.Obj.Data = Db.SQL("SELECT p FROM Person p").First;?

Good catch, it should throw exception. I have a unittest that succeeds, but it looks a little different. Wonder how I missed this. 

Anyway, it's a bug. I will fix it ASAP.

**Comment by chrhol** [comment]
I've pushed a fix for this now. 

It's strange, because I remember looking into this case earlier and adding the check for empty template (and not just null), but I can find no commit or no trace of it. I've must have messed up and discarded it instead of comitting or something.

**Comment by Mackiovello** [comment]
This is now documented here: https://docs.starcounter.io/v/2.4/guides/typed-json/json-data-bindings#scerrinvalidoperationdataonemptyjson-(scerr14013)

Closing as done
