### ISSUE TITLE
Administrator slow and unstable

### ISSUE THREAD

**Issue by andwah** [Starcounter/Home#259]
The GUI Administrator feels very slow and unstable since switching to Palindrom.

II constantly need to Refresh (F5) the browser to be sure about the database/apps status. this was not an issue before when we used a early version of puppets.

**Comment by warpech** [comment]
Is this for the current version? Some improvements were released yesterday https://github.com/Starcounter/Home/issues/239

**Comment by andwah** [comment]
sorry, forgot to include the version, i used Starcounter-RC-2.3.1.7211

**Comment by andwah** [comment]
i will upgrade and test the latest RC.

**Comment by miyconst** [comment]
@andwah can you please check if the issue is still in place?

**Comment by andwah** [comment]
My experience with a newer starcounter version is much better.   Closing
