### ISSUE TITLE
Starcounter throws a 413 when sending large payloads to a post handler

### ISSUE THREAD

**Issue by Razkan** [Starcounter/Home#261]
Hi Starcounter Developers, 

Starcounter doesn't allow for large payloads to be sent to the post handler. The following warning is found in the Db management log: **"Attempt to HTTP upload of more than 1048576 bytes. Closing socket connection."**

This can be replicated by passing a large body through a http post (for example a base64 image).

**Comment by mtornwall** [comment]
Hi @Razkan,

You should be able to configure this by changing the value of the `MaximumReceiveContentLength` node in `%userprofile%\Documents\Starcounter\Personal\scnetworkgateway.xml`.

**Comment by Razkan** [comment]
Thanks for the response @mtornwall 

I'll close this issue for now, and reopen if the issue persist!

**Comment by warpech** [comment]
I think that the maximum limit is 4 MB for the request anyway.

Large files should be uploaded with WebSocket. Example is available in KitchenSink: StarcounterSamples/KitchenSink:src/KitchenSink/FileUploadPage.json.cs@master.

@alemoi can you pls confirm?

@Mackiovello can you pls make sure this is in the docs?

**Comment by alemoi** [comment]
That's correct. WebSockets is the recommended way of streaming up. If large files are for download, 'Response.StreamedBody' can be used, or also, WebSockets.

**Comment by Mackiovello** [comment]
Documentation for this is created here: https://docs.starcounter.io/guides/network/handling-http-requests#size-limit-on-payloads

If that covers it properly, please close.

**Comment by miyconst** [comment]
Thanks @Mackiovello. Closing the issue.
