### ISSUE TITLE
Include Polymer 1.10.1 in Starcounter 2.3.1

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#262]
@alshakero could you pls test if Polymer 1.10.1 works well and make a PR that includes it in Starcounter 2.3.1?

cc @miyconst

**Comment by alshakero** [comment]
On it. I was waiting for https://github.com/Starcounter/level1/pull/4287.

**Comment by warpech** [comment]
Done in https://github.com/Starcounter/level1/pull/4287. Thanks @alshakero
