### ISSUE TITLE
Max response size should be configurable

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#269]
If I try to return a `Response` larger than 500MB ([source, for insiders only](https://github.com/Starcounter/level1/blob/develop/src/Starcounter.Internal/Constants/Constants.cs#L73)) I get an exception. Why is this even in place? The developers should be able to return as much as they want. At least it should be configurable like max receive size

CC @alemoi may have some information on it

**Comment by warpech** [comment]
Related https://github.com/Starcounter/Home/issues/261

**Comment by alemoi** [comment]
> Related #261

Its the limitations on upload.

> The developers should be able to return as much as they want. At least it should be configurable like max receive size

I think this is an artificial limitation actually. I will remove it.

**Comment by joozek78** [comment]
Thanks! But :) Don't you think we shouldn't remove public fields without first deprecating them? I don't know if this was used by customers<sup>1</sup>, but if so it can introduce problems with migrating (and I think this will be published in 2.3.1 as well, so should be backwards compatible?). Of course it takes more work to deprecate (introduce a way to tell if this version uses it or not) and then remove. Maybe it's not worth it in this case. @miyconst what do you think? I guess it's your job now to decide on such things?

---

<sup>1</sup> In my case (tpcc benchmark) I can just use some ugly reflection for a while and live with it, but I would loathe to advise it to an actual customer

**Comment by miyconst** [comment]
@alemoi will revert the change and deprecate the property following an offline discussion.

**Comment by alemoi** [comment]
Fixed via 04421385f0c80ebe69c1fd56a48639df21f78fe0

**Comment by joozek78** [comment]
The way I see it (looking at the revision linked) the size limit is still there. I would expect the limit gone.

**Comment by alemoi** [comment]
So you want to deprecate the property but change the behavior? Sounds like its against the obsoletion rules :)

**Comment by joozek78** [comment]
IMO if we remove the limit on response size we keep the backwards compatibility. The property should still be there, to prevent any apps that use it from failing the build.

**Comment by miyconst** [comment]
@alemoi please remove the response limitation side and deprecate the property with proper warning message.

**Comment by alemoi** [comment]
Done!

**Comment by miyconst** [comment]
Should we close the issue then?

**Comment by joozek78** [comment]
I guess so. Technically, the issue is already closed
