### ISSUE TITLE
Using index with "WHERE x IS (NOT) NULL" clause gives wrong result.

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#271]
Sorry if this has already been reported. I couldn't find an issue for it. Related to https://github.com/Starcounter/level1/issues/3546, but slightly different.

Error occurs when a property is null, not because it was set to null, but because the object it referred to was deleted. Here's code to show the problem:

```C#
using Starcounter;

namespace DeletedObjectTest
{
    [Database]
    public class C1
    {
        public override string ToString() => $"Object no {this.GetObjectNo()}";
    }

    [Database]
    public class C2
    {
        public C1 reference;

        public override string ToString() => $"Object no {this.GetObjectNo()}, with reference to {reference?.ToString() ?? "null"}";
    }

    class Program
    {

        static void Main()
        {
            Handle.GET("/deletedtest", () =>
            {
                string result = "";

                result += "Setting up test data\n";
                Db.Transact(() =>
                {
                    var c1 = new C1();
                    var c2 = new C2() { reference = c1 };
                    c1.Delete();     // <--------- This is where c2.reference is nulled without being explicitly set to null!
                });

                result += " Count number of C2 object with C2.reference == null, without index.\n";
                Db.Transact(() =>
                {
                    int count = 0;
                    var c2s = Db.SQL<C2>("SELECT c2 FROM C2 c2 WHERE c2.reference IS NULL");
                    foreach (var c2 in c2s)
                    {
                        result += $"  Found {c2} ({(c2.reference == null ? "OK" : "WRONG")})\n";
                        ++count;
                    }

                    result += $"  Found {count} C2 objects with C2.reference == null ({(count == 1 ? "OK" : "WRONG")})\n";
                });

                result += " Count number of C2 object with C2.reference != null, without index.\n";
                Db.Transact(() =>
                {
                    int count = 0;
                    var c2s = Db.SQL<C2>("SELECT c2 FROM C2 c2 WHERE c2.reference IS NOT NULL");
                    foreach (var c2 in c2s)
                    {
                        result += $"  Found {c2} ({(c2.reference != null ? "OK" : "WRONG")})\n";
                        ++count;
                    }

                    result += $"  Found {count} C2 objects with C2.reference != null ({(count == 0 ? "OK" : "WRONG")})\n";
                });

                result += "Creating index\n";
                Db.SQL($"CREATE INDEX FailIndex ON {typeof(C2).FullName} ( {nameof(C2.reference)} )");

                result += " Count number of C2 objects with C2.reference == null, with index.\n";
                Db.Transact(() =>
                {
                    int count = 0;
                    var c2s = Db.SQL<C2>("SELECT c2 FROM C2 c2 WHERE c2.reference IS NULL");
                    foreach (var c2 in c2s)
                    {
                        result += $"  Found {c2} ({(c2.reference == null ? "OK" : "WRONG")})\n";
                        ++count;
                    }

                    result += $"  Found {count} C2 objects with C2.reference == null ({(count == 1 ? "OK" : "WRONG")})\n";
                });

                result += " Count number of C2 objects with C2.reference != null, with index.\n";
                Db.Transact(() =>
                {
                    int count = 0;
                    var c2s = Db.SQL<C2>("SELECT c2 FROM C2 c2 WHERE c2.reference IS NOT NULL");
                    foreach (var c2 in c2s)
                    {
                        result += $"  Found {c2} ({(c2.reference != null ? "OK" : "WRONG")})\n";
                        ++count;
                    }

                    result += $"  Found {count} C2 objects with C2.reference != null ({(count == 0 ? "OK" : "WRONG")})\n";
                });


                result += "Clean up!\n";
                Db.Transact(() =>
                {
                    var c2s = Db.SQL<C2>("SELECT c2 FROM C2 c2");
                    foreach (var c2 in c2s)
                        c2.Delete();
                });

                Db.SQL($"DROP INDEX FailIndex ON {typeof(C2).FullName}");

                return result;
            });
        }
    }
}
```

Here's the output:

```
Setting up test data
 Count number of C2 object with C2.reference == null, without index.
  Found Object no 52, with reference to null (OK)
  Found 1 C2 objects with C2.reference == null (OK)
 Count number of C2 object with C2.reference != null, without index.
  Found 0 C2 objects with C2.reference != null (OK)
Creating index
 Count number of C2 objects with C2.reference == null, with index.
  Found 0 C2 objects with C2.reference == null (WRONG)
 Count number of C2 objects with C2.reference != null, with index.
  Found Object no 52, with reference to null (WRONG)
  Found 1 C2 objects with C2.reference != null (WRONG)
Clean up!
```

I think you can figure this one out without me explaining what I think is going on under the hood. Tricky one to solve to complete satisfaction is what I suspect.

Tested on Starcounter-RC-2.3.1.7371.

**Comment by eriksunsol** [comment]
Tested on Starcounter-RC-2.3.1.7371

**Comment by k-rus** [comment]
Thank you for great report! As I understood the incorrect result is produced when index is involved.

@bigwad Do you think this bug should be resolved in the kernel or on the level of the query processor?

**Comment by bigwad** [comment]
>Do you think this bug should be resolved in the kernel or on the level of the query processor?

It's QP responsibility according to the original design: https://github.com/Starcounter/level1/issues/2362#issuecomment-183633605

**Comment by eriksunsol** [comment]
@k-rus 
> As I understood the incorrect result is produced when index is involved.

Yes.

**Comment by un-tone** [comment]
> It's QP responsibility according to the original design: https://github.com/Starcounter/level1/issues/2362#issuecomment-183633605

It looks exactly as described in that comment. I checked that the bug appears in both cases of null equality: with literals (`IS (NOT) NULL`) and with `null` variable passing in `Db.SQL`.

What can I do to fix this? I see one way: don't use IndexScan for such filter and apply managed Comparison.

> `*_get_reference` evaluates the weak reference

Or we can use this way somehow?

@bigwad @k-rus, any thoughts on it?

**Comment by bigwad** [comment]
An index can be used in the sense that if a reference is indexed as `null` then it really has the null value and no need to evaluate it with `*_get_reference`. 
We can leverage this fact:
* `IS NULL` can be evaluated as `(ref==NULL) OR ((ref !=NULL ) AND (star_get_reference(ref) == NULL))`
* `IS NOT NULL` can be evaluated as `(ref != NULL) AND (star_get_reference(ref) != NULL )`

Conditions `ref == NULL` and `ref != NULL` are suitable for index scan.

**Comment by un-tone** [comment]
I have a fix for the `IS NOT NULL` case in the https://github.com/Starcounter/level1/commit/b22fc5f13689f14424d87777031a1574e0908739 commit.

To fix the `IS NULL` case in the way proposed by @bigwad I have to spend much more time. Currently, I'm not really sure how I can implement this "concatenation" of executions and leave the support of offset keys and other features.

**Comment by miyconst** [comment]
During the last release planning it was agreed to first make the query work correctly without utilizing any indexes, and only then perform optimization to utilize an index if applicable.

**Comment by un-tone** [comment]
Fixed in https://github.com/Starcounter/level1/pull/4698 and https://github.com/Starcounter/level1/pull/4787
