### ISSUE TITLE
Redirect doesn't work

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Home#272]
## Steps to reproduce:

1. Clone https://github.com/Mihaiii/RedirectExample , build and run it.
2. Navigate to `/RedirectExample/test1` and click on `Press me`. 

## Expected result:
URL in the address bar should be `/RedirectExample/test3` and Test3Page should be displayed.

## Actual result:
URL in the address bar is `/RedirectExample/test2` and the same initial page (Test1Page) is displayed.

SC version 2.3.1.7478

Link to the docs:
https://docs.starcounter.io/guides/network/url-aliases-and-redirects/#redirect

**Comment by Mihaiii** [comment]
The initial post was updated.

**Comment by miyconst** [comment]
@Mihaiii this issue does not seem to be valid, and the result is expected.

When the first click happens, the request is `Accept:application/json-patch+json`, and not `Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`.

I am not sure what exactly you are trying to achieve by making a redirect for a `json-patch+json` request, but here is what we can do:

- Check request headers on server side and perform proper action.
- Implement proper handling for `302` and `301` response status codes in client side Palindrom.

I am closing the issue as invalid.

If you still believe that we should implement the second option, please open appropriate issue in the [Palindrom](https://github.com/Palindrom/Palindrom) repository and provide proper description.

**Comment by warpech** [comment]
@Mihaiii maybe there's is some good idea about this, but I agree it needs to be properly defined. now it works according to the design, so it is rather a missing feature than a bug.

I agree that it is confusing especially in context of the docs page: https://docs.starcounter.io/guides/network/url-aliases-and-redirects/#redirect

I created an issue to discuss it further: https://github.com/Palindrom/Palindrom/issues/187
