### ISSUE TITLE
HTML composition REST API uses wrong content type

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#274]
This [handler](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter.Extensions/HTMLComposition.cs#L50) (internal) returns HTML but has the content-type to application/json. It's a simple fix by someone that has level1 build setup, just change [this line](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter.Extensions/HTMLComposition.cs#L57) to text/html.

**Comment by warpech** [comment]
This is a good catch, though I am not sure if this API is ever used. We are not using it in our apps and it might be obsoleted in future versions.

Anyway, @un-tone can you pls fix that?

**Comment by Mackiovello** [comment]
> This is a good catch, though I am not sure if this API is ever used. 

If it's not, would it be possible to deprecate or rewrite and move CompositionEditor/Provider?

**Comment by warpech** [comment]
Yes, it would be possible to deprecate it even in 2.3.1. I have made an issue for that: https://github.com/Starcounter/Home/issues/283

**Comment by un-tone** [comment]
Created PR https://github.com/Starcounter/level1/pull/4314

**Comment by un-tone** [comment]
Closing as done.
