### ISSUE TITLE
Starcounter and Swagger

### ISSUE THREAD

**Issue by JoaSel** [Starcounter/Home#275]
Has anyone used Swashbuckle/Swagger together with Starcounter?

**Comment by Mackiovello** [comment]
Not that I know of. Is there any reason you don't think it will work or do you need some help getting started? Sorry for the delayed answer by the way.

**Comment by JoaSel** [comment]
I would love some help getting started. Installing Swashbuckle into the solution is no problem but the actual code of enabling it is a little unclear to me.  The Swashbuckle tutorial tells me to add  it to a HttpConfiguration object:

httpConfiguration
     .EnableSwagger(c => c.SingleApiVersion("v1", "A title for your API"))
     .EnableSwaggerUi();

But I am unsure if Starcounter actually has such an config object and if so, where it could be found.

**Comment by Mackiovello** [comment]
Okay, I understand the problem.

Starcounter uses its own web server which means that you can't use it together with Swagger/Swashbuckle. Of course, you could use an HTTP server that is supported by Swagger, but that would mean you miss out on many of the good parts with Starcounter.

It seems like ASP.NET Core Web API works well with Swagger. You could use that together with the Starcounter version that let you plug in Starcounter as a service to ASP.NET Core. It's under development, so not everything is in place, but if you want a REST API with Starcounter as a database, it works fine. If that would be interesting for you, I could help you every step of the way to get started.

**Comment by JoaSel** [comment]
I see, thank you for your answer. We are using Starcounter "all the way" so I guess we will have to do without swagger.

Could you think of any other smart way to create documentation for the Starcounter endpoints?

**Comment by Mackiovello** [comment]
> Could you think of any other smart way to create documentation for the Starcounter endpoints?

What I would do is use the network tab of the Administrator to extract the endpoints, their HTTP methods, and URI: http://localhost:8181/#/server/network. The rest would then have to be filled in manually.

I don't know any neat way to do it automatically. 

To write the stuff down, we use GitBook which has native support for REST endpoints, you can take a look at how we've used it on this page: https://docs.starcounter.io/guides/web-apps/import-html-composition

**Comment by Mackiovello** [comment]
Closing the issue as answered. I hope this was helpful.
