### ISSUE TITLE
Blender resets activation states after calling MapUri

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#276]
While reproducing #251 on last SC 2.3.1.7454 I found the following issue: deactivated mapped handlers are still called. After detailed investigating I isolated the issue. Please look at the code below.

```csharp
public static void TestBlenderDeactivating()
{
    Dictionary<String, List<BlendingInfo>> allBlendings = Blender.ListAllByUris();
    Assert.AreEqual(0, allBlendings.Count);

    String called = "";

    Handle.GET("/op1", () =>
    {
        called += "op1";
        return "op1";
    });
    Handle.GET("/op2", () =>
    {
        called += "op2";
        return "op2";
    });
    Handle.GET("/op3", () =>
    {
        called += "op3";
        return "op3";
    });

    Blender.MapUri("/op1", "token1");
    Blender.MapUri("/op2", "token1");

    Response resp = Self.GET("/op2");
    Assert.AreEqual(resp.Body, "op2");
    Assert.AreEqual(called, "op2op1");
    called = "";

    Blender.Deactivate("/op1", "token1");

    resp = Self.GET("/op2");
    Assert.AreEqual(resp.Body, "op2");
    Assert.AreEqual(called, "op2");
    called = "";

    Blender.MapUri("/op3", "token1");

    resp = Self.GET("/op3");
    Assert.AreEqual(resp.Body, "op3");
    Assert.AreEqual(called, "op3op2");
    called = "";
}
```

It breaks on last asserting `Assert.AreEqual(called, "op3op2");`. Activation flags are correct while `Blender.MapUri("/op3", "token1");` is not called. After this deactivated mapping pair `"/op1", "token1"` becomes active which is wrong.

@alemoi please take a look.

**Comment by alemoi** [comment]
Very nicely found @un-tone !
I have produced the fixes and added tests.
Just one thing to mention in addition:

```cs
Blender.Deactivate("/op1", "token1");

resp = Self.GET("/op1");
Assert.AreEqual(resp.Body, "op1");
Assert.AreEqual(called, "op1"); // Since the blending is inactive.
called = "";
```
if the blending is deactivated, it will not trigger the corresponding blendings on the same token.
This was just a clarification on how its going to work for this case.

**Comment by alemoi** [comment]
I have produced a build @un-tone if you want to check it before tomorrow: http://downloads.starcounter.com/download/Starcounter/Custom/2.3.1.7491

**Comment by un-tone** [comment]
@alemoi it fixes the issue. Currently it works well, thanks!
