### ISSUE TITLE
Add stardump to PATH

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#278]
It is very inconvenient that `stardump`, unlike `star` and `staradmin` is not automatically added to PATH by Starcounter installer.

Is there a reason for that?

It would turn https://github.com/Starcounter/RebelsLounge/issues/184 into a more pleasant experience.

**Comment by miyconst** [comment]
This was already requested multiple times, let's just add it to `PATH`.

@ubbeK it should be done by the installer, right?

**Comment by ubbeK** [comment]
> @ubbeK it should be done by the installer, right?

Yes, today we add `StarcounterBin` as an environment variable and add that value to `PATH` in the [InstallerEngine](https://github.com/Starcounter/level1/blob/v2.3/src/Starcounter.Installer/Starcounter.InstallerEngine/Components/InstallationBase.cs#L127-L141). The path to `StarDump` may be added to `PATH` in the same file.

**Comment by miyconst** [comment]
@ubbeK please fix the issue today/tomorrow, I wanna include it into `2.3.1` and it's release approaching.

**Comment by ubbeK** [comment]
Ok, but I was hoping that it wasn't that urgent so the new guy could fix it when he starts.

**Comment by ubbeK** [comment]
Implemented, tested and committed to `RC` and `develop`.
