### ISSUE TITLE
Implement a caching strategy in htmlmerger

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#280]
Right now, Starcounter has a decent strategy for caching static files (CSS, JS, custom elements):

- a 200 OK response contains headers: `Cache-Control:public,max-age=0,must-revalidate`, `Last-Modified:Wed, 18 Oct 2017 07:08:20 GMT`
- consequtive requests come with a header `If-Modified-Since:Wed, 18 Oct 2017 07:08:20 GMT`, to which server responds with a 304 Not Modified

In contrast to the above the requests for HTML views (e.g. `/sc/htmlmerger?WebsiteEditor_0=%2FWebsiteEditor%2Fviewmodels%2FMasterPage.html`) get these response headers for 200 OK: `Cache-Control:no-store`. This makes them completely not cacheable.

I propose that `htmlmerger` gets the following changes:
- change the response headers to `Cache-Control:public,max-age=0,must-revalidate`, `Last-Modified:Wed, 18 Oct 2017 07:08:20 GMT` if all files in the merged response are static files. Last-Modified is the date of the last modification of the newest file
- implement responding with 304 Not Modified if a request `If-Modified-Since` arrives and the files were not modified.

@alemoi is this something you could work on? A lot of people complain about the performance of our apps and this is a first step to improve that.

[Source of htmlmerger](https://github.com/Starcounter/level1/blob/7d7f9fd1f1af98d2f323cf5a0b8caba513a09d65/src/Starcounter.Apps.JsonPatch/SystemHandlers.cs#L339-L374)

Bonus question, what is the difference between:

- https://github.com/Starcounter/level1/blob/7d7f9fd1f1af98d2f323cf5a0b8caba513a09d65/src/Starcounter.Hypermedia/StaticWebServer.cs#L108
- https://github.com/Starcounter/level1/blob/7d7f9fd1f1af98d2f323cf5a0b8caba513a09d65/src/Starcounter.Hypermedia/StaticWebServer.File.cs#L48

I do not insist on having this in 2.3.1, it can be in Odessa.

**Comment by alemoi** [comment]
I will check if it should work out of the box simply.

**Comment by alemoi** [comment]
>  if all files in the merged response are static files.

@warpech can it be that some files are not static? I mean, theoretically ofc, but have you seen such things in practice?

**Comment by warpech** [comment]
Yes, it is totally possible that some of the HTMLs are dynamically created by a handler in an app.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
