### ISSUE TITLE
Change proposal: Get rid of the need to use static constructor and DefaultTemplate in TypedJSON.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#281]
A pattern we use today in TypedJSON (specifically Json-by-example) to specify bindings and instancetypes is to use the static constructor and modify values for a specific template. I feel this was (in hindsight) a bad direction to go.

The code looks quite ugly and the developer needs to know about specifics about templates and the use of static `DefaultTemplate`. Also there are quite heavy limitations on how the syntax *must* look to work.

One possible alternative, would be to use attributes on the code-behind class instead and combined with the use of the `nameof` and `typeof` syntax makes it a bit more robust then just specifying properties as strings.

An example, having the following json:

**Example.json**
```javascript
{
  "BoundToSmtElse": "",
  "NotBoundAtAll": "",
  "DoubleValue": 0.0,
  "ReuseObject": { },
  "ReuseArray": [ 
    {  } 
  ],
  "NestedObject": {
      "ChangeBind": ""
  }
}
```

Would look like this today, with changes in binding, and specifying types:

**Example.json.cs**
```csharp
[Example_json]
partial class ExampleJson : Json {
    static ExampleJson(){
        DefaultTemplate.BoundToSmtElse.Bind = nameof(Person.Firstname);
        DefaultTemplate.NotBoundAtAll.Bind = null;
        DefaultTemplate.DoubleValue.InstanceType = typeof(double);
        DefaultTemplate.ReuseObject.InstanceType = typeof(SomeJson);
        DefaultTemplate.ReuseArray.ElementType.InstanceType = typeof(SomeJson);
    }

    [Example_json.NestedObject]
    partial class NestedObjectJson : Json {
        static NestedObjectJson(){
            DefaultTemplate.ChangeBind.Bind = nameof(DataObject.Value);
        }
    }
}
```

Instead, switching to attributes would look something like this:

**Example.json.cs**
```csharp
[Bind(nameof(BoundToSmtElse), nameof(Person.Firstname))]
[Bind(nameof(NoutBoundAtAll), null)]
[Type(nameof(DoubleValue), typeof(double))]
[Type(nameof(ReuseObject), typeof(SomeJson))]
[Type(nameof(ReuseArray), typeof(SomeJson))]
[Example_json]
partial class ExampleJson : Json {

    [Bind(nameof(ChangeBind), nameof(DataObject.Value))]
    [Example_json.NestedObject]
    partial class NestedObjectJson : Json {
    }
}
```

The first parameter of both these attributes (`BindAttribute`, `TypeAttribute`) is a string with the name of the property. This name will be matched during the buildtask, which will mean that an invalid name will trigger a *compile-time* error. Together with the usage of `nameof` we should avoid some problems with matching strings.

We get rid of the usage of the static constructor, and removes the need to know about the static `DefaultTemplate`, and how templates look underneath.

The work to get this in place is also quite moderate. It's not a huge change from how it works today (with the perspective on codegenerator and parser). We can also gradually move away from using static constructor, so there is no need for a huge migration step. Both ways can work side-by-side.

/cc @warpech, @miyconst, @joozek78, @Mackiovello, @rogeralsing  (and anyone else interested)

WDYT?

**Comment by miyconst** [comment]
Overall I like the idea, but there are a few points which are not covered.

Currently the static constructor and default template works differently for nested objects and nested objects inside arrays. Will it be possible to unify usage and specify those attributes on template level, rather than on instance of the template level?

I am not sure that Typed JSON is the way to go. Some time ago we agreed to perform a survey with our partners and see what they think about Typed JSON, then decide what we do with and how to proceed. It ended up nowhere. Can we first focus on this and only then in case of a positive feedback work on Typed JSON improvements?

**Comment by warpech** [comment]
The proposal looks OK to me but I don't feel a dramatic difference. 

I totally agree with @miyconst that we should base further developments on the problems that our customers have to be solved. I believe Strict JSON and Compiled JSON are the alternatives we should consider - and then maybe there is no point in making API changes to TypedJSON.

Maybe someone from @Starcounter/sc-apps can provide insight.

**Comment by chrhol** [comment]
Fair enough. Let's wait for the decision on the way forward then. Thanks for the feedback.

**Comment by habib535** [comment]
How about adding the attribute on top of each `Property` instead of piling up on top of `class`?  I really like this idea of getting away from the `static` constructor.

**Comment by warpech** [comment]
I guess it is because data-bound properties are not defined in C# partial class, they are defined in JSON-by-example. Hence in the @chrhol's example there is no property to annotate with an attribute.

**Comment by Joltrix** [comment]
I was talking to Sebastian (from Colabers) today, and he is binding without the static constructor at all.

So, for example, if we have an array in the TypedJSON called Subscriptions
```json
  "Subscriptions": [
    {
      "CustomerName": "",
      "SubscriptionId": "",
      "StartDate": "",
      "SubscriptionStatus": "",
      "SubscriptionKey": ""
    }
  ],
```

```c#
static SubscriptionsPage()
{
    DefaultTemplate.Subscriptions.Bind = nameof(BoundSubscriptions);
}
public IEnumerable<Subscription> BoundSubscriptions => UnitOfWork.Instance.SubscriptionRepository.GetSubscriptions();
```

Could just be:
```c#
public IEnumerable<Subscription> Subscriptions => UnitOfWork.Instance.SubscriptionRepository.GetSubscriptions();
```

Is there a reason we are not / should not use the "straight away binding"? and why we instead should use the binding from within the static constructor?

cc @warpech @chrhol @habib535

**Comment by Mackiovello** [comment]
> Is there a reason we are not / should not use the "straight away binding"? and why we instead should use the binding from within the static constructor?

The "straight away binding" is the sort of binding we usually use, as described here: https://docs.starcounter.io/guides/typed-json/json-data-bindings#binding-to-code-behind-properties
It's the same that happens when you use `json.Data` to create bindings with data objects.

The bindings in the static constructor are used to modify the way bindings work by default, for example binding to a property with a different name: 
https://docs.starcounter.io/guides/typed-json/json-data-bindings#modify-bindings

**Comment by joozek78** [comment]
BTW I use `DefaultTemplate` to access binding information in [Authorization Library](https://github.com/starcounter/authorization/blob/e102d4d656c6c0e2df88c86d41125a43905bee5d/Authorization/PageSecurity/PageSecurity.cs#L126)
