### ISSUE TITLE
Deprecate HTML Composition REST API in 2.3.1 and remove in 2.4

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#283]
HTML Composition REST API ([source](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter.Extensions/HTMLComposition.cs#L35-L96)) is only used in a single place in all of our apps: https://github.com/Starcounter/starcounter-include/blob/3.0.0-rc.6/starcounter-include.html#L345-L363

That usage is actually being removed in a PR right now, which will go in Starcounter 2.3.1: https://github.com/Starcounter/starcounter-include/pull/62/commits/215d6cf745fec321c9a6a2859598ba873749ff7f

Therefore, I suggest to mark this API as deprecated in 2.3.1 and remove it in 2.4.

How can we mark a REST API as deprecated? I guess writing it in the docs is a way to go?

@miyconst, @Mackiovello WDYT?

**Comment by Mackiovello** [comment]
Yes! 

> I guess writing it in the docs is a way to go?

Yea, I don't think there's another way of doing it

**Comment by miyconst** [comment]
Let's do it.

**Comment by warpech** [comment]
Assigning it to:

- [ ] @Mackiovello for deprecating this API in 2.3.1 docs and removing it from 2.4 docs
- [ ] @un-tone for removing it from 2.4 `level1`

**Comment by Mackiovello** [comment]
This seems to be done. Closing

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- included in level1 https://github.com/Starcounter/level1/pull/4315
