### ISSUE TITLE
Assertion failed in Safari

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#285]
## Steps to reproduce

1. Build and run [KitchenSink](https://github.com/Starcounter/KitchenSink) `develop` branch. 
   - I am using version Starcounter/KitchenSink@ad6d39022461f11a82f6048775c895e12367731e but actually, any blendable Starcounter app should reproduce this problem
2. Open http://localhost:8080/kitchensink in Safari 11.0

## Expected

Should render the same as it renders in Chrome or Firefox

## Actual

There is a blank screen. 

Console shows "Assertion failed" error in `webcomponents.js`.

![pasted image at 2017_10_24 05_38 pm](https://user-images.githubusercontent.com/566463/31954609-593fe198-b8e6-11e7-853d-bcd1fd3537ae.png)

**Comment by alshakero** [comment]
I isloated this into a bug in `document-register-element`. I filed an issue (https://github.com/WebReflection/document-register-element/issues/128)

**Comment by andwah** [comment]
I get a blank screen on:
- Chrome on Android phone 
- Chrome on Ipad
- Safari on Ipad

Is this issue releated or should i create an new issue?

**Comment by warpech** [comment]
The iPad & Android case will be evaluated separately.

The Safari problem is now being addressed, a solution will be pushed to Starcounter by the end of the week. All plain JS custom elements that use CEv1 will need to be reverted to CEv0 or made hybrid.

**Comment by warpech** [comment]
This issue is fixed in https://github.com/Starcounter/level1/pull/4331 and waiting for https://github.com/Starcounter/Home/issues/296 to be included there as well.

**Comment by warpech** [comment]
Closing as done
