### ISSUE TITLE
DateTime in json may be in the wrong format

### ISSUE THREAD

**Issue by andwah** [Starcounter/Home#286]
It looks like a DateTime object with the Kind "Local" is converted to "2017-10-25 12:00:00Z" in the json patch.  

I think it should not have the trailing 'Z' if the kind is "Local"

**Comment by miyconst** [comment]
There is no `DateTime` format in JSON, and applications should care about date time values on their own by sending it as a string of a known format for client and server side.

Still, if we have some automated converters, it should respect the `Kind` property.

**Comment by warpech** [comment]
Working with dates is a typical use case of business apps. Starcounter as a framework for apps should support it nicely, without asking each developer to reinvent the wheel. It is solved in every other serious framework.

The standard is ISO 8601, so it should be either:

- `1970-01-01T00:00:00Z` if you are sending UTC time
- `1970-01-01T00:00:00-0500` if you are sending a local time

EcmaScript 5th edition [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) constructor and [`Date.parse`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) can parse such timestamp [successfully](https://stackoverflow.com/questions/2587345/why-does-date-parse-give-incorrect-results).

In my opinion, this is the format to which we should serialize. Working with UTC and local times should be presented in the docs and KitchenSink.

**Comment by chrhol** [comment]
If we are talking about the server, then the automatic conversion is done when a string-property is bound to a datetime property. Currently the string is formatted using "u" (Universal sortable date/time pattern).

Should we change this then to ISO 8601? Not sure if this should be treated as a bug and fixed right away or be considered a kind of breaking change (since we're changing the default format) which might introduce some problems for existing apps.

**Comment by warpech** [comment]
> Currently the string is formatted using "u" (Universal sortable date/time pattern).

Is it explained anywhere in the docs? If no then please add it.

> Should we change this then to ISO 8601? Not sure if this should be treated as a bug and fixed right away or be considered a kind of breaking change (since we're changing the default format) which might introduce some problems for existing apps.

Can we do it as a non-breaking change, by including some configuration for how the dates are serialized in a property?

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
