### ISSUE TITLE
ScErrInstallerAborted (SCERR11015): Installation process has been aborted. User has rejected the choice to kill running Starcounter processes.

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#290]
I am getting the following error often when upgrading Starcounter RC nightly installation on my local Windows 10 running in VirtualBox.

## Steps to reproduce

1. Install Starcounter 2.3.1.7454 with default settings
1. Run a database on port 8080 and start KitchenSink
2. Run the installer of Starcounter 2.3.1.7534
3. Press OK when the installer asks: "Would you like to upgrade Starcounter v2.3.1.7454 to v2.3.1.7534?"

## Expected 

The installer should upgrade Starcounter

##  Actual

**Sometimes** the following comes few seconds after question: "Would you like to upgrade Starcounter v2.3.1.7454 to v2.3.1.7534?"

```
ScErrInstallerAborted (SCERR11015): Installation process has been aborted. User has rejected the choice to kill running Starcounter processes.
Version: 2.3.1.7478.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR11015.
```

I get the error "User has rejected the choice to kill running Starcounter processes." even though I was not even given this choice.

Running the installer for the second time results in "Upgrade successful".

This problem is not specific to these versions. I have observed it for many weeks.

## Screenshot

![image](https://user-images.githubusercontent.com/566463/32043425-02b8d87e-ba3b-11e7-896b-a811c3412992.png)

**Comment by warpech** [comment]
I have improved the steps to reproduce.

**Comment by miyconst** [comment]
This also happens when Visual Studio is open and it locks some of the `Starcounter/*.dll` assemblies, the installer fails to empty the installation folder and fails.

Restarting installer does not solve the problem in this case, only closing Visual Studio, and restarting installer.

**Comment by ubbeK** [comment]
Will have to check if Installer ever performs a `staradmin kill all`.
