### ISSUE TITLE
Blender.MapUri: Use another characters to mark variable values in specific URIs?

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#291]
As presented in https://docs.starcounter.io/guides/blending/blending#blending-specific-uris, when blending specific URIs, I need to wrap the variable values in URIs in curly braces (`{` and `}`).

Sadly, these characters do not play well with C# interpolated strings. You end up with something like ([source](https://github.com/Starcounter/SampleWebsiteTheme/pull/19/files)):

```c#
CreatePinningRule(topBarCenterBlendingPoint, 
   $"/images/partials/somethings-single-static/{{{concept.GetObjectID()}}}");
```

Unfortunately, curly braces seem to be the industry standard :( This is what other templating languages are using:

- [WCF uses curly braces](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/uritemplate-and-uritemplatetable)
- [ASP.NET Core uses curly braces](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
- [RFC6570 uses curly braces](https://www.rfc-editor.org/rfc/rfc6570.txt)

Should we get used to this? Any better ideas?

cc @alemoi, @miyconst, @un-tone

**Comment by alemoi** [comment]
The original idea was the same as we had with curly braces in handlers URI. Wouldn't it be the same problem with them? I just like the usage of the same type of brackets.

**Comment by miyconst** [comment]
Although I like to follow standards and the least surprise principle, this issue is really annoying and "everyone else" together with "standards" is not yet the final argument so we could use `[?]`, `[{concept.GetObjectID()}]` instead.

**Comment by alemoi** [comment]
Is it really worth a change? For me `[{concept.GetObjectID()}]` looks even uglier actually, its almost like using all types of brackets: `([{concept.GetObjectID()}])`. Having same brackets is at least a unification of some sort.

**Comment by warpech** [comment]
That's an interesting point of view @alemoi, I am almost convinced. I tried hard to research other popular ways to denote variables in URIs but all I can find is `{xxx}`. So maybe we should keep it as is.

**Comment by miyconst** [comment]
@warpech can we close the issue?

**Comment by warpech** [comment]
Yes, closing
