### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Home#292]
- My Starcounter version is: Starcounter-RC-2.3.1.7478 (Oct 18, 2017 9:11:42 AM)
- I have a solution with two apps that share the same library (project). 
- Visual Studio will start both apps with debugger attached
- If I am not rebuilding the solution before I debug i get the following exception:

> System.ArgumentException: 'ScErrBadArguments (SCERR1001): One or more arguments was invalid. Types Namespace.Model and Namespace.Model  are not compatible.

`Namespace.Model` is a replacement for the actual namespace and model. The content of Namespace.Model can varied. 

Unfortunate I can't share my code but I can screen share to identify the problem.

**Comment by miyconst** [comment]
@jwillmer thank you for reporting the issue.

>If I am not rebuilding the solution before I debug i get the following exception:

Do you mean that you have to rebuild solution regardless of changes? Even if you did not make any changes, solution rebuild is still required to debug. Is that correct?

Please try to run your apps without debugging, and then attach the debugger to `sccode.exe` process and see if it fails as well.

**Comment by miyconst** [comment]
Archiving as there is no response from @jwillmer.
