### ISSUE TITLE
Custom HTTP handlers

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#293]
I can't seem to get custom HTTP handlers to work properly. What's the problem with the code in this example? @alemoi

```c#
public class Program
{
    public static void Main()
    {
        Handle.CUSTOM(8003, "FOO /getfoo", () => new Response {Body = "Foo body"});
        var request = (HttpWebRequest) WebRequest.Create("http://127.0.0.1:8003/getfoo");
        request.Timeout = 5000;
        request.Method = "FOO";
        try
        {
            var response = (HttpWebResponse) request.GetResponse();
            var reader = new StreamReader(response.GetResponseStream());
            var data = reader.ReadToEnd();
        }
        catch (WebException we)
        {
            var error = we.Message;
            // The operation has timed out
        }
    }
}
```
```
Version=2.3.1.7581
```
SC admin:
![screen shot 2017-10-30 at 00 02 44](https://user-images.githubusercontent.com/16880339/32149538-3ff41442-bd06-11e7-880d-5a6e0c077b40.jpg)

**Comment by alemoi** [comment]
Thanks for asking. Not a Starcounter issue: https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.method(v=vs.110).aspx

The Method property can be set to any of the HTTP 1.1 protocol verbs: GET, HEAD, POST, PUT, DELETE, TRACE, or OPTIONS.

**Comment by erikvk** [comment]
```c#
public class Program
{
    public static void Main()
    {
        Handle.CUSTOM(8003, "FOO /getfoo", () => new Response {Body = "Foo body"});
        var response = Http.CustomRESTRequest
        (
            method: "FOO ",
            uri: "http://127.0.0.1:8003/getfoo",
            body: default(string),
            headersDictionary: null,
            receiveTimeoutSeconds: 10
        );
        var data = response.Body;
        // System.IO.IOException: Remote host closed the connection.\r\n   
        // at Starcounter.NodeTask.PerformSyncRequest() 
        // in C:\\TeamCity\\BuildAgent\\work\\sc-10022\\Level1\\src\\Starcounter.Internal\\Rest\\NodeTask.cs:line 514
    }
}
```

**Comment by erikvk** [comment]
I tried with the Starcounter.Http class for requests, that doesn't work either

**Comment by Mackiovello** [comment]
> The Method property can be set to any of the HTTP 1.1 protocol verbs: GET, HEAD, POST, PUT, DELETE, TRACE, or OPTIONS.

Doesn't that mean the documentation is misleading? It has examples such as:

```cs
Handle.CUSTOM("REPORT /hello/{?}", (string p1) =>
{
    return 500;
});
```

Reopening since the issue doesn't seem to be resolved.

**Comment by erikvk** [comment]
The documentation merely describes the handlers, not the ways to make requests to those handlers. The quote refers to the Method property of HttpWebRequest. So I think the documentation is fine – I just need a way to actually call the handler.

**Comment by Mackiovello** [comment]
> The documentation merely describes the handlers, not the ways to make requests to those handlers. The quote refers to the Method property of HttpWebRequest. So I think the documentation is fine – I just need a way to actually call the handler.

Got it, I should have read the issue more closely. Will document how to call custom handlers once it's figured out.

**Comment by erikvk** [comment]
I have tried curl, Starcounter.Http and HttpWebRequest. No client can call my FOO handler. @alemoi – how would you call a handler registered with a custom HTTP verb?

**Comment by alemoi** [comment]
Sure, I will check and respond!

**Comment by alemoi** [comment]
Thanks @erikvk for pushing this. I have checked the Nginx parser that we use and there is the list of methods we (and nginx) support:

![image](https://user-images.githubusercontent.com/208134/32190235-697fc9da-bdad-11e7-978a-ea0c7a192a81.png)

I will add this to documentation.

**Comment by erikvk** [comment]
OK, good to know! Thank you, @alemoi
