### ISSUE TITLE
Non-transient backing field for public instance property marked as transient

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#297]
The following class definition:

```c#
[Database]
public class TestClass
{
    public string NonTransient { get; set; }
    [Transient] public List<string> Transient { get; set; }
}
```
... will give you this error at runtime:
```
The data type is not supported. The data type of a field or property in an Entity class is not
supported by the database. Attribute: TestProject.Program::TestClass.<Transient>k__BackingField
(System.Collections.Generic.List`1<System.String>) (ScErrUnsupportedAttributeType 
(SCERR4012))
```
This looks like a bug to me. It would be more appropriate to always treat backing fields of transient auto-properties as also transient. The definition above should, in my opinion, be treated as equivalent to this:

```c#
[Database]
public class TestClass
{
    public string NonTransient { get; set; }
    [Transient] private List<string> _transient;
    public List<string> Transient
    {
        get => _transient;
        set => _transient = value;
    }
}
```
`Version=2.3.1.7581`

**Comment by per-samuelsson** [comment]
@erikvk, thanks for reporting this.

I will consider it a bit and get back.

**Comment by per-samuelsson** [comment]
I set it up and confirm it's a bug. `[Transient]` seem not to work properly on auto-implemented properties, just as you describe.

The workaround is to write it with an explicit backing field as in your example, or instead declare it as a field:

```csharp
[Database]
public class TestClass {
    [Transient] public List<string> Transient;
}
```

I will assign this to me to fix eventually, but since there are functional (yet not optimal) workarounds, I won't treat it as a top prio.

**Comment by erikvk** [comment]
> I set it up and confirm it's a bug. [Transient] seem not to work properly on auto-implemented properties, just as you describe.
Are you sure the problem is that general? I have had no problem with transient auto-implemented properties where the property type is an accepted database entity type, for example string. It's with properties of non-database entity types (e.g. List<string>) that things break.

I have not tested it thoroughly, but it's probably a good idea to check that Starcounter properly handles things like:

```c#
[Database]
public class TestClass
{
    [Transient] public string Transient { get; set; }
}  
````
Without creating "columns" for the `Transient` property's backing field.

**Comment by per-samuelsson** [comment]
> Are you sure the problem is that general?

Well, the more narrow it is, the better. 😸 I will do a throughout check any way, including your final question about columns. Most likely next week.

**Comment by miyconst** [comment]
@erikvk, @per-samuelsson the transient database properties will be [deprecated](https://github.com/Starcounter/Home/issues/309) in `2.3.1` and removed later.

Closing the issue as won't fix.
