### ISSUE TITLE
Questions about SQL and LINQ

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#299]
I'm working with implementing pagination in [RESTar](https://www.nuget.org/packages/RESTar/), and have some questions on when to use Starcounter SQL for things like FETCH and OFFSET and when it's fine to use LINQ commands like Take() and Skip().

1. Which of these implementations is faster, and how much faster is it?
```c#
Db.SQL<Thingy>("SELECT t FROM App.Thingy t OFFSET ? FETCH ? ", 1, 10);
Db.SQL<Thingy>("SELECT t FROM App.Thingy t").Skip(1).Take(10);
```

2. Will the difference between the implementations in 1 be greater on larger tables?

3. Are there differences in memory-use between the two implementations in 1?

@k-rus

**Comment by k-rus** [comment]
> Which of these implementations is faster, and how much faster is it?
> Db.SQL<Thingy>("SELECT t FROM App.Thingy t OFFSET ? FETCH ? ", 1, 10);
> Db.SQL<Thingy>("SELECT t FROM App.Thingy t").Skip(1).Take(10);
> Will the difference between the implementations in 1 be greater on larger tables?

I don't know which implementation is faster. @miyconst was doing measurements, but I don't think he covered this case.

I don't know  how LINQ is implemented. Thus I don't know what to expect.



> Are there differences in memory-use between the two implementations in 1?

I am not so good in C# GC to answer this question either.

Implementation of SQL will retrieve and iterate over all objects until it get the one to report. Thus if GC cleans these short running objects fast, the memory footprint will be small.
How much memory will LINQ be using, I don't know as I don't know how it is implemented.

May be @miyconst or @rogeralsing can give some inside about LINQ option performance and memory footprint and general C# GC work. I only can clarify how SQL works and can add more information when needed.

**Comment by erikvk** [comment]
OK, @k-rus . 

Also: what I'm looking for here is general guidelines, not necessary accurate technical specs. How much faster is Db.SQL? 1.0005x? 5x? 100x?

**Comment by miyconst** [comment]
@erikvk, the current situation is as follow:

**Db.SQL is times faster than LINQ**

- If there is a unique or non unique index which can be utilized.
- When retrieving objects by it's number, the `Db.FromId` method.

**Db.SQL is on par, sometimes slightly faster, sometimes slightly slower than LINQ**

- With simple `SELECT`, `WHERE`, `ORDER BY` queries.
- With simple `SELECT` with a `GROUP BY`.

**Db.SQL is slower than LINQ**

- When `JOIN` is used.
- When object properties, but not objects selected.

**Db.SQL is times slower than LINQ**

- When multiple `JOIN` statements are used.
- When joining a table to itself.
- With complex `GROUP BY` in combination with `WHERE` and `ORDER BY`.

**Comment by miyconst** [comment]
Closing the issue as answered. Please reopen if it's not yet clear.
