### ISSUE TITLE
⏰ index on parent table corrupts WHERE with navigations

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#304]
Coming from - [System.IndexOutOfRangeException: Index was outside the bounds of the array](https://github.com/Starcounter/Home/issues/303).

### Description

The following SQL query fails if these conditions meet:

```sql
SELECT COUNT(c)
FROM Child c
WHERE c.ParentId IS NULL AND c.Extra.Name IS NULL
```

- The `Child` table inherits from `Parent`.
- The `ParentId` property is defined in the `Parent` table.
-  The `Extra` property is defined in the `Child` table.
- There is an index over `Parent.ParentId` column.
- There is at least one row, which is `Parent`, but not `Child`.

**Stacktrace**

```
"System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Starcounter.Internal.DbState.View.GetObject(TypeBinding binding, Int32 index, Object proxy) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Internal\DbState.cs:line 71
   at Starcounter.Home.Issues303.Parent.Starcounter.IObjectView.GetObject(Int32 index)
   at Starcounter.Query.Execution.StringPath.EvaluateToString(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Paths\StringPath.cs:line 154
   at Starcounter.Query.Execution.ComparisonString.Evaluate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\ComparisonString.cs:line 141
   at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 127
   at Starcounter.Query.Execution.LogicalOperation.Filtrate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 209
   at Starcounter.Enumerator.MoveNext() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Mock\Enumerator.cs:line 256
   at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 484
   at Starcounter.Query.Execution.IndexScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 521
   at Starcounter.Query.Execution.Aggregation.MoveNext() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:line 188
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Starcounter.Home.Issues303.Program.<>c.<Main>b__1_0() in D:\Temp\AdFenix\AdFenixDatabase\AdFenix\Program.cs:line 33
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2146233080
"
```

### How to reproduce

- Run the code snippet below. It's a complete Starcounter application.
- Navigate to `/select` to make sure that everything works.
- Navigate to `/insert` to insert a `Parent` row.
- Make sure that `/select` still works.
- Navigate to `/create-index` to create an index over `Parent.ParentId` property.
- Check `/select` - **it fails with the exception shown above.**
- Navigate to `/drop-index` to drop the index.
- Check `/select` - it works again.

```cs
using System;
using System.Linq;
using Starcounter;

namespace Starcounter.Home.Issues303 {
    [Database]
    public class Parent {
        public string ParentId { get; set; }
    }

    [Database]
    public class Child : Parent {
        public Extra Extra { get; set; }
    }

    [Database]
    public class Extra {
        public string Name { get; set; }
    }

    class Program {
        static string indexName = $"IX_Starcounter_Home_Issues303_{nameof(Parent)}_{nameof(Parent.ParentId)}";

        static void Main() {
            Handle.GET("/select", () => {
                long count = Db.SQL<long>($@"SELECT COUNT(c)
                        FROM {typeof(Child)} c
                        WHERE c.{nameof(Child.ParentId)} IS NULL
	                        AND c.{nameof(Child.Extra)}.{nameof(Extra.Name)} IS NULL").FirstOrDefault();

                return $"Total count: {count}.";
            });

            Handle.GET("/insert", () => {
                Db.Transact(() =>
                {
                    new Parent();
                });

                return $"A {typeof(Parent)} row inserted.";
            });

            Handle.GET("/create-index", () => {
                Db.SlowSQL($"CREATE INDEX {indexName} ON {typeof(Parent)}({nameof(Parent.ParentId)})");
                return $"Index {indexName} created.";
            });

            Handle.GET("/drop-index", () => {
                Db.SlowSQL($"DROP INDEX {indexName} ON {typeof(Parent)}");
                return $"Index {indexName} dropped.";
            });
        }
    }
}
```

**Comment by miyconst** [comment]
### Query plans

**Without index**

```
Tables(
 0 = Starcounter.Home.Issues303.Child
 1 = 
  TemporaryType(
   0 : Int64
  )
)
Projection(
 0 = 
  IntegerProperty(1, 0)
)
Aggregation(
 1
 FullTableScan(
  Starcounter.Home.Issues303.Child
  0
  LogicalOperation(
   AND
   ComparisonString(
    IS
    StringProperty(0, ParentId)
    StringLiteral()
   )
   ComparisonString(
    IS
    StringPath(
     ObjectProperty(0, Extra)
     StringProperty(-1, Name)
    )
    StringLiteral()
   )
  )
  Ascending
 )
 MultiComparer(
 )
 SetFunctions(
  IntegerSetFunction(
  COUNT
   ObjectThis(0)
  )
 )
 LogicalValue(TRUE)
)
```

**With index**

```
Tables(
 0 = Starcounter.Home.Issues303.Child
 1 = 
  TemporaryType(
   0 : Int64
  )
)
Projection(
 0 = 
  IntegerProperty(1, 0)
)
Aggregation(
 1
 IndexScan(
  IX_Starcounter_Home_Issues303_Parent_ParentId ON Starcounter.Home.Issues303.Parent
  0
  ParentId
  StringDynamicRange(
   StringRangePoint(
    LessThanOrEqual
    StringLiteral()
   )
  )
  LogicalOperation(
   AND
   ComparisonString(
    IS
    StringPath(
     ObjectProperty(0, Extra)
     StringProperty(-1, Name)
    )
    StringLiteral()
   )
   IsTypePredicate(
    IS
    ObjectThis(0)
    Starcounter.Home.Issues303.Child
   )
  )
  Ascending
 )
 MultiComparer(
 )
 SetFunctions(
  IntegerSetFunction(
  COUNT
   ObjectThis(0)
  )
 )
 LogicalValue(TRUE)
)
```

**Comment by miyconst** [comment]
cc @k-rus

**Comment by k-rus** [comment]
This sounds similar to what I observed in another issue: https://github.com/Starcounter/level1/issues/3447#issuecomment-210785883

I was able to debug the problem in that issue, but I wasn't able to find a way to fix it. I guess it requires refactoring.

**Comment by un-tone** [comment]
Closing as done.
The changes are applied for SC 2.3 (https://github.com/Starcounter/level1/pull/4414) and for SC 2.4 (https://github.com/Starcounter/level1/pull/4415).

**Comment by miyconst** [comment]
Tested and accepted. Great job @un-tone!

**Comment by miyconst** [comment]
Unfortunately the issue is not solved.

Due to - [Treat navigation properties in SQL as LEFT JOIN not INNER JOIN](https://github.com/Starcounter/Home/issues/343).

After the fix, `SELECT COUNT(*)` and `SELECT *` are inconsistent.

The `SELECT COUNT(*)` treats navigation properties as `LEFT JOIN`, while `SELECT *` treats navigation properties as `INNER JOIN`.

It results in the following inconsistency:

```sql
SELECT COUNT(*)
FROM Starcounter.Home.Issues303.Child c
WHERE c.ParentId IS NULL AND c.Extra.Name IS NULL
```

```sql
SELECT *
FROM Starcounter.Home.Issues303.Child c
WHERE c.ParentId IS NULL AND c.Extra.Name IS NULL
```

- `SELECT COUNT(*)` counts all rows where `c.Extra` **is null or** `c.Extra.Name` **is null**.
- `SELECT *` selects all rows where `c.Extra` **is not null and** `c.Extra.Name` **is null**.

**Comment by un-tone** [comment]
> After the fix, SELECT COUNT(*) and SELECT * are inconsistent.

I see that we have this issue before and after the current fixes. Shouldn't we create a new separate issue for that, @miyconst?

**Comment by miyconst** [comment]
@un-tone can we fix the `SELECT COUNT(*)` behavior to work as `INNER JOIN`, not as `LEFT JOIN` in scope of this issue?

This issue is also very closely related - [In SQL queries, Count not working as expected](https://github.com/Starcounter/level1/issues/3447).

**Comment by un-tone** [comment]
As I see, the `SELECT COUNT(*)` behavior should be fixed on Prolog side. The Prolog server should build Join node as it does the `SELECT *` query, but it doesn't.

**Comment by k-rus** [comment]
I don't see why do you think it is a Prolog issue? The query plans doesn't indicate any usage of outer join. Do you see outer join in the answer returned by Prolog?

**Comment by k-rus** [comment]
The bug might be in `StringPath` operator implementation.

**Comment by un-tone** [comment]
Thanks for the clue, @k-rus. Please check the PR https://github.com/Starcounter/level1/pull/4421

**Comment by un-tone** [comment]
I've created a new PR https://github.com/Starcounter/level1/pull/4423 instead of #4421

**Comment by un-tone** [comment]
Fixes merged in https://github.com/Starcounter/level1/pull/4480.
Build log for `develop` branch: <https://teamcity.starcounter.org/viewLog.html?buildId=45688&tab=buildResultsDiv&buildTypeId=Starcounter_DevelopDailyWindows>

**Comment by un-tone** [comment]
Closing as done.

**Comment by un-tone** [comment]
Reopening.
There is a problem with build on ` Develop-Daily-SC-Nova-Windows-Debug`: <https://teamcity.starcounter.org/viewLog.html?buildId=45692&tab=buildResultsDiv&buildTypeId=StarcounterDevelop_DevelopDailyScCoreWindowsDebug>

**Comment by un-tone** [comment]
I'm working on the fix. But it seems that there are also issues with the new added tests running in Nova.

**Comment by un-tone** [comment]
@k-rus @bigwad is there something in Nova which causes that such query works differently in v2.3-v2.4 and in Nova?
```sql
select count(b) from SQLTest.EmployeeDb.EmployeeBounty b where b.SalaryEmployee.NCommission is NULL
```

```
ExpectedResult: 
 ! Int64 ! 
 | 1 | 

ActualResult1: 
 ! Int64 ! 
 | 2 | 
```

**Comment by un-tone** [comment]
My current fixes are in `fix-sql-tests-nova` branch.
Build: <https://teamcity.starcounter.org/viewLog.html?buildId=45705&tab=buildResultsDiv&buildTypeId=StarcounterDevelop_DevelopDailyScCoreWindowsDebug>

**Comment by bigwad** [comment]
Doesn't it mean an old query processor is on use? Nova uses query.processor through nuget. So one should publish a new one and probably update a reference from nova

**Comment by un-tone** [comment]
PR https://github.com/Starcounter/level1/pull/4483

**Comment by un-tone** [comment]
I saw the steps for building and pushing QueryProcessor package but it requires to know MyGet API key.
@bigwad, do you know, should I ask someone to push the package or to provide me the key?

**Comment by miyconst** [comment]
cc @ubbeK

**Comment by bigwad** [comment]
>it requires to know MyGet API key

https://github.com/Starcounter/AdminTrack/issues/392#issuecomment-351400125

**Comment by un-tone** [comment]
I updated Starcounter.QueryProcessor package and updated references.
I tested it locally - all tests pass. The created PR: https://github.com/Starcounter/level1/pull/4484.

**Comment by un-tone** [comment]
Build log: https://teamcity.starcounter.org/viewLog.html?buildId=45903&tab=buildResultsDiv&buildTypeId=StarcounterDevelop_DevelopDailyScCoreWindowsDebug

Closing...
