### ISSUE TITLE
Administrator removes all extra queries when executed selected chunk of SQL contains a semicolon

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#305]
I have the following SQL:

```sql
SELECT p
FROM Person

SELECT c
FROM Company;
```

Now, when selecting

```sql
SELECT c
FROM Company;
```

and executing it, entire SQL text field is replaced with:

```sql
SELECT c
FROM Company
```

The easy fix for this is to not remove the semicolon if something is selected.

**Comment by Mihaiii** [comment]
Closing as done.
