### ISSUE TITLE
Current release candidate link is not working

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#306]
Seems like link for current version of Starcounter Release Candidate is broken. When You go to https://starcounter.io/download/ and click on release version as usual, nothing will happen. 
![image](https://user-images.githubusercontent.com/25042256/32655155-caaf01dc-c60c-11e7-92bc-e990c94a61a2.png)
Seems like address for a link is missing. 
Going to http://downloads.starcounter.com/download and downloading from there works just fine.
CC: @Mackiovello

**Comment by Mackiovello** [comment]
This is fixed now, the problem was due to an attempted fix for https://github.com/Starcounter/TechComm/issues/348.

I'm surprised I missed this one.

**Comment by Mackiovello** [comment]
Please ping me on Slack to make sure next time, but thank you for reporting
