### ISSUE TITLE
Cannot have a button with a Font Awesome Icon only?!

### ISSUE THREAD

**Issue by johano99** [Starcounter/Home#307]
Following html gives a very cryptic javascript error when button is clicked, saying "invalid frame header" leaving no clue on whats the problem...:

`<button class="btn btn-xs btn-success" value="{{model.Refresh$::click}}" onmousedown="++this.value"><i class="fa fa-refresh"></i></button>`

Adding some character, could be anything like a '-' after the fa-icon and everything works fine.

`<button class="btn btn-xs btn-success" value="{{model.Refresh$::click}}" onmousedown="++this.value"><i class="fa fa-refresh"></i></button>`

Guess how many hours that took to hunt down... :-(

**Comment by johano99** [comment]
That working example should be:
`<button class="btn btn-xs btn-success" value="{{model.Refresh$::click}}" onmousedown="++this.value"><i class="fa fa-refresh"></i> - </button>`

**Comment by Mihaiii** [comment]
Hi @johano99 !

I don't think it has to do with FA. A way to make it work is using `pointer-events: none` CSS rule on the icon.

Relating the error, yes, I had the same problem in the past and it is annoying. Until it is fixed, you can see a detailed log on `http://localhost:8181/#/server/log` that should provide more information about the error. 

Please see https://docs.starcounter.io/guides/working-with-starcounter/error-log for more details.

**Comment by johano99** [comment]
Ok thanks!

**Comment by Mihaiii** [comment]
Closing.
