### ISSUE TITLE
Remove transient properties of database classes

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#311]
Continuation from [Deprecate transient properties of database classes](https://github.com/Starcounter/Home/issues/309).

@per-samuelsson please assign on @Mackiovello to update the documentation when done.

**Comment by Mackiovello** [comment]
Wasn't this decided against in https://github.com/Starcounter/Home/issues/309#issuecomment-367659934 so this can be closed?

**Comment by miyconst** [comment]
Yes, this issue is an artifact, closing.
