### ISSUE TITLE
Passing arguments to Main() in a Starcounter application?

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#312]
Sorry if this has been asked before, but I can't find anything on this topic.

How, if at all possible, can I pass command-line arguments to the `Main()` function of a Starcounter app?

In a normal application you would just declare your  `Main()` to accept a string array, e.g.:

```
class Program {
  static void Main(string[] args) {
    if (args.Any(arg => arg == "-someparam")) {
      // Adjust behavior
    }
  }
}
```

And on the command line:

```CMD
myApplication -someparam
```

How can I do this with a Starcounter application?

```CMD
star myApplication -someparam
```

Will the above work? Even so, assuming that whatever comes after the application name is passed to the `Main()` function of the application, if I want to specify the argument when running the application from inside VisualStudio, how can I do that given that the arguments specified there do not include the application name which is implied through other means? If I specify `-someparam` there I suppose it will translate into this:

```CMD
star -someparam myApplication
```

which probably isn't going to make much sense.

**Comment by k-rus** [comment]
If I remember correctly it is possible. I think @per-samuelsson can tell how to do so. @Mackiovello may be knows where it is documented.

**Comment by per-samuelsson** [comment]
Basic usage:

`
star app.exe this is it
`

```csharp
class Program {
  static void Main(string[] args) {
    Assert.Equal(3, args.Length);
    Assert.True(args[0], "this");
    ...
  }
}
```

**Comment by per-samuelsson** [comment]
> ... if I want to specify the argument when running the application from inside VisualStudio, how can I do that ...

As you would to a standard application, via `Project Properties | Debug | Command line`. I'll see if I can find a link to docs.

**Comment by Mackiovello** [comment]
Here's how to do it in VS: https://docs.starcounter.io/guides/working-with-starcounter/starting-and-stopping-apps#specifying-options-in-visual-studio

**Comment by per-samuelsson** [comment]
> Here's how to do it in VS: https://docs.starcounter.io/guides/working-with-starcounter/starting-and-stopping-apps#specifying-options-in-visual-studio

Also please not that example just illustrate how to specify the database, and that's consumed by the driver (i.e. `star.exe`). To pass arguments to the actual application entrypoint, just use:

```
-d=foo these 6 are passed to main
```

or

```
these 6 are passed to main
```

**Comment by per-samuelsson** [comment]
Finally, also this old issue provide valid information:

https://github.com/Starcounter/level1/issues/2584

Note especially that you need to take special care when using application arguments starting with hyphens, something we'll improve in future versions.

**Comment by Mackiovello** [comment]
[Specifying options in Visual Studio](https://docs.starcounter.io/v/2.4/guides/working-with-starcounter/starting-and-stopping-apps#specifying-options-in-visual-studio) and [Passing custom arguments](https://docs.starcounter.io/v/2.4/guides/working-with-starcounter/star-cli#passing-custom-arguments) in the docs has been updated to explain this. 

I hope this was useful @eriksunsol. If you have any more questions, don't hesitate to ask.

Closing as answered.
