### ISSUE TITLE
Transaction Rollback with RedirectUrl fails

### ISSUE THREAD

**Issue by andwah** [Starcounter/Home#316]
What am i doing wrong?
If i do a transaction.rollback on some new instances that has not yet been commited then the palindrome-redirect wont redirect.

**// Handler**
```
Handle.GET("/Screens/addscreen", (Request request) =>
            {
                MainPage mainPage = Utils.GetMainPage(request);
                User user = UserSession.GetSignedInUser();
                if (user == null)
                {
                    return mainPage;
                }

                mainPage.Content = Db.Scope(() =>
                {
                    ScreenPage screenPage = new ScreenPage
                    {
                        Data = new UserScreenRelation { Screen = new Screen(), User = user }
                    };

                    screenPage.Init();

                    return screenPage;
                });

                return mainPage;
            });

```

**// Json page**
```
    public void Handle(Input.CloseTrigger action)
        {
            if (this.Transaction.IsDirty)
            {
                this.Transaction.Rollback();
            }
            this.RedirectUrl = "/Screens/screens";
        }

```

**// html**
```
<link rel="import" href="/sys/polymer/polymer.html">
<link rel="import" href="/sys/palindrom-redirect/palindrom-redirect.html">

<template>
    <template is="dom-bind">
...
        <link is="palindrom-redirect" history url$="{{model.RedirectUrl}}" />
   </template>
</template>

```

**How to reproduce:**

Pull this code:
[https://github.com/Smorgasbord-Development/Screens](url)

1 - Run the app and navigate to http://localhost:8080/Screens/addscreen
2 - Click the "Close" button

The first click fails to redirect, if you click a second time the redirect work 

using Starcounter-RC-2.3.1.7802

**Comment by miyconst** [comment]
@andwah please provide more information.

>... the palindrome-redirect wont redirect.

What does it stand for? 

- Is the patch successfully delivered from the server to client, but `palindrom-redirect` ignores it? 
- Is the patch never send from the server to client? 
- Is the patch ignored on the client? 
- Is the value never updated on the server side?

**Comment by andwah** [comment]
Thanks for your response, i will try to investigate and update this issue with more information.

**Comment by andwah** [comment]
> Is the patch successfully delivered from the server to client, but palindrom-redirect ignores it?

Can not see any patch that set the "RedirectUrl" property

> Is the patch never send from the server to client?

There one patch sent to the client, setting (clearning) out some porperties. the "RedirectUrl" property is not mentioned in the patch.

> Is the patch ignored on the client?

Not sure how to check that?

> Is the value never updated on the server side?

The serverside "RedirectUrl" property is updated correctly.

**Comment by miyconst** [comment]
>Can not see any patch that set the "RedirectUrl" property

Then there is nothing related to redirect. Please investigate why the updated value is not sent to the client side. @chrhol might help you, if needed.

**Comment by chrhol** [comment]
Unfortunately this seems to be a bug when the dirtycheck detects that a databaseobject is deleted. For some reason, there is a piece of code that marks unbound values (like `RedirectUrl` as non-dirty in the wrong place. This has the effect that this property does not get sent to the client properly.

I will take a look.

**Comment by miyconst** [comment]
@chrhol once you have nailed down the bug, please create a new issue with proper description and close this one.

**Comment by chrhol** [comment]
New issue created. Closing this one then.
