### ISSUE TITLE
Remove `starcounter-debug-aid` from PartialToStandaloneHtmlProvider

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#317]
`starcounter-debug-aid` is being transformed into a Chrome and Firefox extension (https://github.com/Starcounter/starcounter-debug-aid/issues/51).

It should be done this week, so I advise to remove `starcounter-debug-aid` from Starcounter 2.3.1 already.

@miyconst WDYT?

**Comment by alshakero** [comment]
To reinforce the argument:

Loading KitchenSink is 1.3M => first meaningful paint is 15.5 seconds on slow 3G. 
Loading KitchenSink without `sc-debug-aid` is 172KB =>  first meaningful paint is 9.2 seconds on slow 3G.

6 seconds with one line removal is huge.

**Comment by miyconst** [comment]
Although I am really doubting about the removal, but it makes sense. Please proceed with it, but make sure that the Chrome extension is delivered in time and documented well.

**Comment by warpech** [comment]
This is done now.

The blog post announcement about it should include:

- **starcounter-debug-aid is replaced by a Chrome and Firefox extension**
- starcounter-debug-aid is removed from the default `PartialToStandaloneHtmlProvider` bootstraping code in 2.3.1
- instead, one can use a Chrome and Firefox add-on "Starcounter DevTools" or a bookmarklet: `javascript:(function(){var script = document.createElement('script');script.src = 'https://rawgit.com/Starcounter/starcounter-debug-aid/extension/build/webextension/injected_script.js';document.body.appendChild(script);})()`
- benefits are: greatly improved page load performance (see numbers in https://github.com/Starcounter/Home/issues/317#issuecomment-345693842) and faster release cycle of new features in Starcounter DevTools

**Comment by warpech** [comment]
Closing as done. The documentation change is tracked in https://github.com/Starcounter/TechComm/issues/372
