### ISSUE TITLE
Db.FromId question.

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#319]
If `Db.FromId<table>(tablePrimaryKey)` is for retreiving `table`'s unique row/object,
`Db.FromId` should be return null if `tablePrimaryKey` does not belong to `table`,
but retuns exception if belongs to `anotherTable`.
System.InvalidCastException: Unable to cast object of type `anotherTable` to type `table`.

If `tablePrimaryKey` is not used in any other tables `Db.FromId` returns null as expected.

`tbl = Db.FromId<table>(0);`  // returns null
`tbl = Db.FromId<table>(5);`  // returns `table` record
`tbl = Db.FromId<table>(570);`  // exception because 570 is `anotherTable`'s PrimaryKey

v2.4

**Comment by per-samuelsson** [comment]
Thanks for giving us feedback @SenerDemiral.

> ...  should be return null if tablePrimaryKey does not belong to table, but retuns exception if belongs to anotherTable.

What is the current experience that is flawed do you mean? I think we are returning null for any ID that is not assigned to any object, and you'll see an invalid cast if the ID exist, but is owned by an object of a type that is not possible to cast to the one you requested? If so, I don't see anything that could be improved?

**Comment by SenerDemiral** [comment]
Otherwise it force me to use `Db.SQL<table>("select t from table t where t.ObjectNo = ?", tablePrimaryKey).FirstOrDefault();` but `Db.FromID` is 6 times faster from above SQL.

I want to use `Db.FromID` without bothering exception.

**Comment by SenerDemiral** [comment]
I specially requested "retrieve this table object" using `Db.FromID<table>(PK)`
I don't want to know this `PK` assigned to `otherTable`.
I want to know if there is such object exist in this `table`.

**Comment by miyconst** [comment]
@SenerDemiral in this case you have to use `Db.FromId` method like:

```cs
var obj = Db.FromId(570) as Table;
```

The `Db.FromID<T>` is designed to throw an exception when application assumes that there is an object with certain number and certain type, but the object type is not what application assumes.

**Comment by miyconst** [comment]
Closing the question as answered.

**Comment by per-samuelsson** [comment]
> I want to know if there is such object exist in this `table`.

I see. Then use not the static cast, but a conditional. Such as @miyconst suggested. Or, to see the entire answer to all those statements:

```csharp
var f = Db.FromId(123);
if (f == null) {
  Console.Write("No such object");
}
else if (f is Foo) {
  // Or, if you want to go here instantly, f = FromId(123) as Foo;
  Console.Write("It's a Foo");
}
else {
  Console.Write($"123 is of type {f.GetType()}");
}
```

**Comment by SenerDemiral** [comment]
Yes thank you.
Best match:
```
if (f != null && f is Foo) 
  // use object : (f as Foo).prop
```

**Comment by SenerDemiral** [comment]
Another way: Pattern matching with `is` `Type pattern`
```
if (Db.FromId(123) is Foo f)
{
  // if expr is not null and is Foo
  // Use f as foo
}
```
