### ISSUE TITLE
Document deprecation of `Scheduling.ScheduleTask` in favor of `Scheduling.RunTask`

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#320]
The following methods are now deprecated and replaced with their counterparts which return .net `Task` object. This means that:

- Exceptions thrown in the synchronous tasks are brought to the waiting thread and logged.
- Exceptions thrown in the asynchronous tasks are logged only.
- Exceptions thrown in any scheduled task do not bring down code host.
- Log entries are available from the Starcounter Administrator Log page.
- It is not possible to `await` scheduled tasks, but all code after an awaited task will be executed on a new .net thread, which is not a Starcounter thread.

**Examples:**

```cs
// Deprecated:
Scheduling.ScheduleTask(() => { });

// New syntax:
Scheduling.RunTask(() => { });
```

```cs
// Deprecated:
Scheduling.ScheduleTask(() => { }, true);

// New syntax:
Scheduling.RunTask(() => { }).Wait();
```

```cs
// Deprecated:
Session.ScheduleTask("", (s, id) => { });

// New syntax:
Session.RunTask("", (s, id) => { });
```

```cs
// Deprecated:
Session.ScheduleTask("", (s, id) => { }, true);

// New syntax:
Session.RunTask("", (s, id) => { }).Wait();
```

```cs
// Deprecated:
Session.ForAll((s, id) => { });

// New syntax:
Session.RunTaskForAll((s, id) => { });
```

```cs
// Deprecated:
Session.ForAll("", (s, id) => { }, true);

// New syntax:
Session.RunTaskForAll("", (s, id) => { }).Wait();
```

```cs
Person p = Db.FromId<Person>(123);

// Awaiting a task.
await Scheduling.RunTask(() => p.SendMail());

// Error, database access is not available from the .net threads.
// The thread is no longer hosted by Starcounter.
p.EmailSentDate = DateTime.Now;
```

```cs
Person p = Db.FromId<Person>(123);

// Synchronously waiting for the task.
Scheduling.RunTask(() => p.SendMail()).Wait();

// The thread is still hosted by Starcounter.
// The database access is available.
p.EmailSentDate = DateTime.Now;
```

**Comment by Mackiovello** [comment]
Documentation is updated: https://starcounter.gitbook.io/starcounter/guides/transactions/running-background-jobs#exceptions-in-scheduled-tasks

Blog post has been posted to announce the changes: https://starcounter.io/updated-scheduling-api-better-usability/

Closing as done
