### ISSUE TITLE
Different behavior for [Database] attribute in 2.3 and 2.4

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#324]
I've created a Starcounter Class Library with the following class
```cs
[Database]
    public class Entity1
    {
        public string Field1;
    }
```
Then I created a Starcounter Application and referenced the class library, it's Program.cs is
```cs
class Program
    {
        static void Main()
        {

        }
    }
```

When I run this application and go to Starcounter Administrator, the following query in `2.3` gives me the correct schema but in `2.4` gives error `Failed to process query: SELECT * FROM StarcounterClassLibrary1.Entity1: Unknown class StarcounterClassLibrary1.Entity1`

`SELECT * FROM StarcounterClassLibrary1.Entity1`

This issue was originally found in https://github.com/Starcounter/Website/issues/284 where we published `Simplified` as nuget package to use in 2.4 but all the queries were failing because for database none of those models were defined.

**Comment by per-samuelsson** [comment]
> Then I created a Starcounter Application and **referenced the class library** ...

The problem is that the compiler will not emit any metadata reference from your application to your library if you are not using it. And in 2.4, we have changed weaving only to consider references actually in use, not each library in the same directory.

Retry and just add this to your entrypoint:

```csharp
var e = Db.SQL("SELECT e FROM Entity1 e");
Console.Write(e);
```

And let me know if the query work after that.

**Comment by habib535** [comment]
> in 2.4, we have changed weaving only to consider references actually in use

Thanks @per-samuelsson that makes sense. The problem was in the Nuget Package as the output path for Simplified project was set to '$(StarcounterBin)\Public Assemblies' after changing it to `bin\$(Configuration)` worked fine.
