### ISSUE TITLE
HTML view file cannot contain URI used for handler in its name

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#327]
This issue is presented on `10_map_Url` branch in Kitchensink. Related PR https://github.com/Starcounter/KitchenSink/pull/204

When I renamed view file from `GeoPage.html` to `MapPage.html` strange things started to happen. it seems like response for calling for view html file was replaced with response from handler. After further investigation turns out that actually happen. When You call for `http://localhost:8080/KitchenSink/MapPage.html` this handler will respond:
`Handle.GET("/KitchenSink/Map", () => WrapPage<MapPage>("/KitchenSink/partial/Map"));` which is obviously a bug (interesting one though).
@alemoi

**Comment by SenerDemiral** [comment]
I had the same situation. Coerciblely changed the uri to gMapPage from MapPage.

**Comment by alemoi** [comment]
Thanks for reporting! So basically a wrong handler is called, right? Seems like its yet another bug with old URI matcher..

**Comment by PatrykSzwer** [comment]
Yeah, instead of getting view html file, the handler '/map` is called.

**Comment by warpech** [comment]
This commit exhibits the change: https://github.com/Starcounter/UniformDocs/commit/e6a63e94162b4807cb25564dce7f00f01cedda48

**Comment by tomalec** [comment]
It is not only related to "map". I have the same problem with `KitchenSink/NavPage.html` (an any other `KitchenSink/Nav*.html`) given the handler: `Handle.GET("/KitchenSink/nav", () => new NavPage());`

**Comment by scmichal** [comment]
I also found this problem. In my case
`http://127.0.0.1:8080/bioconcept/customers_does_not_matter_what_I_add_here`
will match
`http://127.0.0.1:8080/bioconcept/customers`

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
