### ISSUE TITLE
`Data` with `IBound` should never be null, `Data` without `IBound` should always be null

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#329]
In Typed JSON, assigning `Data` to `Json` is optional. If you don't do it, then the JSON is serialized with the default values from JSON-by-example, which are usually zeroes and empty strings. 

Most of the time this is unwanted on the client side. The client has no way of knowing if a zero is a legitimate value bound to a data object, or is it a fallback because `Data` was unassigned.

One way to fix this is to allow using the `Data` property only if a data type it is declared with `IBound<T>`. Serialization of `IBound` object should throw an exception when `Data` is `null`.

It was brought to my attention by Pergite.

cc @miyconst, @chrhol

**Comment by miyconst** [comment]
>Serialization of `IBound` object should throw an exception when `Data` is `null`.

This scares me. It may bring some unwanted behavior and break some existing apps. What we actually want is this:

```json
{
    "Html": "",
    "Person": { "Name": "", "Age": 0 }
}
```

If the `Person` is `IBound<Database.Person>` and it's `Data` is not set, then the entire piece of JSON should not be present.

**Comment by warpech** [comment]
> If the `Person` is `IBound<Database.Person>` and it's `Data` is not set, then the entire piece of JSON should not be present.

This would also be acceptable, but it might be harder for the developer to understand the reason.

**Comment by miyconst** [comment]
@warpech how important this issue is? I think, we should have an online or offline discussion involving multiple people.

Yours and mine proposals are rather big API changes, and for sure should not go into `2.3.1`.

**Comment by chrhol** [comment]
Good feedback. I agree with @miyconst, a discussion about the exact behaviour would be needed. 

> Yours and mine proposals are rather big API changes, and for sure should not go into 2.3.1.

And for sure this.

**Comment by warpech** [comment]
Perhaps we can discuss some time early next year?

Of course, there is no rush with such severe API change, but I believe that the argument is valid.

**Comment by warpech** [comment]
This is a possible solution to the issue that comes up very commonly in developer feedback and should be prioritized in 2018: https://github.com/Starcounter/level1/issues/3864

**Comment by warpech** [comment]
This is a possible solution to a pull request that I needed to prepare recently: https://github.com/Starcounter/Showroom/pull/55

**Comment by warpech** [comment]
To clarify my proposal in OP. If the `Data` becomes null during the view-models life-cycle, the whole view-model should be disposed.

**Comment by miyconst** [comment]
Closing as XSON is no longer supported by Starcounter 3.
