### ISSUE TITLE
Implement binary compatibility regression test

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#331]
Regression test should check that:

- `2.3.1` database seamlessly migrates under `2.4`.
- `2.4` database fails to start, but does not corrupts under `2.3.1`.
- `2.4.x` database seamlessly migrates under `2.4.y` in case of meta schema changes between the versions.
- `2.4.y` database fails to start, but does not corrupts under `2.4.x` in case of meta schema changes between the versions.
- `2.4.y` database seamlessly starts under `2.4.x` in case of no meta schema changes between the versions.

**Note:** `2.4.y` is a greater version compare to `2.4.x`.

**Comment by k-rus** [comment]
I can suggest one more regression test to check migration between 2.3.0 and 2.3.1 in both directions. Is it valuable to add to the list?

**Comment by ubbeK** [comment]
Added to `UrbanStar` project

**Comment by ubbeK** [comment]
This could be tested kernel without level1.

cc @bigwad

**Comment by miyconst** [comment]
Archiving.
