### ISSUE TITLE
Change IgnoreJsonWithoutHtml to `true` in HtmlFromJsonProvider

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#332]
To avoid problems like https://github.com/Starcounter/level1/issues/4145, we should change the default value of `IgnoreJsonWithoutHtml` to `true`. 

I guess the value was decided to be `false` because we made a wrong assumption that all apps that return `Json` will have a view.

@miyconst can you please classify in what release this should go?

**Comment by miyconst** [comment]
This change is welcome in `2.3`, if it can be done this week.

**Comment by un-tone** [comment]
Yes, I'll take it

**Comment by Mackiovello** [comment]
Do we know that this won't break existing code? If it does, should it be added in 2.3?

**Comment by un-tone** [comment]
Working on the CompositionProvider test, I found an issue there https://github.com/Starcounter/CompositionProvider/issues/18. It should be resolved before continuing the work on the test.

> a test in CompositionProvider to check if Json without Html is not wrapped

Also @warpech, could you clarify what exactly do you expect this test will check. It looks like a mistake since CP wraps nothing.

**Comment by warpech** [comment]
> Do we know that this won't break existing code? If it does, should it be added in 2.3?

I don't know for sure but I think it won't break. The tests should show it.

> Also @warpech, could you clarify what exactly do you expect this test will check. It looks like a mistake since CP wraps nothing.

You are right. I thought that there is some `Application.Use` middleware, but in fact, there is only `OnJsonMerge`. 

So I guess a test in CompositionProvider is not needed as long as the existing tests are passing?

Still https://github.com/Starcounter/CompositionProvider/issues/18 is a real issue but I guess it does not block https://github.com/Starcounter/Home/issues/33?

**Comment by un-tone** [comment]
> So I guess a test in CompositionProvider is not needed as long as the existing tests are passing?

The new test in https://github.com/Starcounter/CompositionProvider/pull/19 PR covers the case.

> Still Starcounter/CompositionProvider#18 is a real issue but I guess it does not block #33?

Yes.

**Comment by warpech** [comment]
Great, can you make a PR to level1 then if all is sorted out?

**Comment by un-tone** [comment]
Not this one https://github.com/Starcounter/level1/pull/4397?

**Comment by warpech** [comment]
Sorry, I missed it.

Please always mention me in the comment because I don't get a notification otherwise.

**Comment by un-tone** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- included in level1 https://github.com/Starcounter/level1/pull/4397 and https://github.com/Starcounter/level1/pull/4418
- listed in CHANGELOG.md
- released in https://starcounter.io/starcounter-2-3-1-8329-release/
