### ISSUE TITLE
Load bootstraping HTML in PartialToStandaloneHtmlProvider dynamically

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#334]
In order to provide a smooth upgrade path from Polymer 1 to Polymer 2, we need to make it possible to dynamically replace the bootstraping HTML returned from `PartialToStandaloneHtmlProvider`.

A way to achieve that is to load `PartialToStandaloneHtmlProvider` default template dynamically from a URI (`/sys/app-shell/app-shell.html`) and provide a default app-shell in Level1.

The default template should be cached after the first load.

SysUpgrade can overwrite the app-shell with one that is compatible with a specific version of Polymer.

**Comment by alshakero** [comment]
I'm facing a little dilemma here:

[This method](https://github.com/Starcounter/level1/blob/f4c4fa394a3f7e726c3c377dde22cb65dcaf9d9a/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs#L112) is `static`, so it needs the template value to be either `const` or `static`. 

[I went for `static`](https://github.com/Starcounter/level1/blob/f28dc0a808a38f88a5c61efc28ebae4a213c0cf0/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs#L28-L42), but `static` means the value is assigned when you run Starcounter, and it this point StarcounterClientFiles isn't available yet which breaks Starcounter. And you obviously can't start StarcounterClientFiles before Starcounter. 

Any ideas?

**Comment by miyconst** [comment]
>The default template should be cached after the first load.

We should not implement the caching ourselves, it's the static files server's job.

**Comment by alshakero** [comment]
I changed the design a little bit and building now, let's see.

**Comment by alshakero** [comment]
@miyconst does the static files serves cache in memory? And even if it does the TCP call will still happen and this is very slow compared to a memoized string I would say.

**Comment by miyconst** [comment]
@alshakero if you cache the HTML string, the more problems arise:

- Making changes in the file will require database restart.
- Starting a sys upgrade app after the cache will mean that it won't be able to overwrite the value.

Currently Starcounter keeps every static file from the resource folders in RAM and serves it from there.

**Comment by alshakero** [comment]
I don't know why I misunderstood what I should do initially -_- 

My initial understanding was making StarcounterClientFiles necessary. Now it all makes sense.

**Comment by warpech** [comment]
Thanks @miyconst for reminding that we do not need to implement the cache!

**Comment by alshakero** [comment]
This is done [here](https://github.com/Starcounter/level1/tree/Make-app-shell-dyanmic).
Build is [here](http://teamcity.starcounter.org/repository/download/Starcounter_DevelopNightlyWindows/40163:id/Starcounter-Develop-2.4.0.4131-Setup.exe) 

And it's working perfectly. I didn't PR waiting for StarcounterClientFiles to be [approved](https://github.com/Starcounter/StarcounterClientFiles/issues/13) to allow the reviewer to test with and without it.

**Comment by alshakero** [comment]
PRed in https://github.com/Starcounter/level1/pull/4407

**Comment by warpech** [comment]
Closing as done

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- included in level1 https://github.com/Starcounter/level1/pull/4407
- listed in CHANGELOG-develop.md
