### ISSUE TITLE
Line breaks in headers => new headers

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#337]
@alemoi Including line breaks and colon-separated strings in response headers will implicitly create new response headers.

```c#
public class Program
{
    public static void Main()
    {
        Handle.GET(8100, "/test", () => new Response
        {
            StatusCode = 200,
            StatusDescription = "OK",
            Headers = {["X-MySingleHeader"] = "Some value\r\nFoo: other value\r\nBar: third value"}
        });
        var response = Http.GET("http://localhost:8100/test");
        var fooHeader = response.Headers["Foo"];
        // other value
    }
}
```

**Comment by erikvk** [comment]
A consequence of this is that if you try to insert the message from an exception, which often contains line-breaks and colon-separated strings, you will end up with additional response headers, possibly breaking things (in our case an IIS reverse proxy).

**Comment by erikvk** [comment]
`Version=2.3.1.7742`

**Comment by alemoi** [comment]
Thanks for the question! I think its even against HTTP specification actually:
```
HTTP/1.1 defines the sequence CR LF as the end-of-line marker for all
protocol elements except the entity-body (see appendix 19.3 for
tolerant applications). The end-of-line marker within an entity-body is defined by its associated media type, as described in section 3.7.
```
So you want the exception string to be a part of header? I think you will have to Base64 encode then.

**Comment by erikvk** [comment]
OK, good to know. I still think you should throw some exception if strings with line breaks are used as header values – if these cannot be handled as expected.

**Comment by alemoi** [comment]
@erikvk I think in this case we need to check for any invalid symbol in header.

**Comment by alemoi** [comment]
I thought about this and I suppose performance wise it won't be a good idea unfortunately. So I will have to keep it this way @erikvk

**Comment by erikvk** [comment]
Ok, it’s your call. If line breaks result in new headers (for external requests, `Self` calls work as expected), I think it should at least be added to the documentation.

**Comment by alemoi** [comment]
Yes, I will provide this in documentation. Thanks for the input!
