### ISSUE TITLE
Send exception stack trace in a WebSocket message frame

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#340]
Right now, if an exception happens in the server while processing a JSON Patch, Starcounter sends it in the closing frame of WebSocket, which is limited to 123 bytes.

After https://github.com/Palindrom/Palindrom/issues/188 is implemented, please send the exception stack trace in the text frame, which does not have this size limitation.

This is a continuation of https://github.com/Starcounter/Home/issues/174#issuecomment-350803808

**Comment by alemoi** [comment]
So the client will determine that its not a JSON message and will succeed parsing it? Can you please tell us more about client behavior?

**Comment by warpech** [comment]
As explained in Starcounter/Home#174 (comment), Palindrom will try to parse any WebSocket message as JSON. If the message does not parse as JSON (for example because it is a stack trace text), this is considered a fatal error end the text that did not parse will be logged as error in the browser console.

**Comment by alemoi** [comment]
Already implemented but didn't yet push to v2.3 or develop, since the JS is not ready yet.
Here is the personal build you can test: http://downloads.starcounter.com/download/Starcounter/Custom/2.3.1.8089

**Comment by warpech** [comment]
Thanks! This should be targeted at `develop`. The JavaScript part will be implemented soon. Please do not merge before the JS part is included in Starcounter.

**Comment by alemoi** [comment]
What's the status on this? Thanks!

**Comment by warpech** [comment]
The JavaScript part is finished (https://github.com/Palindrom/Palindrom/issues/188) but not yet released. It should be released within the next few days, for Starcounter 2.4+.

**Comment by warpech** [comment]
The JavaScript part is released in [Palindrom 5.0.0](https://github.com/Palindrom/Palindrom/releases/tag/v5.0.0), which was released:

- in [StarcounterClientFiles 2.2.0](https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.2.0) that was included in Starcounter 2.4 in PR https://github.com/Starcounter/level1/pull/4477
- in [StarcounterClientFiles 1.2.0](https://github.com/Starcounter/StarcounterClientFiles/releases/tag/1.2.0) that was included in Starcounter 2.3 in PR https://github.com/Starcounter/level1/pull/4478

From JS end, this can be closed. From C# end, I assume it can be closed as well, @alemoi? Is it added to changelog?

**Comment by warpech** [comment]
Closing as done
