### ISSUE TITLE
Treat navigation properties in SQL as LEFT JOIN not INNER JOIN

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#343]
Currently we treat navigation references in SQL statements as INNER JOIN. Explanation: the following SQL statement will return products where `p.Category` is not null and `p.Category.Name` is null.

```cs
SELECT *
FROM Product p
WHERE p.Category.Name IS NULL
```

My proposal is to change the behavior and return products where `p.Category` is null or `p.Category.Name` is null.

The proposed behavior is less surprising I believe.

cc @k-rus, @warpech, @dan31, @LarsTjernstrom, @atifwaqar, @un-tone, @mmnosek, @joozek78, @Joltrix

**Comment by warpech** [comment]
As I understand, the dot operator in our SQL acts similarly but not exactly like [`?.` in C#]( https://en.wikipedia.org/wiki/Safe_navigation_operator). The similarity is that it does not crash if `Category` is null. The difference is that it does not match null if the `Category is null.

If we make the change according to OP, the dot operator would work **exactly** like safe navigation operator. I like that.

On the other hand, if we apply the changes from OP then if I really want the current behavior, I will need to explicitly write `WHERE p.Category IS NOT NULL AND p.Category.Name IS NULL`. I am fine with this.

Personally, I agree, but I think that I know too little about SQL to impose my opinion. I just wish it has behavior that feels idiomatic in SQL, so I will be happy with whatever we choose as long as it feels consistent with the spirit of SQL.

**Comment by habib535** [comment]
The default join in SQL is Inner. By looking at the query I am expecting the same result as you described "`where p.Category is not null and p.Category.Name is null`"

Using `p.Category.Name` tells that you are expecting the Category to exist unless you explicitly say `p.Category IS NULL OR .. `.

**Comment by miyconst** [comment]
@habib535, @Mihaiii, thank you for the input. Let's see what others think.

**Comment by k-rus** [comment]
I think the current behaviour follows the least surprise principle, at least for users experienced in SQL.
However, I have no idea what is common expectation among our customers and if we even have enough customers with enough experience to provide feedback that we can base our decision.

IMHO the behaviour should be based on solid rules of dealing with nulls. Deciding behaviour by looking to isolated use cases will bring to us troubles of different rules being inconsistent to each other resulting to unfixable bugs with unexpected behaviours.

Currently navigation property is sugaring for inner join on foreign key, i.e., the query will look like:

```sql
SELECT *
FROM Product p INNER JOIN Category c ON p.Category = c
WHERE c.Name IS NULL
```

As I understand the proposal is to treat it as left outer join, i.e.:

```sql
SELECT *
FROM Product p LEFT OUTER JOIN Category c ON p.Category = c
WHERE c.Name IS NULL
```

What we know now is that optimising queries with outer joins is difficult and is not straightforward in contrast to queries with inner join. Suboptimial queries might be up to several magnitude slower than better optimised queries.

@Starcounter/qpt if you have anything to say about options for OP case, welcome to comment.

**Comment by mmnosek** [comment]
I think that from the developer perspective current behavior is expected and we shouldn't make any change. @miyconst have you heard any complaints about this from our partners/other developers?

For me it's natural, but maybe because of some previous Java experience. There is something like `JPQL` (Java Persistence Query Language) in the Java Persistence API, and path expressions are supported there. According to the [docs](https://docs.oracle.com/html/E13946_01/ejb3_langref.html#ejb3_langref_path) 10.2.3.4 - it also uses `inner join` to compose path expression statements. 

So IMO, following well-established patterns, we should leave it as it is. But maybe there are other examples?

**Comment by miyconst** [comment]
Okay. Looks like nothing has to be changed, let's wait for @atifwaqar and close the issue.

**Comment by miyconst** [comment]
@atifwaqar also agrees that the current functionality is good and should not be changed. Closing the issue.
