### ISSUE TITLE
Haw to copy database to another pc without unload/load?

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#344]

**Comment by k-rus** [comment]
To my understanding: just copy the database or server folder to another computer, fix paths in configuration files. Make sure that the same version of Starcounter is installed on the other computer.

I don't think we have tool support for this.
@Mackiovello Do we have documentation for this question? Do you know more details how to answer it?

**Comment by Mackiovello** [comment]
These are the instructions for doing a backup, which should be the same as copying to another PC without unload/reload: https://docs.starcounter.io/guides/working-with-starcounter/run-starcounter-in-production#database-backups

Does that answer the question @SenerDemiral?

**Comment by SenerDemiral** [comment]
Yes thank you.
It will be better to name `Files to backups` as `Moving database`.

**Comment by Mackiovello** [comment]
Great! Closing the issue
