### ISSUE TITLE
Document that Brackets are not supported as escape characters in SQL statements

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Home#346]
You used to be able to use brackets to escape keywords in `CREATE INDEX` (and probably other DDL):

     CREATE INDEX FooIndex ON Foo([Index])

In recent `develop` this fails with:

> ScErrSQLNotSupported (SCERR7023): Not supported SQL feature. Index expressions are not supported in CREATE INDEX. The error near or at position Line 1 Col 1. In query: CREATE INDEX FooIndex ON Foo([Index])

I suspect this was introduced in https://github.com/Starcounter/level1/commit/53d1c7f41fbf882173e221a4e0e8f17a8389c140.

**Comment by miyconst** [comment]
@mtornwall we have never guaranteed or documented the `[]` support as escaping characters and it's not the [SQL standard](https://stackoverflow.com/questions/19657101/what-is-the-difference-between-square-brackets-and-single-quotes-for-aliasing-in). The standard escaping character is the double quote - `"`.

@Mackiovello please add a documentation line explicitly stating that `[]` not supported.

**Comment by Mackiovello** [comment]
> @Mackiovello please add a documentation line explicitly stating that [] not supported.

Done: https://docs.starcounter.io/v/2.4/guides/sql/reserved-words#escaping-reserved-words

I expect that this issue can be closed now

**Comment by miyconst** [comment]
@Mackiovello thank  you for the quick response, but it has to be documented in `2.3.1` and `2.4`.

**Comment by Mackiovello** [comment]
> @Mackiovello thank you for the quick response, but it has to be documented in 2.3.1 and 2.4.

It has been documented in both 2.3.1 and 2.4, I just linked to 2.4
