### ISSUE TITLE
Use .NET Framework 4.6.1 for apps

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Home#347]
I have installed fresh VS2017 that comes with .NET Framework 4.6.1. But most of our apps uses 4.5. I think it would be cool if flow mentioned at https://docs.starcounter.io/getting-started#1.-install-visual-studio would be as simple as it seems:
1. Download VS2017 - with the default setup,
2. Install Starcounter,
3. Open existing app solution (with no warnings and errors),
4. build and run.

Currently, even though it [seems it's installed in VS](https://www.microsoft.com/net/download/visual-studio-sdks) asks me to either switch the project to 4.6.1 (what I did, usually without problems), or to download 4.5 what is yet few additional steps to take and distract my focus on the new amazing technology - Starcounter.

I think it would improve initial developer impression

**Comment by warpech** [comment]
Do you mean `4.6.1`? If yes, I agree.

@kegor could you please do it for the [current apps of the Web Platform Team](https://github.com/search?utf8=%E2%9C%93&q=topic%3Aweb-platform-team+topic%3Aapp+org%3AStarcounter+fork%3Atrue&type=Repositories), **excluding the apps with topic `frozen`**?

@Mackiovello maybe you want to apply this also to HelloWorld, @Mihaiii maybe you want to apply this to prefab apps?

I've found one prefab that is already on that version: https://github.com/StarcounterApps/Content/blob/7bbc4a4dec865bdd02e56f29092b85439685f766/src/Content/Content.csproj#L14

**Comment by Mackiovello** [comment]
Updated for HelloWorld

**Comment by kegor** [comment]
Updated for StarcounterClientFiles, PalindromBenchmark and Blending. Other apps or already have highest version of targetFramework either do not have project file. 

On my view it looks like "ready to close" for now.

**Comment by Mackiovello** [comment]
> On my view it looks like "ready to close" for now.

Great! Good work @kegor 

Closing the issue

**Comment by Mackiovello** [comment]
Missed that the apps haven't been updated. When you're done, please close the issue @Mihaiii

**Comment by Mihaiii** [comment]
The `master` branches of public repos under StarcounterApps were updated.
Closing.
