### ISSUE TITLE
Msbuild zombie process is left alive after building

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#348]
Starcounter version: 2.4.0.4476
Repro:
```
ps msbuild // verify no msbuild is running prior to repro
git clone git@github.com:starcounter/blending
cd blending
git checkout 7c8d1c48641586e0a01652d0d7f92acf046a433c
msbuild ./Blending.sln
ps msbuild
```
**After the build finishes, msbuild process is left behind running.** It locks the starcounter files, which causes problems in CI.

Possible workaround is to kill all msbuild processes after building, but blindly killing processes may lead to other problems and should not be our final answer to that.

**Comment by per-samuelsson** [comment]
This is standard. I think it's usually referred to as "node reuse" in MsBuild-lingo.

FWIW, we have (unofficial) `staradmin kill devall´ that brutally kill every msbuild process in 2.4, if you need inspiration.

**Comment by per-samuelsson** [comment]
Try: `msbuild /nodeReuse:false`.

**Comment by joozek78** [comment]
Thanks for the explanation. I had no idea msbuild would do such things
