### ISSUE TITLE
Trailing slash by default in Starcounter apps

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#349]
I've noticed that Starcounter doesn't recognize slash-ended Uri's in apps. Trailing slash is a pretty common mechanism and I can't see why We shouldn't use it. Are there any practical reasons why We don't have it implemented?

**Comment by k-rus** [comment]
As I remember the question was discussed and answered, but I cannot find the issue. May be someone can find the issue or repeat answer here.

My memory says that there was some obvious reason unrelated to us.

**Comment by miyconst** [comment]
We do support URLs with trailing slashes, but it's important to understand that `/url` and `/url/` are two **different** things with **different** behavior.

Some copy paste:

>It is not a question of preference. `/base` and `/base/` have different semantics. In many cases, the difference is unimportant. But it is important when there are relative URLs.
>- `child` relative to `/base/` is `/base/child`.
>- `child` relative to `/base` is (perhaps surprisingly) `/child`.

Read more on StackOverflow - [When should I use a trailing slash in my URL?
](https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url).

And lastly, if there is a need to have a URI handler with a trailing slash, it can be easily registered that way:

```cs
Handle.GET("/uri/", () => "I have a trailing slash.");
```
