### ISSUE TITLE
I change the default path to "My Documents" 

### ISSUE THREAD

**Issue by andwah** [Starcounter/Home#351]
I change the path to "My Documents" in windows 10. so all documents is saved to my D: drive.
resulting that starcounter scservice fails to start.

When i install starcounter the repository is created in the correct place. `D:\documents\starcounter`
But when i check inside `Personal.server.config` there is still paths pointing to `C:\Users\...`

Can someone please verify that this works on another machine, maybe just mine was in some strange state

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
