### ISSUE TITLE
VS: .Net Framework version select box value is ignored upon project creation

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#354]
When creating a project in Visual Studio, it's possible to select .Net Framework version. Still, when creating a Starcounter project the option value is ignored, and the project is always created with .Net 4.5.

![image](https://user-images.githubusercontent.com/6435556/35145153-171ea924-fd07-11e7-991d-99ca03b322f6.png)

@Mihaiii do you think you could look at this?

**Comment by Mihaiii** [comment]
Yes! Thank you! This is an interesting task.

**Comment by Mihaiii** [comment]
Closing as done: will be included in the next release of the extension.
