### ISSUE TITLE
Problems starting network gateway process. v2.4.0.4613

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#355]
Upgrade from working v2.4.0.4593.
(Unable to downgrade previous version. Setup is not working)

C:\Program Files\Starcounter>scservice
Starting Starcounter PERSONAL engine...
Press CTRL-C to exit.

Reading server configuration from: C:\Starcounter\Personal\PERSONAL.server.config
Reading gateway configuration from: C:\Starcounter\Personal\scnetworkgateway.xml
Error: ScErrStartNetworkGateway (SCERR2110): Problems starting network gateway process.
Please review server log in: C:\Starcounter\Personal\Logs

**Comment by miyconst** [comment]
@SenerDemiral thank you for the report, it seems to be an issue in the latest builds.

>Unable to downgrade previous version. Setup is not working

Please go to the control panel and uninstall Starcounter from there, then you will be able to install older version which does not have the issue.

**Comment by alemoi** [comment]
Thanks for reporting! The issue was with adding one file to white-list. The fix is available in the coming nightly!
