### ISSUE TITLE
Method not found: RunUriMatcherAndCallHandler in Self-Hosted Starcounter

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#357]
Starcounter version: `2.4.0.4593`
I'm trying to follow the guide to setting up tests in Self-Hosted Starcounter: [link](https://docs.starcounter.io/v/2.4/cookbook/unit-testing-with-database-access). It fails when `Runtime.Run` method is called:
```
System.MissingMethodException
Method not found: 'Boolean Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(System.String, System.String, Starcounter.Request, UInt16, Starcounter.Response ByRef)'.
   at Starcounter.Internal.AppsBootstrapper.InitAppsBootstrapper(Byte numSchedulers, UInt16 defaultUserHttpPort, UInt16 defaultSystemHttpPort, UInt32 sessionTimeoutMinutes, String dbName, Boolean noNetworkGateway)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupFromConfiguration(IHostConfiguration config)
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider)
   at Authorization.Database.Tests.TestContext..ctor() in C:\Users\joozek\dev\authorization\Authorization.Database.Tests\TestContext.cs:line 38
```
Reproduction code: https://github.com/Starcounter/Authorization.Simplified
Build, and then try to run [`TestIfTestsTestTheTests`](https://github.com/Starcounter/Authorization.Simplified/blob/master/Authorization.Simplified.Tests/Class1.cs#L13)

**Comment by joozek78** [comment]
@alemoi git says you were the last person to edit this code. Have you got any idea what that could be?

**Comment by per-samuelsson** [comment]
@joozek78,

Since references are now copy-local in 2.4 (you have assured that, right?), this could possibly be due to some mismatch. Have you tried a full clean (verifying all binaries in your project output are actually gone) and then build / run again?

**Comment by joozek78** [comment]
> you have assured that, right?

Right, I've used the Starcounter Library template and it did its job well

> Have you tried a full clean (verifying all binaries in your project output are actually gone) and then build / run again?

I did. It didn't help :(

**Comment by per-samuelsson** [comment]
> I did. It didn't help.

OK. That's bad. Then I don't have any real ideas at this point. The feeling you get is that the installation is corrupt somehow.

**Comment by joozek78** [comment]
I'll try to reinstall then. Thanks for pointers

**Comment by joozek78** [comment]
Reinstalling (and upgrading to 2.4.0.4627) didn't help

**Comment by per-samuelsson** [comment]
How urgent is this? Wan't me to get involved, setting up an environment and help you diagnose it?

**Comment by joozek78** [comment]
It's not urgent. I need it to properly move Authorization to 2.4. Let's wait and see if @alemoi knows anything about it

**Comment by alemoi** [comment]
I would agree with @per-samuelsson that its some DLLs mismatch. I would search all `Starcounter.REST.dll` and find duplicates.

**Comment by joozek78** [comment]
I have no `Starcounter.REST.dll` in my project directory. I've tried adding `Starcounter.Server.Rest` as a dependency, but it didn't help.

**Comment by joozek78** [comment]
@alemoi have you got any idea how to follow up on that? It's not urgent, but I don't it to be forgotten

**Comment by joozek78** [comment]
I've updated the repro code: https://github.com/Starcounter/Authorization.Simplified. Just follow the instructions to test

**Comment by per-samuelsson** [comment]
Seems like @alemoi is on https://github.com/Starcounter/CompanyTrack/issues/393. I assume the best is to await that to be done and then check if this is still an issue.

What about we close this one and have as a prerequisite that https://github.com/Starcounter/CompanyTrack/issues/393 test this case before it can be considered done? @joozek78? @alemoi?

**Comment by alemoi** [comment]
The assemblies from Visual Studio reference assemblies directory `Public Assemblies` (newly `VsRefAssemblies`) are moved to all binaries directory. Whole Starcounter binaries directory becomes Visual Studio reference assemblies directory. NOTE: Starcounter Visual Studio plugin needs to be reinstalled because of this change (so that reference assemblies are located properly).

**Comment by alemoi** [comment]
@joozek78 I think unfortunately some tests are needed to be adjusted once again (like when `Public Assemblies` was renamed to `VsRefAssemblies`). Thank you for adopting.

**Comment by joozek78** [comment]
Now it fails with another exception:
```
System.InvalidCastException
[A]Sc.Server.Weaver.Schema.DatabaseAssembly cannot be cast to [B]Sc.Server.Weaver.Schema.DatabaseAssembly. Type A originates from 'Starcounter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' in the context 'LoadNeither' at location 'C:\Program Files\Starcounter\Starcounter.dll'. Type B originates from 'Starcounter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' in the context 'LoadFrom' at location 'C:\Users\joozek\dev\authorization.simplified\Authorization.Simplified.Tests\bin\Debug\Starcounter.dll'.
   at Sc.Server.Weaver.Schema.DatabaseAssembly.Deserialize(Stream stream) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter\Mock\Schema\DatabaseAssembly.cs:line 190
   at Sc.Server.Weaver.Schema.DatabaseSchema.DeserializeFrom(Stream stream) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter\Mock\Schema\DatabaseSchema.cs:line 357
   at Starcounter.Hosting.RuntimeHosts.SelfHosted.AssemblyResolver.Starcounter.Hosting.IAssemblyResolver.RegisterApplication(String executablePath, DatabaseSchema& schema) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter.Hosting\RuntimeHosts\SelfHosted\AssemblyResolver.cs:line 35
   at StarcounterInternal.Hosting.Loader.ExecuteApplication(Void* hsched, ApplicationBase appBase, EntrypointOptions entrypointOptions, Stopwatch stopwatch) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Loader.cs:line 109
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 appStartProvider) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 337
   at Authorization.Database.Tests.TestContext..ctor() in C:\Users\joozek\dev\authorization.simplified\Authorization.Simplified.Tests\TestContext.cs:line 38
```

Do you think I should post another issue and close this one?

**Comment by alemoi** [comment]
I would suggest deleting all copied local assemblies because it feels like there is a duplicate somewhere.

**Comment by alemoi** [comment]
@per-samuelsson im i right about guess about some duplicate somewhere?

**Comment by per-samuelsson** [comment]
> @per-samuelsson im i right about guess about some duplicate somewhere?

Not entirely I think. Looks like the last issue is about deserializiation problem in self-hosted mode, caused by one assembly being used when serializing and the other when deserializing.

> Do you think I should post another issue and close this one?

Yes, please do. And also if you have the time and patience, I would be really happy to see an isolated, small-as-possible sample where it was reproduced. It could be that this is something we actually need to spend time to fix properly. Please ping me in the new issue.

**Comment by per-samuelsson** [comment]
Oh, and @joozek78, could you please try to do an as-brutal-as-possible Clean on that project and try building after that? Like do "Clean". Then test. If still doesn't work, delete entirely `bin` and `obj` folders and try again. Would be highly appreciated!

**Comment by joozek78** [comment]
@per-samuelsson Cleans didn't help. I've posted [the new issue](#380)
