### ISSUE TITLE
staradmin.exe Redirect output

### ISSUE THREAD

**Issue by careri** [Starcounter/Home#358]
I'm writing a tool that interacts with your executables. 
In this case I want to list the running databases.

From cmd this works:
> staradmin list db

But when I create a new Process from c# I just get this error:
>default
>The handle is invalid.

I tried using the correct way with redirecting the streams and reading the output from the streams. I use the same code for other executables and that works fine.

So to get around the problem I tried writing the command to a batch that in turn redirects the output to another file. That didn't work either. The problem seems to be that I can't redirect at all.

Try this from cmd:
> staradmin.exe list db 1> knas.txt 2>&1

The contents of knas.txt is:
>default
>The handle is invalid.

**Comment by andwah** [comment]
Just an side not.. why not use the REST api..  
Try this:
http://localhost:8181/api/engines/default

**Comment by careri** [comment]
I'll have a look at that for now. Since I'm stuck at the moment

**Comment by careri** [comment]
Hmm, that url only shows running databases. I want to get all of them. I'll try to find another url.

**Comment by careri** [comment]
That was easy :)
http://localhost:8181/api/databases

**Comment by miyconst** [comment]
@careri can we close the issue as answered?

**Comment by careri** [comment]
Not really, I did a work around. It should still be possible to redirect the StdOut and StdErr

**Comment by miyconst** [comment]
>It should still be possible to redirect the StdOut and StdErr

It definitely should, and it will be in the new version of the `staradmin` tool which is already planned. Existing tool is very unlikely to be modified.

**Comment by careri** [comment]
By a chance I got the same error executing my application in powershell.
In my case it was:
```cs
Console.TreatControlCAsInput = true;
```

Don't know if this is of any help?

>Unhandled Exception:
>
>System.TypeInitializationException: The type initializer for 'ShadowSpawnTest.Program' threw an exception. ---> System.
IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.set_TreatControlCAsInput(Boolean value)
   at ShadowSpawnTest.Program..cctor()
   --- End of inner exception stack trace ---
   at ShadowSpawnTest.Program.Main(String[] args)

**Comment by careri** [comment]
This is still a problem for me. 
I'm writing a deployment script for HeadsOne in Powershell. 
Your executables don't play nice in powershell
> The handle is invalid

**Comment by miyconst** [comment]
@per-samuelsson could you take a look please? Maybe we can fix it?

**Comment by per-samuelsson** [comment]
> @per-samuelsson could you take a look please?

Can someone else? I don't think i'm more fit then anyone else, and it should be straightforward to trace the reason. I have 0 clue unless I check.

(I have a memory it was reported same thing from bash many years ago btw).

If no one else can, I can o/c do it, but haven't got a good env setup I think.

**Comment by miyconst** [comment]
Agreed with @per-samuelsson that he will take a look, eventually.

**Comment by per-samuelsson** [comment]
> Agreed with @per-samuelsson that he will take a look, eventually.

Hopefully some time next week.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
