### ISSUE TITLE
First meaningful paint is slow 

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Home#362]
SC Version 2.4.0.4671

Here I have a very simple html with just 1 h1 tag. and an empty viewModel, but my page's performance is very poor. Is this the standard SC page speed? or is there something wrong with my code?

![image](https://user-images.githubusercontent.com/4388707/35353768-815bd5f6-0148-11e8-9a9f-18b61b719659.png)

**Comment by miyconst** [comment]
cc @warpech, @alshakero

**Comment by warpech** [comment]
The Chrome DevTools performance audit simulates a slow CPU on a slow network. 

In one of our Starcounter apps (that consists of much more than just `<h1>`), it takes 1.9 s to full render on my machine, still Chrome reports 9.5 s in an audit. I wonder why you get 13 s with just a `<h1>`.

On our roadmap, we will February and March 2018 on improving the page load performance. I am sure that you will get better results then.

Please note that Starcounter does not have response gzipping or HTTP/2. It is advised to use a proxy server that can add gzip and HTTP/2. CloudFlare is the easiest solution to achieve that.

Is this ok if I close this thread and redirect you to an umbrella issue: https://github.com/Starcounter/RebelsLounge/issues/225

**Comment by atifwaqar** [comment]
@warpech Thanks for the detailed response. 
And noticed gzip issue some days ago, and @mmnosek explained that it used to be in Strcounter, but for some issue, it got removed.
Anyway, I'll try to configure CloudFlare on my server, and try to check the performance again. 

I'm closing this issue now, and i'll impaciently wait for the `early February` release you mentioned :)
