### ISSUE TITLE
Document database cleaner tool

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#364]
@Mackiovello please document how to clean up the database after the DDL statement executions.

Currently supported DDL statements are:

- `DROP TABLE X`.
- `ALTER TABLE X DROP COLUMN x`.
- Both of the statements are allowed only if the table `X` is not loaded by any application.

After those statements, the actual tables and columns are not deleted, only marked as deleted. The applications won't see the deleted items, and the database will behave as if they are not there. Still, physically, they are there.

To remove the dropped items, a cleaning procedure has to be called:

- `staradmin start cleaner`.

This applies to Starcounter `2.3.1` release and up.

**Comment by k-rus** [comment]
I think it is important to note that cleaning process might produce transaction conflicts with actual applications, thus it is recommended to run it during low load time to avoid performance drop.

**Comment by atifwaqar** [comment]
> To remove the dropped items, a cleaning procedure has to be called:
staradmin start cleaner.

@miyconst  This means we have to stop the DB first?

**Comment by miyconst** [comment]
@atifwaqar, no, that the whole point, you don't have to stop the database to perform those operations. The only requirement, is that the CLR classes to dropped altered tables are not loaded.

**Comment by miyconst** [comment]
[How to delete unused tables and columns](https://docs.starcounter.io/cookbook/how-to-delete-unused-tables-and-columns).

**Comment by mmnosek** [comment]
Guys, don't you think "cookbook" isn't the best place for such documentation? It's quite important. It should be mentioned in couple places:
* https://docs.starcounter.io/guides/working-with-starcounter/staradmin-cli
* `DDL` support probably requires additional page in "database section"
* https://docs.starcounter.io/guides/working-with-starcounter/database-refactoring#refactorings

**Comment by miyconst** [comment]
>Guys, don't you think "cookbook" isn't the best place for such documentation? It's quite important. It should be mentioned in couple places:

I just need to be able to find and share the page, if it's better to move to another section - I don't mind.

**Comment by k-rus** [comment]
NewQP syntax including DDLs are described in a documentation, which was moved from RebelsLounge to CompanyTrack.

It is long standing issue how to gradually move from OldSQL documentation to NewQP documentation as functionality is moving to the product.
