### ISSUE TITLE
Update the Shadow copy documentation

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#366]
This section - [Run Starcounter in Production - Database Backups](https://docs.starcounter.io/guides/working-with-starcounter/run-starcounter-in-production#database-backups) needs to be updated.

The proposed command to create a shadow copy uses `%date%` variable which outputs date in local format, which leads to weird folder structure or even invalid folder names with different culture settings.

```
c:\Users\User\Documents\Starcounter\Personal\Data\Default\Default-20150915T100722555\ Q: robocopy Q:\ Y:\Backup\%date%_%time:~0,2%-%time:~3,2%-%time:~6,2% /s
```

Instead it should be:

```
ShadowSpawn.exe C:\Users\User\Documents\Starcounter\Personal\Data\default\Default-20150915T100722555\ Q:\ robocopy Q:\ "Y:\Backup\%date:~10,4%.%date:~4,2%.%date:~7,2%-%TIME:~0,2%.%TIME:~3,2%.%TIME:~6,2%" /s
```

**Comment by miyconst** [comment]
Also add link to the [Microsoft DOS robocopy command](https://www.computerhope.com/robocopy.htm) documentation.

**Comment by Mackiovello** [comment]
Done
