### ISSUE TITLE
Access denied: unable to install Starcounter on Windows Server 2016 essentials

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#367]
```
Starcounter-RC-2.3.2.157
```

![image](https://user-images.githubusercontent.com/6435556/35484226-6b481c2c-044d-11e8-866f-570cda0f690d.png)

No extra items in the Windows logs.

**Comment by miyconst** [comment]
Trying to install `Developer mode`.

**Comment by miyconst** [comment]
Starcounter `2.3.1.8329` installs with no problem.

**Comment by atifwaqar** [comment]
I am trying SC 2.4 and i am facing the same issue

**Comment by miyconst** [comment]
@atifwaqar please specify full version of Starcounter and Windows.

**Comment by atifwaqar** [comment]
I have Windows 10 Pro on my machine and i tried to install SC 2.4.0.4692, 2.4.0.4671 & 2.4.0.4593

**Comment by miyconst** [comment]
cc @ubbeK

**Comment by atifwaqar** [comment]
> Starcounter 2.3.1.8329 installs with no problem.

I just tested this, and its also fails if my windows defender is active. 
This is how i turned windows defender off 
![image](https://user-images.githubusercontent.com/4388707/35504732-1e7ab2f0-04e4-11e8-9505-2773ae1a6bfd.png)
and then everything worked fine (Only for 2.3.1.8329)

**Comment by ubbeK** [comment]
Have you tried to just give an exclusion to a specific folder:

Windows Defender Security Center => Virus & threat protection => Virus & threat protection settings => Add or remove exclusion => Add an exclusion => Folder

**Comment by ubbeK** [comment]
Is this still an issue?

There have been issues with anti-virus programs before.

https://github.com/Starcounter/Home/issues/370

**Comment by atifwaqar** [comment]
The installation error reported by @miyconst seems to be disappeared from my machine. 

However 1 symptom from the same installation error is left. Just checked with following SC versions : 
2.4.0.4672.  Installed successfully but failed to start SC server
2.4.0.4963. Installed successfully and started DB successfully 
2.3.2.157.  Installed successfully and started DB successfully 

When it did not work, I mean Staradmin keeps trying to start the server
![image](https://user-images.githubusercontent.com/4388707/36028229-80c3be4e-0d9e-11e8-9feb-2109c48825fd.png)

![image](https://user-images.githubusercontent.com/4388707/36028255-92ae844a-0d9e-11e8-8d2d-e8ee888d7235.png)

@miyconst Since the latest 2.4 works fine, I'd say you can close this issue?

**Comment by miyconst** [comment]
I am still having the problem installing latest 2.3.2` on Windows Server 2016.

```
Starcounter-RC-2.3.2.373-Setup.exe
```

![image](https://user-images.githubusercontent.com/6435556/36029819-0dbb9dac-0da5-11e8-9a91-d79a5990be6d.png)

**Comment by miyconst** [comment]
Happened when I tried to upgrade from `Starcounter-Release-2.3.1.8329-Setup.exe`.

**Comment by miyconst** [comment]
Also installer shuts down without any message when trying to downgrade from `Starcounter-RC-2.3.2.373-Setup.exe` to `Starcounter-Release-2.3.1.8329-Setup.exe`.

**Comment by iqbalskd** [comment]
I tried installing Starcounter on a [Windows Server  2016 Essential (Evaluation)](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2016-essentials) on a virtual machine. The installer installed VC++ Resdistributable, It didn't work with the Restributable that installer installs, it was complaining about `Missing msvcr100.dll` Then I installed the [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://www.microsoft.com/en-us/download/details.aspx?id=5555).
After that I was able to start the service successfully. I could not reproduce the screen shots attached here.

**Comment by miyconst** [comment]
@iqbalskd did you try the same steps? 

>Happened when I tried to upgrade from Starcounter-Release-2.3.1.8329-Setup.exe.

>Also installer shuts down without any message when trying to downgrade from Starcounter-RC-2.3.2.373-Setup.exe to Starcounter-Release-2.3.1.8329-Setup.exe.

**Comment by iqbalskd** [comment]
> @iqbalskd did you try the same steps?
Also installer shuts down without any message when trying to downgrade from Starcounter-RC-2.3.2.373-Setup.exe to Starcounter-Release-2.3.1.8329-Setup.exe.

Yeah this issue exits, currently the installer seems unable to upgrade from any RC to Release. I will further look into it.

**Comment by iqbalskd** [comment]
Can I now close this issue, as I was not able to reproduce the screen shots attached here, the only issue I faced was regarding VC++ Redistributable which is already being discussed in a [new issue](https://github.com/Starcounter/level1/issues/4505).
@miyconst @ubbeK @atifwaqar

**Comment by miyconst** [comment]
Let's close it, and I will reopen if I hit it with the latest installers.
