### ISSUE TITLE
"RegisterMergeCallback" callback is triggered too many times

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#369]
## Steps to reproduce

Using Starcounter 2.4

1. Build and run BlendingEditor and BlendingProvider using `run.bat` from https://github.com/Starcounter/Blending `f34b1326eb854bf0cf9e1df71a3741b3aae65ce6`
2. Go to <http://localhost:8080/BlendingEditor> in a web browser
3. Open Starcounter DevTools
4. In the "View-model" tab, expand the path `/BlendingProvider_0/Sections/TopbarRight`

## Expected

In the namespace `TopbarRight` there should be a single object with the key `BlendingProvider_0` with 6 properties in it.

## Actual

In the namespace `TopbarRight` there are two objects:

- `BlendingProvider_0` - unexpected, empty object
- `BlendingProvider_1` - the object with 6 properties that I was expecting in `BlendingProvider_0`

I have seen this error when I first tried 2.4 few weeks ago, but I forgot to report.

@chrhol can you please check?

cc @PatrykSzwer, @kegor, @un-tone 

![2018-02-01 21_50_41-](https://user-images.githubusercontent.com/566463/35702679-0282d236-079a-11e8-9e21-286d653cc7cc.png)

**Comment by chrhol** [comment]
Right, I think you talked about this some time ago and I completely forgot it. Thanks for creating an issue. 

One question: is this different from how it works in `2.3.*`?

**Comment by chrhol** [comment]
This does look correct though, there is an empty handler that is registered in `BlendingHandler.cs` (https://github.com/Starcounter/Blending/blob/master/src/BlendingProvider/Website/Api/BlendingHandlers.cs#L463-L469) that returns an empty json which will be namespaced with `BlendingProvider_0`. 

The result from the merge-callback will then be added as `BlendingProvider_1`

**Comment by warpech** [comment]
Thanks for the investigation. Sorry for the trouble! I started to notice the problem of too many empty objects around the time when we migrated to 2.4, so I connected these two facts. But maybe they are not related.

I will close this issue for now until I figure out if this is actually a problem. It seems that it is by design of BlendingProvider.
