### ISSUE TITLE
One or more errors occured

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Home#370]
I tried to upgrade Starcounter, from 2.4.0.x (now, I cannot recall nor track precise version).
After installation completed the operation I tried to run an app. That seems to hang on creating a database.
So I did `staradmin kill all` and, now I'm trying to just start Starcounter server (using desktop icon created by installation). That results in system tray notification:

> Starcounter service error
> One or more errors occured

and nothing more.
I tried pruning Starcounter as much as I could: uninstalled, removed Starcounter folder from my Documents, and install a fresh version.
For `2.4.0.4903`, `2.4.0.4671`, `2.4.0.4886`, I got the same behavior. Logs at `Documents\Starcounter\Personal\Logs` are also empty.

**Comment by ubbeK** [comment]
Is not possible to start with CLI command either?

`staradmin start server`

**Comment by ubbeK** [comment]
> I tried pruning Starcounter as much as I could: uninstalled, removed Starcounter folder from my Documents, and install a fresh version.

Double check if %StarcounterBin% environment variable and %PATH% has been cleaned as well.

**Comment by tomalec** [comment]
> Is not possible to start with CLI command either?
>
>`staradmin start server`

It started the server successfully, but I still cannot use administrator: `127.0.0.1:8181`.
Deleting database (`staradmin delete db default`) hangs as well.

**Comment by tomalec** [comment]
> Double check if `%StarcounterBin%` environment variable and `%PATH%` has been cleaned as well.

Checked, both were cleaned.

**Comment by ubbeK** [comment]
Sounds like I need to try it out myself.

**Comment by ubbeK** [comment]
I have been upgrading / downgrading between `2.4.0.4903` and `2.3.2.322` a bunch of times and can unfortunately not reproduce this.

I cannot remember any third party changes in `develop` lately other .NET 4.6.1 dependency and I bet you already have that installed.

Otherwise, you need vc++ redist (which should be installed by installer if you dont have it installed), https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by andwah** [comment]
maybe some disturbing antivirus software?

**Comment by ubbeK** [comment]
> maybe some disturbing antivirus software?

Maybe add an exclusion to the database
`Windows Defender Security Center` => `Virus & threat protection` => `Virus & threat protection settings` => `Add or remove exclusion` => `Add an exclusion` => `Folder`

**Comment by tomalec** [comment]
> maybe some disturbing antivirus software?

I've already disabled my Avast, I'd try fiddle around it as well

**Comment by tomalec** [comment]
It seems I have fixed this. However, I still don't know what was it (seems that this https://twitter.com/bendhalpern/status/578925947245633536 applies not only to JS).

What I suppose was a solution:
- uninstall Starcounter (2.4),
- remove `profile/Documents/Starcounter`
- install Starcounter Stable `Starcounter-Release-2.3.1.8329-Setup`,
- start server,
- `staradmin delete db default`,
- `staradmin kill all`,
- uninstall Avast antivirus,
- uninstall Starcounter (2.3.1),
- remove `profile/Documents/Starcounter`,
- `staradmin start server`,
- `staradmin delete db default`,
- install and enable Avast,
- Run the app.

phew....
