### ISSUE TITLE
Administrator "Allow Remote Access" after-change message

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#374]
By default "Allow Remote Access" is disabled. When I change it, the message "The new settings will be used the next time the server starts." is shown.
It is incorrect because the new value is applied right after saving, without server restarting.

![scadmaram1](https://user-images.githubusercontent.com/1625378/35938041-0e4bc14a-0c59-11e8-8274-25f032366755.png)

The message should be fixed since it deceives users.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
