### ISSUE TITLE
VSIX Visual Studio Package not working

### ISSUE THREAD

**Issue by careri** [Starcounter/Home#375]
Microsoft Visual Studio Enterprise 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

SC Version: 2.3.2.348

I updated to this version, and now I seem to be missing **Starcounter.Cli.dll**
I doesn't exist in the installation folder. 

But looking in the installer the file is there. Maybe visual studio had it locked somehow?
(I might have had visual studio open, but probably not)

Maybe you should add some verification that all files are written to the installation folder?

This is from the visual studio activitylog.xml

```xml
<description>
LegacySitePackage failed for package [Starcounter.VisualStudio.VsPackage, Starcounter.VisualStudio, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf]Source: &apos;
Starcounter.VisualStudio&apos;
 Description: Could not load file or assembly &apos;
Starcounter.CLI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf&apos;
 or one of its dependencies. The system cannot find the file specified.&#x000D;
&#x000A;
System.IO.FileNotFoundException: Could not load file or assembly &apos;
Starcounter.CLI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf&apos;
 or one of its dependencies. The system cannot find the file specified.&#x000D;
&#x000A;
File name: &apos;
Starcounter.CLI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf&apos;
&#x000D;
&#x000A;
   at Starcounter.VisualStudio.VsPackage.Initialize()&#x000D;
&#x000A;
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)&#x000D;
&#x000A;
&#x000D;
&#x000A;
WRN: Assembly binding logging is turned OFF.&#x000D;
&#x000A;
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;
&#x000A;
Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;
&#x000A;
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;
&#x000A;
</description>
```

**Comment by ubbeK** [comment]
@careri Can you please provide a link to what version of Starcounter.VisualStudio you are referring to?

**Comment by careri** [comment]
Microsoft Visual Studio Enterprise 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

**Comment by miyconst** [comment]
@careri please do the following:

- Uninstall Visual Studio extension.
- Close Visual Studio.
- Uninstall Starcounter.
- Install Starcounter.
- Install the Visual Studio extension.
- Check if it works.

**Comment by careri** [comment]
I already got it working yesterday. Just wanted to inform you that this happened.
I got no error messages during install but still the Starcounter.CLI.dll was missing.

**Comment by miyconst** [comment]
@ubbeK, @iqbalskd please see if there is something we can do in a reasonable amount of time. Close the issue otherwise.

**Comment by iqbalskd** [comment]
Tested this creating a basic starcounter database app seems working fine. I tested it as follows:

- Created  a fresh  virtual machine, with Visual Studio 2017 Enterprise (15.5.7), Version (4.6.04586)
- Installed starcounter v2.3.2.593, `since mentioned version was not available on the page`.
- Created a basic starcounter app with a one DB entity.
- App build fine.

Feel free to re-open this again if this issue still persist.
