### ISSUE TITLE
Document transient database properties

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#382]
Coming from - [Deprecate transient properties of database classes](https://github.com/Starcounter/Home/issues/309).

**Comment by Mackiovello** [comment]
This is the existing documentation: https://docs.starcounter.io/guides/database/creating-database-classes#preventing-fields-from-becoming-database-columns

I should clarify how it works and what you can/cannot do with it

@per-samuelsson had something to add regarding SQL queries and the values of these properties

**Comment by per-samuelsson** [comment]
> @per-samuelsson had something to add regarding SQL queries and the values of these properties

```csharp
[Database]
public class Foo {
  public string Name;
  [Transient] public int Bar2;
}

var f = new Foo() { Bar = "Mackiovello", Bar2 = 1 };
Console.Write(f.Bar2); // "1"

f = Db.SQL<Foo>("SELECT f FROM Foo f WHERE f.Name = 'Mackiovello'").First();
Console.Write(f.Bar2); // "0"
```

**Comment by miyconst** [comment]
It is also worth mentioning that reference navigation is always creating a new proxy objects.

```cs
[Database]
public class Parent {
    [Transient] public string Note { get; set; }
}

[Database]
public class Child {
    public Parent Parent { get; set; }
}

Child child = new Child();

child.Parent = new Parent();
child.Parent.Note = "A note";

// note will be null, since `child.Parent` getter will always return a new instance of the Parent class.
string note = child.Parent.Note;
```

**Comment by Mackiovello** [comment]
Done: https://docs.starcounter.io/guides/database/creating-database-classes#preventing-fields-from-becoming-database-columns
