### ISSUE TITLE
Cannot stop SC server using tray icon

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#383]
Starcounter version: Starcounter-Develop-2.4.0.5135

When I right-click on the SC server tray icon and select "stop server" from the context menu it doesn't stop and the error appears: `Starcounter service error. Invalid URI: The hostname could not be parsed.`

![windows_10](https://user-images.githubusercontent.com/4943949/36602029-27f25bb2-18b7-11e8-85be-f129449c8a0f.png)

**Comment by ubbeK** [comment]
cc @iqbalskd

**Comment by iqbalskd** [comment]
Tested using custom builds and merged.
