### ISSUE TITLE
2.4 installer includes Simplified.Data.Model.dll

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#384]
2.4 installer includes `Simplified.Data.Model.dll` in the installation root directory.

Simplified should not be included in the Starcounter 2.4 installation.

This is a serious problem for apps in 2.4, because this file actually gets weaved instead of the file of the same name in the app `bin/Debug/` folder.

cc @alemoi, @ubbeK

**Comment by alemoi** [comment]
@per-samuelsson might need your help here. Isn't it that local(Copy Local) file is always preferred over the one in `StarcounterBin`?

**Comment by per-samuelsson** [comment]
> @per-samuelsson might need your help here. Isn't it that local(Copy Local) file is always preferred over the one in StarcounterBin?

That's not important really. Because of this:

> Simplified should not be included in the Starcounter 2.4 installation.

But to answer: the 2.4 weaver is much simpler than that. It doesn't weave references at all. It weaves only what you pass to it. Nothing more, nothing less.

**Comment by alemoi** [comment]
So, as I understand, the Simplified whatever you reference in your project will be weaved, right? So I suppose there is a wrong reference of Simplified in the project? Instead of local app Simplified, the one in StarcounterBin is referenced.

**Comment by per-samuelsson** [comment]
> So, as I understand, the Simplified whatever you reference in your project will be weaved, right?

Not sure who you are asking, me or @warpech. But I repeat: in 2.4, weaving happen at *compile time*. Meaning `Simplified` must be weaved at compile time, and it clearly cant never be referenced before compiled. 😃

**Comment by warpech** [comment]
This is the reference to Simplified that triggered the problem ([source](https://github.com/Starcounter/Blending/blob/a84d3e8d8a6615ac57ea46edcd0bc309116ddc85/src/BlendingEditor/BlendingEditor.csproj#L51-L53))

```
    <Reference Include="Simplified.Data.Model, Version=1.0.6.0, Culture=neutral, processorArchitecture=AMD64">
      <HintPath>..\..\packages\Starcounter.Simplified.Data.Model.1.0.6\lib\net461\Simplified.Data.Model.dll</HintPath>
</Reference>
```

Still, a file that was at `C:\Program Files\Starcounter\Simplified.Data.Model.dll` (which was Simplified 1.0.4) took priority and was loaded, as it was reported to me by VS  ("Modules" window). I was seeing a bunch of errors when starting the app: some from the weaver and some from the QP.

So we have two problems:

1. files in `%StarcounterBin%` have priority over the files referenced by the app
2. `Simplified.Data.Model.dll` is distributed with Starcounter 2.4 and it should not be

**Comment by ubbeK** [comment]
> 2. Simplified.Data.Model.dll is distributed with Starcounter 2.4 and it should not be

Seems easy to fix, just remove it from the WhiteList file. But is it used by any product in 2.4? If not, it should be removed from the source, e.g. [Simplified at branch master-2.4](https://github.com/StarcounterApps/Simplified/tree/master-v2.4).

**Comment by alemoi** [comment]
I also wonder if we remove the file, how projects will find reference to the DLL?

@per-samuelsson is there a possibility that weaver prioritizes reference from StarcounterBin as @warpech dedcribes above?

**Comment by per-samuelsson** [comment]
> I also wonder if we remove the file, how projects will find reference to the DLL?

How does projects find a reference to `NewtonSoft.Json`, `NUnit`, `log4net`, etc? Hint: they don't reference them from %StarcounterBin%. 😜 

Seriously, please please, we need to get away from thinking we need to provide these special, built-in libraries, being part of the runtime.

> @per-samuelsson is there a possibility that weaver prioritizes reference from StarcounterBin as @warpech dedcribes above?

I think it's the host, not the weaver. And yes, that is possible. If you load `Starcounter.dll` from `this\path\right\here` and have `Foo.dll` in the same directory, that will always be the prio of the CLR resolver. (Except that GAC has priority, but that's so fucked up I won't even comment on it further, and also not in play here).

**Comment by warpech** [comment]
> But is it used by any product in 2.4? If not, it should be removed from the source, e.g. Simplified at branch master-2.4.

> Seriously, please please, we need to get away from thinking we need to provide these special, built-in libraries, being part of the runtime.

The apps are using it through NuGet https://www.nuget.org/packages/Starcounter.Simplified.Data.Model/, as explained in the page https://github.com/StarcounterApps/Simplified#adding-simplified-to-your-project

**Comment by per-samuelsson** [comment]
@warpech 

That's great news, and what I hoped for. Reason I wrote that statement was b/c of this:

> I also wonder if we remove the file, how projects will find reference to the DLL?

**Comment by alemoi** [comment]
Hmm, strange, I have removed Simplified and SO from white-list.
However, I don't think that this is resolved (I might be very wrong):
```
This is a serious problem for apps in 2.4, because this file actually gets weaved instead of the file of the same name in the app bin/Debug/ folder.
```

**Comment by ubbeK** [comment]
@warpech @alemoi Any way to test if this is resolved now?

**Comment by miyconst** [comment]
>Any way to test if this is resolved now?

I guess, it's as easy as:

- Install latest 2.4.
- Go to the installation folder.
- Search for the `Simplified` files.
- Make sure there is none.

I just tested with:

- `Starcounter-RC-2.3.2.922`, the `Simplified.Data.Model.dll` **is there**.
- `Starcounter-Develop-2.4.0.5827`, the `Simplified.Data.Model.dll` library **is not there**.

Closing the issue as completed. @warpech please reopen if I missed something.
