### ISSUE TITLE
Staradmin doesn't output errors when one or more error occurred

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#386]
```
> staradmin delete db default
You are asking to delete database "default"
There is no going back - ALL data will be lost!
Are you sure about this?

If sure, enter the name of the database ("default"), then press ENTER
To abort, just press ENTER.

I want to stop and permanently delete database with name:
default
One or more errors occurred.
```

It's really hard for me to know what's wrong when there's no proper error message. I expect that all the errors are output to the console.

The issue was that the server was not running.

**Comment by ubbeK** [comment]
What Sc version?

**Comment by Mackiovello** [comment]
Version=2.4.0.5313

To reproduce:
* `staradmin kill all`
* `staradmin delete db [non-existent database]`

```
> staradmin delete db something
You are asking to delete database "something"
There is no going back - ALL data will be lost!
Are you sure about this?

If sure, enter the name of the database ("something"), then press ENTER
To abort, just press ENTER.

I want to stop and permanently delete database with name:
something
One or more errors occurred.
```

The errors here is that there is no such database and the server is not running.

**Comment by ubbeK** [comment]
So we should either

* start db and try to delete. @Mackiovello Does this give a proper error message that we cannot delete a non-existing database?

or

* simply give error that server is not running

or

* implement functionality so db can be deleted even if the server is not running.


@per-samuelsson Do you recall how it has been implemented before? Has this always been the case?

**Comment by Mackiovello** [comment]
After looking a bit more at this, it seems like `staradmin delete db` lets you delete non-existing databases. So I don't understand why it's "one or more errors". Anyway, I think it would make sense to output an error that the server is not running.

**Comment by per-samuelsson** [comment]
> Anyway, I think it would make sense to output an error that the server is not running.

Of course it does. This seem to be a bug.

> @per-samuelsson Do you recall how it has been implemented before? Has this always been the case?

Not sure tbh. It's a bug clearly. I know in the past I did give some thought to how to treat similar cases, and was thinking about that tooling should be consistent: like if `staradmin delete db` would require the server to be started (or else would error), then should others (e.g. `list db`, `start db`, etc) too. And vice versa. But I probably didn't get time to assure all that, so some commands might slightly differ in behavior I'm afraid.

As I've understood, you are about to throw all old tooling away, and then maybe we should leave this as a known bug? Fixing it shouldn't be much work though (all commands share common code in `Starcounter.CLI` library, so it's easy to check if server is running, force it to start, etc.

**Comment by per-samuelsson** [comment]
Hmm, I wonder if this actually haven't worked before and was broken? I tested with other commands, and all show the same behavior. At least some commands in the past showed "Server is not running".

**Comment by ubbeK** [comment]
> As I've understood, you are about to throw all old tooling away, and then maybe we should leave this as a known bug? Fixing it shouldn't be much work though (all commands share common code in Starcounter.CLI library, so it's easy to check if server is running, force it to start, etc.

Yes, I want to leave it and fix them in new CLI tools. cc @miyconst

**Comment by miyconst** [comment]
Closing as won't fix. Currently we don't have resources to fix the old CLI tools. The new tools will be designed and developed for Nova from scratch.
