### ISSUE TITLE
Starcounter 2.3.1 and starcounter in visual studio 3.0.0 are not compatible

### ISSUE THREAD

**Issue by Shrn-Prmshr** [Starcounter/Home#388]
I am a newbie with Starcounter and I am trying to create a project by that. But unfortunately I have faced to an error when I try to create a simple hello world project! (I must use 2.3.1 version) 

> Severity	Code	Description	Project	File	Line	Suppression State
Error		This project specifies its compatible with Starcounter 2.4 while the installed version of Starcounter requires 2.3. The probable cause is you have an incompatible version of the Starcounter Visual Studio extension installed. For Starcounter version 2.3, we recommend extension versions >=1.0.0 <2.0.0. Please see https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility if you need further help.	StarcounterThree

I have installed release version 2.3.1.8367 which automatically installed Starcounter in visual studio extension 3.0.0 and I have VS 2017.

As error says it is a problem with starcounter extension versioning but I can not downgrade to an older version. (https://github.com/Microsoft/vscode/issues/12764)

Anyone know how should I fix this?

**Comment by Shrn-Prmshr** [comment]
I managed to fix that by
- Uninstalled all that I had
- Remove manually Starcounter extension
- Restart
- Install again which the key was to not automatically install extension (I removed the check at the beginning of the installation)
- Open the _startcounter_ folder and looked for _vsis_ and run manually.

You need to create the project again. I could not use created ones.

**Comment by Mihaiii** [comment]
For future cases:

There's no need to downgrade the VS extension. We will update the error message since it's old and indeed misleading.
You most probably created a "Starcounter 2.4 Application" (.NET Framework >= 4.6.1) instead of "Starcounter 2.3 Application" (.NET Framework < 4.6.1).

This can be easily be fixed by deleting `<StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>` from `*.csproj`.

Also, in 2.3 we reference `Simplified.Data.Model.dll` and have `Copy Local` to `false` for Starcounter references and also.

//cc @iqbalskd

**Comment by Mackiovello** [comment]
Thank you for reporting this! I've updated the tutorial to explicitly say that you have to create a "Starcounter 2.3 Application". With that, it shouldn't be a problem. Don't hesitate to create issues in the future if there's anything you're wondering or if something doesn't seem right. We appreciate all the feedback we can get.

> There's no need to downgrade the VS extension. We will update the error message since it's old and indeed misleading.

Do we have an issue for this?

**Comment by Mackiovello** [comment]
Created an issue for the error message issue: https://github.com/Starcounter/Home/issues/391
