### ISSUE TITLE
Question about StreamedBody disposal

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#390]
@alemoi 

If I assign a large `FileStream` to `Response.StreamedBody` in a HTTP response, but the client closes the TCP connection before the `Stream` is being read – will Starcounter still dispose the `Stream` (as it usually does)? The reason I ask is that I find residual temporary files on a server computer, that are automatically removed when their corresponding `FileStream`s are disposed.

When I inspect these files, they are still used by `sccode`, minutes after their corresponding requests, and they are indeed removed when I kill `sccode`.

`Version=2.3.1.8329`

**Comment by miyconst** [comment]
cc @alemoi.

**Comment by alemoi** [comment]
If the corresponding TCP connection is closed, then server should close the stream object. I will double-test this and respond to you.

**Comment by alemoi** [comment]
@erikvk The fixed is produced and pushed to 2.3 and develop. Please let me know how it goes, when you have time.

**Comment by miyconst** [comment]
@erikvk beware, that the fix is pushed to `2.3.2`, not to `2.3.1`.

**Comment by erikvk** [comment]
Nice – I will enjoy this feature when it finds its way to release :)

**Comment by miyconst** [comment]
>Nice – I will enjoy this feature when it finds its way to release :)

Another release will find it :), this won't be merged to `2.3.1`.

**Comment by miyconst** [comment]
Closing the issue as fixed. @erikvk please reopen if it's still not working.
