### ISSUE TITLE
/signin/profile Not working as expected on warehouse.starcounter.com

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Home#393]
I see a blank page when I open the link http://warehouse.starcounter.com/signin/profile

**Comment by Mackiovello** [comment]
Thank you for reporting! What do you expect to find on that page?

**Comment by atifwaqar** [comment]
Something similar to this

![image](https://user-images.githubusercontent.com/4388707/37395291-32875d52-2776-11e8-901b-011334a11325.png)

**Comment by miyconst** [comment]
cc @warpech
