### ISSUE TITLE
Error on 2.4 upgrade - System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#395]
I try to upgrade SC v2.4.0.5135 to 5497 on my local machine - Windows 10. As a result, I get an exception:

![screenshot_21_03_2018__13_08](https://user-images.githubusercontent.com/4943949/37708981-ff105e9a-2d08-11e8-8dcf-0317a541fd4b.png)

I try to do it as an administrator.

**Comment by chrhol** [comment]
I installed this version both on my dev laptop and on a VM running win10 and din't get this problem. I wonder what is different (and I hope it's not because of my recent changes 😊)

**Comment by mmnosek** [comment]
This version installation works fine (tried after this), just upgrade didn't work. I can try upgrade once again.

**Comment by mmnosek** [comment]
I tried again, and it worked smoothly. Three times back and forth... so... any ideas or should I close? I cannot reproduce anymore.

**Comment by chrhol** [comment]
Lets ping @ubbeK and @iqbalskd and see what they say.

**Comment by SenerDemiral** [comment]
It worked smoothly on the first time.

**Comment by iqbalskd** [comment]
I tried it upgrading/downgrading couple of times, worked fine each time.

**Comment by mmnosek** [comment]
Wow, thanks guys for trying to reproduce! Unfortunately, I cannot reproduce it anymore as well. Closing. I will reopen if I find this again.
