### ISSUE TITLE
Serverside Session does not seem to be disposed after exception

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#397]
and client keeps sending request using that session.

Found by heads in `2.3.1` and reproduced it in the latest develop version.

The effect today can be one of the following (depending on when the exception is thrown):
- If the exception is thrown when changes are collected, the client will reconnect or send something and fail, over and over. 
- If the exception is thrown from (for example) an input-event, it's still possible to edit values *and* patches are sent both to and from server while the client shows a connection error popup.

Since we don't know what state the viewmodels and session are in at this time, the behaviour in the second point is undefined (although probably nothing critical can happen, the server still decides what to do).

There are a couple of things that should be investigated/implemented:
- Have this changed or have we never disposed the session? I was sure that we always disposed it when we catch an unhandled exception but obviously not.
- Disregarding the result from above, make sure session is disposed when an unhandled exception occurs.
- The client should probably remove the sessionid/location when it receives an error back from the server and not send requests back to the same session (if the point above is solved, this is of lesser importance).

I've labeled it `json`, `json-typed` although I'm not sure that this is directly connected to that (needs to be investigated). It might be that this is a bug in the handling in the request pipeline for the codehost.

cc @miyconst, @warpech

**Comment by miyconst** [comment]
@chrhol how much time would that take to fix in `2.3.1`, `2.3.2`, and only `develop`?

**Comment by chrhol** [comment]
I think I'm wrong about this, and it was my test that I misread what happened:
> If the exception is thrown when changes are collected, the client will reconnect or send something and fail, over and over.

When client reconnects, no session is sent. The second point still holds true though.

> @chrhol how much time would that take to fix in 2.3.1, 2.3.2, and only develop?

The code doesn't differ much between versions for this part. I think the fix will be the same, so a little extra time to merge and test it for each version we add it to, but other than that it shouldn't be a problem adding it in all versions. 

I need to investigate a little, but I think the fix will be quite small. It looks at first glance that we end up in the same place (i.e. the exception is handled in one place quite far out).

I'm still curious why the session isn't disposed though. In my mind I was absolutely certain that we did it.

**Comment by chrhol** [comment]
A short update: the fix was as I suspected not that big (altough the session needs to be destroyed in a couple of places, and not just one).

I wanted to add some test for it though, but this is a bit more work. Since we  need to test the actual request pipeline you cannot write it as a standalone test, or a unittest. It needs to be a full:ish test with server and a client that connects and sends patches both with websocket and http.

I have a beginning of a test that currently only test one of the paths, so need to add the other ones as well.

**Comment by miyconst** [comment]
@chrhol are you also implementing this test in `2.3.1`?

**Comment by chrhol** [comment]
> @chrhol are you also implementing this test in 2.3.1?

I see no problem having it for `2.3.1` as well, there is nothing that behaves differently for this test between the versions. 

I will start with `2.3.2` and `develop` though to make sure my changes work properly and then cherrypick the commits to `2.3.1`

**Comment by chrhol** [comment]
Pushed to `v2.3.2` and `develop` now. Not yet moved to `2.3.1`

**Comment by chrhol** [comment]
Backported and merged to `v2.3.1-LTS` branch now. One item left to do: publish a new version.

**Comment by miyconst** [comment]
@chrhol I guess you can do that by running a `2.3.1` build with generating and uploading installer set to `true`.

**Comment by miyconst** [comment]
An LTS build `2.3.1.8415 (Apr 5, 2018 2:41:18 PM)` is available for download. Closing the issue as done. @chrhol thanks for fixing it.

**Comment by chrhol** [comment]
Succesful build here: https://teamcity.starcounter.org/viewLog.html?buildId=52052&buildTypeId=StarcounterGeneric_StarcounterLTS231_V23NightlyWindows&tab=buildResultsDiv

Looking at the end of the build log I see that a new package was uploaded succesfully to the download server, however I don't see it on the download page. Is there some additional step that needs to be taken to bump this number? (perhaps some step mentioned in https://github.com/Starcounter/AdminTrack/blob/master/Release/how_to_release_starcounter.md) cc @ubbeK

**Comment by chrhol** [comment]
> An LTS build 2.3.1.8415 (Apr 5, 2018 2:41:18 PM) is available for download. Closing the issue as done. @chrhol thanks for fixing it.

Ohh commented at the same time. I did not see this version

**Comment by chrhol** [comment]
Because I'm looking at the wrong section! Just disregard the two previous comments. Considering this issue done.
