### ISSUE TITLE
Document Starcounter.Internal.CurrentVersion static class

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#398]
@Mackiovello please update the documentation with info about the `Starcounter.Internal.CurrentVersion` class.

**Comment by Mackiovello** [comment]
This should not be documented manually. This should be part of generated documentation. See https://github.com/Starcounter/TechComm/issues/379 (internal issue)

Will close this when generated documentation is done

**Comment by miyconst** [comment]
Okay. I am closing the issue then. No need to keep it around.
