### ISSUE TITLE
Settings database attribute to an interface gives weaver exception

### ISSUE THREAD

**Issue by Razkan** [Starcounter/Home#402]
According to the DatabaseAttribute the following usages of the attribute is allowed: 

`[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple = false, Inherited = true)]`

When I test the interface in the following manners: 

`
[Database]
public interface Execute
{
    void Run();
}
`
`
public class A : Execute
{
    public void Run()
    {
        throw new NotImplementedException();
    }
}
`

I get the following error: 

> An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. ( ScErrUnhandledWeaverException (SCERR6066))

I haven't found anything in the documentation about this matter. Is it supposed to be allowed or is it an oversight?

Starcounter version: 2.3.1.7786

**Comment by miyconst** [comment]
This is a bug, the `[Database]` attribute is not supported for the interfaces. Thank you for reporting, it will be fixed in the later versions of Starcounter.

cc @per-samuelsson

**Comment by per-samuelsson** [comment]
> This is a bug, the `[Database]` attribute is not supported for the interfaces.

Actually, I think I once implemented support for that, and hence `AttributeTargets.Interface` is set. But maybe there is a bug, or the error came from something else. I can investigate it eventually.

Simplest thing would o/c be not to support it on interfaces though.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
