### ISSUE TITLE
Schema change in Starcounter.HtmlViewAttachment

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#404]
I'm getting this error when upgrading an application from `2.3.1` to `2.3.2`:

```
Schema of given type does not match with schema of the existing type. The following 
properties/fields have been removed from class 'Starcounter.HtmlViewAttachment' but
 not dropped from the database: 'AttachedViewUri'.
Removed properties/fields have to be manually dropped. ( ScErrSchemasDoNotMatch (SCERR15009))
```

I understand that I have to manually run `ALTER TABLE` commands after schema changes on `2.3.2`. With my own db classes, this is easy to manage. Am I required to write `ALTER TABLE` commands for Starcounter's own tables as well?

**Update 1:**

Also this:

```
Schema of given type does not match with schema of the existing type. The following 
properties/fields have been removed from class 'Starcounter.HtmlViewComposition' but not dropped
from the database: 'MainViewUri', 'Version'.
```

**Update 2:**

After running commands:

`ALTER TABLE Starcounter.HtmlViewAttachment DROP COLUMN AttachedViewUri`
`ALTER TABLE Starcounter.HtmlViewComposition DROP COLUMN MainViewUri`
`ALTER TABLE Starcounter.HtmlViewComposition DROP COLUMN Version`

The app starts again.

@miyconst

**Comment by erikvk** [comment]
Also:
```
Schema of given type does not match with schema of the existing type. The following properties/fields
 have been removed from class '**Starcounter.HtmlViewComposition**' but not dropped from the database: '**MainViewUri**', '**Version**'.
```

**Comment by miyconst** [comment]
@erikvk thank you for reporting, `Starcounter.HtmlViewXxxx` is not a meta data table, it contains information for blending between the apps. In this case you have to manually perform the `ALTER TABLE` statements manually.

If you ever receive any such error about `Starcounter.Metadata.Xxx` or `Starcounter.Internal.Metadata.Xxx` tables - then it's a bug, please report.

Closing the issue as answered question.

**Comment by erikvk** [comment]
This is actually a problem for us right now. We distribute apps over the Starcounter App Warehouse, and now upgrades through the warehouse will stop working. I will have to write a separate guide on how to go to 2.3.2. Our customers are often not familiar with SQL.

The best solution to all this would be if I could include a text file with the warehouse package, containing SQL commands that are run before the app is loaded. I could put all the ALTER TABLE commands there.

**Comment by k-rus** [comment]
> Starcounter.HtmlViewXxxx is not a meta data table, it contains information for blending between the apps. In this case you have to manually perform the ALTER TABLE statements manually.

If I don't mistake it is a table created and used by Starcounter product. It is not a user table and thus users are not supposed to fix Starcounter's table. IMHO this is a bug, which simple work around. IMHO it should be documented in the release notes together with the work around and it should not appear in the future releases.

I reopen the issue. cc @miyconst @dan31

**Comment by PatrykSzwer** [comment]
I talked with @miyconst and created a PR to documentation with information about this bug and how to deal with it: https://github.com/Starcounter/Docs/pull/222 Due to fact that SC 2.3.1 and 2.3.2 are already released I believe this is the best thing we could do right now.

**Comment by k-rus** [comment]
> Due to fact that SC 2.3.1 and 2.3.2 are already released I believe this is the best thing we could do right now.

We also need to prevent from this bug to happen in new releases.

**Comment by PatrykSzwer** [comment]
PRs with documentation about this are already merged. I'll leave decision about closing/pushing forward this issue to @miyconst.

**Comment by miyconst** [comment]
[Migrating From Starcounter 2.3.1 to 2.3.2 troubleshooting](https://docs.starcounter.io/cookbook/migrating-from-2.2-to-2.3+#migrating-from-starcounter-2-3-1-to-2-3-2-troubleshooting).

**Comment by miyconst** [comment]
This issue only appears when migrating a database created with Starcounter older than `2.3.1` to Starcounter `2.3.2`. Still, we will try to avoid such situations in the future.

Thanks @erikvk for reporting and @PatrykSzwer for documenting.
