### ISSUE TITLE
Outdated template for Starcounter html file

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#405]
I just noticed that right now, when you create new html view trough visual studio and our templates, you will get file with content like this:
```
<link rel="import" href="/sys/polymer/polymer.html">

<template>
    <template is="dom-bind">
        
    </template>
</template>
```

which in case of SC 2.4 is outdated (and not working) since: 
1. `<link rel="import" href="/sys/polymer/polymer.html"> is not needed at all.`
2. We're using nomenclature compatible with Polymer 1 and 2, so proper template should look like this:
```
<template>
    <dom-bind>
        <template is="dom-bind">
        </template>
    </dom-bind>
</template>
```

cc @Starcounter/webplatformteam

**Comment by alshakero** [comment]
This is done but unmerged in https://github.com/Starcounter/Starcounter.VisualStudio/pull/37

**Comment by alshakero** [comment]
https://github.com/Starcounter/Starcounter.VisualStudio/pull/37 is merged.

**Comment by warpech** [comment]
@Mihaiii, @ubbeK, @iqbalskd how come the previous solution for this issue was lost? We already fixed this once in a PR to `develop` in January (https://github.com/Starcounter/Starcounter.VisualStudio/pull/26). 

There was a big debate to get that change released to VS marketplace.

PR https://github.com/Starcounter/Starcounter.VisualStudio/pull/37, on the other hand, was made to `master`. 

Does it seem strange only to me, that fixes to this repo are done both on `develop` and `master` branch?

**Comment by alshakero** [comment]
I thought I was delusional tbh. I remember the January change.

**Comment by ubbeK** [comment]
I am kind of lost when it comes to this extension as I never use it. I remember that I had to go in and redo a lot of changes, and then @iqbalskd released a version `3.X` which is compatible for both Sc 2.3 and 2.4

**Comment by warpech** [comment]
Can you please release a new version of the extension? The fix was merged 6 weeks ago but not yet released.

**Comment by ubbeK** [comment]
@iqbalskd Can you please release this on `NuGet` and `VisualStudio Marketplace`.

Bump the version to [3.0.1](https://github.com/Starcounter/Starcounter.VisualStudio/blob/master/build/version.txt). 

`master` of https://github.com/Starcounter/Starcounter.VisualStudio

**Comment by iqbalskd** [comment]
Created new release tag, and published the package to [Nuget](https://www.nuget.org/profiles/Starcounter) and [Visual Studio Market Place](https://marketplace.visualstudio.com/manage/publishers/starcounter?src=Starcounter.StarcounterforVisualStudio).

**Comment by ubbeK** [comment]
Awesome, thanks @iqbalskd
