### ISSUE TITLE
Add mime type for appcache static files

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Home#406]
To support [ApplicationCache](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) in our apps, we need to add a manifest file that has the extension `.appcache`. Browsers don't respect this file unless it's served with the correct `Content-Type` header. 

So please add this new MIME to our static file server:

Extension: `appcache`
MIME-Type: `text/cache-manifest`

For more info and motivation behind this: https://github.com/Starcounter/RebelsLounge/issues/252#issuecomment-384642587

/cc @alemoi

**Comment by warpech** [comment]
Can we pls have this in 2.4? It should be few minutes of work.

**Comment by alemoi** [comment]
Sure, I will do that! Is it only for 2.4 I hope?

**Comment by alshakero** [comment]
Works like a charm! Thanks a lot. 

Closing as done.
