### ISSUE TITLE
Automatic binding to nullable types in Json

### ISSUE THREAD

**Issue by malx122** [Starcounter/Home#409]
Starcounter database supports nullable types like 
`public DateTime? MyTime {get;set;}`
But the automatic binding with Json does not support those.
It would be good if that could be fixed.

**Comment by k-rus** [comment]
@miyconst can you comment about the status of this issue here?

**Comment by miyconst** [comment]
>But the automatic binding with Json does not support those.
It would be good if that could be fixed.

It's not yet decided how, but this feature will be implemented in Starcounter Nova. Starcounter 2.3 and most likely 2.4 won't be enhanced.

**Comment by miyconst** [comment]
Closing as won't fix. Starcounter.XSON has been discontinued.
