### ISSUE TITLE
Windows Defender SmartScreen prevented an unrecognized app from starting.

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Home#411]
Yes, I will click on "Run anyway", but this would scare new devs that want to try SC.
Few days ago I didn't had this message (on another SC version) and I haven't changed any settings in the meantime. It would be nice if someone would confirm, though.

![smartscreen](https://user-images.githubusercontent.com/8951553/39633856-7972b7d2-4fb9-11e8-8cc0-849e0a6cc271.png)

---

Full text copy/paste for ease of searching: "Windows protected your PC
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

**Comment by SenerDemiral** [comment]
It happened to me.

**Comment by alemoi** [comment]
Hmm, maybe there is some problem with signing certificate on the installer? I remember @ubbeK said something about incomplete rights on the new certificate that we had to re-obtain?

**Comment by Mackiovello** [comment]
@ubbeK wrote a text about this in the urban-starteam channel on Slack. This is temporary and a fix should be in place early next week.

**Comment by ubbeK** [comment]
We have ordered a new code signing certificate which will not have this issue. It should be delivered to us this week.

**Comment by ubbeK** [comment]
This is not an issue anymore.
