### ISSUE TITLE
How to move objects with the IDs from one DB into another

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#414]
I want to copy some objects/records from one DB to another DB (via write to file and read from file)
without changing ObjectNo. Like you do in StarDump.
(FirstObjectID of AnotherDB is greater than lastObjectID of FirstDB)
Can I do that?

As far as I know, App can't connect more than one DB.
Is it correct?

**Comment by miyconst** [comment]
@SenerDemiral thank you for the question.

As of now there is no high level API to insert an object with ID. You still can use StarDump to perform such actions. We may also expose this API if it's really needed.

>As far as I know, App can't connect more than one DB.

No, it's not possible to run a single application in multiple databases at the same time. Still, you can connect to a foreign Starcounter database using [OdataApi](https://github.com/Starcounter/ODataApi).

**Comment by SenerDemiral** [comment]
In accounting, each account closes with balance at the end of year and the new year begins with these records and other description tables.
Previous year are closed and marked as read-only.
So the current year is not tied to the previous year.

I mean, I need such an API.

**Comment by miyconst** [comment]
>I mean, I need such an API.

Is it something you need to perform all the time, or it's a one time migration/merging of two databases?

**Comment by SenerDemiral** [comment]
All the time, at least one per year.

**Comment by miyconst** [comment]
>All the time, at least one per year.

Could you please describe the situation better, please? It sounds like you are creating and merging the databases every year.

**Comment by SenerDemiral** [comment]
Account definitions can not change in year.
Because all data send to government electronically in every month.
All year data send to the government again at the end of year.
Year Data is a unity.
Next year starts with balances as a new company.

**Comment by miyconst** [comment]
Sorry, I still don't get why it's important to merge the databases and keep the object IDs.

**Comment by miyconst** [comment]
Sorry for not being clear enough.

>Transferring some records from DB to new DB is a must for me.

I would like to understand the reasoning for this. What makes it *a must*? Is it for historical purposes not to populate working database? What is the purpose for transferring the records? Why StarDump does not work for this case?

**Comment by miyconst** [comment]
Okay, do you need to move those objects to a single historical database or every year it's a new one? Why StarDump is not applicable here? It's possible to execute unload/reload on a live database.

**Comment by SenerDemiral** [comment]
There is one DB for each year.
In Current DB have summary records and other tables of previous year.
I try to figure out using StarDump with required table selection.

How StarDump ReLoad behave when the records exists?

**Comment by k-rus** [comment]
Thank you for explaining your application.

May I suggest another implementation design:

1. At the end of the year the database is copied/backed up instead of creating new database.
2. The application logic doesn't allow to modify data if they are from the previous year.
3. Data from previous years are deleted when they are not needed, since a copy of the database already exists.

So the main idea is not to copy data from the last database, but create the last/historical database from the current database and delete the old data.

Let us know if you have tried this approach and if experienced some problems.

**Comment by k-rus** [comment]
I see one drawback with the approach I suggested is that refactoring of the database schema becomes more complex. Note that we are working on a tool, which should simplify the task of refactoring.

**Comment by SenerDemiral** [comment]
Thank  you @k-rus.
My suggestions:
1. At the end of the year the database is copied/backed up.
2. ReLoad to New DB. (Because user wants to access older ones)
3. Data from previous years are deleted when they are not needed in NewDB.
4. There can be last minute correction on previous DB and should be copied these changes to NewDB which is already using by other users.

In fact, I want to access more than one DB from one code host.
Will Starcounter Nova do this?

**Comment by miyconst** [comment]
@SenerDemiral thank you for the explanation. It seems like connecting to multiple databases and moving objects preserving their IDs is not the best design, but I might not see the whole picture and be wrong.

Here are some answers for your questions:

>How StarDump ReLoad behave when the records exists?

Inserting a record with an id, which was already taken will result into a crash.

StarDump has a special argument `--reassignobjectno` which allows to automatically shift objects number of reloaded objects to avoid collision with existing objects. In this case all the relations are kept.

StarDump has a special argument `--forcereload` to force reload into a database which already contains data.

StarDump has a special argument `--skipschema` to skip database schema validation. It allows to reload a dump into a database with not identical database schema. Only those tables and columns which already exist in the database will be reloaded from the dump.

>In fact, I want to access more than one DB from one code host.
>Will Starcounter Nova do this?

Starcounter application is something like a stored procedure in traditional databases. Those, it's not possible to run a single application inside multiple databases. There are different ways of communication with foreign Starcounter database, but direct memory access is not possible between multiple databases.

Starcounter Nova will not support this feature either.

-------------

There is Starcounter API to insert objects with predefined number, but it is not designed for applications usage, and may lead to inconsistent database state when used wrongly. That is why we strongly recommend to avoid such operations.

If you understand the risk, and there is absolutely no other solution - we will consider to expose the API.

**Comment by miyconst** [comment]
>By the way, stored procedure in traditional databases can connect to other DBs.

That's true. Connect to a database and be inside the database are different things though. A single stored procedure may belong to a single database. Another database may have a copy of it, but not the same instance.

**Comment by k-rus** [comment]
My suggestion is one possible work around. IMHO the proper solution is to store all the data in a single database, since you want to keep read access to historical data and possibilities for corrections for recent archived data in addition to the operational data. This approach requires that application implements control to the data that historical data are not updated.

Have you met any limitations in Starcounter for implementing this solution?

Currently Starcounter doesn't provide any solution to support this pattern.



> By the way, stored procedure in traditional databases can connect to other DBs.

It is not recommended, but you have possibility to communicate from one application in one database to another application in another database using HTTP and REST. However, you will be lacking, for example, transactions and ACIDness, but this is true and for other databases, I believe.

**Comment by SenerDemiral** [comment]
I want to give simple example about accounting to clarify.
```
[Database]
AccDef
{
	string AccNo	
	string AccName
}

[Database]
AccDetail
{
	AccDef AccDef
	double Debit
	double Credit
	string Info
}
```
```
PreviousYearDB 
AccDef Data
AccNo     AccName
100       Cash
100.01    Cash Istanbul
102       Banks
102.01    IsBank
102.01.01 IsBank Branch#12345
102.01.02 IsBank Branch#23456
102.02    GarantiBank

AccDetail Data
Full of Debits/Credits records referring AccDef
```
One senario about deletion:
Previous year company worked with IsBank Branch#23456 but current year not.
User wants to delete this entry because never work again. (There is no AccDetails record depends on this)
This deletion is impossiple if we store all the data in a single database.

One senario about modification:
Company opened bank account on same Barnch, User wants to insert new record under the branch.
So new records should be like below. (Again there is no AccDetails records referring this) 
```
NewYearDB
AccDef Data
102.01       IsBank
102.01.01    IsBank Branch#12345
102.01.01.01 IsBank Branch#12345 IBAN:2343452354
102.01.01.02 IsBank Branch#12345 IBAN:5787856735

AccDetail Data
Empty
```
Modification is impossiple if we store all the data in a single database.
Because type of record is changed. 
In prevYear 102.01.01 is working account (can be used in AccDetail) but now it is not, it is aggregator account.
You can't do that, because previous year data sent to government.

**Comment by SenerDemiral** [comment]
Final notes.
I'm about to start a new project about factory production planning.
It is a big project (for me).

Hierarchical product structure (raw material -> semi products -> products),
Order Chain Management (Buying and Selling),
Accounting,
Cost accounting,
Preliminary accounting (order, waybill, invoice)
Personnel Management.

I am not sure enough that I am able to write this project using Starcounter.
It scares me quite.
No one around can help me, unfortunately no one knows anything about Starcounter.
I am using traditional database since 1990.
I know what can I do and I can't do.
I'm using DB Management tools on `live` DB to change record structure and Insert/Update/Delete Data. (Not like Unload -> Change -> ReLoad)
I do not know what I can do and can't do without this tool.

I want to write desktop (mature) application to analyze data (OLAP) for power users also.
REST/json interface is slow for hundred of thousands records.
I have to find more efficient protocol to communicate with DB.
Efficient Serialization/DeSerialization of binary data is another problem.

Anyway, these are all my problems.
Thanks again.

**Comment by k-rus** [comment]
I will some other ideas and thoughts about your scenario. My aim is not to convince you to stay with Starcounter or solve your problem, but I just want to share my thoughts, which I got when I read your requirements.

> One senario about deletion:
> Previous year company worked with IsBank Branch#23456 but current year not.
> User wants to delete this entry because never work again. (There is no AccDetails record depends on this)
> This deletion is impossiple if we store all the data in a single database.

IMHO, data  should never be deleted, but access to data should not be given. So the particular group of users cannot see the data, or some users can specify that the data are not visible to other users.



> Modification is impossiple if we store all the data in a single database.
> Because type of record is changed.
> In prevYear 102.01.01 is working account (can be used in AccDetail) but now it is not, it is aggregator account.
> You can't do that, because previous year data sent to government.

I don't have any good idea here. The first thing, which comes to my mind, is a new table is needed for new year. Actually I heard that creating a separate table for each year it is a rather common approach. I don't favour it. In a sense it is similar to having another database, but  another table instead. In RBDMSs it is possible to utilise built-in security to limit access to tables with historical data, in Starcounter it is necessary to build such security inside application.

Good luck!

**Comment by SenerDemiral** [comment]
Yes, I really need "good luck".
Thanks @k-rus.

**Comment by miyconst** [comment]
>No one around can help me, unfortunately no one knows anything about Starcounter.

Unfortunately, this is true. If you are interested, we may have a discussion outside of GitHub (or another GitHub issue) and see how we may collaborate and help you with the project.

**Comment by SenerDemiral** [comment]
With pleasure, thank you @miyconst .
May we use eMail?

**Comment by miyconst** [comment]
For sure, you can mail me at: `kostiantyn.cherniavskyi@starcounter.com`.

**Comment by miyconst** [comment]
@SenerDemiral can we close the issue as answered or you still need a solution to move objects with their IDs?

**Comment by SenerDemiral** [comment]
I will search different way to solve my problem.
Thank you.
