### ISSUE TITLE
Cannot create new default database: System.IO.IOException: Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#415]
During maintenance of our virtual machine which hosts kitchensink demo, I wanted to update starcounter to the newest version. To achieve that I:
1. removed already existing database by calling `staradmin delete db default`
2. Downloaded and installed/updated newest version of SC (2.4.0.6146)
3. Run server and called: `staradmin new db default DefaultUserHttpPort=80`

After 3rd step I got errors:
![image](https://user-images.githubusercontent.com/25042256/40309561-3b8f8590-5d0a-11e8-9123-2fe15991211f.png)

It's a long shot but maybe It's because of the really bad specification of the hosting machine (1GB of RAM memory, Intel Xeon CPU E5-2676 v3 2,40GHz) but still, there should be more informative error message about the actual cause of the issue. (About disc space, there is 14gb free space so I assume It's not fault of this)

Possible solutions/clues:
Reinstalling Starcounter didn't help.
Uninstalling starcounter, removing Personal folder and installing starcounter again fixed the issue.

CC: @warpech

**Comment by miyconst** [comment]
@PatrykSzwer thank you for reporting. This happens when the old `default` database files failed to completely delete.

Do you still have the environment to test with?

**Comment by PatrykSzwer** [comment]
Unfortunately, I wanted to fix this ASAP so Kitchensink demo would be accessible again, but I assume that It should be possible to reproduce it again on that machine. Here is the instruction how to access it:
https://github.com/Starcounter/KitchenSink/blob/master-2.4/CONTRIBUTING.md#how-to-deploy-to-kitchensinkstarcounterio

**Comment by miyconst** [comment]
Okay, putting the issue on hold for now.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
