### ISSUE TITLE
Data transfer between Windows client and  Starcounter DB using gRPC.

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#416]
Does anyone have worked on this?
I need a clue.

Client received 20K messages/sec from streaming gRPC server on same machine.
But same client received 10K messages/second with gRPC in Starcounter App.
Is there any other alternatives to write server side with gRPC which read/write working SC DB?

**Comment by miyconst** [comment]
@SenerDemiral thank you for the question, could you please specify more broader description? 

>Client received 20K messages/sec from streaming gRPC server on same machine.

This does not sound very efficient. What is the reason to use RPC if the client and the server are on the same machine?

What is the `Windows client`? Is it a WPF application or?
