### ISSUE TITLE
(Re)move "IResource" from Starcounter.Internal.dll due to unit test problems

### ISSUE THREAD

**Issue by jedynykaban** [Starcounter/Home#421]
Hi, I'm covering my code with unit test, but have "silly" problem with automatically generated JSON descendant classes (strongly typed JSON code behind is really great). Whenever I want to check property of any particular JSON, test project asks me to and Starcounter.Internal.dll (and then all dependencies), and then that cause that Unit Tests project became no longer "unit test" but "starcounter" project - all because (I think that at least) of light "IResource" interface placement. Without accessing any property importing Starcounter.XSON lib is enough, and all tests run ok.

So my humble ask is to change placement of mentioned IResource interface if possible, not to cause stream of dependencies import needs. I talked tentatively with @warpech and He suggested to report present issue.

**Comment by miyconst** [comment]
@jedynykaban thank you for reporting the problem.

Am I right that:

- You are using `Starcounter.XSON` in a Unit Test project which is **not** a Starcounter project.
- The Unit Test project does not need and does not perform any database access.

**Comment by jedynykaban** [comment]
Exactly:
* Starcounter.XSON is used because we use "strongly typed JSON" in our view-model layer,
* Unit Test project not need to access database/perform operations on database, 'cause everything is hidden behind interface layer (IDbSelectionUtil, IDbDataManipulationUtil, IDbObjectFactory).

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
