### ISSUE TITLE
Starcounter cannot be installed after uninstalling second visual studio instance

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#422]
I had 2 instances of VS on my PC, 2017 community and professional. I uninstalled the community one, and only professional left (With namespace `Visual Studio 2017 Professional (2)` ). Right now when I tried to reinstall/install starcounter I'm getting:
![image](https://user-images.githubusercontent.com/25042256/41237961-3128e394-6d95-11e8-9e48-b4344fcae854.png)
And then
![image](https://user-images.githubusercontent.com/25042256/41237985-389539ac-6d95-11e8-8b55-6e218bfbcea3.png)

I tried to:
- Reinstall redistributable manually.
- Repair Visual studio.
- Uninstall starcounter.
- Check the registry for correctness of key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64 

I'm afraid that last step that I can do is reinstall visual studio completely which I preferred to avoid, but I think I have no other choice.

**Comment by bigwad** [comment]
Try to install x86 redistributable. Stacounter installer seems to check both - x86 and x64

**Comment by ubbeK** [comment]
> Try to install x86 redistributable. Stacounter installer seems to check both - x86 and x64

If this works, lets remove the x86 as it isn't needed for Starcounter 2.4. @iqbalskd

**Comment by PatrykSzwer** [comment]
I had x86 installed, It's not that. I'm currently reinstalling my VS, I'll let you know if that helps.

**Comment by PatrykSzwer** [comment]
FYI Reinstalling Visual Studio fixes the issue.

**Comment by bigwad** [comment]
I'll just leave a link that detecting vc runtime doesn't always work as expected: https://developercommunity.visualstudio.com/content/problem/111499/how-to-detect-if-visual-c-2017-redistributable-is.html

**Comment by PatrykSzwer** [comment]
It happens to me again, this time on my private PC where I have/had only 1 instance of VS all the time, so it can be related to something else.
![image](https://user-images.githubusercontent.com/25042256/42992510-09bad226-8c09-11e8-85c3-deec54bcdaaa.png)

It really should be taken care of, right now the only fix I know is to reinstall VS which is time consuming and annoying...

**Comment by iqbalskd** [comment]
It's bug with the latest version of VC ++ Redistributable of 14.14.x.x.

A work around exists which is mentioned under [this issue](https://github.com/Starcounter/Home/issues/430). Closing this as Duplicate in favour of the mentioned issue.
