### ISSUE TITLE
Exception during transaction is not rollbacking it

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#423]
I have method inside Db.Transact which creates multiple database objects. When I was creating one group of those objects I've got an exception. Turns out that entities that were created before this exception were actually added to the database. Shouldn't exception inside transaction rollback it automatically? 

cc: @miyconst

**Comment by miyconst** [comment]
@PatrykSzwer please provide minimal reproduction scenario.

**Comment by PatrykSzwer** [comment]
The origin place of the issue was in the blending editor. [Here](https://github.com/Starcounter/Blending/blob/mapping/src/BlendingEditor/Website/Helpers/MigrationHelper.cs#L44) I'm calling a method inside a transaction. During that method [here](https://github.com/Starcounter/Blending/blob/mapping/src/BlendingEditor/Migration/JsonMigrationContainer.cs#L156) I'm calling several `RecreateDbEntity()` methods (which looks like [this](https://github.com/Starcounter/Blending/blob/mapping/src/BlendingEditor/Migration/MigrationClasses/WebSectionMigration.cs#L25)). During third one, when I was creating [webUrls](https://github.com/Starcounter/Blending/blob/mapping/src/BlendingEditor/Migration/JsonMigrationContainer.cs#L173) exception occurs during getting new sort number for the entity ([here](https://github.com/Starcounter/Blending/blob/mapping/src/BlendingEditor/Migration/MigrationClasses/WebUrlMigration.cs#L54)).

I guess the exact scenario to reproduce it would be, have a method which has `Db.Transact()` which inside calls method, which then calls several other generate entities methods when one of them should throw an exception. I can try to provide some simple program/partial code to reproduce it in other environment, but I think the easiest way would be to provide reproduction branch of blending app (since the exception throwing code is fixed already).

**Comment by miyconst** [comment]
>I guess the exact scenario to reproduce it would be, have a method which has Db.Transact() which inside calls method, which then calls several other generate entities methods when one of them should throw an exception.

@PatrykSzwer please provide a minimal self-contained example, which could be easy consumed.

**Comment by PatrykSzwer** [comment]
For the unknown reason, I can't reproduce the issue anymore. Either it was unintentionally fixed in one of the new Starcounter versions, or we fixed it on blending app level by accident. I'll close the issue for now, and reopen if I step on this again/find out what was wrong.
