### ISSUE TITLE
Resharper stopped recognizing properties from typed json

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#424]
After I reinstalled VS and installed resharper again, my VS stopped recognizing properties from the view-model:

![image](https://user-images.githubusercontent.com/25042256/41410991-8fb837dc-6fdb-11e8-977a-93a697c306e1.png)

before reinstall, everything worked smoothly. 

I tried:
- Cleaning and building again.
- Restarting VS.
- Restarting resharper.

I'm using Visual studio 2017 and Resharper Ultimate 2018.1.2

**Comment by PatrykSzwer** [comment]
The problem lays in the newest release of Resharper, 2018.x. I installed resharper 2017.3.5 and it fixed the issue. It should probably be looked at, why the newest version is causing troubles, but I assume we don't have resources to take care of that now.

**Comment by miyconst** [comment]
@habib535 & @bouguila confirm the issue. It could be the problem of ReSharper.

**Comment by joozek78** [comment]
What is the expected time this will be fixed? Is somebody working on it? It severely hinders productivity. Furthermore, new developers probably won't even know there is a workaround

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
