### ISSUE TITLE
Blend responses from the same app

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#432]
In the branch https://github.com/Starcounter/UniformDocs/compare/issues/351-present-blendable-menus, @tomalec is trying to show an example of blended views where 2 views come from the same app.

The `blend.json` file has the entries for both of the views: https://github.com/Starcounter/UniformDocs/blob/8b8b0ae209bf30317b626007f11bc99b49850179/src/UniformDocs/blend.json#L23-L36

Me and @tomalec think that requesting one of these URIs through `Self.GET` should result in the other one being attached through the blending engine. 

It seems that the blending engine ignores the blended views declared within the same app that is making the `Self.GET` call. Is this the case @alemoi? If yes, it seems to me that is unnecessary. Can we have this limitation removed?

**Comment by kegor** [comment]
Looks like I met a similar problem in `HeadsOmni` (`HeadsOne`): we would like to show partial page for managing recommended products on the product details page (of the same `Showroom` app) but we can't achieve this with adding following blending rule (latter): https://github.com/Starcounter/Showroom/blob/c449ee752761fc77a47df54bffc58d1b5d47a2ee/src/Showroom/blend.json.

**Comment by warpech** [comment]
@mmnosek just tested that if one app (Products) is blended with two views (Showroom), also only one view from each app is used.

It seems that the last view matching to a `FullClassName` + `Contexts` from an app is attached by the blending engine.

Expected behavior is that all matching views should be attached.

This is needed for Omni. Can it be fixed, or should we search for workarounds?

**Comment by alemoi** [comment]
I have started the investigation. Is it that only 1 of 2 handlers is called? Or the handlers are called but not blended correctly?

**Comment by mmnosek** [comment]
My investigation shows that second handler is not called at all.

**Comment by alemoi** [comment]
After fixing the issue https://github.com/Starcounter/level1/issues/4750 I tried to reproduce the problem described here on the same setup with 2 apps and couldn't. Try the next successful build to see if problem persists. If it does, I need a reproduction scenario, alike the one in https://github.com/Starcounter/level1/issues/4750

**Comment by warpech** [comment]
Can you pls make a build with the `mapping` branch of Starcounter so that we can test?

**Comment by mmnosek** [comment]
It still doesn't work, I checked with the `2.4.990.158`. I will give you the repro scenario directly.

**Comment by alemoi** [comment]
I have tested more in non-mapping branch and everything seems to work fine. That's why I suspect that maybe its because of mapping converters that are used in blending: https://github.com/Starcounter/level1/blob/mapping/src/Starcounter/Apps/Blender.cs#L405

Lets have a session tomorrow.

**Comment by warpech** [comment]
cc @mtornwall, can you pls check that?

**Comment by warpech** [comment]
I just tested the OP (with the updated testing code https://github.com/Starcounter/UniformDocs/commit/4f83880d4d063b52a00248171a1d95e70567c3a2).

I can confirm that the problem with OP is not reproducible anymore with neither 2.4.990.161 nor 2.4.990.161.

Perhaps why we didn't see the blended page is because of the same reason as https://github.com/Starcounter/HeadsOmni/issues/263

**Comment by mmnosek** [comment]
I confirm that the problem is not reproducible with `2.4.990.161`

**Comment by kegor** [comment]
I confirm that the problem is not reproducible even with 2.4.990.127, now I am on the current `master` of the `HeadsOmni` with bumped `Showroom` which has updated rules in blend.json:
![image](https://user-images.githubusercontent.com/17431807/45427936-c9ba7080-b6a8-11e8-9d7f-a25ab28eccbe.png)

**Comment by mmnosek** [comment]
Shall we close it then? 😃

**Comment by warpech** [comment]
Closing as invalid
