### ISSUE TITLE
DbLinq not returning expected result

### ISSUE THREAD

**Issue by bouguila** [Starcounter/Home#434]
I'm trying to transform this query to DbLinq : 

original query:
`IEnumerable<Tag> Tags => Db.SQL<Tag>($"SELECT t.Tag FROM {typeof(TagRelation)} t WHERE t.Product=?", prod);` 

DbLinq query:
`IEnumerable<Tag> Tags => DbLinq.Objects<TagRelation>().Where(x => x.Product==prod).Select(y=> y.Tag);`

the 1st query is working fine but the 2nd is giving me `null`. 
also strange that if i add ToList to both ends of the query it works fine, like this: 
`IEnumerable<Tag> Tags => DbLinq.Objects<TagRelation>().Where(x => x.Product==prod).**ToList()**.Select(y=> y.Tag).**ToList()**;`

**Comment by un-tone** [comment]
`.Select` method currently is not supported https://github.com/Starcounter/Starcounter.Linq/issues/46.
I hope I could take this issue next week. I guess this one can be closed as a duplicate.

**Comment by bouguila** [comment]
thanks @un-tone for the reply.

**Comment by bouguila** [comment]
closing as duplicate.
