### ISSUE TITLE
Upgrade few builds up failed

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#435]
I tried to upgrade from `2.4.990.122` to `2.4.990.127` and it failed, again... First, installer asked me if I want to delete all files from my previous installation folder (that is wrong behavior):
![starcounter installer](https://user-images.githubusercontent.com/4943949/44262868-df10bc00-a21c-11e8-88f7-bc052067c42e.png)

Then when I clicked "yes" another error happened:
![starcounter installer2](https://user-images.githubusercontent.com/4943949/44262876-e932ba80-a21c-11e8-8022-8d1bafbc0477.png)

How should I upgrade?

@ubbeK @iqbalskd

**Comment by ubbeK** [comment]
@mmnosek Still having this issue?

**Comment by mmnosek** [comment]
@ubbeK I didn't try to upgrade again (there's no newer version available anyway). I can let you know on the next upgrade.

**Comment by mmnosek** [comment]
@ubbeK I still have the same issue. Today I tried to upgrade from 2.4.990.161 to 2.4.990.168 and:

![windows_10](https://user-images.githubusercontent.com/4943949/46159556-e053f080-c280-11e8-9701-e85fb8ee479c.png)

**Comment by iqbalskd** [comment]
This happens when we have starcounter app loaded in visual studio, visual studio keeps few files locked including `Starcounter.dll`, a simple work around is to close visual studio and run the installer again.

**Comment by ubbeK** [comment]
> This happens when we have starcounter app loaded in visual studio, visual studio keeps few files locked including Starcounter.dll, a simple work around is to close visual studio and run the installer again.

@mmnosek @miyconst @per-samuelsson 

What would the desired functionality be?

* Killing Visual Studio (checking if devenv.exe is running)
  * always
  * only if user checks some box / answer yes in popup
* Only giving a better error message stating that it could not delete `Starcounter.dll` because it might be locked by devenv.exe process (it such process exists).

Any other solution?

**Comment by per-samuelsson** [comment]
> > This happens when we have starcounter app loaded in visual studio, visual studio keeps few files locked including Starcounter.dll, a simple work around is to close visual studio and run the installer again.
> 
> @mmnosek @miyconst @per-samuelsson
> 
> What would the desired functionality be?
> 
> * Killing Visual Studio (checking if devenv.exe is running)
>   
>   * always

Please don't do that. That's just not an option IMO. Consider someone with 20 VS instances running, and uninstalling Starcounter - boom, all just killed.

>   * only if user checks some box / answer yes in popup

Could be an alternative, yes.

> * Only giving a better error message stating that it could not delete `Starcounter.dll` because it might be locked by devenv.exe process (it such process exists).

Also an alternative.
 
> Any other solution?

The proper solution, IMO, is to take the final step separating Starcounter installation from the VS extension entirely. So that VS extension code is always distributed (and loaded) in isolation. That is probably quite some work though. Depending on the future of the extension, I think both above options are decent alternatives (and faster).

Just me 2c.

**Comment by miyconst** [comment]
>... a simple work around is to close visual studio and run the installer again.

This is not always enough, sometimes it's required to manually kill `msbuild` process(es).

**Comment by mmnosek** [comment]
> This is not always enough, sometimes it's required to manually kill msbuild process(es).

Exactly, my Visual Studio was closed at that time. The problem with a better message is, that if you try it again - it's a new installation, it's not an upgrade anymore. So it will not help 100%.

It would help if it's checked before the process is started.

**Comment by ubbeK** [comment]
> Exactly, my Visual Studio was closed at that time. 

Are you totally sure that there wasn't a msbuild.exe process still running that locked the files? https://github.com/Starcounter/level1/issues/4776

> The problem with a better message is, that if you try it again - it's a new installation, it's not an upgrade anymore. So it will not help 100%.

`Upgrade = uninstall old starcounter + install new installation`, so its not really a problem.

> It would help if it's checked before the process is started.

So what will you have us do here? If `devenv.exe` or `msbuild.exe` is running, what should happen?

**Comment by mmnosek** [comment]
> Are you totally sure that there wasn't a msbuild.exe process still running that locked the files? Starcounter/level1#4776

I don't know really. What I know is that I closed visual studio. 

> So what will you have us do here? If devenv.exe or msbuild.exe is running, what should happen?

I think that before the uninstallation process is started, we should check if everything is "ready-to-go". If `devenv` or `msbuild` is running, the message should be shown at the very beginning.

**Comment by ubbeK** [comment]
Lets see if we can add some pop-up message where the user may cancel or continue when a `devenv` or `msbuild` process is running.

**Comment by iqbalskd** [comment]
Added a warning message if user has msbuild and/vs running. Also upgraded the error message on re-installation asking the user to close the vs and kill all msbuild processes.

**Comment by ubbeK** [comment]
> Also upgraded the error message on re-installation asking the user to close the vs and kill all msbuild processes.

Do you mind adding a screenshot here of that error message?

**Comment by iqbalskd** [comment]
The warning and error messages look like this now:

Warning:
![image](https://user-images.githubusercontent.com/28513553/49218351-74048300-f3d0-11e8-9905-6e710e7c43a6.png)
Error:
![image](https://user-images.githubusercontent.com/28513553/49218389-91d1e800-f3d0-11e8-8607-ef86c39bc28d.png)
