### ISSUE TITLE
ObjectID in Admin panel

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#442]
This problem related to testing single app hits me over and over.

I have a page `shoppingcart/product/X` that shows a specific product. This page is related to a product (X). It's not possible to open this page through navigation in the app, it's only specific URL that has to be opened. So I have to figure out what X is.

This page expects there `ObjectID`. I go to the Admin tool and execute the query: `SELECT * FROM Showroom.Database.Product` but I get only `ObjectNo`. There's no way to retrieve `ObjectId` easily, and it affects all of Starcounter apps. What can we do about that?

**Comment by miyconst** [comment]
>There's no way to retrieve ObjectId easily, and it affects all of Starcounter apps. What can we do about that?

We can add a UI tool to convert `ObjectNo` to `ObjectId` and other way around. Would that work?

**Comment by Mihaiii** [comment]
> We can add a UI tool to convert ObjectNo to ObjectId and other way around.

The conversion shouldn't be made in JS given that JS is not good with big numbers.
That being said, if you still want to do it on Admin app level - meaning after it receives the data - I'm fine with it.

**Comment by mmnosek** [comment]
From the user/developer perspective it doesn't really matter how. I would like to have either additional column, or to click on `ObjectNo` and then receive `ObjectId`

**Comment by warpech** [comment]
Meanwhile, anyone who needs a tool to convert ObjectNo to ObjectID, can use my command line app: https://gist.github.com/warpech/9c624c954afbbb70f28c77dec9702261

**Comment by warpech** [comment]
@Mihaiii made a better hosted tool: https://mihai.lib.id/base64@dev/?id=123456

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
