### ISSUE TITLE
Custom arguments in CLI arguments not escaped as excepted

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#451]
According to the [docs](https://docs.starcounter.io/topic-guides/working-with-starcounter/star-cli):

> Custom arguments starting with hyphens will throw ScErrBadCommandLineSyntax (SCERR1031). To prevent this, prefix the argument with any other character:
>
> `star app.exe \-argument1`

## Expected

After reading the docs, I expect the following call

```
star sample.cs \-api-token
```

Will result pass an escaped form of my argument to the app, i.e. `-api-token` (without slash).

## Actual

When you start the app with the command given above, the app receives the argument literally as `\-api-token` (with slash).

## Steps to reproduce

Put the following content in `sample.cs` and run it using the above command:

```cs
using System;
using System.Linq;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Args that I got: " + string.Join(", ", args));
        }
    }
}
```

**Comment by Mackiovello** [comment]
This is most likely just sloppy documentation writing. I interpret it this way: "Starting an argument with a dash is illegal, so start the argument with any other character instead."

There's never any escaping.

**Comment by warpech** [comment]
> This is most likely just sloppy documentation writing. I interpret it this way: "Starting an argument with a dash is illegal, so start the argument with any other character instead."

It cannot be written that way then. It sounds as if it was the CLI user's choice how to spell an argument. The choice of the argument spelling is made by the app author, so I recommend to change the docs to something like:

> Custom arguments starting with hyphens are not legal in Starcounter apps and will throw ScErrBadCommandLineSyntax (SCERR1031). To prevent this, it is recommended that apps use arguments that do not start with a hyphen.

**Comment by Mackiovello** [comment]
I've updated the documentation
