### ISSUE TITLE
Interesting Performance results!

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#452]
Total records read: `3,509,000`

1: `14500 ms`
```
ulong aaa = 0;
for (int i = 0; i < 1000; i++)
{
	var macs = Db.SQL<MAC>("select r from MAC r where r.CC.Dnm = ?", 17); 
	foreach (var mac in macs)
	{
	    aaa += mac.HPP1.GetObjectNo();
	}
}
```
2: `8600 ms`
```
ulong aaa = 0;
for (int i = 0; i < 1000; i++)
{
	var macs = Db.SQL<MAC>("select r from MAC r");
	foreach (var mac in macs)
	{
		if (mac.CC.Dnm == 17)
		{
			aaa += mac.HPP1.GetObjectNo();
		}
	}
}
```

**Comment by k-rus** [comment]
Thank you for reporting your experience with performance. What version of Starcounter have you used? I guess there is no index on `MAC`, right?
I noticed that recently an optimisation was removed from query execution.

cc @un-tone

**Comment by k-rus** [comment]
> I noticed that recently an optimisation was removed from query execution.

It is not related to the above query. I missed to see that the query accesses a property, which is a reference to another record. If you can share the query plan for the query, it might be helpful.

**Comment by SenerDemiral** [comment]
`select r from BDB2.MAC r where r.CC.Dnm = 17`
```
Tables(
 0 = BDB2.MAC
 1 = BDB2.CC
)
Projection(
 0 =
  ObjectThis(0)
)
Join(
 Inner
 FullTableScan(
  MotherOfAllLayouts_SetspecIndex ON BDB2.MAC
  0
  LogicalValue(TRUE)
  Ascending
 )
 ReferenceLookup(
  1
  ObjectProperty(0, CC)
  ComparisonNumerical(
   Equal
   IntegerProperty(1, Dnm)
   IntegerLiteral(17)
  )
 )
)
```

**Comment by k-rus** [comment]
Thank you for sharing the plan. It looks to be as expected.

@un-tone Will you be able to look this issue?

cc @dan31

**Comment by un-tone** [comment]
@k-rus I will

**Comment by miyconst** [comment]
Archiving.
