### ISSUE TITLE
Communication is broken after a time of inactivity

### ISSUE THREAD

**Issue by stefanedqvist** [Starcounter/Home#454]
As a customer when not touching the screen for a longer while the communication between server and client seems broken. If I click a button or link the new URL shoes in the browser address field but I will not be brought to the new view. A refresh or hit enter in the url field will solve it. 
Is this what you saw as well @miyconst

**Comment by miyconst** [comment]
@warpech you are probably right here. Currently link click tries to perform URI morphing, and if the connection is broken - nothing happens. I think, Palindrom, in this case, should perform full page reload.

**Comment by miyconst** [comment]
Archive.
