### ISSUE TITLE
Starcounter uninstallation fails on XSON files being used by VS Code/OmniSharp

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#460]
Starcounter version: `2.4.990.245`.

### Issue type

- [x] Bug
- [ ] Feature request
- [ ] Suggestion
- [ ] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Issue description

When I uninstall or upgrade Starcounter, and Visual Studio Code is running, the uninstaller fails because few XSON DLL files are used by OmniSharp. Is there anything we can do with that?

![2019-03-28 14_27_11-Apps _ WebPlatform _ Blending _ Blending Master with Starcounter Develop Nightly](https://user-images.githubusercontent.com/566463/55161660-566cdd80-5166-11e9-8e55-3320b10bcc32.png)

![2019-03-28 14_27_28-Starcounter Setup](https://user-images.githubusercontent.com/566463/55161665-5967ce00-5166-11e9-938c-dfd6ac2edb88.png)

![2019-03-28 14_28_42-Process Explorer Search](https://user-images.githubusercontent.com/566463/55161666-5b319180-5166-11e9-8067-3eba29c6e884.png)

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
