### ISSUE TITLE
Transactions blocking each-other?

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#462]
Starcounter version: `2.3.1.8415`.

### Issue type

- [X] Question

### Issue description

I have a few situations where I'm experiencing that a server gets congested when code running inside a `Db.Transact()` takes a considerable amount of time, e.g. about 60 seconds. Of course this code is not ideal, but nevertheless, it got me curious.

What happens is that during that 60 second transaction, no other requests are served until it has completed. I want to dig deeper to find out under what exact conditions this happens, but before I go ahead with that I want to ask if there are any known caveats that would make transactions queue up, or even database access outside any running transaction to be queued up until a previously running transaction has finished.

To be fair, there is the odd chance that there is something else causing the congestion, but I have tried in one case to split the 60 second code snippet into many small transactions, and in that case the congestion is gone. That indicates that my monster transaction is involved somehow.

Our code uses both `Db.Transact()` and `Db.TransactAsync()`, not sure if that matters.

**Comment by bigwad** [comment]
I can hardly imagine such a situation. What is the CPU usage when congestion occurs? Could it be that all CPUs are just busy processing this large transaction?

**Comment by eriksunsol** [comment]
The CPU load is ~8% when the congestion occurs. This hardware has 6 cores with hyper-threading, i.e. 12 execution threads, 100% / 12 = 8.333%. The large transaction is not using any parallel execution paths so it's definitely just a single thread which is blocking.

We're using quite a lot of nested transactions if that matters. Only the outermost call should have any effect of course, but I'm grasping at straws here and don't know what might be relevant.

**Comment by eriksunsol** [comment]
I think it's safe to assume that this is a non-issue, i.e. the transactions are in fact __not__ blocking each other. See #465.
