### ISSUE TITLE
How does Starcounter's Schedulers work with respect to Starcounter.Session?

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#465]
Starcounter version: `<2.3.1.8415>`.

### Issue type

- [x] Bug
- [ ] Feature request
- [ ] Suggestion
- [X] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Issue description

Continuation of #462. While investigating further into #462 I started suspecting that the transactions were not the cause for requests being blocked. As stated in #462 I tried to split a very time consuming transaction into smaller pieces and experienced an improvement. This turned out to be random though. Even with that change, requests get blocked, randomly it seemed at first.

Things noted:

- One request may be blocked while another one isn't, simultaneously.
- If I stop all threads in the debugger when blocking occurs, there is actually only one thread executing code to serve a request.

So, I started suspecting that the requests are not allowed to run at all when blocked. In that case it may be an issue with how requests are scheduled. I realize that I may have used the term "request" in the wrong sense here. What I'm talking about is "XSON processing an incoming JSON PATCH".

It seems that each `Starcounter.Session` is permanently assigned a Scheduler Id, which I assume corresponds to a worker thread. It also seems that many sessions share the same Scheduler Id. Am I correct then to assume that processing of incoming patches for all sessions sharing the same Scheduler Id will actually execute on the same thread?

That would explain the behavior I'm seeing. Next question: What would be the best course to deal with this?

__Update__: "requests" are actually a mix of "XSON processing an incoming JSON PATH" and `Handle.GET()` delgated producing responses without upgrading to XSON websockes.

**Comment by bigwad** [comment]
>It seems that each Starcounter.Session is permanently assigned a Scheduler Id, which I assume corresponds to a worker thread. It also seems that many sessions share the same Scheduler Id. Am I correct then to assume that processing of incoming patches for all sessions sharing the same Scheduler Id will actually execute on the same thread?

Not necessarily on the same physical thread, but sharing the same scheduler (several threads may be assigned to the same scheduler). But in practice you're right - in most scenarios only one thread per scheduler serves a request.  I actually thought about it when considered #462, but you said all requests get blocked at some point, while schedulerid is assigned to sessions in a round-robin manner. If you see that congestion only regarding the subset of sessions that are attached to the same scheduler - then yes: the behavior is explicable and designed like that. cc @alemoi

**Comment by alemoi** [comment]
There should be no assumptions about threading. Sessions arrive to schedulers they are assigned to and will execute on those schedulers. Basically there is a queue of requests to each scheduler and sessions might be in those requests.

**Comment by eriksunsol** [comment]
> If you see that congestion only regarding the subset of sessions that are attached to the same scheduler - then yes: the behavior is explicable and designed like that.

Is there any way to have this fixed? With the explanation above, I would consider this an error in the specification. What I would like to be able to assume is that a request for one session is never blocked by a request for another session even it is misbehaves.

**Comment by bigwad** [comment]
@eriksunsol, I understand your concern and agree with you that this should have been designed better. 

>Is there any way to have this fixed?

Apart from the refactoring of app handler in the app, I see two approaches we can take in Starcounter. They have different trade-offs, so we need to discuss them first.

cc @dan31

**Comment by miyconst** [comment]
Archiving.
