### ISSUE TITLE
There is no 2.4 version link in download page.

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#466]
Starcounter version: `<>`.

### Issue type

- [ ] Bug
- [ ] Feature request
- [ ] Suggestion
- [ ] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Reproduction code snippet

```cs

```

### Exception stack trace

```
```

**Comment by miyconst** [comment]
Hello @SenerDemiral and thank you for the interest in Starcounter.

Currently we do not have plans releasing the 2.4 version of Starcounter. Instead we are working on Starcounter 3.0, which is going to be cross platform (work on Windows & Linux) as well as support web & desktop applications.

**Comment by SenerDemiral** [comment]
v3.0 Wonderful news!
