### ISSUE TITLE
Delete corresponding subdirectory in Temp on `staradmin delete db` command

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Home#468]
Starcounter version: `<2.3.1.8415>`.

### Issue type

- [ ] Bug
- [x] Feature request
- [ ] Suggestion
- [ ] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Issue description
For DevOps and CI reasons, I would like the corresponding subdirectory in `%StarcounterDataRepo%/Temp` to be deleted when executing `staradmin delete db`.

Example: only `%USERPROFILE%\Documents\Starcounter\Personal\Data\foo\foo-20190620T093110985` gets deleted, but not the `%USERPROFILE%\Documents\Starcounter\Personal\Temp\foo\foo-20190620T093110985` directory does not. That folder contains the weaved files which takes up ~440Mb for us on each run/CI-build.

**Comment by miyconst** [comment]
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.
