### ISSUE TITLE
Feature: Allow TObject to add another TObject without TObjArr constraint

### ISSUE THREAD

**Issue by Razkan** [Starcounter/Home#469]
Starcounter version: `LTS-2.3.1.8584`.

### Issue type

- [x] Feature request

### Feature description
Currently the public API does not allow for two separate `TObject`'s, non `TObjArr`, to be combined since it is limited by the constraints. 
```csharp
public T Add<T>(string name, TObject type) where T : TObjArr, new()
```

However below is a workaround that can be used, but it may have undesired side effects.

```csharp
T obj = TObject.Add<T>(Name);

foreach ( var prop in otherTObject.Properties )
{
	prop.Parent = null;
	obj.Properties.Add(prop);
}
```

Something similar can be found when using the `{ "$": { "reuse": "..." } }` pattern in `Json-By-Example` where it seems to combine two different `TObject`'s.

**Comment by miyconst** [comment]
@Razkan thank you for the request, but we are not enhancing `Starcounter.XSON` with new features, since it's going to be replaced with `Starcounter.Palindrom` in Starcounter 3.0.

Closing as won't fix.
