### ISSUE TITLE
Cache invalidation strategy

### ISSUE THREAD

**Issue by dan31** [Starcounter/Home#50]
@dan31 commented on [Tue Dec 16 2014](https://github.com/Starcounter/Level1/issues/2452)

Working with Starcounter, @malx122 experience cache invalidation issues while evolving applications to newer versions (I followed up with Anders ). @malx122, can you explain the issue in more details? We need then to think on better cache invalidation strategy. I personally admit that we face with "probably cache hasn't been cleaned" problem quite frequent.

---

@k-rus commented on [Tue Dec 16 2014](https://github.com/Starcounter/Level1/issues/2452#issuecomment-67155909)

Which cache do you mean, Web or SQL?

---

@dan31 commented on [Tue Dec 16 2014](https://github.com/Starcounter/Level1/issues/2452#issuecomment-67163306)

Browser's cache. It's when you go to some page in your app, and it's loaded from browser's cache, while is supposed to be invalidated and loaded from the app directly.

---

@malx122 commented on [Tue Dec 16 2014](https://github.com/Starcounter/Level1/issues/2452#issuecomment-67163872)

Yepp, browsers cache, static content. I always have chromes developer tools open and the "disable cache (while DevTools is open)" checkbox checked. That is the only way I know of getting updates to work...

---

@miyconst commented on [Mon May 09 2016](https://github.com/Starcounter/Level1/issues/2452#issuecomment-217990763)

In the old web times we added a version parameter to static resources links. The version number is incremented every time a new app released. For example:

``` html
<!-- Original link -->
<link href="styles.css" rel="stylesheet" />

<!-- Updated link -->
<link href="styles.css?v=1.0.0" rel="stylesheet" />
```

This can solve the issue for application specific static content, but won't work for WebComponents import as browser will treat same URL with different version as different components and load it twice.

There is also a possibility to register a handler which would serve all of the app's static content.

``` cs
Handler.GET("/MyApp/content/{?}", (string path) => ReadFileContent(path));
```

This is not recommended and not efficient since Starcounter saves all of the static files in RAM, and in case of the Handler it will be useless.

## 

What we need is Request Filters for static content. In this case the issue can be solved by registering a static content request filter and set custom cache header which would invalidate the browser's cache.

**Comment by miyconst** [comment]
Archiving. The issue was fixed by @alemoi with proper cache invalidation of the static files.
