### ISSUE TITLE
Is it possible to get physical size consumed in RAM for a database and/or specific object?

### ISSUE THREAD

**Issue by dan31** [Starcounter/Home#58]
@miyconst commented on [Fri Sep 09 2016](https://github.com/Starcounter/Level1/issues/3834)

So, the questions are:
- Is it possible to get physical size of a database in RAM?
  - And on HDD.
- Is it possible to get physical size of an object in RAM?
- Is is possible to get physical size of tables in RAM?

---

@k-rus commented on [Sat Sep 10 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-246101574)

> Is is possible to get physical size of tables in RAM?

see #2448

In general, there is no notion of a table in the physical storage.

---

@bigwad commented on [Fri Sep 23 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-248344841)

I assume, that in general you're asking for a programmatic way of getting this information, but as long as we don't have it yet, I'll share what we do have.

Let's try to answer it piecemeal. Here is some info regarding 2.3 (aka pnext).
1. Physical size of a database in RAM
   Pnext kernel tracks amount of memory it allocates. One may use perfmon utility to get it. Utility is not included in the setup, so look for it on the build server. Command line for utility: perfmon <instance_id>, where instance id is usually 1. You may find out correct instance_id exploring command line parameters of appropriate sccode.exe process. Instance_id is the first one.
   So. Running this utility you get two numbers: allocated_blocks and used_blocks. Size of each block is 256 byte.
   If perfmon is not an option, there is a way to get similar number using sysinternal's vmmap utility. I may show it in additional post if you are interested.
2. Database size on disk
   It's just the size of db log directory. There is subfolder "archive", that could be counted separately. This folder is the subject for automatic clean up but if you're not interested in log replication, it's safe to clean it up manually.

---

@bigwad commented on [Fri Sep 23 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-249131773)

Here goes some info about 2.2:
1. Physical size of a database in RAM
Generally, you have two same ways of getting this information: perfmon and vmmap. Command line for perfmon in 2.2 has different format: perfmon <servername_databasename>, where servername is usually PERSONAL. Consumed memory is reported with storage_memory.total_pages parameter, that gives the number of 1Kb pages.
2. Database size on disk
Again, it's just the size of db log directory. Don't forget to periodically cleanup .log.bak files. They can consume significant amount of space. Apart from .log.bak files, size of the data on disk is pretty much the same as in memory.

---

@bigwad commented on [Fri Sep 23 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-249133566)

Some observations about 2.2 vs 2.3 resource consumption:
1. 2.2 seems to be more thrifty about RAM. My test shows 2.2 takes about 20% less RAM than 2.3 for  the same amount of data.
2. It's opposite for the disk. 2.3 seems to occupy half as much space as 2.2 does. But it goes with the cost of increased database startup time.

---

@dan31 commented on [Fri Sep 23 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-249135283)

> 2.3 seems to occupy half as much space as 2.2 does. But it goes with the cost of increased database startup time.

@bigwad what is your current observation on startup time? We admit it is synthetic test.

---

@bigwad commented on [Fri Sep 23 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-249146523)

For my ~60M records database:

| Version | Time, sec |
| --- | --- |
| 2.2 | 30 |
| 2.3 | 400 |

---

@dan31 commented on [Mon Sep 26 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-249703175)

@bigwad thanks, what is the size in Gb approximately? I guess the difference feels really noticeable, and we'd have to work on improving it soon, most likely before releasing 2.3. Not discussing it further there, this is a separate issue subject.

As for objects and tables. A tool existed in 1.x https://github.com/Starcounter/Starcounter/issues/372. I guess the current repeated customer demand is to provide such facility in Administrator. Definitely a feature request.

---

@miyconst commented on [Tue Sep 27 2016](https://github.com/Starcounter/Level1/issues/3834#issuecomment-249761509)

Not only in Administrator, but also as an API to be able to get the values in an application.

**Comment by miyconst** [comment]
Archiving the issue.
