### ISSUE TITLE
Starcounter RC upgrade failed

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#63]
I have Starcounter 2.3.0.5451 and I've tried to upgrade to the newest RC 2.3.0.6114, but with no success.

* Message appeared: "User has declined to accept changes, installation aborted" - it's not exact message, I don't have it.
* I've tried to Run Starcounter (it's not completely uninstalled) but now I have an error message: "ScErrBadServiceConfig (SCERR2113): Service configuration is invalid."
* When I try to run 2.3.0.6114 once again, it starts Starcounter installation from scratch. What went wrong? I need to make the same operation on production-like environment and I'm a little bit scared that the same thing will happen.

@andwah

**Comment by andwah** [comment]
Not sure how i can help.. but there may be a installation logfile @alemoi  do you know?

**Comment by dan31** [comment]
Hm, is this because of added ```sccleaner```? CC @per-samuelsson @eriohl

**Comment by mmnosek** [comment]
I've tried from 2.3.0.5451 to 2.3.0.6045:

<img width="801" alt="sc_upgrade" src="https://cloud.githubusercontent.com/assets/4943949/24362096/05bd4112-130c-11e7-9130-6598b815c9fe.png">
I clicked "yes":
<img width="801" alt="sc_up2" src="https://cloud.githubusercontent.com/assets/4943949/24362118/14c827da-130c-11e7-8815-a1b7a5ae7c0d.png">

**Comment by alemoi** [comment]
Hi @mmnosek ! Isn't the message "User has declined to accept changes, installation aborted" because you have clicked No to delete the old Starcounter directory, as shown on the pic above?

**Comment by per-samuelsson** [comment]
> Hm, is this because of added sccleaner? CC @per-samuelsson @eriohl

No, that one is not integrated yet. It's WIP.

**Comment by mmnosek** [comment]
> Hi @mmnosek ! Isn't the message "User has declined to accept changes, installation aborted" because you have clicked No to delete the old Starcounter directory, as shown on the pic above?

@alemoi, nope I didn't have a chance to click anything.

**Comment by alemoi** [comment]
> @alemoi, nope I didn't have a chance to click anything.

As I see in the message above. The installation directory is occupied by some entity. Were you able to repro the situation?

**Comment by lazaridis-com** [comment]
@dan31 , @per-samuelsson , are you actually aware that this looks like the team is "playing github"?

Do you really expect that I trust your product, after seeing how you process a trivial update/installation error?

@andwah mentioned:

> Not sure how i can help.. but there may be a installation logfile

So, questions:

- is there an installation logfile?
- where is this installation logfile?
- why does not every(!) member of this organization know where this logfile is?

**Comment by mmnosek** [comment]
I didn't reproduce this situation later at all. I've upgraded SC without any problems many times. Archiving.
