### ISSUE TITLE
System.Exception: Unknown WebSocket frame type: 0

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#65]
```
System.Exception: Unknown WebSocket frame type: 0
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4113\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 719
HResult=-2146233088
```

@alemoi what does this mean? How to debug it?

**Comment by chrhol** [comment]
It's probably due to the websocket implementation lacking support for fragmentation.

**Comment by alemoi** [comment]
> It's probably due to the websocket implementation lacking support for fragmentation.

100%

I have to hurry up fixing this, otherwise you will hang me, guys :)

**Comment by miyconst** [comment]
@alemoi any progress on this issue?

**Comment by zafrul-adfenix** [comment]
Any update on this issue? Earlier I  have posted this issue:(https://github.com/Starcounter/Home/issues/187)

**Comment by alemoi** [comment]
The support for fragmentation is added and tested via Autobahn. Hope you enjoy this feature 😄

**Comment by Razkan** [comment]
Opening this issue, @alemoi.

After a websocket upgrade is established, the first chunk of data gives the error message. The data is sent as Base64.

`System.Exception: Unknown WebSocket frame type: 0
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-4222\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 764
HResult=-2146233088`

**Comment by Mackiovello** [comment]
@Razkan, this was added in 2.3.1, so that's why you're hitting it on 2.3.0. I guess you could split the data on the client side and send it. That would be a workaround until you upgrade to 2.3.1.

**Comment by Razkan** [comment]
@Mackiovello The data is already chunked from the client side, but at the size of 262kb for each chunk. Should it be lower?

**Comment by Mackiovello** [comment]
That does sound weird. Let's hear from @alemoi or @miyconst

**Comment by alemoi** [comment]
I will try to test with bigger chunks.

**Comment by alemoi** [comment]
> @Mackiovello The data is already chunked from the client side, but at the size of 262kb for each chunk. Should it be lower?

Yes, you need to split it in smaller pieces. Its hard to say to how small, since it depends on the middle parties that decide to fragment it. Try lets say 1Kb. However I would suggest upgrading to the newest 2.3.1 version of Starcounter, where WebSocket fragmentation is fixed.

**Comment by Mackiovello** [comment]
Okay, let's close this as answered then. Thank you @alemoi
