### ISSUE TITLE
The state of aggregates in Starcounter

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#66]
In [our documentation](https://docs.starcounter.io/guides/SQL/aggregates/) we write that:

> The current version of Starcounter SQL does not officially support aggregates because the support of aggregates is not yet performance optimized.
> However, there is an experimental support for aggregates in the SQL browser in Starcounter Administrator. It is also available in your code by using the method Db.SQL

This conflicts with the reference documentation for [`Db.SlowSQL`](http://reference.starcounter.io/api/Starcounter.Db.html#Starcounter_Db_SlowSQL__1_System_String_System_Object___) where it says that:

> Returns the result of an SQL query as an SqlResult which implements IEnumerable. Especially queries with expected slow execution are supported, as for example aggregations.

Which one is it? Trying to use aggregators in `Db.SQL` seems to work, so it seems like it is the first case. 

It also seems like the reference documentation for `Db.SlowSQL` is wrong. Doesn't it return `QueryResultRows<T>` and not `SqlResult`?

**Comment by dan31** [comment]
CC @k-rus

**Comment by k-rus** [comment]
> It also seems like the reference documentation for Db.SlowSQL is wrong. Doesn't it return QueryResultRows<T> and not SqlResult?

We have public docs generated, where it specifies what it returns. `Db.SlowSQL` and `Db.SQL` returns the same - `IEnumarable`. Then it is possible to get actual enumerator, which will enumerate over returned rows. This is normally hidden behind `foreach` or `First`.

**Comment by Mackiovello** [comment]
Just to be really clear:
* Does the current version of Starcounter SQL officially support aggregates?
* Are aggregates performance optimized?

From what I understand, they return the same class which inherits from `IEnumerable`. This class is called `QueryResultRows` and not `SqlResult`. In that case, the documentation is wrong.

**Comment by k-rus** [comment]
> Does the current version of Starcounter SQL officially support aggregates?

I don't know what means officially. I only know that you can execute it.



> Are aggregates performance optimized?

No, and there is benchmark written by @miyconst.



> From what I understand, they return the same class which inherits from IEnumerable. This class is called QueryResultRows and not SqlResult. In that case, the documentation is wrong.

I guess it was refactored, but the documentation was not fixed accordingly.

**Comment by Mackiovello** [comment]
Thank you, I'll consider my question answered.
