### ISSUE TITLE
Application stalls on certain hardware

### ISSUE THREAD

**Issue by dan31** [Starcounter/Home#68]
When running on certain Hetzner machine, @atifwaqar noticed SC 2.3 RC goes into stall for minutes at certain moments when files are copied on the server (hence the disk is in use). Files being copied aren't anyhow relate to Starcounter. @miyconst reports he has noticed the same phenomenon once or twice.

This might be a combination of Starcounter's default ```disksync``` mode, which raises the requirement on the hardware quality, and the given hardware. As an outcome of the current issue, an advice on hardware configuration shall come out.

@bigwad advised to investigate things this way.

_profile the system with wpr_

1. when system become unresponsive - start performance recording with the command "wpr.exe -start GeneralProfile"

2. keep calling your handler to make sure system is still unresponsive

3. from task manager create dump file for starcounter processes: scdata, sccode, scdblog, scnetworkgateway. Send them to us   

4. wait for about 1 minute.

5. stop performance recording with the command "wpr.exe -stop <filename>", where filename is name of file to store data.

6. wpr will create file named <filename> and the folder named <filename>.NGENPDB. Send both to us.

small addition. I think it's better to take dumps before starting "wpr.exe -start GeneralProfile", i.e. to move step 3 ahead of step 1

CC @MujahidRashid @atifwaqar @bigwad @miyconst

**Comment by miyconst** [comment]
@atifwaqar, @MujahidRashid, were you able to investigate the issue with the steps provided by @dan31?
