### ISSUE TITLE
Star counter issue after fresh re installation

### ISSUE THREAD

**Issue by iliassays** [Starcounter/Home#69]
After a crash, i uninstall my starcounter and again reinstall it. Having bellow issue.

![sc-error](https://cloud.githubusercontent.com/assets/3203987/24455579/f1dac172-14b1-11e7-8d98-1de64a87b8e3.PNG)

**Comment by miyconst** [comment]
And what Starcounter and Windows logs say?

**Comment by iliassays** [comment]
[2.2.5.zip](https://github.com/Starcounter/Home/files/879130/2.2.5.zip)

**Comment by andwah** [comment]
@iliassays also check the EventViewer for `Starcounter TrayIcon` entries.
See example image below:

![image](https://cloud.githubusercontent.com/assets/2656996/24456663/0a6fff7c-1494-11e7-88fd-eef2cbb1c169.png)

**Comment by iliassays** [comment]
Hello
No such error reported.

**Comment by iliassays** [comment]
Any idea what to do? I get the latest 2.3 build and still facing the same issue.

**Comment by miyconst** [comment]
Do you have old database files in your documents folder?

**Comment by iliassays** [comment]
Did you meant this?
![sc-doc](https://cloud.githubusercontent.com/assets/3203987/24458881/051c7078-14bc-11e7-83e9-9e8d1180d1fa.PNG)

**Comment by miyconst** [comment]
I mean the `Starcounter` folder. Do you have any databases inside? If so, try to (re)move them.

**Comment by miyconst** [comment]
If that does not work then:

- Uninstall Starcounter.
- (Re)move the Starcounter documents folder.
- Install Starcounter again.
- Start Starcounter server.
- Report here if it starts or not.

**Comment by miyconst** [comment]
@iliassays what is the progress of this issue? Did it work for you?

**Comment by miyconst** [comment]
Archiving.
