### ISSUE TITLE
Correct Links, Takedown Inactive Resources

### ISSUE THREAD

**Issue by ghost** [Starcounter/Home#71]
https://starcounter.com/support/

Community Support

https://github.com/Starcounter/Starcounter - Broken Link (i guess its not **this** repo)

https://gitter.im/Starcounter/Starcounter -> inactive, should be possibly taken down

https://stackoverflow.com/questions/tagged/starcounter -> inactive

-

You should possibly just correct the overall **support** section.

**Comment by Mackiovello** [comment]
I'm in contact with the person responsible for the Starcounter.com to clean up some of the things that have been left there too long.

Yes, the gitter should probably be killed off. 

The Starcounter/Starcounter has been moved to a private repo and is thus not available for everyone. We're working on cleaning up links to that repository.

Thank you for your comments. I'll take it from here.

**Comment by lazaridis-com** [comment]
@Mackiovello , one can only hope that you do not demonstrate such sloppiness (that's the word, take it) within your coding-processes.

> I'm in contact with the person responsible for the Starcounter.com

Fire the person responsible for the text. 

Keep the designer.

Remove this strange looking "Website built by Business Reflex AB".

**Comment by Mackiovello** [comment]
This is now taken care of. Closing
