### ISSUE TITLE
Update README to better reflect what Starcounter is

### ISSUE THREAD

**Issue by lazaridis-com** [Starcounter/Home#73]
...should stay away from documentation, and focus on code.

The README needs a complete rewrite. Example:

>Starcounter makes creating sexy and fast line-of-business application a breeze by collapsing the stack.
>
> Starcounter removes the boundaries between primary and secondary memory (getting rid of application to database glue code) and allows server side view models (getting rid of the need for service API design and MVC client/server to client glue code).
>
> This Starcounter is a fused ACID memory centric database engine and C# VM.
>
> This repository is reserved for the public Starcounter bits.

Remove it. Or (if your really want to repeat your "marketing babbling" within a repo, write it like this:

**Starcounter combines the C# Virtual Machine with a proprietary in-memory-ACID database.

It removes the need for cross-server database-glue-code and cross-machine MVC-glue-code.

This introduces a new kind of non-repetitive-code development, resulting in lightning-fast applications which can serve millions of users from just one server.**

**Comment by Mackiovello** [comment]
> The Person which has written the README here should stay away from documentation, and focus on code.

I appreciate that you take your time to express your feedback. As a friendly reminder, please avoid insulting specific people. Let me remind you of the wonderful quote "praise by name, criticize by category". Targeting specific individual is not going to cause goodwill and change.

You're right that this description is not completely suitable for a public repo. I'll take care of it.

Thank you the suggestion.

**Comment by Mackiovello** [comment]
Fixed in 4f7271d0e10084b4b17c4adcfb99d3bdd396535e closing

**Comment by lazaridis-com** [comment]
@Mackiovello , the only one who has possibly insulting behavior is you, just by accusing me of beeing insulting. I was not, and it is you very personal problem if you interpret it this way. 

Please keep your "wonderful quotes" for some kiddos, which you can possibly impress.

Having said this, changing the title is like you did is an act of barbarism (and please, no new quotes now). Barbarism, because you destroyed the integrity o one persons writings (without even grasping the essence of those writings).

Think about it.

-

You produce a data-base-system, so act like database producers, and display the discipline that is needed from such a team.

> You're right that this description is not completely suitable for a public repo.

Stop placing words into my mouth. I did not say that. I said:

"The Person which has written the README here... ...should stay away from documentation, and focus on code."

Which is the essence: every team-member has his strengths. Core-developers should simply stay away from documentation: they mess it up, especially those with good abstract thinking.

-

The readme contains still and invalid link: "https://github.com/Starcounter/Starcounter/issues/new"

This Issue is still open. The goal is to produce a written rule, which dictates that core-developers should not document the system (similar to not testing the code they write themselves).

**Comment by warpech** [comment]
@lazaridis-com please take some self-reflection: https://github.com/search?utf8=%E2%9C%93&q=mentions%3Alazaridis-com+language&type=Issues

Take some time off the keyboard and read this classic book on communication skills: https://www.amazon.com/How-win-friends-influence-people-ebook/dp/B01H38S9FY/ref=sr_1_1?s=books&ie=UTF8&qid=1490961783&sr=1-1&keywords=how+to+win+friends+and+influence+people

**Comment by warpech** [comment]
To be clear: We value constructive feedback, but we will block people who abuse the public issue tracker to insult people.
