### ISSUE TITLE
Rename this repo from "Home" to "feedback"

### ISSUE THREAD

**Issue by lazaridis-com** [Starcounter/Home#74]
I don't think that this need further elaboration.

It would be even better to delete this repo completely, but if you keep it, please rename it to "feedback".

**Comment by Mackiovello** [comment]
> It would be even better to delete this repo completely, but if you keep it, please rename it to "feedback".

That depends completely on what school of thought you belong to. Both [asp.net](https://github.com/aspnet/Home) and [NuGet](https://github.com/NuGet/Home) are using a home repo. 

The idea is that this an entry point from where the rest of the repositories can be found. 

I do agree that it should be easier to contribute, though, calling this repo "feedback" would be misleading.

**Comment by lazaridis-com** [comment]
> That depends completely on what school of thought you belong to. Both asp.net and NuGet are using a home repo.

So, you declare yourselves "following dummies", yet you say that you produce next-generation game-changing systems? Very disappointing.

Both, asp.net and NuGet, are doing wrong. Instead of asking gitHub to provide a "homing" functionality, they implement a dirty workaround, which other projects (like you) adopt, without further (logical) verification.

 => The "Following Dummies"

The main problem is that GitHub is not the best system to host complex projects. GitHub is essentially a mess (e.g. project-hierarchy, the issue-tracker, with the ridiculous labels, no hierarchy, no hierarchical display). 

> Have a question that is not covered in our docs here: https://docs.starcounter.io, or want to file a bug?

The project which you name "Home" is essentially the project "Starcounter". In order for this to become logically valid, you have to view the full path:

 * Starcounter/Home

Even then, it is wrong, and shoul be named:

* Starcounter/main

-

**Comment by miyconst** [comment]
@Mackiovello has provided a nice and broad answer, closing the issue as invalid.
