### ISSUE TITLE
Simplify flow of converting TypedJSON to some representation based on mimetype.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#78]
When trying to fix #76 I found some things around the way we convert a TypedJSON instance to some other representation based on mimetype that is somewhat flawed and unnecessarily complex, where the implementations of interfaces `IResource` and `IResponseConverter` called eachother from different places.

The following things will be done:
- Obsolete/deprecate `IResponseConverter`. It's only usage today is in XSON and it's not mentioned in any documentation.
- Move code that implements `IResponseConverter` to Starcounter.XSON project.
- Implementation of `IResource` interface in TypedJSON will use parts of the old `IResponseConverter` implementation. 
- The converter implementation will no longer call the `IResource` implementation.

**Comment by chrhol** [comment]
As usual when you start looking into something it's just falls apart. I will fix #76 first, simplest way possible, and let this be for a while. There's alot that needs to be changed around this I think, and it feels a bit premature to start with this.

**Comment by chrhol** [comment]
I'm back to this again, due to the problems described in #171. 

We need to rework and simplify how we convert some resource to a specific mimetype from a response, and also this is a good opportunity to remove some dependencies from `Starcounter.XSON` to make the transition to a separate package easier.

**Things to obsolete (in `v2.3`) and remove (in `develop`):**
- Obsolete/remove the `IResource` interface 
- Obsolete/remove the implementation of `IResource` from TypedJSON. If an app needs to have some custom conversion based on mimetype, the app should handle this themselves and if needed register a callback using the `MimeTypeProvider` middleware to hook it into the response pipeline.
- Obsolete/remove the `IResponseConverter` interface (well actually more rename it).
- Obsolete/remove the `JsonMimeConverter` class that implements the `IResponseConverter`

**Things to change/add**
- Simplify `Response` by merging the different fields for body (`Body, BodyBytes, Resource` ) into one property.
- Add new implementation for interface `IResponseConverter` (or whatever we decide to call this interface) that probably will reside in `Starcounter.App.Server` that contains other internal handlers for patching and other stuff.

The main change from before will be that the converter will *always* be called, which will allow the correct handling of generating patches when body is not set, but there is a `Session`.

To keep the flow as similar as it is currently, this is the order/handling of the body in the response:
1. If body is of type `string` or `byte[]` it will be used as is, meaning that the mimetype will be ignored.
2. Mimetypes `application/json` and `application/json-patch+json` and TypedJSON will be handled in the converter. This includes using the informatioin from session when needed.
3. For other mimetypes and body-types, the middleware will be invoked first.
4. If still not handled and the body is TypedJSON, a fallback conversion is invoked. This last part is taken from the current implementation, I don't really know why this is done at this time. Needs to be investigated.
5. If still not handled, throw an exception for unsupported mimetype.

Hopefully I can do these points and still keep backwards compability. If not, then I will have to consider some alternative way forward.

@warpech, @joozek78  (or anynone else interested): The main point from the outside is the obsoletion/removal of the `IResource` interface. I think this one is very rarely used (if ever) and we don't really use the `json.AsMimeType(...)´ methods. Is this a correct assumption? And is it ok to remove this functionality?

**Comment by chrhol** [comment]
One other question: should registered middleware for handling mimetypes be triggered *first* and not *last*? It feels a bit strange that you can register a middleware for a specific mimetype (i.e. `application/json-patch+json` and `application/json`) that will never be triggered.

**Comment by joozek78** [comment]
> The main point from the outside is the obsoletion/removal of the IResource interface. I think this one is very rarely used (if ever) and we don't really use the `json.AsMimeType(...)´ methods. Is this a correct assumption? And is it ok to remove this functionality?

It's actually used in [Authorization / Routing](https://github.com/Starcounter/authorization/blob/master/Authorization/Routing/Router.cs#L24) to construct a Response. I'd welcome a deprecation phase to allow me to change it to a new construction scheme.

As far as I understood you want to have one polymorphic `Body` property. Why not use (existing?) interface to hide different underlying bodies? I thought that was the idea behind `IResource` and I'm not sure why do you want it removed

**Comment by chrhol** [comment]
> It's actually used in Authorization / Routing to construct a Response. I'd welcome a deprecation phase to allow me to change it to a new construction scheme.

Yeah I saw that, but the only thing there is that it's set as `response.Resource`. It will be quite easy to migrate and keep the same functionality.  And of course, the aim is to keep it compatible in `v2.3` and remove it later when `Starcounter.XSON` is moved to a separate package.

> Why not use (existing?) interface to hide different underlying bodies? I thought that was the idea behind IResource and I'm not sure why do you want it removed

I want to simplify as much as possible. We have too many different ways to achieve the same thing and too many interfaces that are not really used or thought through. The logic for handling a response gets very messy, as seen in the current implementation which is just bad.

Maybe we can keep the interface, but the methods with parameters containing very starcounter specific types  (`Starcounter.MimeType`, `Starcounter.Request`) are a problem. Also `Starcounter.MimeType` is a very limited enum so it's not that many mimetyes you can handle from these methods.

**Comment by joozek78** [comment]
> The logic for handling a response gets very messy, as seen in the current implementation which is just bad.

I admit I haven't seen this code, but I believe it will be messy if we have a property of unspecified type (object?).

> Maybe we can keep the interface, but the methods with parameters containing very starcounter specific types (Starcounter.MimeType, Starcounter.Request) are a problem. Also Starcounter.MimeType is a very limited enum so it's not that many mimetyes you can handle from these methods.

I think we can represent mime type as string without a problem. I don't know how is `request` parameter used exactly, but maybe we should just remove that? I looks strange. When we already have generated response why would we need request again?

**Comment by chrhol** [comment]
> I think we can represent mime type as string without a problem. I don't know how is request parameter used exactly, but maybe we should just remove that? 

As for `request` I have no idea either. Looking at the git log it seems to have been there since the beginning. 

Alright, so lets keep the interface, but deprecate the methods that uses `Starcounter.MimeType` and `Starcounter.Request` as parameter to make it a bit more simpler (and by that easier to use).

Thanks for the feedback @joozek78!

**Comment by chrhol** [comment]
> As far as I understood you want to have one polymorphic Body property. Why not use (existing?) interface to hide different underlying bodies?

> I admit I haven't seen this code, but I believe it will be messy if we have a property of unspecified type (object?).

As for this, there are already a lot of different representations on `Response` that cannot implement `IResource` so there are separate fields for `string`, `byte[]`, `Stream` and `Resource` that needs to be taken in consideration already when serializing a response, so this section was more to simplify the `Response` class a bit. 

I will perhaps leave that to later (or leave it for @alemoi :wink:). It's not strictly needed to solve this issue and it's better to make sure I finish it in time.

**Comment by joozek78** [comment]
I don't want to go into the details (among other reasons, I don't know them well), but I'll just toss an idea:

> As for this, there are already a lot of different representations on Response that cannot implement IResource so there are separate fields for string, byte[], Stream and Resource that needs to be taken in consideration already when serializing a response, so this section was more to simplify the Response class a bit.

Why not wrap them in a struct?

**Comment by chrhol** [comment]
This is more or less in place (although it is not merged yet). Will be merged with all the other changes in #139.

**Comment by chrhol** [comment]
This is done. As we discussed `IResource` is still in place, although I simplified it to contain only one method, that takes both the `Starcounter.MimeType` and the mimetype as string as parameter. 

This way it will be fast to check the types in the enum, while still have the option to use the string for other minetypes (or additional info from a mimetype). 

Merged a couple of days ago.
