### ISSUE TITLE
Case sensitive strings in queries and indexes?

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#80]
I have a class like this (stupid example, but should illustrate what I'm struggling with):

```C#
[Database]
public class Foo {
  public string TheString { get; set; }
}
```

I have an unique index on `Foo.TheString` and run queries like `Db.SQL<Foo>("SELECT f FROM Foo WHERE TheString = ?", searchString)`.

Question: How to get the query and the index to be case sensitive?

**Comment by mtornwall** [comment]
To my knowledge you can't configure an index to be case-sensitive.

Depending on how many false positives you expect to get, you could filter the result using Linq:

    Db.SQL<Foo>("SELECT f FROM Foo f WHERE TheString = ?", searchString).Where(f => f.TheString == searchString);

**Comment by k-rus** [comment]
I confirm that indexes and SQL are case and accent insensitive. Thus it is necessary to filter after getting query result.

We haven't yet discussed supporting case or accent sensitive comparison of strings in SQL. This would require extending SQL syntax similarly to other DBMSs. This is unlikely to be done in the current version of SQL implementation, it can be done in coming SQL implementation, but in long terms.

**Comment by eriksunsol** [comment]
OK, thx. I'll just have to take care when using strings as keys.

FYI: The use case here is that one or more objects' `GetObjectId()` strings (joined with a separator, e.g. `; ` are used as a combined key for associating things with an arbitrary number of objects. Because of the above `GetObjectId()` is a bad choice because it gives you strings whose case matters. Although slightly less compact, `GetObjectNo().ToString()` is a better choice.

I have a related question which I will post as a separate issue.
