### ISSUE TITLE
ScErrConstraintViolationAbort doesn't say what constraint has been violated

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#81]
This error sometimes happens to me when committing a transaction. It isn't very helpful without mentioning what constraint was violated.

1. Add the information about what constraint has been violated to the error message
1. If that's impossible, explain it in the [error page](https://github.com/Starcounter/level1/wiki/SCERR8001#scerrconstraintviolationabort-a-transaction-was-aborted-because-a-constraint-was-violated)

**Comment by per-samuelsson** [comment]
I have a vague memory we did something about this in the past, that we have had similar requests and discussed what would be possible to achieve.

If I can find that info, I'll share it here. Or maybe @eriohl has some memory of that?

**Comment by per-samuelsson** [comment]
Might have been https://github.com/Starcounter/level1/issues/1207 I was thinking about, but that was addressed. It doesn't apply to all violations though.

**Comment by eriohl** [comment]
Exception is supposed to be accompanied with additional information on what constraint was violated. But it might not be working properly in 2.3. Task to address it seems to be in the [backlog](https://github.com/Starcounter/level1/issues/3138) still.

**Comment by joozek78** [comment]
If this is tracked already, then I'm closing this.
