### ISSUE TITLE
What's the full spec of Starcounter.Session.SessionId?

### ISSUE THREAD

**Issue by eriksunsol** [Starcounter/Home#82]
As expressed in the title, what are the requirements on `Starcounter.Session.SessionId`?

Specifically, related to #80, can this string be safely used as a key to store information in the database specific to the session?

**Comment by Mackiovello** [comment]
Do we have an answer for this? @per-samuelsson 

I don't know how helpful it is, but this is how we use it in our apps: https://github.com/search?p=1&q=sessionid+user%3AStarcounterApps+&type=Code&utf8=%E2%9C%93

**Comment by miyconst** [comment]
@alemoi you should know the answer to this question.

**Comment by Mackiovello** [comment]
ping @alemoi 

Documentation about it is here: https://docs.starcounter.io/guides/web-apps/sessions#operating-on-multiple-sessions, I guess it doesn't address the specific question

**Comment by alemoi** [comment]
I definitely remember someone was writing info about the session format. I think it was @warpech 
Do you recall anything, @warpech ?

**Comment by warpech** [comment]
I don't recall anything like that, I was never part of the decision making for the session format. 

I *think* `Starcounter.Session.SessionId` is a case insensitive string. Can you check in code? Can we consider this format fixed and put it to the docs?

**Comment by warpech** [comment]
I don't recall anything like that, I was never part of the decision making for the session format. 

I have only seen `Starcounter.Session.SessionId` as an upper case string, but I am not sure if it is case insensitive. @alemoi you check in code? 

Can we consider the current format fixed and put it to the docs?

**Comment by dan31** [comment]
Archived.
