### ISSUE TITLE
SC & CommitHook, migration experience from 1.3 to 2.x ask

### ISSUE THREAD

**Issue by jedynykaban** [Starcounter/Home#83]
Hi, 

I'd like to get information what is advised method of migration pattern for activities triggered by some CRUD operation (basically "CUD", i.e. "OnInsert" "OnEdit" "OnDelete" or looking from DB perspective what is alternative to database "triggers"?

Framework applied in SC 1.3 version provided base "CommitHook<T>" class, that had abstract (virtual) methods mentioned above. SC 2.x model is POCO oriented, so obviously described pattern is no longer valid. I'm aware that there is IEntity interface in SC 2.x, but it only allows to support "OnDelete" operation, what is suggested pattern for "OnInsert"/"OnEdit" operations?

Regards,
Michal

**Comment by per-samuelsson** [comment]
@jedynykaban 

We still have support for hooks in 2.x:

https://docs.starcounter.io/guides/transactions/commit-hooks/

Is it some functionality there you lack, compared to 1.3?

**Comment by jedynykaban** [comment]
Great, that should do it. Couldn't find this, thanks for help!

**Comment by per-samuelsson** [comment]
> Great, that should do it. Couldn't find this, thanks for help!

Perfect. I'll close this issue.
