### ISSUE TITLE
How to check if DB object is already persistent outside current transaction

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#84]
Sometimes, when the page is wrapped inside `Db.Scope` and the object that is bound to this page is created inside this scope, there is a need to check whether this object is visible outside current transaction scope, or not (if it will disappear on rollback). Have a look at this situation:

```
Handle.GET("/App/page", () =>
{
       return Db.Scope(() =>
       {
            var page = new Page();
            page.Data = new Something();
             return page;
        });
});
```

How to check inside `Page` viewmodel if transaction (and object inside `Data`) has been commited? The only solution known to me is to create nested transaction and try to retrieve object with given `Key`. If it doesn't exist, then object is not persistent yet.

Is there any better option? Shouldn't we introduce something to the API that will do something as I described without any additional code?

cc @miyconst @TakhirMamirov

**Comment by miyconst** [comment]
>... is to create nested transaction and try to retrieve object with given `Key`.

Not a nested, but parallel transaction.

Anyway, you have a very valid point, but unfortunately there is nothing available to solve this issue at the moment. I will bring up this subject at the next release planning meeting.

I would like to have the following knowledge:

- List of **all** changes inside ongoing transaction.
- This includes per property changes.
- The changes should be split into created, updated, deleted lists.

**Comment by mmnosek** [comment]
> List of all changes inside ongoing transaction.
This includes per property changes.
The changes should be split into created, updated, deleted lists.

Amazing idea! 👍 to all of them!

**Comment by miyconst** [comment]
This all will be implemented with the new branching mechanism. For now, we have to wait though. Please close the issue if your question was answered.

**Comment by mmnosek** [comment]
Thanks @miyconst ! @TakhirMamirov if you have any further questions feel free to reopen this issue.

**Comment by TakhirMamirov** [comment]
Thank you for update, guys!
