### ISSUE TITLE
Use `starcounter-include` in default PartialToStandaloneHtmlProvider

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Home#89]
Currently default `PartialToStandaloneHtmlProvider` uses just `imported-template` to stamp root partial:
```html
<body>
    <template is=""dom-bind"" id=""puppet-root"">
        <template is=""imported-template"" content$=""{{{{model.Html}}}}"" model=""{{{{model}}}}""></template>
    </template>
     ...
```

It results in lack of support for any layout features, like default `declarative-shadow-dom` (eventually could be fixed by https://github.com/Starcounter/RebelsLounge/issues/78) and explicit Shadow DOM compositions (ones from `Starcounter.HTMLComposition` given by CompositionProvider).

That's why I would suggest to
1. Use `starcounter-include` on root level:
   ```html
   <body>
       <starcounter-include view-model=""{{{{model}}}}""></starcounter-include>
       ...
    ```
    As we didn't deprecate non-namespaced view-models yet (https://github.com/Starcounter/starcounter-include/issues/29) it should work out of the box. But given that we decided to deprecate it eventually, it would require to have namespaced view-model JSON on root level. @chrhol is that possible, easy enough to implement?

  Alternatively we could

2. Rely on `declarative-shadow-dom` as independent custom element (https://github.com/Starcounter/RebelsLounge/issues/78 once it's done) . Then default ones (provided by app devs - from app code) should work regardless of the container. Then the explicit custom ones, given by the composer/editor/designer app/person (ones from the database) could be delivered also using `<declarative-shadow-dom>` merged by HTML merger.
    However, this would require:
    1. Implementing `<d-s-d>` as independent CE which may take some time and is at risk due to lack of `is=""` support in browsers and other potential lifecycle problems,
    2. Heavy re-design in composition flow (which I planned anyways, but in long-term),
    3. Changes to HTML Merger, which was pretty stable so far,
    4. Implementing additional feature to `<d-s-d>` to overwrite instead of appending Shadow DOM
    5. Workaround in some other way the problem of missing slots and slot names (current responsibility of `<starcounter-include>`/`<juicy-composition>`
3. Suggest to all app developers, to use `MaterPage.html` - which we already found confusing.

/cc @warpech @Mackiovello

**Comment by warpech** [comment]
1. Looks the best to me. It goes on pair with https://github.com/Starcounter/level1/issues/4017.

**Comment by warpech** [comment]
Ping @chrhol

**Comment by warpech** [comment]
Ping @chrhol. This is very much needed

**Comment by chrhol** [comment]
So the tasks are to:
- Update `PartialToStandaloneHtmlProvider` to use `starcounter-include`
- Change so that root json is namespaced.

Is that correct, or is the second task optional? I feel a little confused :) And there is no other things that needs to be changed, so although behaviour is changing, it shouldn't break any apps?

**Comment by warpech** [comment]
Yes, the beginning might be as easy as changing 

```html
<template is=""imported-template"" content$=""{{{{model.Html}}}}"" model=""{{{{model}}}}""></template>
``` 

to 

```html
<starcounter-include view-model=""{{{{model}}}}""></starcounter-include>
```

@tomalec perhaps you could make a PR to Starcounter that does that?

The intent to implement https://github.com/Starcounter/starcounter-include/issues/29 in `starcounter-include` requires https://github.com/Starcounter/level1/issues/4017 to be implemented in server-side first, but that one is already tracked.

I tried to check if there are any more challenges, but could not find such.

**Comment by tomalec** [comment]
> Yes, the beginning might be as easy as changing

But isn't it just maintaining one hack just to hide a problem?

>  Starcounter/starcounter-include#29 in `starcounter-include` requires Starcounter/level1#4017 
Does it? why? I think currently it doesn't and I would say using `sc-include` on root level requires it

**Comment by warpech** [comment]
>> Yes, the beginning might be as easy as changing

> But isn't it just maintaining one hack just to hide a problem?

What do you mean by *hack*? This is exactly what's is asked in the title of this issue.

>>  Starcounter/starcounter-include#29 in `starcounter-include` requires Starcounter/level1#4017 

>Does it? why? I think currently it doesn't and I would say using `sc-include` on root level requires it

Sorry, that was a mental shortcut. What I meant was:

If we put `starcounter-include` to `PartialToStandaloneHtmlProvider` right now, then Starcounter/starcounter-include#29 must be postponed until Starcounter/level1#4017 is done. That is fine for me.

**Comment by tomalec** [comment]
Solved as suggested above by https://github.com/Starcounter/level1/issues/4223

**Comment by warpech** [comment]
@tomalec will you please write an announcement about this change? https://github.com/Starcounter/Announcements
