### ISSUE TITLE
The Git Commit of the release

### ISSUE THREAD

**Issue by careri** [Starcounter/Home#91]
Would it be possible to provide the commit-hash of the version being built.
From time to time I compile part of the code myself to figure out strange behaviour and enable debugging.

It would simplify for me if I knew the exact commit the release was made from

**Comment by alemoi** [comment]
The problem is that we have many repositories: Level0, Level1, Simplified, SO, etc. So it should be a combination of commit hashes probably. 
@careri do you store everything in one repository?

**Comment by careri** [comment]
Morning.

No we use multiple repos. 
Each repo is responsible for prodividing the output assebmlies with a version number and commit hash. 
So in your case:
Level0 would build it's assemblies and inject the commit hash and version number.
Level1 would use the assemblies built by level0 to build it's assemblies with another hash and version number.

**Comment by alemoi** [comment]
So, the commit hash comes as information in the assembly, to which repository it belongs. We will think of something like this as a solution.
