### ISSUE TITLE
SQL: Why object comparison is executed with >= & <= filters?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#92]
@k-rus I have the following query:

```sql
SELECT *
FROM Palma.CustomGoalValue
WHERE ProductProperty = OBJECT 511094
```

Which produces the following query plan:

```
....
IndexScan(
 CustomGoalValueProductPropertyIdx ON Palma.CustomGoalValue
 0
 ProductProperty
 ObjectDynamicRange(
  ObjectRangePoint(
   GreaterThanOrEqual
   ObjectLiteral(511094)
  )
  ObjectRangePoint(
   LessThanOrEqual
   ObjectLiteral(511094)
  )
 )
 LogicalValue(TRUE)
 Ascending
)
```

My questions is why for the object comparison `GreaterThanOrEqual` + `LessThanOrEqual` is used instead of just `Equal`? Is it an implementation detail or there is something wrong with indexes?

**Comment by k-rus** [comment]
Because there is no `Equal` in range comparison. Range comparison is a range with starting and ending points, which might be inclusive or exclusive.

The presentation of query plans in OldSQL is not ideal, but I am not sure if it worth the effort to improve it.

**Comment by miyconst** [comment]
@k-rus thank you for the answer. 

>Because there is no `Equal` in range comparison.

This makes me wonder, why "range comparison" while it's just a single value.

Anyway, if it's suppose to be like this, and not broken indexes on my side, then I close the issue.
