### ISSUE TITLE
CalculatePatchAndPushOnWebSocket - how does it work?

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#93]
I have a large view-model with multiple properties which take time to load. To speed up the page load I try the following:

```cs
public List<Row> Rows
{
    get
    {
        if (this.rows != null)
        {
            return this.rows;
        }

        string sessionId = Starcounter.Session.Current.SessionId;
        Starcounter.Session.ScheduleTask(sessionId, (s, id) =>
        {
            if (s == null)
            {
                return;
            }

            this.rows = this.CalculateRows();
            s.CalculatePatchAndPushOnWebSocket();
        });
    }
}
```

I expect the `CalculatePatchAndPushOnWebSocket` re-evaluate view-model and send the difference from the previous state to the client.

Instead, if `CalculatePatchAndPushOnWebSocket` was called before the page load finished, it is just ignored.

If I add `System.Threading.Thread.CurrentThread.Join(1000)` before the call, which is enough to wait till page loads, then it works as expected.

cc @alemoi, @chrhol

**Comment by alemoi** [comment]
To be clear, is `s.CalculatePatchAndPushOnWebSocket();` executing before the `this.rows = this.CalculateRows();`?

**Comment by miyconst** [comment]
No. It's executed after the calculation.

**Comment by alemoi** [comment]
Hmm, I thought the origin of the problem is with scheduling. That tasks
execute in the wrong order, but seems its not the case, right? Regarding
patch calculation, @chrhol can probably clarify.

**Comment by miyconst** [comment]
>Hmm, I thought the origin of the problem is with scheduling. That tasks
execute in the wrong order, but seems its not the case, right?

I can't be sure about it and don't know how to check it. The symptoms I have described above.

**Comment by alemoi** [comment]
When is `Rows->get` called? Some time during patch processing?

**Comment by miyconst** [comment]
Yes, it is executed for the first time when the client request view model.

**Comment by alemoi** [comment]
I think @chrhol would be best to answer regarding view-model patch evaluation.
However my guess is that simply view model is not updated properly at the time when patch is calculated, as you point:
> If I add System.Threading.Thread.CurrentThread.Join(1000) before the call, which is enough to wait till page loads, then it works as expected.

**Comment by miyconst** [comment]
Okay. Let's wait for him to get back from the vacation.

**Comment by Mackiovello** [comment]
Related https://github.com/Starcounter/level1/issues/4144 and https://github.com/Starcounter/TechComm/issues/39

**Comment by alemoi** [comment]
I will start working on this after I push Blender and add the hooks system.

**Comment by alemoi** [comment]
I think its all about how exactly the JSON patch is calculated. So I have to unassign myself unfortunately. @chrhol let me know if I can help somehow.

**Comment by miyconst** [comment]
Duplicate of an internal issue. Closing.
