### ISSUE TITLE
SQL: Unknown property Length of class String

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Home#95]
I have a database class with a string property. I want to select length of the string value. The query looks like this:

```sql
SELECT Name.Length
FROM Palma.N1Property
```

Which results in the following error:

```
Failed to process query: SELECT Name.Length FROM Palma.N1Property: Unknown property Length of class String. View the log for more details.
```

So, I have two questions:

- Why the error message is such? It is very misleading, since the `String` class actually has the `Length` property.
- Is it anyhow possible to select length of a string value using SQL?

cc @k-rus

**Comment by k-rus** [comment]
> Why the error message is such? It is very misleading, since the String class actually has the Length property.

I don't know why the error message is such. I believe nobody knows.



> Is it anyhow possible to select length of a string value using SQL?

Only properties on database classes are available in SQL to my knowledge. I believe the class `String` is a system, not database class, right?

**Comment by miyconst** [comment]
>Only properties on database classes are available in SQL to my knowledge. I believe the class String is a system, not database class, right?

Yes. 

So, the answer to my question is:

>Currently it is not possible to perform any operations with string length inside SQL, since the SQL `LEN` operator is not supported.

Am I right?

**Comment by k-rus** [comment]
> Currently it is not possible to perform any operations with string length inside SQL, since the SQL LEN operator is not supported.
> Am I right?

If the operator is not documented, then it is not supported. Answering more precise requires to look into the source code and it is not obvious to prove non-existence there.

**Comment by miyconst** [comment]
>... since the SQL `LEN` operator is not supported.

It was a statement, not a question.

Closing the issue as answered.
