### ISSUE TITLE
Create HTTP Handle helper methods: GetRegisteredHandlers, GetHandlerForUri

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#99]
As discussed in https://github.com/StarcounterApps/Website/pull/92#discussion_r113448720, Website app needs two helper methods in `Handle` class:

- `GetRegisteredHandlers` - returns a list of strings or dictionary with a format "method_space_uri" (`GET /people/person/{?}`)
- `GetHandlerForUri` - takes a real URI (might be from the HTTP request) and returns a registered handler URI that matches it

@alemoi thanks for looking into this!

**Comment by alemoi** [comment]
Both features are added.
